### PR TITLE
Allow a device to specify that it must be involved in a composite update

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
It feels like this PR is a workaround for a badly crafted composite CAB during development. Is that right?

**Comment by hughsie** [comment]
> It feels like this PR is a workaround for a badly crafted composite CAB during development. Is that right?

Yes, it's when the user downgraded the child device version manually (e.g. using install-blob) and then we "repair" the device by upgrading to any version. But because the main firmware isn't included we flash the child device and make the situation worse.

**Comment by superm1** [comment]
So then perhaps should install blob be blocked entirely for this class of device?

**Comment by hughsie** [comment]
> So then perhaps should install blob be blocked entirely for this class of device?

I think that would make development much harder. Install-blob is supposed to be a "I really know what I'm doing" action. I think you can get into the same situation if you install the correct firmware on a standard device, if you remove the physical device before the main firmware has been written. I agree it's an edge case.

**Comment by hughsie** [comment]
@hardboprobot do you concur with this? I'm kinda guessing this works for you.

**Comment by hughsie** [comment]
@hardboprobot do you think we should close this PR?

**Pull request closed without merging**
