### PR TITLE
mtd: Use dummy SMBIOS data to fix self test on s390x

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
Does s390x even support `mtd` devices?  Maybe we should just skip it.  Also - would really love if we could get s390x building in CI again :/

**Comment by hughsie** [comment]
tbh, it's no s390 specific at all, it's just the only architecture we test that doesn't have either SMBIOS or DT exposed on the runner.

**Comment by superm1** [comment]
> 

Ah got it.  Then yeah this approach makes sense.  Really we probably should be setting that for all the test suites to give a known environment.

**Comment by hughsie** [comment]
>  Really we probably should be setting that for all the test suites

Agreed, added.

**Review by superm1 — APPROVED** [review]

**Pull request merged**
