### PR TITLE
trivial: Make messages about missing declaration of unsigned/signed l…

### PR DESCRIPTION
**Pull request by superm1**
…ouder

Upgrade these messages to critical, which should cause CI failures for anything missing them.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
I'm expecting that steelseries makes noise to prove this works to fail CI, and then we can fix steelseries to the right value. @d4s can you please advise!

**Comment by hughsie** [comment]
> I'm expecting that steelseries makes noise to prove this works

I was expecting another failure too. Do you get the critical error running the device tests locally?

**Comment by superm1** [comment]
> > I'm expecting that steelseries makes noise to prove this works
> 
> I was expecting another failure too. Do you get the critical error running the device tests locally?

I saw it as a warning locally, I'm thinking it's got to do with how the daemon is launched locally vs in CI.

I think all the stuff in this PR makes sense even if it doesn't bring up the problem yet, which is why I marked it ready for review.

**Comment by d4s** [comment]
I'll try to clarify with Vendor ASAP.
@superm1 just to clarify, need info about the payload, i.e. for the the flag `FWUPD_DEVICE_FLAG_UNSIGNED_PAYLOAD` or `FWUPD_DEVICE_FLAG_UNSIGNED_PAYLOAD`, correct?

**Comment by superm1** [comment]
> I'll try to clarify with Vendor ASAP. @superm1 just to clarify, need info about the payload, i.e. for the the flag `FWUPD_DEVICE_FLAG_UNSIGNED_PAYLOAD` or `FWUPD_DEVICE_FLAG_UNSIGNED_PAYLOAD`, correct?

Yeah exactly.  This _should_ have failed CI in this PR but isn't for some reason.  I reproduced it locally when I was running device tests.

**Comment by superm1** [comment]
The problem seems to be that `G_DEBUG` needs to be set in the environment _before_ the app is launched, not compiled into it.

IE even this doesn't fail:
```
(void)g_setenv("G_DEBUG", "fatal-criticals", TRUE;
```

But this does:
```
G_DEBUG=fatal-criticals fwupd -v
```

**Comment by superm1** [comment]
> Authenticating?          [ -                                     ]Authenticating?          [ -                                     ]18:42:28.614 FuEngine             elantp [1deb68aaada5acf7b8e3ee880f4f74ae867021d8] does not declare signed/unsigned payload -- perhaps add fu_device_add_flag(device, FWUPD_DEVICE_FLAG_UNSIGNED_PAYLOAD);

@jinglewu @josh-chen-elan can you please clarify which one elantp should have?  I'll fix it up.

**Comment by d4s** [comment]
@superm1 all F/W for steelseries plugin are unsigned.
The patch is in https://github.com/fwupd/fwupd/pull/8095.

I don't know what to do with [Rival 100](https://github.com/fwupd/fwupd/blob/main/plugins/steelseries/fu-steelseries-mouse.c) since we have no update implementation for that mouse. @hughsie do you think we steel need to keep it?

**Comment by hughsie** [comment]
> I don't know what to do with [Rival 100](https://github.com/fwupd/fwupd/blob/main/plugins/steelseries/fu-steelseries-mouse.c) since we have no update implementation for that mouse

I think it's useful to keep; I think it's a fair assumption to assume the firmware is unsigned too.

**Review by hughsie — DISMISSED** [review]

**Pull request merged**
