### PR TITLE
trivial: wacom: Add support for second vendor ID

### PR DESCRIPTION
**Pull request by superm1**
Wacom indicates that some systems will use this alternative VID.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
(And I think this should probably backport to 1_2_X as well before 1.2.11)

**Comment by hughsie** [comment]
Can we add this kind of thing as a quirk?

**Comment by superm1** [comment]
Maybe if we do something like this.  I think the `WacomAES` and `WacomEMR` GUIDs will handle it.

```
diff --git a/plugins/wacom-raw/fu-plugin-wacom-raw.c b/plugins/wacom-raw/fu-plugin-wacom-raw.c
index 0815555b..02119376 100644
--- a/plugins/wacom-raw/fu-plugin-wacom-raw.c
+++ b/plugins/wacom-raw/fu-plugin-wacom-raw.c
@@ -47,11 +47,6 @@ fu_plugin_udev_device_added (FuPlugin *plugin, FuUdevDevice *device, GError **er
        if (g_strcmp0 (fu_udev_device_get_subsystem (device), "hidraw") != 0)
                return TRUE;
 
-       /* wacom */
-       if (!(fu_udev_device_get_vendor (device) == FU_WACOM_DEVICE_VID) ||
-            (fu_udev_device_get_vendor (device) == FU_WACOM_DEVICE_VID2))
-               return TRUE;
-
        /* no actual device to open */
        if (g_udev_device_get_device_file (fu_udev_device_get_dev (device)) == NULL)
                return TRUE;
diff --git a/plugins/wacom-raw/wacom-raw.quirk b/plugins/wacom-raw/wacom-raw.quirk
index 51ceee1a..49c3677c 100644
--- a/plugins/wacom-raw/wacom-raw.quirk
+++ b/plugins/wacom-raw/wacom-raw.quirk
@@ -13,6 +13,12 @@ Plugin = wacom_raw
 Guid = WacomAES
 Flags = is-bootloader
 
+# AES bootloader mode
+[DeviceInstanceId=HIDRAW\VEN_2D1F&DEV_0094]
+Plugin = wacom_raw
+Guid = WacomAES
+Flags = is-bootloader
+
 # EMR bootloader mode
 [DeviceInstanceId=HIDRAW\VEN_056A&DEV_012B]
 Plugin = wacom_raw
```

**Comment by hughsie** [comment]
I think exactly like that. If it works, LGTM.

**Comment by superm1** [comment]
Oh well, it will actually cause some problems while other hidraw devices are added because the final return condition for that function is `FALSE`.

So no, I think we need to have the vendor check in place.

**Comment by hughsie** [comment]
> return condition for that function is FALSE

I think we're missing the `return TRUE` below the `fu_plugin_device_add()` line in both places.

**Comment by superm1** [comment]
> I think we're missing the return TRUE below the fu_plugin_device_add() line in both places.

Right, just added that.
But still if I have a hidraw device that's not wacom (say a synaptics touchpad), do you expect that `fu_plugin_udev_device_added` should be returning true at the end of the function or false?  Right now it would return true from the wacom-raw plugin.

**Comment by hughsie** [comment]
> do you expect that fu_plugin_udev_device_added should be returning true at the end of the function or false

I don't think it matters. I'd err on TRUE, as then there's no g_warning() on the console. I'd maybe err on removing that `Only EMR or AES devices are supported` error too. I guess the other thing we could do is only return false with an error if `fu_device_get_plugin()` matches the plugin name, i.e. there was a quirk with Plugin = wacom_raw but no matching WacomAES/EMR GUID

**Comment by superm1** [comment]
> I guess the other thing we could do is only return false with an error if fu_device_get_plugin() matches the plugin name, i.e. there was a quirk with Plugin = wacom_raw but no matching WacomAES/EMR GUID

That seems like it might be overkill - you'd have to knowingly mess up the quirk file then.

**Comment by hughsie** [comment]
True. Does removing the error work for you?

**Comment by superm1** [comment]
I don't have the hardware myself yet for this, this is stuff that will be built later.  I think it should, I'll fix-up and force push again.

**Comment by hughsie** [comment]
If it works on real hardware, LGTM, thanks.

**Comment by superm1** [comment]
the hardware is pretty far out, I won't be able to test the alternative VID for a while, any opposition to including it untested?  it's only for bootloader mode, it should be pretty harmless.

**Comment by hughsie** [comment]
No objection from me.

**Pull request merged**
