### PR TITLE
Change the style guide to no space before the bracket

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]
If no extra fixups, the python script becomes less important.

**Comment by hughsie** [comment]
That works exactly like I imagined, good job. Do you know why "git diff -U0 master" is failing in the CI?

**Comment by superm1** [comment]
> That works exactly like I imagined, good job. Do you know why "git diff -U0 master" is failing in the CI?

Its not checking out enough commits to refer to "master"

**Comment by hughsie** [comment]
Squash the last few then lgtm, thanks!

**Pull request merged**
