### PR TITLE
Allow the root user to ask the daemon to quit

### PR DESCRIPTION
**Pull request by hughsie**
This makes it easier to test the installed fwupd for the installed tests.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
TBH this feels pretty heavy handed. 99% of people won't quit this way.

Why not just support a unix signal sent as root to let the daemon signal handler intercept and cleanly shutdown?

**Comment by hughsie** [comment]
> TBH this feels pretty heavy handed. 99% of people won't quit this way.

Sure, I don't think it makes sense for users to know this subcommand, I even thought about hiding it so that it doesn't show in the --help output.

> Why not just support a unix signal sent as root to let the daemon signal handler intercept and cleanly shutdown?

I thought we wanted this to work with Win32, no? I don't think we can handle signals there. Also, assuming we don't need this on win32, we'd also need a way (a property?) to get the PID of the fwupd process so we knew what to kill.

**Comment by superm1** [comment]
Oh yeah great arguments.

How about moving the command to fwupdtool instead?

**Comment by hughsie** [comment]
> How about moving the command to fwupdtool instead?

I guess we could, but I'm not sure it makes sense. In my head `fwupdmgr` is *tell the daemon to do something* and `fwupdtool` is *JFDI, right now*. I don't think it makes sense to have fwupdtool as an overflow of "half useful stuff".

**Comment by superm1** [comment]
As this is limited purpose - how about just dbus send or call the CI app in python? I just don't think this needs to be in fwupdmgr.

**Comment by hughsie** [comment]
> how about just dbus send

Yup, that works, good idea.

**Pull request merged**
