### PR TITLE
Wip/hughsie/esp recurse

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
As a different heuristic what do you think about checking if the filesystem is a Linux filesystem? Or Linux partition type? Those can't be ESPs anyway.

**Comment by hughsie** [comment]
> Or Linux partition type? Those can't be ESPs anyway.

IIRC I think there are quite a few different things that *could* be ESPs -- e.g. you can use NTFS with some firmware. EXT3/4 would be unusual, but wouldn't be madness.

**Comment by superm1** [comment]
How about if there are multiple ESPs then ignore the Linux ones then?

**Comment by hughsie** [comment]
Lets keep it simple; we'll do what you suggest and just filter out ext4 as a type from the ESPs. If someone wants to do it we can say "not supported". Updated.

**Review by superm1 — APPROVED** [review]

**Pull request merged**
