### PR TITLE
Do not accidentally depend on python 3.9

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/5898

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@kloczek -- can you verify please

**Comment by kloczek** [comment]
Instead checking that in custom script IMO better would be use meson `python` module to check python version.
Really it is not possible to use 3.8? 🤔

**Comment by hughsie** [comment]
> Really it is not possible to use 3.8?

Try this branch on 3.8 please.

**Review by superm1 — APPROVED** [review]

**Comment by kloczek** [comment]
Still I think that better would be just check python version by use `dependency('python3 >= 3.9')`

**Comment by superm1** [comment]
> Still I think that better would be just check python version by use `dependency('python3 >= 3.9')`

Why? It's not a hard dependency and this will allow it to work on more machines still.

**Comment by kloczek** [comment]
Seems it is hard dependency because now without python >=3.9 it is not possible to generate dbus interface file.

**Comment by superm1** [comment]
It generates, it's just ugly.

**Pull request merged**
