### PR TITLE
nordic-hid: Inhibit the dongle when there are peripheral updates pending

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by MarekPieta** [comment]
Seems that error returned by `fu_util_update_device_with_release` in `fu_util_update` while updating dongle leads to instant `return FALSE`. That prevents `fwupdmgr` CLI tool from even trying to update dongle connected peripherals.

Maybe we could e.g. explicitly skip devices with problems or `continue` on the error instead of `return FALSE`?

**Comment by hughsie** [comment]
> Seems that error returned by fu_util_update_device_with_release in fu_util_update while updating dongle leads to instant return FALSE

Isn't that what we want? e.g. I thought that we'd run `fwupdmgr update` to update all the peripherals, and then `fwupdmgr update` to update the dongle. Although this is a bit sucky, 99% of the updates are going to be deployed from a GUI tool, and the effect of the device problem will be that the peripherals will be shown to update, then they'll be applied, then that will disappear, and the dongle will appear so it can be updated. I think that's pretty good.

**Comment by MarekPieta** [comment]
Hi @hughsie
I agree that for a GUI use-case the fix would work quite well.

Still, the CLI use-case may not provide the best user experience. The first run of `fwupdmgr update` would not update peripherals. Even if the peripherals connected through dongle are available, the fwupdmgr only emits the log `Nordic Semiconductor ASA Dongle nRF52 Desktop is not currently updatable: Device is waiting for the update to be applied`. No matter how many times we call the command, we will always only see the log and peripherals will remain not updated. We could work it around by passing GUID of peripherals explicitly, but it may not be the best user experience.

**Comment by hughsie** [comment]
> Even if the peripherals connected through dongle are available, the fwupdmgr only emits the log Nordic Semiconductor ASA Dongle nRF52 Desktop is not currently updatable

Okay, that's not what I hoped for. I hoped that the dongle would be inhibited if the peripherals have pending updates -- and **only** the dongle. My logic is maybe funky -- the FuNordicHidCfgChannel shouldn't have the FuDeviceProblem at all.

Maybe I've misunderstood things -- I thought the parent FuNordicHidCfgChannel was the dongle and the children are the peripherals?

If that's true, can you set a brakepoint and see what's calling fu_device_add_problem() on the dongle?

**Comment by MarekPieta** [comment]
> > Even if the peripherals connected through dongle are available, the fwupdmgr only emits the log Nordic Semiconductor ASA Dongle nRF52 Desktop is not currently updatable
> 
> Okay, that's not what I hoped for. I hoped that the dongle would be inhibited if the peripherals have pending updates -- and **only** the dongle. My logic is maybe funky -- the FuNordicHidCfgChannel shouldn't have the FuDeviceProblem at all.
> 
> Maybe I've misunderstood things -- I thought the parent FuNordicHidCfgChannel was the dongle and the children are the peripherals?
> 
> If that's true, can you set a brakepoint and see what's calling fu_device_add_problem() on the dongle?

Actually, the dongle is properly inhibited by the problem that was introduced by your PR (and **only dongle** seems inhibited by the problem so it works as expected). You are also right that dongle is parent and peripherals are children. The problem here is the fact that `fwupd` actually stops iterating over devices after dongle reports problem - as I described in my previous comment:

>Seems that error returned by fu_util_update_device_with_release in fu_util_update while updating dongle leads to instant return FALSE. That prevents fwupdmgr CLI tool from even trying to update dongle connected peripherals.
>Maybe we could e.g. explicitly skip devices with problems or continue on the error instead of return FALSE?

**Comment by hughsie** [comment]
@MarekPieta ahh, i see what you mean now. Does the follow up commit help?

**Comment by MarekPieta** [comment]
Hi @hughsie
Sorry for delayed answer. I was on vacation. I will let you know if the fix works for me as soon as I check it locally.

**Comment by MarekPieta** [comment]
Hi @hughsie,
The change seems to work fine now. The first invocation of `fwupdmgr update` updates only the HID peripherals (dongle is marked as `• Device is waiting for the update to be applied`). The second invocation of `fwupdmgr update` updates dongle. Thanks for the fixes!

**Review by MarekPieta — APPROVED** [review]

**Pull request merged**
