### PR TITLE
trivial: fix test plugin version check

### PR DESCRIPTION
**Pull request by superm1**
The upgrade to 1.2.4 fails because `fu_strsafe()` intentionally replaces a newline character with a period but `fu_strtoull()` explicitly looks for a new line character.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
I don't trigger the CI failure locally for some reason.

**Comment by superm1** [comment]
I think that the modifying the binary is the right solution here; but the key for 48A6D80E4538BAC2 is the LVFS key, I think you'll need to make a new detached signature for it.

**Comment by hughsie** [comment]
We probably ought to switch it to jcat at the same time; I want to rip the "bare asc" support out of fwupd soon as now the lvfs depends on fwpud 1.4.5 -- give me a few mins

**Comment by hughsie** [comment]
@superm1 i've uploaded the new .cab files to the branch -- can we use those directly or do we need to construct the .cab files as before? if the latter lets just use the .jcat flle rather than the .asc one.

**Comment by superm1** [comment]
We can use CAB directly but I want to make sure we still have somewhere in tree that we run build-cabinet to make sure it doesn't break again in future.

**Comment by superm1** [comment]
To make sure CI can do cabinet-build I extracted, let's see if all the CI works end to end with this.

**Pull request merged**
