### PR TITLE
uefi: Don't overwrite BootNext and create new Boot#### when installin…

### PR DESCRIPTION
**Pull request by superm1**
…g 2 FW

Fixes: #2169

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
That seems kinda fragile... I don't think it's actually addressing the bug, just working around it. A better workaround would be not to use that global `Dir` object, and another would be to set up bootnext on composite_finish() or whatever we called the vfunc.

**Comment by superm1** [comment]
I don't think we can get a pointer to Dir without changes to efivar.

**Comment by superm1** [comment]
In terms of composite - that's going to be a not good enough workaround. If you install one update, and then don't reboot your machine and install another you'll hit the same failure, but it won't be composite.

**Comment by superm1** [comment]
close in favor of #2485

**Pull request closed without merging**
