### PR TITLE
trivial: Add fu_udev_device_query_file_exists() which can be emulated…

### PR DESCRIPTION
**Pull request by hughsie**
… by devices

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 with this, would you be able to create a proper update emulation for amd_gpu?

**Comment by superm1** [comment]
> @superm1 with this, would you be able to create a proper update emulation for amd_gpu?

No, it doesn't seem to work.  I tried on a system with a dGPU and this is all it gets in setup.json.

```
{
  "UsbDevices" : [
    {
      "GType" : "FuUdevDevice",
      "BackendId" : "/sys/devices/pci0000:60/0000:60:03.1/0000:61:00.0",
      "DeviceFile" : "/dev/dri/card0",
      "Subsystem" : "pci",
      "Driver" : "amdgpu",
      "BindId" : "0000:61:00.0",
      "Vendor" : 4098,
      "Model" : 27009,
      "Created" : "2024-10-27T04:36:39.550628Z"
    }
  ]
}
```

**Comment by hughsie** [comment]
@superm1 I moved this to the baseclass; can you check amd-gpu pls.

**Comment by superm1** [comment]
It works!  You should be able to emulate it now.  I just did it on a different machine with the emulation from my workstation.
[dgpu.zip](https://github.com/user-attachments/files/17602313/dgpu.zip)

**Comment by superm1** [comment]
Btw, I was thinking as these are all JSON files that are for enumeration only we shouldn't store them at LVFS.  I started this repo:
https://github.com/fwupd/fwupd-emulation

What do you think of that?

**Review by superm1 — APPROVED** [review]

**Comment by hughsie** [comment]
I was putting the emulatuons in the existing (non free?) external test data repo.

**Comment by superm1** [comment]
> I was putting the emulatuons in the existing (non free?) external test data repo.

But as zips. That's not too pretty for just a json used for enumeration.

#8011 is what I'm thinking.

**Pull request merged**
