### PR TITLE
Wip/hughsie/boilerplate

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by hughsie** [comment]
The WacomAES/WacomEMR ones are 100% untested due to lack of hardware.

**Comment by hughsie** [comment]
Also, don't merge this branch yet, I think more cleanups are possible -- but I wanted to check with the general concept before doing more work.

Ideally I want to get fwupd into a place where there are as few plugin vfuncs as we can get away with.

**Comment by superm1** [comment]
Well so conceptually I like this; but I wonder about exposing GType into quirks.  Isn't that an implementation specific detail?

**Comment by hughsie** [comment]
I don't think it's more implementation specific than the other plugin-specific keys. My worry was more that it's a bit magic, although I suppose if everything is using quirk-plugin then we can remove the non-quirk plumbing code. Same for the other vfuncs.

**Comment by superm1** [comment]
> I don't think it's more implementation specific than the other plugin-specific keys. My worry was more that it's a bit magic, although I suppose if everything is using quirk-plugin then we can remove the non-quirk plumbing code. Same for the other vfuncs.

Well I guess what i'm getting at is what value does GType give you that you don't get from `plugin_name`?

**Comment by hughsie** [comment]
Ahh, in most cases it's very similar. In some cases there are different GTypes depending on the instance id. E.g. EMR and AER panels. Maybe we could set the gtype in the quirk and then get the plugin automatically. That does make the loader much more complex.

**Comment by hughsie** [comment]
@superm1 I'm happy with this now -- 800 lines less of complexity! What do you think?

**Comment by superm1** [comment]
Everything else looks great to me besides that one comment.

**Pull request merged**
