### PR TITLE
Wip/hughsie/hsi

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
Wait a minute. Won't this break AMD security? Haven't tried yet but would think it would.

**Comment by hughsie** [comment]
> Won't this break AMD security

We still do the INTEL check, no? I can check on AMD in a few mins if that helps.

**Comment by superm1** [comment]
> > Won't this break AMD security
> 
> We still do the INTEL check, no? I can check on AMD in a few mins if that helps.

What system do you have? Does it support the AMD stuff?

**Comment by hughsie** [comment]
Lenovo T14, so no.

**Comment by superm1** [comment]
OK just double checked it on a Z13.  It's fine, no worries.

**Pull request merged**
