### PR TITLE
Set the SMBIOS chassis type to portable if a DT battery exists

### PR DESCRIPTION
**Pull request by hughsie**
This allows getting the HSI result on a Pinebook Pro laptop.

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
This feels like an abuse of the chassis type.  Can't a phone also have a battery and not be a portable chassis?  Or a tablet have a battery?

Since this is DT - I think what we want to do is add something to DT to specify the form factor or chassis type.

**Comment by hughsie** [comment]
> I think what we want to do is add something to DT to specify the form factor or chassis type.

I don't think this is going to work for all the devices in the field right now; I'd be happy to support a DT type and fallback to the battery heuristic. If there's already a DT attribute for this please let me know!

**Comment by superm1** [comment]
I glanced through the spec and didn't see anything.  I guess i'm with that approach, but please submit a request to DT spec to add the field so we can start to rely upon that for the future!

**Comment by hughsie** [comment]
> please submit a request to DT spec

I've banged some Tom Toms and I'll see where that leads. If something appears I'll fix up the code of course.

**Pull request merged**
