### PR TITLE
trivial: Install gcovr on Fedora before meson configure runs

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/8024

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
Since we have 3 different "test" scripts all doing the exact same thing, should we split to `coverage.sh` which is called by them?

**Comment by hughsie** [comment]
Certainly, but lets see if this works first :)

**Comment by hughsie** [comment]
@superm1 is that what you expected?

**Comment by superm1** [comment]
Looking at the artifacts they're still missing everything for Fedora:

```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE coverage SYSTEM 'http://cobertura.sourceforge.net/xml/coverage-04.dtd'>
<coverage line-rate="1.0" branch-rate="1.0" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0" complexity="0.0" timestamp="1730757507" version="gcovr 7.2"><sources><source>.</source></sources><packages/></coverage>
```

I double checked the job was working to install gcovr before, but it's still not running in the test container.

**Comment by superm1** [comment]
I wonder if the coverage files to parse are ending up in a different directory on Fedora?

**Comment by hughsie** [comment]
> I wonder if the coverage files to parse are ending up in a different directory 

Will debug a bit more tmw, sleep calls. :)

**Comment by superm1** [comment]
Yup it's a base directory thing based on where it gets built.  I used a container and here's where I found some coverage files after running fwupdtool.

```
[root@cee223f52521 src]# ls /root/rpmbuild/BUILD/fwupd-2.0.2-build/fwupd-2.0.2/redhat-linux-build/src/fwupdtool.p/
fu-tool.c.gcda  meson-generated_.._fu-engine-struct.c.gcda
```

**Pull request closed without merging**
