### PR TITLE
Support new Huddle device

### PR DESCRIPTION
**Pull request by vcdmp**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

Support new Logitech Huddle device, Updated required proto files

### CODE REVIEW

**Review by hughsie — APPROVED** [review]

**Comment by vcdmp** [comment]
Thank you Richard. Truly appreciated. I was struggling with pre-commit hooks. How do I run these hooks on my Ubunto dev machine!

**Comment by superm1** [comment]
> Thank you Richard. Truly appreciated. I was struggling with pre-commit hooks. How do I run these hooks on my Ubunto dev machine!

`./contrib/setup`

**Comment by vcdmp** [comment]
Thanks Mario,  I did followed https://github.com/fwupd/fwupd/blob/main/CONTRIBUTING.md, But I was running into issues with other plugins build on my older Ubuntu box, so was using "--no-verify" with git commit. Now I have Ubuntu 22.04.2 LTS, so will revisit.

**Comment by superm1** [comment]
OK, if you run into any other problems with it feel free to open a discussion and we can look at it.  The pre-commit stuff saves my butt all the time for otherwise embarrassing mistakes :)

**Comment by vcdmp** [comment]
👍

**Comment by hughsie** [comment]
> How do I run these hooks on my Ubunto dev machine

If it helps, I sometimes resort to `find . -name '*.c' -o -name '*.h' -o -name '*.proto' | xargs clang-format -i`

**Pull request merged**
