### PR TITLE
Move some binaries to usr/bin

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
If they're in bindir, they need manpages too :(

**Comment by superm1** [comment]
> If they're in bindir, they need manpages too :(

Yep, I made them.

**Comment by superm1** [comment]
> What about the other tools?

* `fwupd` should definitely be in `libexecdir`
* `fwupdoffline` is not intended for user use.  It's only used by systemd.
* `fwupdtpmevlog` I'm not sure (I can go either way)

**Comment by hughsie** [comment]
> fwupdtpmevlog I'm not sure

If we're going with the logic of the user running debugging things, I think it should probably treated the same way as fwupdtool and fwupdate.

**Comment by superm1** [comment]
> > fwupdtpmevlog I'm not sure
> 
> If we're going with the logic of the user running debugging things, I think it should probably treated the same way as fwupdtool and fwupdate.

OK I've moved that over as well now.

**Pull request merged**
