### PR TITLE
Wip/hughsie/hsi fixes

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by hughsie** [comment]
Untested; I'm on the wrong laptop to test.

**Comment by superm1** [comment]
If translating ok and fail, I wonder if it's worth trying to make more plugins show that for success and fail rather than details shown now. IE make the description in the title rather than the result.

**Comment by hughsie** [comment]
> If translating ok and fail

**Comment by superm1** [comment]
> ✔  MEI detected

ME Manufacturing mode disabled

>> ✔  Something

Does making it instead like this come across better?

 Something : ✔ 

IE change the OK/Failed into the check / X but leave it in the same place.

**Comment by hughsie** [comment]
> Does making it instead like this come across better?

I think all this is complicated enough for the user. I think we do need to say if something is "locked" or "unlocked" if nothing else so they can file a good bug report. PR 90% done with an idea to clean everything up a bit.

**Comment by hughsie** [comment]
Obsoleted by https://github.com/fwupd/fwupd/pull/2106

**Pull request closed without merging**
