### PR TITLE
Show the user when devices are updatable by inhibited

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/4281

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Screenshot from 2022-02-14 09-17-33

**Review by superm1 — COMMENTED** [review]
Presumably also should do same for fu-tool?

**Comment by hughsie** [comment]
> Presumably also should do same for fu-tool?

Ya, I just wanted broad consensus really. Will copy it over.

**Comment by superm1** [comment]
> > Presumably also should do same for fu-tool?
> 
> Ya, I just wanted broad consensus really. Will copy it over.

Yeah makes sense.  I do think you'll want to do something similar in gnome-software too, this is quite useful IMO.

**Comment by hughsie** [comment]
>  I do think you'll want to do something similar in gnome-software too

That's harder as it'll need UX review, and GNOME is in UI freeze. Will put on the list for when main opens up again. Ive copied the behaviour in fwupdtool now.

**Review by superm1 — APPROVED** [review]

**Pull request merged**
