### PR TITLE
Only save config values to the mutable config file

### PR DESCRIPTION
**Pull request by hughsie**
Leave /etc to whatever the distro decides.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — DISMISSED** [review]

**Comment by superm1** [comment]
I just triggered a run to rebuild-containers.  I think that should sort this out.

**Comment by hughsie** [comment]
> I just triggered a run to rebuild-containers. I think that should sort this out.

Is my follow up patch any good? I figured it was something we should have either way.

**Comment by superm1** [comment]
> > I just triggered a run to rebuild-containers. I think that should sort this out.
> 
> Is my follow up patch any good? I figured it was something we should have either way.

doesn't seem to be working.  In general I think stuff like that should only be done when you can really prove it's non-interactive though too.  I'd say drop it.  If this comes back to bite us again I'll plumb something to detect the environment.

**Comment by hughsie** [comment]
> Failed to create file ?/var/etc/fwupd/fwupd.conf.48X1H2?: No such file or directory

Well, the CI works :)

**Pull request merged**
