### PR TITLE
meson: fix minimum tpm2-tss version

### LINKED ISSUE #1353: Crashing after 1.3.1 update
fwupd is failing to start after the update to 1.3.1.

```
Sep 13 16:32:09 saetre systemd[1]: Starting Firmware update daemon...
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0021 Fwupd                looking for os-release at /etc/os-release
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0021 FuConfig             loading /usr/share/fwupd/metainfo
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0021 XbSilo               attempting to load /var/cache/fwupd/metainfo.xmlb
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0021 XbSilo               file: 451419ad-0e77-5491-b388-e2a624cad17e, current:451419ad-0e77-5491-b388-e2a624cad17e, cached: (null)
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0021 XbSilo               loading silo with file contents
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0021 FuConfig             using config path of /etc/fwupd
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0021 FuConfig             loading config from /etc/fwupd/remotes.d/lvfs-testing.conf
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0021 FuConfig             loading config from /etc/fwupd/remotes.d/vendor-directory.conf
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0022 FuConfig             loading config from /etc/fwupd/remotes.d/dell-esrt.conf
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0022 FuConfig             loading config from /etc/fwupd/remotes.d/lvfs.conf
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0022 FuConfig             loading config from /etc/fwupd/remotes.d/vendor.conf
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0022 FuConfig             loading config from /etc/fwupd/remotes.d/fwupd-tests.conf
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0022 FuConfig             using config path of /usr/lib/fwupd
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0022 FuConfig             path /usr/lib/fwupd/remotes.d does not exist
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0022 FuConfig             ordering lvfs-testing=lvfs+1
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0022 FuConfig             ignoring unfound remote fwupd
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuEngine             client certificate exists and working
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuHistory            trying to open database '/var/lib/fwupd/pending.db'
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuHistory            got schema version of 5
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuIdle               setting timeout to 7200s
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuHwids              smbios property Manufacturer=LENOVO
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuHwids              smbios property EnclosureKind=a
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuHwids              smbios property Family=ThinkPad P52s
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuHwids              smbios property ProductName=20LBCTO1WW
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuHwids              smbios property ProductSku=LENOVO_MT_20LB_BU_Think_FM_ThinkPad P52s
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuHwids              smbios property BiosVendor=LENOVO
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuHwids              smbios property BiosVersion=N27ET32W (1.18 )
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuHwids              smbios property BiosMajorRelease=01
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuHwids              smbios property BiosMinorRelease=12
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuHwids              smbios property BaseboardManufacturer=LENOVO
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuHwids              smbios property BaseboardProduct=20LBCTO1WW
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0028 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/altos.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0029 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/ata.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0029 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/colorhug.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0029 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/csr-aiaiai.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0029 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/dell-dock.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0029 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/dell.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0029 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/dfu.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/ebitdo.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/fastboot.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/nitrokey.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/nvme.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/rts54hid.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/rts54hub.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/solokey.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/steelseries.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/superio.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/synaptics-prometheus.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/synapticsmst.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/uefi-recovery.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/uefi.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/unifying.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0030 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/wacom-raw.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d/wacom-usb.quirk
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 FuQuirks             now 189 quirk entries
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 FuQuirks             no /var/lib/fwupd/quirks.d, skipping
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 FuEngine             remote lvfs-testing not enabled, so skipping
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 FuEngine             remote fwupd-tests not enabled, so skipping
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 FuEngine             remote vendor not enabled, so skipping
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 FuEngine             remote vendor-directory not enabled, so skipping
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 XbSilo               attempting to load /var/cache/fwupd/metadata.xmlb
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 XbSilo               0.02ms      parse blob
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 XbSilo               0.04ms      loaded file
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 XbSilo               file: 008006cd-b548-53e4-9eb7-f3d87e5ca547, current:008006cd-b548-53e4-9eb7-f3d87e5ca547, cached: (null)
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 XbSilo               loading silo with file contents
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 XbSilo               0.00ms      parse blob
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 XbSilo               0.17ms      query on / with `components/component` limit=0 -> 296 results
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 FuEngine             296 components now in silo
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 XbSilo               0.17ms      query on / with `components/component/provides/firmware` limit=0 -> 309 results
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0031 XbSilo               0.08ms      query on / with `components/component/provides/firmware` limit=0 -> 309 results
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0039 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_thunderbolt.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0040 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_thunderbolt.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0040 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_wacom_usb.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0040 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_wacom_usb.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0040 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_steelseries.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0041 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_steelseries.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0041 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_uefi.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0044 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_uefi.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0044 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_rts54hid.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0044 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_rts54hid.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0044 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_csr.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0044 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_csr.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0044 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_nitrokey.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0045 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_nitrokey.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0045 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_colorhug.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0045 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_colorhug.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0045 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_solokey.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0045 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_solokey.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0045 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_altos.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0046 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_altos.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0046 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_thunderbolt_power.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0046 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_thunderbolt_power.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0048 FuPluginThunderbolt  Direct kernel force power support at /sys/devices/platform/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/86CCFD48-205E-4A77-9C48-2021CBEDE341/force_power
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0048 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_nvme.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0048 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_nvme.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0048 FuPlugin             added udev subsystem watch of nvme
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0048 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_superio.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0049 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_superio.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0049 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_unifying.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0049 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_unifying.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0049 FuPlugin             added udev subsystem watch of hidraw
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0049 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_rts54hub.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0050 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_rts54hub.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0050 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_upower.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0050 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_upower.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0050 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_wacom_raw.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0050 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_wacom_raw.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0050 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_redfish.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0051 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_redfish.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0051 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_dell.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0051 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_dell.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0051 FuPluginDell         Using libsmbios 2.4
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0051 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_synaptics_prometheus.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0052 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_synaptics_prometheus.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0052 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_ebitdo.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0052 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_ebitdo.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0052 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_dfu.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0052 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_dfu.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0052 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_fastboot.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0053 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_fastboot.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0053 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_uefi_recovery.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0053 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_uefi_recovery.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0053 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_synapticsmst.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0053 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_synapticsmst.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0053 FuPlugin             added udev subsystem watch of drm
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0053 FuPlugin             added udev subsystem watch of drm_dp_aux_dev
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0053 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_amt.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0054 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_amt.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0054 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_dell_dock.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0054 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_dell_dock.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0054 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_ata.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0054 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_ata.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPlugin             added udev subsystem watch of block
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_udev.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_udev.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPlugin             added udev subsystem watch of pci
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuEngine             adding plugin /usr/lib/fwupd-plugins-3/libfu_plugin_dell_esrt.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPlugin             performing init() on /usr/lib/fwupd-plugins-3/libfu_plugin_dell_esrt.so
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPluginList         uefi [0] to be ordered after upower [0] so promoting to [1]
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPluginList         thunderbolt_power [0] to be ordered after thunderbolt [0] so promoting to [1]
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPluginList         dell [0] to be ordered after uefi [1] so promoting to [2]
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPluginList         uefi_recovery [0] to be ordered after uefi [1] so promoting to [2]
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPluginList         thunderbolt [0] better than dell_dock [0] so bumping to [1]
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPluginList         dell_dock [0] better than synapticsmst [0] so bumping to [1]
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPluginList         thunderbolt [1] better than dell_dock [1] so bumping to [2]
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuEngine             Emitting PropertyChanged('Status'='loading')
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuMain               Emitting PropertyChanged('Status'='loading')
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPlugin             performing startup() on thunderbolt
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPluginThunderbolt  Using kernel 5.2.11-arch1-1-ARCH (minimum 4.13.0)
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPlugin             performing startup() on unifying
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0055 FuPlugin             performing startup() on upower
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0059 FuPlugin             performing startup() on redfish
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0059 FuEngine             disabling plugin because: failed to startup using redfish: no SMBIOS table
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0059 FuPlugin             performing startup() on synapticsmst
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0060 FuPlugin             performing startup() on dell_esrt
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0060 FuEngine             disabling plugin because: failed to startup using dell_esrt: UEFI firmware already supported
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0060 FuPlugin             performing startup() on uefi
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0060 FuPlugin             performing startup() on dell
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0060 FuEngine             disabling plugin because: failed to startup using dell: Firmware updating not supported
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0060 FuPlugin             performing startup() on uefi_recovery
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0060 FuEngine             disabling plugin because: failed to startup using uefi_recovery: not required
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0060 FuPlugin             performing coldplug() on thunderbolt
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0060 FuPluginThunderbolt  adding udev device: c4010000-00a2-a098-a027-f21a2622c022 at /sys/devices/pci0000:00/0000:00:1d.0/0000:07:00.0/0000:08:00.0/0000:09:00.0/domain0/0-0
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0110 FuDevice             using 685059db1d7bba3ac49b1e7810636e1e64f7938b for c4010000-00a2-a098-a027-f21a2622c022
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0110 FuPlugin             emit added from thunderbolt: 685059db1d7bba3ac49b1e7810636e1e64f7938b
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0110 FuPlugin             performing fu_plugin_device_registered() on uefi
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0110 FuPlugin             performing fu_plugin_device_registered() on thunderbolt_power
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0113 FuPluginThunderbolt  Bolt force power support: 1
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0113 FuDeviceList         ::added 685059db1d7bba3ac49b1e7810636e1e64f7938b
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0114 XbSilo               0.52ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='eb8bf568-00a2-51e9-aa09-894358506c50']/../..` limit=1 -> 1 results
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0114 FuHistory            get device
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0114 FuCommon             not checking 14.00 as no version format set
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0114 FuIdle               inhibiting: thunderbolt requires device wakeup
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0114 FuPlugin             performing coldplug() on superio
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0114 FuPlugin             performing coldplug() on amt
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0114 FuEngine             disabling plugin because: failed to coldplug using amt: ME refused connection
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0114 FuPlugin             performing coldplug() on uefi
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0118 FuDevice             using facae3f8c9e996531c93d00358a7d5b40d3260f6 for UEFI-52dd29cd-24b9-4d60-8a45-e72670901924-dev0
Sep 13 16:32:10 saetre fwupd[2685213]: 15:32:10:0127 FIXME                initialized tabrmd TCTI context with id: 0x5c77736f576b9578
Sep 13 16:32:10 saetre systemd[1]: fwupd.service: Main process exited, code=dumped, status=5/TRAP
Sep 13 16:32:10 saetre systemd[1]: fwupd.service: Failed with result 'core-dump'.
Sep 13 16:32:10 saetre systemd[1]: Failed to start Firmware update daemon.
```

Please answer the following questions:

- Operating system and version: Archlinux
- How did you install fwupd (ex: `from source`, `pacman`, `apt-get`, etc): I updated the system package to 1.3.1
- Have you tried rebooting?  Yes
- Are you using an NVMe disk? Yes
- Is secure boot enabled (only for the UEFI plugin)? No

### PR DESCRIPTION
**Pull request by FFY00**
Fixes  #1353

Signed-off-by: Filipe Laíns <lains@archlinux.org>

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by diabonas** [comment]
As stated in https://github.com/fwupd/fwupd/issues/1353#issuecomment-531300924, I believe this is an upstream bug in tpm2-abrmd, or maybe a version mismatch of tpm2-tss and tpm2-abrmd in the Arch Linux repositories, as the code in fwupd doesn't depend on features introduced in 2.3 at the moment. Could you try uninstalling tpm2-abrmd and run with only tpm2-tss 2.2.1 installed? If this works without issues, it is definitely not a problem with fwupd.

That being said, I am not necessarily opposed to depending on the latest minor release (tpm2-tss 2.0 and 2.1 are EOL anyway), just saying that might not necessarily fix the problem (apart from having better error reporting instead of a crash, which I also can't understand).

**Comment by FFY00** [comment]
Removing `tpm2-abrmd` does indeed fix the issue, so I guess I should open a bug there.

I think we should check if this is arch specific, which I am not really convinced. If it's not then it might be good to merge this patch as it will not introduce any kind of limitation AFAIK.

@hughsie @diabonas any thoughts? Are any of you able to test this? I don't have any non-arch machines on me.

**Comment by diabonas** [comment]
The thing to consider is that this doesn't appear to be a problem with fwupd or tpm2-tss itself, it only manifests itself with the *optional* component tpm2-abrmd installed. What's more, even when the tpm2-tss version is bumped, it doesn't actually solve the problem, it only leads to a somewhat more meaningful error message instead of a crash.

On the other hand, the version bump forces everybody to update to the latest tpm2-tss version, which from fwupd's perspective alone wouldn't be necessary and might not happen on all distributions due to LTS considerations (tpm2-tss 2.2 is still supported). I think we shouldn't try to work around the problem in fwupd but fix tpm2-abrmd instead, bumping the tpm2-tss version requirement there if necessary.

I highly doubt this is an Arch-specific problem since we don't do anything special regarding the TPM kernel configuration or tpm2-software packaging in Arch. In fact I can't even reproduce this issue even on Arch with the repository versions of tpm2-tss, tpm2-abrmd and a self-compiled fwupd 1.3.1

**Comment by FFY00** [comment]
Closed in favor of #1361

**Pull request closed without merging**
