### PR TITLE
trivial: Add some Threat Modeling notes

### PR DESCRIPTION
**Pull request by hughsie**
I have to do this for a new Red Hat process, and I think it's easier to keep up to date if it's upstream.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [X] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 I think when we merge this the diagrams should appear -- you can use https://mermaid.live/ if you want a sneak preview.

**Comment by superm1** [comment]
Cool tool! TIL.

It renders here too.
https://github.com/fwupd/fwupd/blob/wip/hughsie/mermaid/SECURITY.md

You're missing entities for the kernel and firmware as data exchanges with both

**Comment by hughsie** [comment]
@superm1 how about that? I added a lot more words too.

**Comment by superm1** [comment]
> @superm1 how about that? I added a lot more words too.

So every threat model I've done includes a few things that I think are missing.  The tool might not support them but I'll mention them in case they can be added:
1. Extra dotted lines to show boundaries, for example a root / kernel boundary, a user / root boundary, web / app boundary.
2. ALL data flows.  This is very UEFI centric right now, but the daemon exchanges a lot of data with the kernel via IOCTLs, sysfs files, etc.  These could potentially be tampered with.  So either more flows needed or more assumptions needed (for example unless you assume UEFI SB trusted by MS + distro kernel under lockdown)

**Comment by hughsie** [comment]
> ALL data flows

I agree, but I don't think we need to enumerate everything on that diagram -- we already have it spelt out in the various plugin README.md files.

> Extra dotted lines to show boundaries

Will ponder. I think I can do a subgraph -- or maybe we just use different colors for different things? Will play -- this is iteration 1 afterall

**Comment by superm1** [comment]
Ah, that's great!  I think the "root" one needs to be split though.  Especially when you think about kernel lockdown; root isn't all powerful.  I think `root` should split into these categories.

`root`
`kernel`
`bios`
`platform`

Within platform you can then have these:
`bios`, `disk`

Within disk you can have the `efi system partition` as a data store.

Within bios you can have
`nvram` as a data store
`runtime services` as an API

**Comment by hughsie** [comment]
> Ah, that's great! I think the "root" one needs to be split though

Hmm, that gets very murky -- I'm trying to show *what* we trust, rather than explicitly show the different privilege layers. What I'm trying to explain is that fwupd-efi is trusted, and the user stuff is untrusted -- rather than showing the interfaces per-se.

I think the traditionally layers of rings diagram is useful, I just think it's an additional diagram. I have added a few of your ideas tho:

Screenshot 2023-08-10 at 19-05-34 Online FlowChart   Diagrams Editor - Mermaid Live Editor

**Comment by superm1** [comment]
Hmm, but the daemon does more to the ESP.  It puts the capsule loader onto the ESP too.  I really think the ESP should be a data store.   I think the problem is that this graph is compounding multiple steps that the daemon does.  The actual act of running the EFI application and what happens from that maybe it should be a separate graph.

**Comment by hughsie** [comment]
>  It puts the capsule loader onto the ESP too

Added

> I really think the ESP should be a data store

I've changed the icon, as I did the statedir and nvram.

>  The actual act of running the EFI application and what happens from that maybe it should be a separate graph

Once I've got the hang of this I was thinking of putting some of this in the plugin readme.md files.

**Comment by superm1** [comment]
I have an idea how to make it obvious that fwupdtool and fwupd support all the same stuff. How about you make an abstraction for the engine and everything that talks to the daemon instead talks to the engine.

**Comment by hughsie** [comment]
> make an abstraction for the engine

Done.

**Comment by superm1** [comment]
In the most recent push I was looking at it and saw what looks like an arrow to nothing.

image

Otherwise I'm happy with this.  I think we can add "low" level graphs for the individual plugins that show the data flows from the engine to the device/kernel as we go forward.

**Review by superm1 — APPROVED** [review]

**Pull request merged**
