### PR TITLE
contrib/ci: Add libpgiod to dependencies

### PR DESCRIPTION
**Pull request by Sean-StarLabs**
Signed-off-by: Sean Rhodes <sean@starlabs.systems>

### CODE REVIEW

**Comment by superm1** [comment]
Why is this needed?  I thought `linux/gpio.h` comes from the linux headers.  Does this fix anything?

**Comment by Sean-StarLabs** [comment]
Not sure on the first - might be an Ubuntu special as I didn't try building for others.
Fixes building:
```
plugins/gpio/meson.build:6:2: ERROR: Problem encountered: linux/gpio.h (with API v2) is required for plugin_gpio
```

**Comment by Sean-StarLabs** [comment]
Might be more helpful - https://launchpadlibrarian.net/586733816/buildlog_ubuntu-focal-amd64.fwupd_1.7.6+f_BUILDING.txt.gz

**Comment by hughsie** [comment]
Nah, linux/gpio.h is a linux header not a userspace thing. Maybe it makes sense to ship a copy in-tree?

**Comment by hughsie** [comment]
> But so they could just -Dplugin_gpio=true or -Dplugin_gpio=false couldn't they?

I think the idea is that we should define a default and not make the deliverable different depending on what headers are installed on the specific system.

**Comment by hughsie** [comment]
>  I do think we should take a copy of the GPIO header

Isn't that going to be GPLv2 rather than the 99% LGPLv+ and 1% GPLv2+ stuff we have now? Maybe we just fix the message to say "kernel too old"?

**Comment by superm1** [comment]
I didn't think about the licensing implication - good point.  How about we just set the plugin to disabled by default for now then.  The cases that we know build kernel is new enough and it's needed we turn it on.

**Comment by eli-schwartz** [comment]
> I think then we get shouted at by the automagic-hating people: https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies

The good news is that Meson's builtin tristate option, "feature" options, has a core builtin option just for automagic-hating people.

```
--auto-features=disabled
```

So that when building projects which have auto detection of dependencies, they can be globally forced on or off.

Automagic dependencies specifically refers to cases where you cannot pass an option to disable it, you need to patch the build files. Manually coding yes/no/check as a tristate in configure.ac is the classic recommended route, and even defaulting to "check" is considered fine. Meson's auto-features takes that a step further.

**Comment by hughsie** [comment]
I also switched around the gpio default. Lets close this one and concentrate on the feature flags.

**Pull request closed without merging**
