### PR TITLE
Always check the BDP partitions when getting all the possible ESPs

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/5035

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 I'm not sure on the *name*....

**Comment by superm1** [comment]
What exactly is BDP?  I don't remember what that GUID represents and our comment is equally helpful.
https://fwupd.github.io/libfwupdplugin/const.VOLUME_KIND_BDP.html

**Comment by hughsie** [comment]
BDP: https://en.wikipedia.org/wiki/Microsoft_basic_data_partition

**Comment by superm1** [comment]
> BDP: https://en.wikipedia.org/wiki/Microsoft_basic_data_partition

ah we should have that link in the documentation too!  Will look at this with that in mind.

**Review by superm1 — APPROVED** [review]

**Comment by hughsie** [comment]
> we should have that link in the documentation too

Done.

**Pull request merged**
