### PR TITLE
Wip/hughsie/android boot

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by DylanVanAssche** [comment]
This segfaults:

```
shift-axolotl:/home/dylan# /usr/libexec/fwupd/fwupd -v
17:20:25:0026 FuDebug              Verbose debugging enabled (on console 1)
17:20:25:0027 FuConfig             trying to load config values from /etc/fwupd/daemon.conf
17:20:25:0027 FuCommon             reading /etc/fwupd/daemon.conf with 2081 bytes
17:20:25:0027 FuConfig             trying to load config values from /var/etc/fwupd/daemon.conf
17:20:25:0027 FuConfig             using autodetected max archive size 18.4 EB
17:20:25:0028 FuRemoteList         loading /usr/share/fwupd/metainfo
17:20:25:0028 XbSilo               attempting to load /var/cache/fwupd/metainfo.xmlb
17:20:25:0028 XbSilo               file: 49551d35-e16f-74b3-d130-82dd6fd45026, current:bb93828f-9373-bfe2-eddd-4e2301e4344c, cached: (null)
17:20:25:0033 FuRemoteList         loading remote from /etc/fwupd/remotes.d/lvfs.conf
17:20:25:0034 FuRemoteList         skipping invalid file /etc/fwupd/remotes.d/vendor-directory.conf.apk-new
17:20:25:0034 FuRemoteList         loading remote from /etc/fwupd/remotes.d/vendor.conf
17:20:25:0034 FuRemoteList         loading remote from /etc/fwupd/remotes.d/lvfs-testing.conf
17:20:25:0034 FuRemoteList         loading remote from /etc/fwupd/remotes.d/vendor-directory.conf
17:20:25:0034 FuRemoteList         loading remote from /etc/fwupd/remotes.d/fwupd-tests.conf
17:20:25:0035 FuRemoteList         ignoring unfound remote fwupd
17:20:25:0035 FuRemoteList         ordering lvfs-testing=lvfs+1
17:20:25:0035 Jcat                 ignoring GPG-KEY-Linux-Vendor-Firmware-Service as not PKCS-7 certificate
17:20:25:0035 Jcat                 ignoring GPG-KEY-Linux-Foundation-Firmware as not PKCS-7 certificate
17:20:25:0035 Jcat                 reading /etc/pki/fwupd/LVFS-CA.pem with 1679 bytes
17:20:25:0035 Jcat                 loaded 1 certificates
17:20:25:0035 Jcat                 ignoring GPG-KEY-Linux-Vendor-Firmware-Service as not PKCS-7 certificate
17:20:25:0035 Jcat                 ignoring GPG-KEY-Linux-Foundation-Metadata as not PKCS-7 certificate
17:20:25:0035 Jcat                 reading /etc/pki/fwupd-metadata/LVFS-CA.pem with 1679 bytes
17:20:25:0035 Jcat                 loaded 1 certificates
17:20:25:0035 Jcat                 reading /var/lib/fwupd/pki/secret.key with 2455 bytes
17:20:25:0035 Jcat                 reading /var/lib/fwupd/pki/client.pem with 1383 bytes
17:20:25:0035 FuEngine             client certificate now exists: nothing to do
17:20:25:0036 FuHistory            trying to open database '/var/lib/fwupd/pending.db'
17:20:25:0036 FuHistory            got schema version of 8
17:20:25:0037 FuIdle               setting timeout to 7200s
17:20:25:0078 FuCommon             reading /proc/self/exe with 330472 bytes
17:20:25:0081 FuQuirks             loading quirks from /usr/share/fwupd/quirks.d
17:20:25:0081 FuQuirks             loading quirks from /var/lib/fwupd/quirks.d
17:20:25:0081 XbSilo               attempting to load /var/cache/fwupd/quirks.xmlb
17:20:25:0081 XbSilo               file: 8a707045-95de-d2ae-8b45-4024c0db60af, current:e3356d23-a76d-337f-2a40-595bedaa8fe7, cached: (null)
17:20:25:0104 FuQuirks             invalid key names: AndroidBootVersionProperty,CcgxDmcTriggerCode,CcgxFlashRowSize,CcgxFlashSize,CcgxImageKind,CorsairDeviceKind,CxaudioChipIdBase,CxaudioPatch1ValidAddr,CxaudioPatch2ValidAddr,DellDockBlobBuildOffset,DellDockBlobMajorOffset,DellDockBlobMinorOffset,DellDockBlobVersionOffset,DellDockBoardMin,DellDockHubVersionLowest,DellDockInstallDurationI2C,DellDockUnlockTarget,DellDockVersionLowest,DfuAltName,DfuForceTimeout,DfuForceVersion,ElantpI2cTargetAddress,ElantpIapPassword,ElantpIcPageCount,FastbootBlockSize,FastbootOperationDelay,GenesysScalerCfiFlashId,GenesysScalerGpioEnableRegister,GenesysScalerGpioOutputRegister,GenesysScalerGpioValue,GenesysUsbhubReadRequest,GenesysUsbhubSwitchRequest,GenesysUsbhubWriteRequest,JabraMagic,LogitechHidppModelId,ModemManagerBranchAtCommand,NordicHidBootloader,ParadeLspconAuxDeviceName,PciBcrAddr,RealtekMstDpAuxName,RealtekMstDrmCardKernelName,Rts54I2cSpeed,Rts54RegisterAddrLen,Rts54TargetAddr,SuperioAutoloadAction,SuperioControlPort,SuperioDataPort,SuperioGType,SuperioId,SuperioPort,SuperioTimeout,SynapticsMstDeviceKind,WacomI2cFlashBaseAddr,WacomI2cFlashBlockSize,WacomI2cFlashSize
17:20:25:0105 FuHwids              loading HwId overrides from /etc/fwupd/daemon.conf
17:20:25:0105 FuHwids              not loading HwId overrides from /var/lib/fwupd/daemon.conf
17:20:25:0105 FuHwids              smbios property Manufacturer=shift
17:20:25:0105 FuHwids              smbios property EnclosureKind=8
17:20:25:0105 FuHwids              ignoring Family: offset bigger than size 6
17:20:25:0105 FuHwids              smbios property ProductName=SHIFT SHIFT6mq
17:20:25:0105 FuHwids              ignoring ProductSku: offset bigger than size 6
17:20:25:0105 FuHwids              ignoring BiosVendor: offset bigger than size 0
17:20:25:0105 FuHwids              ignoring BiosVersion: offset bigger than size 0
17:20:25:0105 FuHwids              ignoring BiosMajorRelease: offset bigger than size 0
17:20:25:0105 FuHwids              ignoring BiosMinorRelease: offset bigger than size 0
17:20:25:0105 FuHwids              ignoring FirmwareMajorRelease: offset bigger than size 0
17:20:25:0105 FuHwids              ignoring FirmwareMinorRelease: offset bigger than size 0
17:20:25:0105 FuHwids              ignoring BaseboardManufacturer: offset bigger than size 0
17:20:25:0105 FuHwids              ignoring BaseboardProduct: offset bigger than size 0
17:20:25:0105 FuHwids              HardwareID-0 is not available, not available as 'Family' unknown
17:20:25:0105 FuHwids              HardwareID-1 is not available, not available as 'Family' unknown
17:20:25:0105 FuHwids              HardwareID-2 is not available, not available as 'BiosVendor' unknown
17:20:25:0105 FuHwids              HardwareID-3 is not available, not available as 'Family' unknown
17:20:25:0105 FuHwids              HardwareID-4 is not available, not available as 'Family' unknown
17:20:25:0105 FuHwids              HardwareID-5 is not available, not available as 'Family' unknown
17:20:25:0105 FuHwids              HardwareID-6 is not available, not available as 'ProductSku' unknown
17:20:25:0105 FuHwids              HardwareID-7 is not available, not available as 'ProductSku' unknown
17:20:25:0106 FuHwids              HardwareID-8 is not available, not available as 'BaseboardManufacturer' unknown
17:20:25:0106 FuHwids              HardwareID-10 is not available, not available as 'Family' unknown
17:20:25:0106 FuHwids              HardwareID-11 is not available, not available as 'Family' unknown
17:20:25:0106 FuHwids              HardwareID-13 is not available, not available as 'BaseboardManufacturer' unknown
17:20:25:0107 FuContext            added udev subsystem watch of firmware-attributes
17:20:25:0107 FuContext            Error opening directory “/sys/class/firmware-attributes”: No such file or directory
17:20:25:0108 FuEngine             building metadata for remote 'vendor-directory'
17:20:25:0108 FuEngine             building metadata for /usr/share/fwupd/remotes.d/vendor/firmware/abl_3.9.20220831.cab
17:20:25:0108 FuCommon             reading /usr/share/fwupd/remotes.d/vendor/firmware/abl_3.9.20220831.cab with 293209 bytes
17:20:25:0108 FuMain               Emitting PropertyChanged('Status'='decompressing')
17:20:25:0113 FuCabinet            failed to verify abl_3.9.20220831.metainfo.xml: no JcatItem
17:20:25:0113 FuCabinet            processing file: abl_3.9.20220831.metainfo.xml
17:20:25:0113 FuCabinet            processing release: 3.9.20220831
17:20:25:0115 FuEngine             ignoring: /usr/share/fwupd/remotes.d/vendor/firmware/README.md
17:20:25:0115 FuEngine             ignoring: Error opening directory “/var/lib/fwupd/local.d”: No such file or directory
17:20:25:0115 FuEngine             ignoring: Error opening directory “/usr/share/fwupd/local.d”: No such file or directory
17:20:25:0115 XbSilo               attempting to load /var/cache/fwupd/metadata.xmlb
17:20:25:0115 XbSilo               file: 9b3b2e57-9989-e11b-dd47-b870e08627de, current:9b3b2e57-9989-e11b-dd47-b870e08627de, cached: (null)
17:20:25:0115 XbSilo               loading silo with file contents
17:20:25:0118 FuEngine             1594 components now in silo
17:20:25:0127 FuEngine             failed to setup backend usb: failed to get USB context: failed to init libusb: Other error [-99]
17:20:25:0139 FuPlugin             init(android_boot)
17:20:25:0139 FuContext            added udev subsystem watch of block
17:20:25:0141 FuContext            battery threshold now 10
17:20:25:0141 FuMain               Emitting PropertyChanged('Status'='loading')
17:20:25:0141 FuEngine             using plugins: android_boot
17:20:25:0156 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda: no plugin ata found
17:20:25:0156 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda: no plugin scsi found
17:20:25:0156 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda: no plugin uf2 found
17:20:25:0156 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda: no plugin emmc found
17:20:25:0158 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda1: no plugin ata found
17:20:25:0158 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda1: no plugin scsi found
17:20:25:0158 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda1: no plugin uf2 found
17:20:25:0158 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda1: no plugin emmc found
17:20:25:0160 FuDevice             unknown device overwriting name value: H28S8Q302CMR->ssd
17:20:25:0161 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda2: no plugin ata found
17:20:25:0161 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda2: no plugin scsi found
17:20:25:0161 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda2: no plugin uf2 found
17:20:25:0161 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda2: no plugin emmc found
17:20:25:0162 FuDevice             unknown device overwriting name value: H28S8Q302CMR->persist
17:20:25:0163 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda3: no plugin ata found
17:20:25:0163 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda3: no plugin scsi found
17:20:25:0163 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda3: no plugin uf2 found
17:20:25:0164 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda3: no plugin emmc found
17:20:25:0165 FuDevice             unknown device overwriting name value: H28S8Q302CMR->misc
17:20:25:0166 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda4: no plugin ata found
17:20:25:0166 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda4: no plugin scsi found
17:20:25:0166 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda4: no plugin uf2 found
17:20:25:0166 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda4: no plugin emmc found
17:20:25:0167 FuDevice             unknown device overwriting name value: H28S8Q302CMR->keystore
17:20:25:0168 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda5: no plugin ata found
17:20:25:0169 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda5: no plugin scsi found
17:20:25:0169 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda5: no plugin uf2 found
17:20:25:0169 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda5: no plugin emmc found
17:20:25:0170 FuDevice             unknown device overwriting name value: H28S8Q302CMR->oem
17:20:25:0171 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda6: no plugin ata found
17:20:25:0171 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda6: no plugin scsi found
17:20:25:0171 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda6: no plugin uf2 found
17:20:25:0171 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda6: no plugin emmc found
17:20:25:0172 FuDevice             unknown device overwriting name value: H28S8Q302CMR->frp
17:20:25:0174 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda7: no plugin ata found
17:20:25:0174 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda7: no plugin scsi found
17:20:25:0174 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda7: no plugin uf2 found
17:20:25:0174 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda7: no plugin emmc found
17:20:25:0175 FuDevice             unknown device overwriting name value: H28S8Q302CMR->super
17:20:25:0176 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda8: no plugin ata found
17:20:25:0176 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda8: no plugin scsi found
17:20:25:0176 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda8: no plugin uf2 found
17:20:25:0176 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda8: no plugin emmc found
17:20:25:0177 FuDevice             unknown device overwriting name value: H28S8Q302CMR->metadata
17:20:25:0178 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda9: no plugin ata found
17:20:25:0178 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda9: no plugin scsi found
17:20:25:0178 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda9: no plugin uf2 found
17:20:25:0178 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:0/block/sda/sda9: no plugin emmc found
17:20:25:0179 FuDevice             unknown device overwriting name value: H28S8Q302CMR->userdata
17:20:25:0181 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:1/block/sdb: no plugin ata found
17:20:25:0181 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:1/block/sdb: no plugin scsi found
17:20:25:0181 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:1/block/sdb: no plugin uf2 found
17:20:25:0181 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:1/block/sdb: no plugin emmc found
17:20:25:0183 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:1/block/sdb/sdb1: no plugin ata found
17:20:25:0183 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:1/block/sdb/sdb1: no plugin scsi found
17:20:25:0183 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:1/block/sdb/sdb1: no plugin uf2 found
17:20:25:0183 FuEngine             failed to add device /sys/devices/platform/soc@0/1d84000.ufshc/host0/target0:0:0/0:0:0:1/block/sdb/sdb1: no plugin emmc found
17:20:25:0184 FuDevice             unknown device overwriting name value: H28S8Q302CMR->xbl a
Segmentation fault
```

gdb trace:

```
17:21:18:0521 FuDevice             unknown device overwriting name value: H28S8Q302CMR->xbl a

Thread 1 "fwupd" received signal SIGSEGV, Segmentation fault.
get_meta (p=p@entry=0xfffff5fdafa0 "S6MQ02056409699") at src/malloc/mallocng/meta.h:141
141	src/malloc/mallocng/meta.h: No such file or directory.
(gdb) bt
#0  get_meta (p=p@entry=0xfffff5fdafa0 "S6MQ02056409699") at src/malloc/mallocng/meta.h:141
#1  0x0000fffff7f7b2b4 in __libc_free (p=0xfffff5fdafa0) at src/malloc/mallocng/free.c:105
#2  0x0000fffff673b874 in ?? () from /usr/lib/fwupd-plugins-7/libfu_plugin_android_boot.so
#3  0x0000fffff7e829b8 in fu_device_probe () from /usr/lib/libfwupdplugin.so.7
#4  0x0000fffff7e878a4 in ?? () from /usr/lib/libfwupdplugin.so.7
#5  0x0000fffff7e7ef98 in fu_device_locker_new_full () from /usr/lib/libfwupdplugin.so.7
#6  0x0000fffff7ea1220 in fu_plugin_runner_backend_device_added () from /usr/lib/libfwupdplugin.so.7
#7  0x0000aaaaaaac9e88 in ?? ()
#8  0x0000aaaaaaad061c in fu_engine_load ()
#9  0x0000aaaaaaabee30 in fu_daemon_setup ()
#10 0x0000aaaaaaab6f30 in main ()
``

**Review by DylanVanAssche — CHANGES_REQUESTED** [review]
Seems that the segfaults happens in the `fu_device_probe`.

**Comment by hughsie** [comment]
You got debug symbols handy? That was unexpected...

**Comment by DylanVanAssche** [comment]
> You got debug symbols handy? That was unexpected...

I have `fwupd-dbg` installed (the one providing debug symbols), but I don't see why they are not completely appearing in the gdb trace. Probably a mistake in the distro packaging. I have a heavy week so looking into this will take some time I'm afraid. All my PRs were finished before my $DAYJOB resumed ;)

**Comment by hughsie** [comment]
Agreed. See if you can get a complete backtrace. The patches here fix ~20 critical warnings on my startup 🙂

**Pull request merged**
