### PR TITLE
Wip/hughsie/config comments main

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]

**Comment by superm1** [comment]
Can you post some sample files that crashed?

**Comment by hughsie** [comment]
It was this:

	[fwupd]
	DisabledPlugins=test;test_ble
	OnlyTrusted=true
	AllowEmulation=false
	DisabledPlugins=test;test_ble
	IgnorePower=false
	OnlyTrusted=true
	AllowEmulation=false

	[msr]
	MinimumSmeKernelVersion=5.18.0

	[redfish]

	[thunderbolt]
	MinimumKernelVersion=4.13.0
	DelayedActivation=false
	RetimerOfflineMode=false

	[uefi_capsule]

The issue was that [redfish] had no keys.

**Comment by superm1** [comment]
Maybe it was tied specifically to a test with an upgrade from from 1.9.11-1 to 1.9.12-4?
```
 85s Unpacking fwupd (1.9.12-4) over (1.9.11-1) ...
```

**Comment by hughsie** [comment]
Yes; I think it's worth doing a 1.9.13 next week with that and the UEFI verfmt history patch -- the latter needing confirmation from the OEM that it actually works...

**Pull request merged**
