### PR TITLE
Wip/hughsie/coverage pefile

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 the debian CI seems unhappy: `E: fwupd source: missing-build-dependency-for-dh-addonebian/rules]`

**Comment by superm1** [comment]
Seems the rendering of the color coding hid the real error.

```
2024-02-13T20:29:47.5819623Z E: fwupd source: ]8;;https://lintian.debian.org/tags/missing-build-dependency-for-dh-addon[97;101mmissing-build-dependency-for-dh-addon[0m]8;; gir (does not satisfy gobject-introspection-bin:any) [debian/rules]
```

**Comment by hughsie** [comment]
Does that mean more to you than me? If you know the fix, please just dump it on this branch and we can merge it together.

**Comment by superm1** [comment]
I guess lintian is being more pedantic about a missing package.  lintian just migrated from unstable to testing today, so this must be a new error from the new lintian:

https://tracker.debian.org/news/1501297/accepted-lintian-21170-source-into-unstable/

I'm not sure what package it is though.

**Pull request merged**
