### PR TITLE
trivial: don't offer to upload reports for 0 length report URIs

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
The other alternative that probably fixes this is to adjust fwupd-remote.c and check the length of the string being set and make the failure mode return NULL there.

**Comment by hughsie** [comment]
That's what I was going to suggest as a counter argument. It saves all the mess of checking at the caller for NULL or "". I can have a go at this on Friday if that helps.

**Comment by superm1** [comment]
> That's what I was going to suggest as a counter argument. It saves all the mess of checking at the caller for NULL or "". I can have a go at this on Friday if that helps.

just adjusted it

**Comment by hughsie** [comment]
Alternate proposal in https://github.com/fwupd/fwupd/pull/3557

**Comment by superm1** [comment]
Sure, looks better.

**Pull request closed without merging**
