### PR TITLE
Only accept application/x-xz compression for the metadata payload

### PR DESCRIPTION
**Pull request by hughsie**
Fixes some of https://github.com/fwupd/fwupd/issues/5553

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
why not also support gzip? for flexibility?

**Comment by hughsie** [comment]
> why not also support gzip

I think it makes it a lot less complicated to only support the one format; I don't think we want to get into the game of decompressing the gzip and compressing it in into a xz when updating the metadata. Using local files for refresh is kinda a debug function and I'd rather just fix the LVFS issue.

**Comment by superm1** [comment]
> > why not also support gzip
> 
> I think it makes it a lot less complicated to only support the one format; I don't think we want to get into the game of decompressing the gzip and compressing it in into a xz when updating the metadata. Using local files for refresh is kinda a debug function and I'd rather just fix the LVFS issue.

OK sounds good.

**Comment by hughsie** [comment]
The other point is we're kinda using the format as an API version -- e.g. in the gz we don't include <artifact> and in the xz we include the tested_by stuff -- i.e. optimizing the metadata contents for the fwupd version we know will support it. e.g. if we ever moved to zstd we could drop some of the artifact source fixups in that.

**Review by superm1 — APPROVED** [review]

**Comment by marmarek** [comment]
How can I get from fwupd which format it expects (for `refresh` call)?

**Comment by hughsie** [comment]
We only support xz now. You can grab that from https://cdn.fwupd.org/downloads/firmware.xml.xz

**Comment by marmarek** [comment]
that I know, but given arbitrary fwupd version, how can I ask it which format it expects?

**Comment by hughsie** [comment]
Hm, now that is a good question. I guess give it xz first, and if there's an error give it gz instead. I'm open for ideas.

**Comment by marmarek** [comment]
Add some explicit info in `fwupd --version`? Or at least declare which version switched the accepted/default compressions? It was a build option for some time, right? if so, just declaring version might not be enough...
How many versions were accepting gz but really expecting xz?

**Comment by marmarek** [comment]
For xz/gz it's probably too late anyway, but could help with future changes (zstd?).

**Comment by hughsie** [comment]
I think for now, using `fwupdmgr --version --json` and then checking the fwupd version is the only thing you can do. 1.8.7 and newer use xz. Lets go back a bit; I think you're the only person other than me to use the _load local files as metadata_ functionality -- are you trying to work around something else we should fix?

**Comment by marmarek** [comment]
I'm finishing/updating qubes integration. fwupd runs in dom0 where you don't have direct network access, only dedicated VM (aka "updatevm") can download stuff. So, a wrapper script downloads stuff in that dedicated VM, verifies its integrity (as extra precaution) and only then passes it to fwupd. It's done for both metadata and actual updates.

**Comment by hughsie** [comment]
I'm hesitant to just say "we can just convert the .gz to .xz in fwupd" as the different metadata files have subtly different contents. Could you look at the MetadataURI in /etc/fwupd/remotes.d/lvfs.conf and use that perhaps?

**Pull request merged**
