### PR TITLE
Allow getting the ESP when there is a block device with no filesystem

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/5313

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@shahms can you test this please.

**Comment by hughsie** [comment]
I can build you a Fedora 37 rpm if that would help.

**Comment by shahms** [comment]
Happy to do so. A fedora 37 rpm would be much appreciated; fwupd has a lot of dependencies.

**Comment by hughsie** [comment]
@shahms build available here: https://copr.fedorainfracloud.org/coprs/rhughes/fwupd/

**Comment by shahms** [comment]
It fixes printing an error, but now says there are no available updates for it via `fwupdmgr update`  and `fwupdmg get-devices` prints:
```
└─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI revocation database
│       Current version:  83
│       Minimum Version:  83
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            fda6234b-adcb-5105-8515-9af647d29775 ← UEFI\CRT_D7F66BE77CEF858C174BF4338A99263C8795B74E02026411F5F532F716AE3263
│                         f8ff0d50-c757-5dc3-951a-39d86e16f419 ← UEFI\CRT_D7F66BE77CEF858C174BF4338A99263C8795B74E02026411F5F532F716AE3263&ARCH_X64
│                         c6682ade-b5ec-57c4-b687-676351208742 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503
│                         f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
│                         7d5759e5-9aa0-5f0c-abd6-7439bb11b9f6 ← UEFI\CRT_ED1FE72CB9CA31C9AF5B757AFCD733323D675825032E6CED7FE1AE9EB767998C
│                         0c7691e1-b6f2-5d71-bc9c-aabee364c916 ← UEFI\CRT_ED1FE72CB9CA31C9AF5B757AFCD733323D675825032E6CED7FE1AE9EB767998C&ARCH_X64
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Only version upgrades are allowed
│                         • Signed Payload
...
________________________________________________

Devices that were not updated correctly:

 • UEFI dbx (83 → 217)
```

**Comment by hughsie** [comment]
> says there are no available updates for it

Mea culpa, that was https://github.com/fwupd/fwupd/pull/5336

I'll merge this PR as it seems to fix the issue, and build a new rpm for you to test with the branches combined.

**Comment by hughsie** [comment]
I've updated the COPR.

**Comment by shahms** [comment]
After updating to fwupd-1.8.9-0.949.20221215git.fc37.x86_64 from the COPR, the update still isn't applied. Is this the right version?

`fwupdmgr update` exits with the same error, `fwupdtool update` issues the error, then asks if I want to reboot (as if the update was applied successfully). Upon rebooting, the dbx version is unchanged.

**Comment by hughsie** [comment]
The same Filesystem failure text after `Blocked executable in the ESP, ensure grub and shim are up to date`? or an actual file?

**Comment by shahms** [comment]
Same error, yeah:
```
Blocked executable in the ESP, ensure grub and shim are up to date: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.UDisks2.Filesystem” on object at path /org/freedesktop/UDisks2/block_devices/sda1
```

**Comment by hughsie** [comment]
Can you try with  1.8.9-0.950.20221215git.fc37  please? If that's the same then you need to explain how to set up a system just like yours so I can reproduce it myself. :)

**Comment by shahms** [comment]
Still fails, with the same error, but looking higher up in the output is a "failed to mount ESP" error that might be relevant:
```
$ rpm -qf `which fwupdtool`
fwupd-1.8.9-0.950.20221215git.fc37.x86_64
[shahms@throne:~]
$ sudo fwupdtool update
Loading…                 [*****                                  ]23:06:41.793 FuPluginUefiCapsule  failed to mount ESP: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.UDisks2.Filesystem” on object at path /org/freedesktop/UDisks2/block_devices/sda1
Loading…                 [**********                             ]23:06:42.187 FuEngine             failed to add device usb:03:00:01:01: no CFI device found
Loading…                 [******************                     ]23:06:42.448 FuPluginIntelMe      failed to get public key using /fpf/OemCred: generic failure [0xb]
Loading…                 [-                                      ]
Devices with no available firmware updates: 
 • BCM920702 Bluetooth 4.0
 • HGST HDN724030ALE640
 • INTEL MEMPEK1W016GA
 • SSD 850 EVO 1TB
 • SSD 850 EVO 500GB
 • SSD 860 EVO 500GB
 • System Firmware
 • Unifying Receiver
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade UEFI dbx from 83 to 217?                                             ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ This updates the dbx to the latest release from Microsoft which adds         ║
║ insecure versions of grub and shim to the list of forbidden signatures due   ║
║ to multiple discovered security updates.                                     ║
║                                                                              ║
║ Before installing the update, fwupd will check for any affected executables  ║
║ in the ESP and will refuse to update if it finds any boot binaries signed    ║
║ with any of the forbidden signatures. If the installation fails, you will    ║
║ need to update shim and grub packages before the update can be deployed.     ║
║                                                                              ║
║ Once you have installed this dbx update, any DVD or USB installer images     ║
║ signed with the old signatures may not work correctly. You may have to       ║
║ temporarily turn off secure boot when using recovery or installation media,  ║
║ if new images have not been made available by your distribution.             ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝

Perform operation? [Y|n]: y
Writing…                 [***************************************]
Waiting…                 [***************************************]
Writing…                 [***************************************]
Restarting device…       [***************************************]
Writing…                 [***************************************]
Decompressing…           [***************************************]
Blocked executable in the ESP, ensure grub and shim are up to date: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.UDisks2.Filesystem” on object at path /org/freedesktop/UDisks2/block_devices/sda1

An update requires a reboot to complete. Restart now? [y|N]: n
```

**Comment by shahms** [comment]
Running the same update with -v has some additional information which may be useful:
```
23:14:37.923 FuVolume             unmounting /org/freedesktop/UDisks2/block_devices/sdc2
23:14:37.949 FuVolume             mounting /org/freedesktop/UDisks2/block_devices/sda1
23:14:37.949 FuVolume             unmounting /org/freedesktop/UDisks2/block_devices/sda1
23:14:37.950 FuDeviceLocker       ignoring close error on aborted open: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.UDisks2.Filesystem” on object at path /org/freedesktop/UDisks2/block_devices/sda1
23:14:37.950 FuPlugin             attach(uefi_dbx)
23:14:37.950 FuDeviceList         no replug or re-enumerate required
23:14:37.950 FuHistory            modifying device UEFI dbx [362301da643102b9f38477387e2193e57abaa590]
23:14:37.954 FuEngine             cleanup -> FuUefiDbxDevice:
  DeviceId:             362301da643102b9f38477387e2193e57abaa590
  CompositeId:          a45df35ac0e948ee180fe216a5f703f32dda163f
  Name:                 UEFI dbx
  Guid:                 fda6234b-adcb-5105-8515-9af647d29775 ← UEFI\CRT_D7F66BE77CEF858C174BF4338A99263C8795B74E02026411F5F532F716AE3263
  Guid:                 f8ff0d50-c757-5dc3-951a-39d86e16f419 ← UEFI\CRT_D7F66BE77CEF858C174BF4338A99263C8795B74E02026411F5F532F716AE3263&ARCH_X64
  Guid:                 c6682ade-b5ec-57c4-b687-676351208742 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503
  Guid:                 f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
  Guid:                 7d5759e5-9aa0-5f0c-abd6-7439bb11b9f6 ← UEFI\CRT_ED1FE72CB9CA31C9AF5B757AFCD733323D675825032E6CED7FE1AE9EB767998C
  Guid:                 0c7691e1-b6f2-5d71-bc9c-aabee364c916 ← UEFI\CRT_ED1FE72CB9CA31C9AF5B757AFCD733323D675825032E6CED7FE1AE9EB767998C&ARCH_X64
  Summary:              UEFI revocation database
  Plugin:               uefi_dbx
  Protocol:             org.uefi.dbx
  Flags:                internal|updatable|supported|registered|needs-reboot|usable-during-update|only-version-upgrade|signed-payload
  VendorId:             UEFI:Linux Foundation
  Version:              83
  VersionLowest:        83
  VersionFormat:        number
  Icon:                 computer
  InstallDuration:      1
  Created:              2022-12-15
  Modified:             2022-12-15
  PhysicalId:           dbx
  AcquiesceDelay:       50
  Order:                -1

23:14:37.954 FuPlugin             cleanup(gpio)
23:14:37.954 FuPlugin             cleanup(jabra)
23:14:37.954 FuPlugin             cleanup(logind)
23:14:37.954 FuPluginLogind       closed logind fd 20
23:14:37.954 FuDeviceList         no replug or re-enumerate required
23:14:37.954 FuHistory            modifying device UEFI dbx [362301da643102b9f38477387e2193e57abaa590]
23:14:37.957 FuHistory            modifying device UEFI dbx [362301da643102b9f38477387e2193e57abaa590]
23:14:37.961 FuPlugin             composite_cleanup(dell_dock)
23:14:37.961 FuPlugin             composite_cleanup(thunderbolt)
23:14:37.961 FuIdle               uninhibiting: update
```

**Comment by shahms** [comment]
It looks like the `g_dbus_proxy_new_sync` call is succeeding (despite the lack of the requisite interface) and not failing until a method is called (via `fu_volume_locker`).

Looking into it a bit more, it appears as though `g_dbus_proxy_new_sync` doesn't check that the interface is implemented: https://github.com/GNOME/glib/blob/ded3099afca49234f407f67d96b99e684a8ff336/gio/gdbusproxy.c#L2093

So it isn't until something attempts to use a method on that interface that the error is actually thrown :-(

**Comment by shahms** [comment]
That appears to do it! (Still logs some errors, but the update is applied successfully) Thanks!

**Comment by superm1** [comment]
> That appears to do it! (Still logs some errors, but the update is applied successfully) Thanks!

To be expected you'll get a warning; we wanted to make sure it was clear that this happened because this is not the standard path that we see normally.

**Pull request merged**
