### PR TITLE
Update TUXEDO quirks

### PR DESCRIPTION
**Pull request by Matombo**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

Updating quirks for TUXEDO devices:
- TUXEDO InfinityBook S 14/15 Gen6 GUID where based on older DMI strings that didn't actually ship
- New GUIDs for TUXEDO InfinityBook Pro 13 v3 (only for BIOS/flashrom plugin as EC/superio plugin is not yet tested on this device

I noticed that the fn-m-me-unlock flag doesn't actually do anything? At least from the command line. Is the promt to reboot with FN+M pressed only for GUI or am I encountering a bug?

### CODE REVIEW

**Comment by hughsie** [comment]
> I noticed that the fn-m-me-unlock flag doesn't actually do anything

Hmm, that's news to me. Can you debug it a bit and see what you can find please?

**Review by hughsie — APPROVED** [review]

**Comment by Matombo** [comment]
> > I noticed that the fn-m-me-unlock flag doesn't actually do anything
> 
> Hmm, that's news to me. Can you debug it a bit and see what you can find please?

Looking in the code, the flag only does something if the region is recognized as a FU_IFD_REGION_ME, but do i interpret the get-device output correctly that the whole chip is recognized as jsut a singular BIOS region?

[get-devices_dump.txt](https://github.com/fwupd/fwupd/files/11837553/get-devices_dump.txt)

**Comment by hughsie** [comment]
> that the whole chip is recognized as just a singular BIOS region

Looks like it, indeed.

**Comment by Matombo** [comment]
can i fix this via quirks or does this need work on the flashrom plugin?

**Comment by hughsie** [comment]
If i'm honest, I don't really understand the IFD flashrom stuff -- sorry

**Comment by Matombo** [comment]
Getting late here now, but as far as I got today: The intel me region is marked as such by the intel-spi plugin it seems, but that seems to be missing in the ubuntu deb and the deb I build myself from the debian docker container. I will dig further to see if I can fix that ^^.

**Pull request merged**
