### PR TITLE
Wait for the child device to replug in more cases

### PR DESCRIPTION
**Pull request by hughsie**
If the child device is using USE_PARENT_FOR_OPEN and the parent is
expected to replug then also mark the child device with WAIT_FOR_REPLUG
to ensure that both come back after the device re-enumerates.

This should make device tests more reliable when the parent and child
are being updated in quick succession.

Fixes the other half of https://github.com/fwupd/fwupd/issues/4843

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@d4s I'm going to need a daemon --verbose log after doing all those device tests please, those device IDs are not exactly self explanatory :)

**Comment by hughsie** [comment]
Also, it would be dead useful to have hardware to test the corsair plugin; I don't have anything here at all.

**Comment by d4s** [comment]
tbh I don't think the problem is in the plugin itself.

however the log from the daemon `--verbose` 
[update_test.log](https://github.com/fwupd/fwupd/files/9142583/update_test.log)

```shell
[root@amber bin]# ./fwupdmgr device-test /home/lxdhome/d4s/work/fwupd/fwupd/data/device-tests/corsair-katar-pro-wireless.json --json
WARNING: This package has not been validated, it may not work properly.
{
  "results" : [
    {
      "filename" : "/home/lxdhome/d4s/work/fwupd/fwupd/data/device-tests/corsair-katar-pro-wireless.json",
      "name" : "Corsair KATAR PRO WIRELESS",
      "interactive" : false,
      "steps" : [
        {
          "url" : "https://fwupd.org/downloads/03c478a9248c658d985267c6a67da878ab8c856e71bbd49105424d48e7fbf98c-corsair-mandarin-receiver-2.3.22.cab",
          "protocol" : "com.corsair.bp",
          "guids" : [
            "8bf1f03f-3c6f-53a1-9169-800fddf0952c"
          ],
          "version" : "2.3.22",
          "success" : true
        },
        {
          "url" : "https://fwupd.org/downloads/713ec6eace214d6646c788fdbaa24b24c1077dc52d8e9e404bf545db63940d00-corsair-mandarin-mouse-2.5.32.cab",
          "protocol" : "com.corsair.bp",
          "guids" : [
            "7235bc76-2e5a-5312-b848-882871503152"
          ],
          "version" : "2.5.32",
          "success" : true
        },
        {
          "url" : "https://fwupd.org/downloads/e89d2bda6e66c1af342ffe307e313c49a16371a83a7e9a5f87dcdeadba61f4ad-corsair-mandarin-receiver-2.3.23.cab",
          "info" : "failed to get device before update: failed to wait for detach replug: device f0f9c1d567dfdf1b10391e7d3469e242ebd6459c did not come back"
        },
        {
          "url" : "https://fwupd.org/downloads/7cccf09f717ae6eb8d5d23fb089aa07f8279edc63ec1dfff9bf2f74d46e498fc-corsair-mandarin-mouse-2.5.33.cab",
          "info" : "No supported devices found"
        }
      ]
    }
  ]
}
```

**Comment by hughsie** [comment]
Ahh, when you're updating the receiver, you can't see the child devices -- correct?

**Comment by hughsie** [comment]
@d4s can you do the --verbose daemon log again please with **main** branch, but this time remove the steelseries device (just to make the log smaller!) and also set FWUPD_PROBE_VERBOSE=1 too. I'm a bit unclear to the starting conditions. Thanks.

**Comment by d4s** [comment]
@hughsie correct, I see the following sequence, please correct me if I'm wrong:
- you updating the receiver
- both -- receiver&mouse are disconnected
- after update, the receiver comes back successfully
- <--- HERE started the update of child (mouse) & failed due unavailability
- the mouse connected to the receiver

Now I'm using SteelSeries Aerox 3 mouse to reproduce the issue (explanation below) 
[update_test.log](https://github.com/fwupd/fwupd/files/9144617/update_test.log)
:
```shell
[root@amber bin]# ./fwupdmgr device-test /home/lxdhome/d4s/work/fwupd/fwupd/data/device-tests/steelseries-aerox-3-wireless.json --json
WARNING: This package has not been validated, it may not work properly.
{
  "results" : [
    {
      "filename" : "/home/lxdhome/d4s/work/fwupd/fwupd/data/device-tests/steelseries-aerox-3-wireless.json",
      "name" : "Steelseries Aerox 3 Wireless",
      "interactive" : false,
      "steps" : [
        {
          "url" : "https://fwupd.org/downloads/dee6986d0faf769bf57869ee2b61118c8142e4a0017dbfc3bb0da24fb6dcfb06-SteelSeries_Aerox_3_Wireless_Dongle_1.2.17.cab",
          "guids" : [
            "291b0582-8d08-5714-88db-986911c744d9"
          ],
          "version" : "1.2.17",
          "success" : true
        },
        {
          "url" : "https://fwupd.org/downloads/35883a1f60f9a171451ccd8ca9e3d89cfaedd99cc1325410465e30d180bcb47a-SteelSeries_Aerox_3_Wireless_Mouse_1.8.1.cab",
          "error" : "Device Aerox 3 Wireless Mouse via USB Receiver [882f18f9cf9ba8f544151b07cd724d64a387cc58] has no firmware version"
        },
        {
          "url" : "https://fwupd.org/downloads/fb8e8253a6c4426233ff88a58ae9323f1a7b9002fe6f68541c2e886cded04d38-SteelSeries_Aerox_3_Wireless_Dongle_1.3.1.cab",
          "guids" : [
            "291b0582-8d08-5714-88db-986911c744d9"
          ],
          "version" : "1.3.1",
          "success" : true
        },
        {
          "url" : "https://fwupd.org/downloads/60627b15b7c1499fcd6a882ef02743f358812fcfc9ed3d1b200f55b91c554796-SteelSeries_Aerox_3_Wireless_Mouse_1.9.3.cab",
          "error" : "Device Aerox 3 Wireless Mouse via USB Receiver [882f18f9cf9ba8f544151b07cd724d64a387cc58] has no firmware version"
        }
      ]
    }
  ]
}
Some of the tests failed
[root@amber bin]# echo $?
1
```
in case of Aerox 3 -- it is expected to get the error reply from the receiver if we query the mouse which isn't connected. The same error message in logs if I just switch off the mouse before the test.


==========================
Tried Corsair KATAR PRO WIRELESS several times from main -- but it works as expected those times until the mouse failed to update and died:
```
"error" : "cannot write firmwarecannot write first chunk: firmware init fail: device replied with error: 0x03"
```
Unfortunately I switched off `--verbose` flag exactly for this test :(

**Comment by hughsie** [comment]
This one jumped out at me:

	20:39:00:0724 FuEngine             reload ->
	FuSteelseriesFizz:
	  DeviceId:             1f914e619b232dc4da68ec3389b98b20163003a2
	...
	FuSteelseriesFizzTunnel:
	  DeviceId:             882f18f9cf9ba8f544151b07cd724d64a387cc58
	  CompositeId:          1f914e619b232dc4da68ec3389b98b20163003a2
	  Name:                 Aerox 3 Wireless Mouse via USB Receiver
	...
	    Inhibit:            [unreachable] Device is unreachable, or out of wireless range

i.e. on ->reload() after the receiver was updated the `fu_steelseries_fizz_tunnel_ping()` failed and the mouse was marked `FWUPD_DEVICE_FLAG_UNREACHABLE`. Perhaps the hardware needs a few ms to initialize after reboot? In other plugins we've done something like:

	static gboolean
	fu_steelseries_fizz_tunnel_reload(device, error)
	{
		/* justification here.... */
		g_usleep(250 * 1000);
		return fu_device_setup(device, error);
	}

...it seems the version is only set if the device is detected as connected, which explains the "has no firmware version" error. If `->reload()` isn't implemented the daemon just does `->setup()` instead which for most hardware is fine.

I do think there's a GMainLoop ordering issue in the daemon, and I have a plan for a possible fix, but I think the post-install reload is probably the first bug we want to squash.

**Comment by d4s** [comment]
JFYI: the fix with `fu_steelseries_fizz_tunnel_reload()` doesn't work

**Comment by hughsie** [comment]
> JFYI: the fix with fu_steelseries_fizz_tunnel_reload() doesn't work

Could we ask steelseries and ask them why fu_steelseries_fizz_tunnel_ping() is failing after the firmware update of the receiver? Perhaps we have to wait a **lot** longer?

**Comment by hughsie** [comment]
Closing issue, but feel free to carry on the discussion.

**Pull request closed without merging**
