### PR TITLE
Add fu_msgpack_item_new_binary_stream() for future use

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
This reduces the RSS requirement by about 150MB at runtime -- which is going to be very helpful on 4GB chromebooks.

**Review by LarsStensen — COMMENTED** [review]
Should this be covered in fu-self-test?

**Comment by hughsie** [comment]
> Should this be covered in fu-self-test?

Yes, 100% valid. Fixed.

**Review by LarsStensen — APPROVED** [review]
looks good

**Pull request merged**
