### PR TITLE
Convert warning messages to ASCII when logged

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
CC @djcampello this might actually also clean up some of the fwupdtool output on ChromeOS, at least when run by the udev runner.  I know it had output some `???` characters previously.

**Comment by hughsie** [comment]
Just so I understand this completely, why are we including UTF-8 in error messages anyway?

**Comment by superm1** [comment]
> Just so I understand this completely, why are we including UTF-8 in error messages anyway?

It comes from glib.  Take at the linked issue to see my sleuthing (and prove it wrong if i'm wrong!): #2234

**Comment by hughsie** [comment]
> It comes from glib

Ahh, that! I wondered if fwupd was injecting color codes or something!

**Pull request merged**
