### PR TITLE
Encourage use of venv for development

### PR DESCRIPTION
**Pull request by superm1**
This adjusts the setup scripts and helper wrapper scripts to encourage people to use a virtualenv to do fwupd development.  This has the advantage of not needing to install to `/usr/local` and the fwupd development environment  can completely be separate from the distro installation.

When a user runs `./contrib/setup` it will place wrappers and information into the development environment.  To start development they would run

```shell
# source venv/bin/activate
```

From within the environment the following will be emitted:
```shell
To build fwupd within development environment run:

# build-fwupd

To run any tool under gdbserver add DEBUG=1 to env, for example:

# DEBUG=1 fwupdtool get-devices

To leave fwupd development environment run:

# deactivate
```

Wrappers are setup so that everything will run from within `venv/`.  Furthermore if `DEBUG=1` is put in the environment then applications will be launched under `gdbserver`.  It can be easily attached to using a `gdb` client application such as vscode and stepped through.

I expect we need to update a lot of documentation to support this change and people may need to re-run `./contrib/setup` to use it, but it should be a net positive.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [x] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Do we need any changes for https://lvfs.readthedocs.io/en/latest/custom-plugin.html#building-fwupd ?

**Comment by superm1** [comment]
> Do we need any changes for https://lvfs.readthedocs.io/en/latest/custom-plugin.html#building-fwupd ?

Yes. And I'm sure there are more places. I didn't try to look for or update documentation as I wanted to make sure it is sensible and a good idea. I think we can follow all those up in another PR/wiki modification/etc.

**Comment by hughsie** [comment]
> And I'm sure there are more places.

I guess we should move that LVFS section into fwupd -- and just put a link in the LVFS location to the fwupd doc.

**Comment by superm1** [comment]
So conceptually okay with this? I'll take a pass on the matching fwupd documentation then around it.

**Comment by hughsie** [comment]
>So conceptually okay with this?

I'm mixed I guess. It's weird seeing `venv/build` rather than `build`, but that's cosmetic. My worry is more about people "getting stuck" in the venv, or using `venv/build` when *not* in the venv...

**Comment by superm1** [comment]
> > So conceptually okay with this?
> 
> I'm mixed I guess. It's weird seeing `venv/build` rather than `build`, but that's cosmetic. My worry is more about people "getting stuck" in the venv, or using `venv/build` when _not_ in the venv...

"Getting stuck" I think is mostly a non-issue - open a new terminal tab and you're out.
As for using the `venv/build` when not in the venv; it _mostly_ works because most of the deps are installed outside of the venv by `contrib/ci/dependencies.xml`.  You just don't get the nice launch wrappers anymore when you launch it anymore.

**Comment by mhalano** [comment]
> > So conceptually okay with this?
> 
> I'm mixed I guess. It's weird seeing `venv/build` rather than `build`, but that's cosmetic. My worry is more about people "getting stuck" in the venv, or using `venv/build` when _not_ in the venv...

Maybe a lengthy instruction about how to create the virtual environment and activate it?

**Comment by superm1** [comment]
> > > So conceptually okay with this?
> > 
> > I'm mixed I guess. It's weird seeing `venv/build` rather than `build`, but that's cosmetic. My worry is more about people "getting stuck" in the venv, or using `venv/build` when _not_ in the venv...
> 
> Maybe a lengthy instruction about how to create the virtual environment and activate it?

I tried with the new documentation building.md

**Comment by hughsie** [comment]
This seems to work for me, and it's a lot less risky than the old approach imo.

**Comment by superm1** [comment]
OK.  I think this is worth backporting to 1_9_X as well, otherwise it's pretty awkard to have the license checks fail because of files in `venv/build`

**Comment by superm1** [comment]
The other thing I would like to do if you're OK with it is force a doc refresh on fwupd.github.io in advance of the 2.0.0 release.  Then we can make the LVFS URL link back to the fwupd.github.io URL now.

**Comment by hughsie** [comment]
>  Then we can make the LVFS URL link back to the fwupd.github.io URL now.

WFM.

**Comment by superm1** [comment]
OK let's merge this and I'll do a separate PR for the 1_9_X backport to make sure I don't take anything risky.

**Comment by hughsie** [comment]
Something like https://gitlab.com/fwupd/lvfs-website/-/merge_requests/1420 perhaps?

**Pull request merged**
