### PR TITLE
Add fu_firmware_set_version_raw()

### PR DESCRIPTION
**Pull request by hughsie**
A few plugins need this now, so move it into the base class.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
Can you please better explain why any plugins _need_ this?  Is it just a debugging feature?  I don't see a _need_ from the diff.

**Comment by hughsie** [comment]
>  Is it just a debugging feature? I don't see a need from the diff.

Fair point. Debugging yes, but main reason is the ccgx and pixart plugins need this in the other two PRs to be able to *build* firmware of a specific version.

**Comment by superm1** [comment]
>Fair point. Debugging yes, but main reason is the ccgx and pixart plugins need this in the other two PRs to be able to build firmware of a specific version.

Haven't looked at the others yet, so that makes more sense knowing there is an actual consumer of it.  I think from a plugin developer perspective there needs to be better explanation of the different between this and regular `version` and whether this is mandatory or optional.

**Comment by hughsie** [comment]
> there needs to be better explanation of the different between this and regular version

I've added gtk-doc comments in both functions; how about that?

**Review by superm1 — APPROVED** [review]

**Pull request merged**
