### PR TITLE
Support devices that need an action during the update process

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
The "_return error and hope the client resubmits the firmware again_" is clunky. There are two affected plugins, and about to be one more.

**Comment by hughsie** [comment]
@superm1 the other way to do this is create an exported FwupdDeviceEvent object and then have a DeviceEvent signal with `asv` -- which is probably less fragile than what I have here. I'm not sure if that's architecture astronauting or not.

**Review by superm1 — COMMENTED** [review]
so my take on this, if you're going to be biting the bullet to allow interactive stuff you may as well let the client block on it, and retry things.  
IE If it's an unplug, have the daemon send an unplug event back to the client and client will retry it's action.
If it's a press a button type thing, daemon sends a "let me know when you've done action" message and then user does it.

Otherwise it's just fragile duct tape not much different than what exists right now.

**Comment by superm1** [comment]
> so my take on this, if you're going to be biting the bullet to allow interactive stuff you may as well let the client block on it, and retry things.
> IE If it's an unplug, have the daemon send an unplug event back to the client and client will retry it's action.
> If it's a press a button type thing, daemon sends a "let me know when you've done action" message and then user does it.
> 
> Otherwise it's just fragile duct tape not much different than what exists right now.

Which I guess is your counterproposal idea, and I think is probably a better way to go.  I think then we get to say what kind of events clients can do, wait for, etc.  IOW when we suddenly have to plug in an ethernet cable for an update to complete, we can actually plumb the events for said things :)

**Comment by hughsie** [comment]
>  IOW when we suddenly have to plug in an ethernet cable for an update to complete, we can actually plumb the events for said things

Yes, it's a whole lot more extensible than this PR. I'll have a rethink and prototype something tomorrow. Thanks for the sanity check.

**Pull request closed without merging**
