### PR TITLE
trivial: contrib: drop dockerfile for snap

### PR DESCRIPTION
**Pull request by superm1**
We build using Github actions and snapcraft now.

Link: https://github.com/fwupd/fwupd/discussions/6620

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by hughsie — APPROVED** [review]

**Comment by hughsie** [comment]
Is this related?

    craft-providers error: Failed to read instance config in environment at /etc/craft-instance.conf
    Full execution log: '/home/runner/.local/state/snapcraft/log/snapcraft-20240105-153111.973990.log'
    Error: The process '/usr/bin/sg' failed with exit code 1

**Comment by superm1** [comment]
I'm not sure, it's really weird. None of that stuff should be used.

**Comment by superm1** [comment]
Seems like it was a transient issue that just coincidentally failed the snap job.  I re-ran and it works :)

**Comment by hughsie** [comment]
Okay, then I'm less confused!

**Pull request merged**
