### PR TITLE
Allow firmware files to apply quirks FIXME

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 before I invest time in this, is the idea crazy or sane?

**Comment by superm1** [comment]
IMO overkill.  Quirks are compiled into the resource files, so this type of stuff is going to save just a few lines of C code.

**Comment by hughsie** [comment]
> IMO overkill

Ya, it feels *heavy*. It turns out that most of the GR usb4 docks all have the same device-id anyway....

**Comment by superm1** [comment]
> > IMO overkill
> 
> Ya, it feels _heavy_. It turns out that most of the GR usb4 docks all have the same device-id anyway....

well they should.  The custom stuff is ID the OEM uses that goes in the NVM.

**Pull request closed without merging**
