### PR TITLE
trivial: Show quirk matches when running verbose

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
So the idea is you set the flag on a device and set verbose and you get quirk matching stuff for the device? Why not just do it for all of them when in verbose or add a new flag for just that?

**Comment by hughsie** [comment]
Ohh sorry, i was unclear. This is just for dumping to the console all the `ONLY_QUIRK` matches. At the moment when we do --verbose there's no way of seeing what quirks were applied and so it makes it tricky to debug. With this PR we set the env variable and then any instance IDs we add with `FU_DEVICE_INSTANCE_FLAG_ONLY_QUIRKS` get added to a special list and then get printed when we do the device `to_string()` fvunc. There should be no behaviour change.

**Comment by superm1** [comment]
Right - but wouldn't it be useful to be able to see what happens with all quirks, not only the ONLY_QUIRKS ones?

**Comment by hughsie** [comment]
Maybe https://github.com/fwupd/fwupd/pull/4165 is a better way to solve this?

**Pull request closed without merging**
