### PR TITLE
Wip/hughsie/sdx xx

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@Fanice-luo

**Comment by Fanice-luo** [comment]
Hi hughsie,
We agree with this pull request.

**Comment by hughsie** [comment]
@Fanice-luo great, but does it *work*? :)

**Comment by Fanice-luo** [comment]
@hughsie yes,it works well.

**Pull request merged**
