### PR TITLE
Create a dummy device for failing to load plugins

### PR DESCRIPTION
**Pull request by superm1**
One way to address the stuff mentioned in https://github.com/fwupd/fwupd/issues/1526.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [x] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
With this in place, here is what shows up when TPM library is missing.

```
├─dell device:
│     Device ID:           274acc02c0c999db4fa80c249403d11cc870280a
│     Update Error:        failed to open plugin /usr/local/lib/x86_64-linux-gnu/fwupd-plugins-3/libfu_plugin_dell.so: libtss2-esys.so.0: cannot open shared object file: No such file or directory
│     GUID:                048ff691-5ebb-5079-9817-e890ffa1ad30 ← /usr/local/lib/x86_64-linux-gnu/fwupd-plugins-3/libfu_plugin_dell.so
│   
└─uefi device:
      Device ID:           415773eab9fa918d3a8084745dba598450ff458d
      Update Error:        failed to open plugin /usr/local/lib/x86_64-linux-gnu/fwupd-plugins-3/libfu_plugin_uefi.so: libtss2-esys.so.0: cannot open shared object file: No such file or directory
      GUID:                4ce8a2db-5cb9-5b07-a3fe-ee09e12be224 ← /usr/local/lib/x86_64-linux-gnu/fwupd-plugins-3/libfu_plugin_uefi.so
```

**Comment by hughsie** [comment]
Not a fan :/ This is going to be really confusing where plugins are intentionally not loaded. I think devices in general need to represent **devices**, not plugins. I think `fwupdmgr get-plugins` would make sense to show this kind of information, but not in the device list.

**Comment by superm1** [comment]
> Not a fan :/ This is going to be really confusing where plugins are intentionally not loaded. I think devices in general need to represent **devices**, not plugins. 

Intentionally not loaded?  Could you give an example?
I was thinking that this should only show plugins that failed to load, not failed to startup.

> I think `fwupdmgr get-plugins` would make sense to show this kind of information, but not in the device list.

Like a debugging feature?  I guess from the way you describe it this is what comes to mind:

```
# fwupdmgr get-plugins:
[color green] dfu: enabled
[color green] colorhug: enabled
[color grey] coreboot: not a coreboot system
.
.
[color red] uefi: disabled: libtss2-esys.so.0: cannot open shared object file: No such file or directory
.
.

```

**Comment by hughsie** [comment]
> guess from the way you describe it this is what comes to mind

Yes, something exactly like that. I think it's a slippery slope trying to represent everything as either a device or release.

**Comment by superm1** [comment]
> Yes, something exactly like that. I think it's a slippery slope trying to represent everything as either a device or release.

OK.  That would require a lot more planning as it's exposing plugins to clients, which is something that doesn't really exist today in the library or dbus interface.  I think we're back at the point of does the effort required to make this happen make sense.

**Pull request closed without merging**
