### PR TITLE
WIP: libfwupdplugin Support new libxmlb query binding API in 0.2.0

### PR DESCRIPTION
**Pull request by pwithnall**
See https://github.com/hughsie/libxmlb/pull/67. This doesn’t bump the
hard version dependency.

Signed-off-by: Philip Withnall <withnall@endlessm.com>

### CODE REVIEW

**Comment by pwithnall** [comment]
This shouldn’t be merged until https://github.com/hughsie/libxmlb/pull/67 lands; marking as WIP until then.

**Comment by hughsie** [comment]
I think this needs reworking with `xb_node_query_with_binding()` as like a grumpy old maintainer I NAKd the API change.

**Comment by pwithnall** [comment]
Yeah, sorry, I’ve been caught up in the great EOS rebase and have had to drop everything else on the ground for several weeks. I’ll pick it up again in some weeks.

**Comment by hughsie** [comment]
> I think this needs reworking with xb_node_query_with_binding()

I'll close this now, but feel free to reopen if the new API lands.

**Comment by pwithnall** [comment]
I’ve pushed an update to the branch to use the updated version of [the libxmlb changes](https://github.com/hughsie/libxmlb/pull/67#issuecomment-723125812), but it seems I don’t have permission to reopen this pull request.

**Comment by superm1** [comment]
I don't appear to either.  I guess open a new PR.

**Comment by pwithnall** [comment]
> I don't appear to either. I guess open a new PR.

Created #2560.

**Pull request closed without merging**
