### PR TITLE
colorhug: Ignore the failure to get the reply on device reset

### PR DESCRIPTION
**Pull request by hughsie**
Reading the response works on Linux, but fails on FreeBSD.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]

**Comment by Asiderr** [comment]
@hughsie The same error still occurs:
```
failed to reset device: failed to send request: USB error on device
273f:1004 : No device [-4] 
```

It is generated during the first g_usb_device_interrupt_transfer():
https://github.com/fwupd/fwupd/blob/4811cd2b1ec2f83c7983567a4bd4243266ae5432/plugins/colorhug/fu-colorhug-device.c#L92

**Comment by hughsie** [comment]
@Asiderr okay, one more try please! ^^

**Comment by Asiderr** [comment]
@hughsie I think that problem is somewhere else:
```
11:05:48:0737 FuPlugin             running superclassed update_detach(colorhug)
11:05:48:0768 FuEngine             Emitting PropertyChanged('Status'='device-restart')
Installing on ColorHug2… [ -
Restarting device…       [ -                                     ]
11:05:48:0773 FuPluginColorHug     ignoring 'USB error on device 273f:1004 : No device [-4]' on reset
11:05:48:0773 FuDeviceList         waiting 10000ms for replug
Restarting device…       [                  -                    ]
failed to get device after detach: failed to wait for detach replug: device 672c087de09848d9e7ee32aa1dea2fbeb8b81e6b did not come back
```

**Comment by hughsie** [comment]
> failed to get device after detach: failed to wait for detach replug: device 672c087de09848d9e7ee32aa1dea2fbeb8b81e6b did not come back

Does BSD take longer to enumerate devices perhaps? Could you get a --verbose daemon log when updating the hardware please. If you want me to try reproducing here with a ColorHug then you'll need to provide some pretty detailed notes; I last used any BSB in anger over 15 years ago....

**Comment by Asiderr** [comment]
@hughsie I've added ifdefs for linux related kernel checks and now it's possible to use `fwupdmgr upadate` instead of `fwupdtool install-blob`. Here are the client and daemon logs:

## fwupd daemon:

```
root@freebsdvm:/usr/local/libexec/fwupd # ./fwupd -v
13:22:46:0882 FuDebug              Verbose debugging enabled (on console 1)
13:22:46:0882 FuConfig             loading config values from /usr/local/etc/fwupd/daemon.conf
13:22:46:0882 FuConfig             using autodetected max archive size 18.4 EB
13:22:46:0883 FuRemoteList         loading /usr/local/share/fwupd/metainfo
13:22:46:0883 XbSilo               attempting to load /var/local/cache/fwupd/metainfo.xmlb
13:22:46:0883 XbSilo               file: 1be2f9c7-6824-9b6a-cf68-fb99445a905d, current:225b07d4-deb3-c0f1-23d6-6d09ebcd8410, cached: (null)
13:22:46:0885 FuRemoteList         loading remote from /usr/local/etc/fwupd/remotes.d/lvfs.conf
13:22:46:0885 FuRemoteList         loading remote from /usr/local/etc/fwupd/remotes.d/vendor-directory.conf
13:22:46:0885 FuRemoteList         loading remote from /usr/local/etc/fwupd/remotes.d/vendor.conf
13:22:46:0885 FuRemoteList         loading remote from /usr/local/etc/fwupd/remotes.d/lvfs-testing.conf
13:22:46:0885 FuRemoteList         ignoring unfound remote fwupd
13:22:46:0885 FuRemoteList         ordering lvfs-testing=lvfs+1
13:22:46:0886 Jcat                 ignoring GPG-KEY-Linux-Vendor-Firmware-Service as not PKCS-7 certificate
13:22:46:0886 Jcat                 trying to load certificate from /usr/local/etc/pki/fwupd/LVFS-CA.pem
13:22:46:0886 Jcat                 reading /usr/local/etc/pki/fwupd/LVFS-CA.pem with 1679 bytes
13:22:46:0886 Jcat                 loaded 1 certificates
13:22:46:0886 Jcat                 ignoring GPG-KEY-Linux-Foundation-Firmware as not PKCS-7 certificate
13:22:46:0886 Jcat                 ignoring GPG-KEY-Linux-Vendor-Firmware-Service as not PKCS-7 certificate
13:22:46:0886 Jcat                 trying to load certificate from /usr/local/etc/pki/fwupd-metadata/LVFS-CA.pem
13:22:46:0886 Jcat                 reading /usr/local/etc/pki/fwupd-metadata/LVFS-CA.pem with 1679 bytes
13:22:46:0886 Jcat                 loaded 1 certificates
13:22:46:0887 Jcat                 ignoring GPG-KEY-Linux-Foundation-Metadata as not PKCS-7 certificate
13:22:46:0887 Jcat                 reading /var/local/lib/fwupd/pki/secret.key with 2455 bytes
13:22:46:0887 Jcat                 reading /var/local/lib/fwupd/pki/client.pem with 1383 bytes
13:22:46:0890 FuEngine             client certificate exists and working
13:22:46:0891 FuHistory            trying to open database '/var/local/lib/fwupd/pending.db'
13:22:46:0891 FuHistory            got schema version of 6
13:22:46:0891 FuIdle               setting timeout to 7200s
13:22:46:0891 FuContext            Failed to load SMBIOS: neither SMBIOS or DT found
13:22:46:0891 FuHwids              ignoring Manufacturer: no structure with type 01
13:22:46:0891 FuHwids              ignoring EnclosureKind: no structure with type 03
13:22:46:0891 FuHwids              ignoring Family: no structure with type 01
13:22:46:0891 FuHwids              ignoring ProductName: no structure with type 01
13:22:46:0892 FuHwids              ignoring ProductSku: no structure with type 01
13:22:46:0892 FuHwids              ignoring BiosVendor: no structure with type 00
13:22:46:0892 FuHwids              ignoring BiosVersion: no structure with type 00
13:22:46:0892 FuHwids              ignoring BiosMajorRelease: no structure with type 00
13:22:46:0892 FuHwids              ignoring BiosMinorRelease: no structure with type 00
13:22:46:0892 FuHwids              ignoring BaseboardManufacturer: no structure with type 02
13:22:46:0892 FuHwids              ignoring BaseboardProduct: no structure with type 02
13:22:46:0892 FuHwids              HardwareID-0 is not available, not available as 'Manufacturer' unknown
13:22:46:0892 FuHwids              HardwareID-1 is not available, not available as 'Manufacturer' unknown
13:22:46:0892 FuHwids              HardwareID-2 is not available, not available as 'Manufacturer' unknown
13:22:46:0892 FuHwids              HardwareID-3 is not available, not available as 'Manufacturer' unknown
13:22:46:0892 FuHwids              HardwareID-4 is not available, not available as 'Manufacturer' unknown
13:22:46:0893 FuHwids              HardwareID-5 is not available, not available as 'Manufacturer' unknown
13:22:46:0893 FuHwids              HardwareID-6 is not available, not available as 'Manufacturer' unknown
13:22:46:0893 FuHwids              HardwareID-7 is not available, not available as 'Manufacturer' unknown
13:22:46:0893 FuHwids              HardwareID-8 is not available, not available as 'Manufacturer' unknown
13:22:46:0893 FuHwids              HardwareID-9 is not available, not available as 'Manufacturer' unknown
13:22:46:0893 FuHwids              HardwareID-10 is not available, not available as 'Manufacturer' unknown
13:22:46:0893 FuHwids              HardwareID-11 is not available, not available as 'Manufacturer' unknown
13:22:46:0893 FuHwids              HardwareID-12 is not available, not available as 'Manufacturer' unknown
13:22:46:0893 FuHwids              HardwareID-13 is not available, not available as 'Manufacturer' unknown
13:22:46:0893 FuHwids              HardwareID-14 is not available, not available as 'Manufacturer' unknown
13:22:46:0893 XbSilo               attempting to load /var/local/cache/fwupd/metadata.xmlb
13:22:46:0893 XbSilo               file: bb716533-3b53-5c97-7b73-0706334d1b6c, current:bb716533-3b53-5c97-7b73-0706334d1b6c, cached: (null)
13:22:46:0894 XbSilo               loading silo with file contents
13:22:46:0894 FuEngine             566 components now in silo
13:22:46:0896 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_bcm57xx.so)
13:22:46:0896 FuContext            added udev subsystem watch of pci
13:22:46:0896 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_ccgx.so)
13:22:46:0896 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_colorhug.so)
13:22:46:0897 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_cpu.so)
13:22:46:0897 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_cros_ec.so)
13:22:46:0897 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_dell_dock.so)
13:22:46:0898 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_dfu.so)
13:22:46:0898 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_dfu_csr.so)
13:22:46:0898 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_ebitdo.so)
13:22:46:0898 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_ep963x.so)
13:22:46:0899 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_fastboot.so)
13:22:46:0900 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_fresco_pd.so)
13:22:46:0900 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_goodixmoc.so)
13:22:46:0900 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_msr.so)
13:22:46:0900 FuContext            added udev subsystem watch of msr
13:22:46:0900 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_solokey.so)
13:22:46:0901 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_hailuck.so)
13:22:46:0901 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_jabra.so)
13:22:46:0901 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_nitrokey.so)
13:22:46:0901 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_rts54hid.so)
13:22:46:0902 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_rts54hub.so)
13:22:46:0902 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_steelseries.so)
13:22:46:0902 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_synaptics_cxaudio.so)
13:22:46:0903 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_synaptics_prometheus.so)
13:22:46:0903 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_system76_launch.so)
13:22:46:0903 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_uefi_pk.so)
13:22:46:0904 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_vli.so)
13:22:46:0905 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_wacom_usb.so)
13:22:46:0905 FuPlugin             init(/usr/local/lib/fwupd-plugins-3/libfu_plugin_analogix.so)
13:22:46:0905 FuPluginList         cpu [0] to be ordered before msr [0] so promoting to [1]
13:22:46:0905 FuPluginList         cannot find plugin 'optionrom' referenced by 'bcm57xx'
13:22:46:0905 FuPluginList         cannot find plugin 'synaptics_mst' referenced by 'dell_dock'
13:22:46:0907 XbSilo               attempting to load /var/local/cache/fwupd/quirks.xmlb
13:22:46:0907 XbSilo               file: dced7525-3033-f1d8-21e0-74f60db46c82, current:cd5f24e2-be20-59e2-fa0f-44f5a84e1384, cached: (null)
13:22:46:0919 FuQuirks             invalid key names: PciBcrAddr
13:22:46:0919 FuEngine             Emitting PropertyChanged('Status'='loading')
13:22:46:0919 FuMain               Emitting PropertyChanged('Status'='loading')
13:22:46:0920 FuPlugin             startup(msr)
13:22:46:0920 FuPlugin             coldplug(cpu)
13:22:46:0920 FuDevice             using 4bde70ba4e39b28f9eab1628f9dd6e6244c03027 for cpu:0
13:22:46:0920 FuPlugin             emit added from cpu: 4bde70ba4e39b28f9eab1628f9dd6e6244c03027
13:22:46:0923 FuPlugin             fu_plugin_device_registered(dell_dock)
13:22:46:0923 FuPlugin             fu_plugin_device_registered(msr)
13:22:46:0923 FuDeviceList         ::added 4bde70ba4e39b28f9eab1628f9dd6e6244c03027
13:22:46:0923 FuPlugin             coldplug(uefi_pk)
13:22:46:0923 FuEngine             disabling plugin because: failed to coldplug using uefi_pk: efivarfs not currently supported on Windows
13:22:46:0924 FuEngine             using plugins: bcm57xx, ccgx, colorhug, cpu, cros_ec, dell_dock, dfu, dfu_csr, ebitdo, ep963x, fastboot, fresco_pd, goodixmoc, solokey, hailuck, jabra, nitrokey, rts54hid, rts54hub, steelseries, synaptics_cxaudio, synaptics_prometheus, system76_launch, vli, wacom_usb, analogix, msr
13:22:46:0929 FuDevice             using 672c087de09848d9e7ee32aa1dea2fbeb8b81e6b for usb:00:01
13:22:46:0988 FuDevice             changing verfmt for 672c087de09848d9e7ee32aa1dea2fbeb8b81e6b: bcd->triplet
13:22:46:0989 FuDevice             changing version for 672c087de09848d9e7ee32aa1dea2fbeb8b81e6b: 0.2->2.0.5
13:22:47:0007 FuPlugin             emit added from colorhug: 672c087de09848d9e7ee32aa1dea2fbeb8b81e6b
13:22:47:0010 FuPlugin             fu_plugin_device_registered(dell_dock)
13:22:47:0011 FuPlugin             fu_plugin_device_registered(msr)
13:22:47:0012 FuDeviceList         ::added 672c087de09848d9e7ee32aa1dea2fbeb8b81e6b
13:22:47:0034 FuEngine             Emitting PropertyChanged('Status'='idle')
13:22:47:0034 FuMain               Emitting PropertyChanged('Status'='idle')
13:22:47:0036 FuEngine             ignoring 2.0.5 == 2.0.5
13:22:47:0036 FuEngine             ignoring 2.0.2 < 2.0.5
13:22:47:0037 GLib-GIO             Failed to initialize portal (GMemoryMonitorPortal) for gio-memory-monitor: Not using portals
13:22:47:0038 GLib-GIO             _g_io_module_get_default: Found default implementation dbus (GMemoryMonitorDBus) for ‘gio-memory-monitor’
13:22:47:0039 FuMain               Daemon ready for requests (locale en_US.UTF-8)
13:22:47:0040 FuMain               acquired name: org.freedesktop.fwupd
13:22:53:0438 FuPlugin             add_security_attrs(uefi_pk)
13:22:53:0438 FuPlugin             add_security_attrs(msr)
13:22:53:0440 FuMain               Called GetPlugins()
13:22:53:0441 FuMain               Called SetFeatureFlags(15)
13:22:53:0442 FuMain               Called GetDevices()
13:22:53:0444 FuMain               Called GetUpgrades(672c087de09848d9e7ee32aa1dea2fbeb8b81e6b)
13:22:53:0446 FuEngine             ignoring 2.0.5 == 2.0.5
13:22:53:0446 FuEngine             ignoring 2.0.2 < 2.0.5
13:22:53:0447 FuMain               Called GetDevices()
13:22:57:0606 FuMain               Called GetDevices()
13:22:57:0609 FuMain               Called GetRemotes()
13:22:58:0764 FuMain               Called Install(672c087de09848d9e7ee32aa1dea2fbeb8b81e6b,15)
13:22:58:0764 FuMain               got option reason
13:22:58:0764 FuEngine             Emitting PropertyChanged('Status'='decompressing')
13:22:58:0764 FuMain               Emitting PropertyChanged('Status'='decompressing')
13:22:58:0766 Jcat                 using gpgme v1.15.1
13:22:58:0785 Jcat                 Using engine at /var/local/lib/fwupd/gnupg
13:22:58:0788 Jcat                 Adding GnuPG public key /usr/local/etc/pki/fwupd/GPG-KEY-Linux-Vendor-Firmware-Service
13:22:58:0792 Jcat                 importing key 3FC6B804410ED0840D8F2F9748A6D80E4538BAC2 [0] Success
13:22:58:0792 Jcat                 ignoring LVFS-CA.pem as not GPG public key
13:22:58:0792 Jcat                 Adding GnuPG public key /usr/local/etc/pki/fwupd/GPG-KEY-Linux-Foundation-Firmware
13:22:58:0796 Jcat                 importing key F2F0325648E1AE4956710198C6361787A0A849E1 [0] Success
13:22:58:0796 Jcat                 Adding GnuPG public key /usr/local/etc/pki/fwupd-metadata/GPG-KEY-Linux-Vendor-Firmware-Service
13:22:58:0799 Jcat                 importing key 3FC6B804410ED0840D8F2F9748A6D80E4538BAC2 [0] Success
13:22:58:0799 Jcat                 ignoring LVFS-CA.pem as not GPG public key
13:22:58:0799 Jcat                 Adding GnuPG public key /usr/local/etc/pki/fwupd-metadata/GPG-KEY-Linux-Foundation-Metadata
13:22:58:0805 Jcat                 importing key CAE0420259890141E701156E0A6DCEF6B46F3DBF [0] Success
13:22:58:0808 Jcat                 returned signature fingerprint 3FC6B804410ED0840D8F2F9748A6D80E4538BAC2
13:22:58:0809 Jcat                 verified: JcatResult:
  Timestamp:             2021-02-01T15:30:37Z
    Authority:             3FC6B804410ED0840D8F2F9748A6D80E4538BAC2
      JcatGpgEngine:
          Kind:                gpg
      VerifyKind:          signature

      13:22:58:0809 Jcat                 got 1 PKCS7 signatures
      13:22:58:0809 Jcat                 verified: JcatResult:
        Timestamp:             2021-02-01T15:30:37Z
  Authority:             O=Linux Vendor Firmware Project,CN=LVFS CA
    JcatPkcs7Engine:
        Kind:                pkcs7
    VerifyKind:          signature

    13:22:58:0810 FuCabinet            verified metadata firmware.metainfo.xml: 4
    13:22:58:0810 FuCabinet            processing file: firmware.metainfo.xml
    13:22:58:0810 FuCabinet            processing release: 2.0.7
    13:22:58:0814 Jcat                 returned signature fingerprint 3FC6B804410ED0840D8F2F9748A6D80E4538BAC2
    13:22:58:0814 Jcat                 verified: JcatResult:
      Timestamp:             2021-02-01T15:30:37Z
        Authority:             3FC6B804410ED0840D8F2F9748A6D80E4538BAC2
  JcatGpgEngine:
      Kind:                gpg
          VerifyKind:          signature

  13:22:58:0814 Jcat                 got 1 PKCS7 signatures
  13:22:58:0815 Jcat                 verified: JcatResult:
    Timestamp:             2021-02-01T15:30:37Z
      Authority:             O=Linux Vendor Firmware Project,CN=LVFS CA
        JcatPkcs7Engine:
    Kind:                pkcs7
        VerifyKind:          signature

13:22:58:0815 FuCabinet            verified payload firmware.bin: 4
13:22:58:0815 FuEngine             Emitting PropertyChanged('Status'='idle')
13:22:58:0815 FuMain               Emitting PropertyChanged('Status'='idle')
13:22:58:0816 FuMain               Emitting PropertyChanged('Status'='waiting-for-auth')
13:22:58:0816 FuIdle               inhibiting: update
13:22:58:0816 FuEngine             composite update 1: 672c087de09848d9e7ee32aa1dea2fbeb8b81e6b
13:22:58:0816 FuPlugin             composite_prepare(dell_dock)
13:22:58:0816 FuHistory            remove device ColorHug2 [672c087de09848d9e7ee32aa1dea2fbeb8b81e6b]
13:22:58:0818 FuHistory            add device ColorHug2 [672c087de09848d9e7ee32aa1dea2fbeb8b81e6b]
13:22:58:0818 FuEngine             prepare -> FuColorhugDevice:
ColorHug2
  DeviceId:             672c087de09848d9e7ee32aa1dea2fbeb8b81e6b
    Guid:                 2082b5e0-7a64-478a-b1b2-e3404fab6dad
      Guid:                 aa4b4156-9732-55db-9500-bf6388508ee3
        Guid:                 101ee86a-7bea-59fb-9f89-6b6297ceed3b <- USB\VID_273F&PID_1004&REV_0002
  Guid:                 2fa8891f-3ece-53a4-adc4-0dd875685f30 <- USB\VID_273F&PID_1004
    Summary:              An open source display colorimeter
      Plugin:               colorhug
        Protocol:             com.hughski.colorhug
  Flags:                updatable|supported|registered|self-recovery|add-counterpart-guids
    Vendor:               Hughski Ltd.
      VendorId:             USB:0x273F
        Version:              2.0.5
  VersionFormat:        triplet
    Icon:                 colorimeter-colorhug
      InstallDuration:      8
        Created:              2021-05-17
  Modified:             2021-05-17
    UpdateState:          failed
      PhysicalId:           usb:00:01
        FirmwareSizeMin:      8192
  FirmwareSizeMax:      32768
    Order:                0
      CustomFlags:          self-recovery
        PossiblePlugin:       colorhug
  InternalFlags:        replug-match-guid

  13:22:58:0852 FuEngine             detach -> FuColorhugDevice:
  ColorHug2
    DeviceId:             672c087de09848d9e7ee32aa1dea2fbeb8b81e6b
      Guid:                 2082b5e0-7a64-478a-b1b2-e3404fab6dad
        Guid:                 aa4b4156-9732-55db-9500-bf6388508ee3
  Guid:                 101ee86a-7bea-59fb-9f89-6b6297ceed3b <- USB\VID_273F&PID_1004&REV_0002
    Guid:                 2fa8891f-3ece-53a4-adc4-0dd875685f30 <- USB\VID_273F&PID_1004
      Summary:              An open source display colorimeter
        Plugin:               colorhug
  Protocol:             com.hughski.colorhug
    Flags:                updatable|supported|registered|self-recovery|add-counterpart-guids
      Vendor:               Hughski Ltd.
        VendorId:             USB:0x273F
  Version:              2.0.5
    VersionFormat:        triplet
      Icon:                 colorimeter-colorhug
        InstallDuration:      8
  Created:              2021-05-17
    Modified:             2021-05-17
      UpdateState:          failed
        PhysicalId:           usb:00:01
  FirmwareSizeMin:      8192
    FirmwareSizeMax:      32768
      Order:                0
        CustomFlags:          self-recovery
  PossiblePlugin:       colorhug
    InternalFlags:        replug-match-guid

13:22:58:0853 FuPlugin             running superclassed update_detach(colorhug)
13:22:58:0880 FuEngine             Emitting PropertyChanged('Status'='device-restart')
13:22:58:0880 FuMain               Emitting PropertyChanged('Status'='device-restart')
13:22:58:0881 FuPluginColorHug     ignoring 'USB error on device 273f:1004 : No device [-4]' on reset
13:22:58:0881 FuDeviceList         waiting 10000ms for replug
13:23:08:0882 FuEngine             Emitting PropertyChanged('Status'='idle')
13:23:08:0882 FuMain               Emitting PropertyChanged('Status'='idle')
13:23:08:0883 FuHistory            modifying device ColorHug2 [672c087de09848d9e7ee32aa1dea2fbeb8b81e6b]
13:23:08:0890 FuPlugin             composite_cleanup(dell_dock)
13:23:08:0892 FuIdle               uninhibiting: update
```
---

## fwupdmgr

```
root@freebsdvm:~ # fwupdmgr update
WARNING: This package has not been validated, it may not work properly.
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade ColorHug2 from 2.0.5 to 2.0.7?                                       ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ This release fixes prevents the firmware returning an error when the remote  ║
║ SHA1 hash was never sent.                                                    ║
║ ColorHug2 and all connected devices may not be usable while updating.        ║
╚══════════════════════════════════════════════════════════════════════════════╝

Perform operation? [Y|n]: Y
Downloading…             [***************************************]
Decompressing…           [***************************************]
Authenticating…          [***************************************]
Updating ColorHug2…      [*************
Restarting device…       [***************************************]
failed to reset device: failed to send request: USB error on device 273f:1004 : No device [-4]
root@freebsdvm:~ # fwupdmgr -v update
(fwupdmgr:10530): GLib-DEBUG: 15:22:53.427: setenv()/putenv() are not thread-safe and should not be used after threads are created
(fwupdmgr:10530): GLib-GIO-DEBUG: 15:22:53.433: _g_io_module_get_default: Found default implementation dummy (GDummyProxyResolver) for ‘gio-proxy-resolver’
(fwupdmgr:10530): Fwupd-DEBUG: 15:22:53.439: Emitting ::status-changed() [idle]
WARNING: This package has not been validated, it may not work properly.
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade ColorHug2 from 2.0.5 to 2.0.7?                                       ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ This release fixes prevents the firmware returning an error when the remote  ║
║ SHA1 hash was never sent.                                                    ║
║ ColorHug2 and all connected devices may not be usable while updating.        ║
╚══════════════════════════════════════════════════════════════════════════════╝

Perform operation? [Y|n]: Y
(fwupdmgr:10530): Fwupd-DEBUG: 15:22:57.622: downloading https://fwupd.org/downloads/0a29848de74d26348bc5a6e24fc9f03778eddf0e-hughski-colorhug2-2.0.7.cab
(fwupdmgr:10530): Fwupd-DEBUG: 15:22:57.622: Emitting ::status-changed() [downloading]
Downloading…             [ -                                     ](fwupdmgr:10530): Fwupd-DEBUG: 15:22:58.562: download progress: 21%
(fwupdmgr:10530): Fwupd-DEBUG: 15:22:58.563: download progress: 21%
Downloading…             [********                               ](fwupdmgr:10530): Fwupd-DEBUG: 15:22:58.680: download progress: 21%
(fwupdmgr:10530): Fwupd-DEBUG: 15:22:58.680: download progress: 21%
(fwupdmgr:10530): Fwupd-DEBUG: 15:22:58.749: download progress: 100%
(fwupdmgr:10530): Fwupd-DEBUG: 15:22:58.752: download progress: 100%
(fwupdmgr:10530): Fwupd-DEBUG: 15:22:58.753: download progress: 100%
(fwupdmgr:10530): Fwupd-DEBUG: 15:22:58.753: download progress: 100%
(fwupdmgr:10530): Fwupd-DEBUG: 15:22:58.753: Emitting ::status-changed() [idle]
Downloading…             [***************************************]
(fwupdmgr:10530): Fwupd-DEBUG: 15:22:58.771: Emitting ::status-changed() [decompressing]
Decompressing…           [***************************************](fwupdmgr:10530): Fwupd-DEBUG: 15:22:58.815: Emitting ::status-changed() [idle]
Decompressing…           [***************************************]
(fwupdmgr:10530): Fwupd-DEBUG: 15:22:58.816: Emitting ::status-changed() [waiting-for-auth]
Authenticating…          [***************************************]
(fwupdmgr:10530): Fwupd-DEBUG: 15:22:58.880: Emitting ::status-changed() [device-restart]
Restarting device…       [***************************************](fwupdmgr:10530): Fwupd-DEBUG: 15:22:58.881: Emitting ::device-changed(672c087de09848d9e7ee32aa1dea2fbeb8b81e6b)
Updating ColorHug2…
Restarting device…       [***************************************](fwupdmgr:10530): Fwupd-DEBUG: 15:23:08.886: Emitting ::status-changed() [idle]
Restarting device…       [***************************************]
(fwupdmgr:10530): Fwupd-DEBUG: 15:23:08.887: Emitting ::device-changed(672c087de09848d9e7ee32aa1dea2fbeb8b81e6b)
failed to get device after detach: failed to wait for detach replug: device 672c087de09848d9e7ee32aa1dea2fbeb8b81e6b did not come back
```
---

>  If you want me to try reproducing here with a ColorHug then you'll need to provide some pretty detailed notes; I last used any BSB in anger over 15 years ago....

Sure, I really appreciate that. At first you need to download [FreeBSD 12.2](https://download.freebsd.org/ftp/releases/ISO-IMAGES/12.2/FreeBSD-12.2-RELEASE-amd64-memstick.img), then follow this doc: https://github.com/3mdeb/fwupd/blob/docs/fwupd-development.md

**Comment by hughsie** [comment]
> 13:22:58:0881 FuDeviceList         waiting 10000ms for replug
> 13:23:08:0882 FuEngine             Emitting PropertyChanged('Status'='idle')

It looks like the device never indeed came back. Is this on a VM or actual hardware? If it's the former, did you do USB passtru for both USB VID/PIDs?

**Comment by hughsie** [comment]
I'll merge this as it fixes half the problem, and when my newly installed freebsd system has finished building I'll have a got with the 2nd half.

**Comment by Asiderr** [comment]
> It looks like the device never indeed came back. Is this on a VM or actual hardware? If it's the former, did you do USB passthrough for both USB VID/PIDs?

@hughsie I've tested following changes at the actual hardware, and it behaves in the same way.

**Comment by hughsie** [comment]
> I've tested following changes at the actual hardware, and it behaves in the same way

Mrgh, I was doing so well installing freebsd ports; but my 20GB VM is now 105% full. To save me a few hours, when you reboot the device back into runtime or bootloader mode, does the device reappear to the freebsd kernel? I think there's some libusb hotplug funkyness happening, which is plausible as I think libusb on linux uses gusb and libusb on win32 uses a dedicated thread...

**Comment by Asiderr** [comment]
> To save me a few hours, when you reboot the device back into runtime or bootloader mode, does the device reappear to the freebsd kernel?

It appears that the device is not rebooting at all. It is available at all times.

**Comment by hughsie** [comment]
There doesn't appear to be any kind of libusb_hotplug_register_callback() in the FreeBSD libusb. I think you might need to use the win32 polling thread before device hotplug will work correctly.

**Comment by Asiderr** [comment]
@hughsie I'll try that.

**Comment by Asiderr** [comment]
@hughsie there is libusb_hotplug_register_callback in FreeBSD https://www.freebsd.org/cgi/man.cgi?format=html&query=libusb%283%29:
```
     int libusb_hotplug_register_callback(libusb_context *ctx,
     libusb_hotplug_event events, libusb_hotplug_flag flags, int vendor_id,
     int product_id, int dev_class, libusb_hotplug_callback_fn cb_fn, void
     *user_data, libusb_hotplug_callback_handle	*handle) 
     
     This function registers a hotplug filter.  The events argument select which events makes the
     hotplug filter trigger.  Available event values are LIBUSB_HOT-PLUG_EVENT_DEVICE_ARRIVED and 
     LIBUSB_HOTPLUG_EVENT_DEVICE_LEFT.  One or more events must be specified. 
     The vendor_id, product_id and dev_class
     arguments can be set to LIBUSB_HOTPLUG_MATCH_ANY to match any value in
     the USB device descriptor.	 Else the specified value is used for match-
     ing.  If the flags	argument is set	to LIBUSB_HOTPLUG_ENUMERATE, all cur-
     rently attached and matching USB devices will be passed to	the hotplug
     filter, given by the cb_fn	argument.  Else	the flags argument should be
     set to LIBUSB_HOTPLUG_NO_FLAGS.  This function returns 0 upon success or
     a LIBUSB_ERROR code on failure.
```

**Comment by hughsie** [comment]
Right, but it's being disabled in https://reviews.freebsd.org/D29332

**Comment by Asiderr** [comment]
@hughsie You should be able to reproduce the problem with this artifact:
https://github.com/3mdeb/fwupd/runs/2638818516

**Comment by hughsie** [comment]
@Asiderr I've got all the bits in place to test this now, and am currently stuck on `memfd_create() not available` -- didn't you have a patch somewhere that converted it to a tmpfile and normal fd?

**Comment by Asiderr** [comment]
@hughsie yes, I will upstream this change in a moment: https://github.com/fwupd/fwupd/commit/443ae53afd929237c884e4f55a09d7770ff9d540

**Comment by Asiderr** [comment]
@hughsie https://github.com/fwupd/fwupd/pull/3279

**Comment by hughsie** [comment]
@Asiderr Did you look at the `/proc/cmdline` thing yet too?

**Comment by Asiderr** [comment]
@hughsie Yes :smile: For now, checks are omitted with ifdefs: https://github.com/3mdeb/fwupd/commit/4e2b2c179ff2e2b78177846d21525664aba9e886

**Comment by hughsie** [comment]
@Asiderr okay, so I managed to reproduce the ColorHug reattach bug. If you comment out the unref of the `usb_device_locker` in fu-usb-device.c then the detach succeeds. i.e. in Linux this seems to work:

    libusb_open(d)
    libusb_intertupt_transfer(d)
    libusb_close(d)
    libusb_open(d)
    libusb_intertupt_transfer(d)
    libusb_close(d)

but in FreeBSD it seems to return NO_DEVICE after the first close. i.e. it seems you can't re-open the same device for some reason. Perhaps the FreeBSD ties the device lifetime to the handle, not the device -- but I've not looked into it any more as I'm OUTOFTIME for today.

**Comment by Asiderr** [comment]
@hughsie Thanks for your help! I'll investigate this further.

**Comment by hughsie** [comment]
If it helps, you can do `sudo ./src/fwupdtool --plugins colorhug --verbose detach` as a minimal reproducer.

**Pull request merged**
