### PR TITLE
trivial: Use json-glib from master to get a fuzzing crash fix

### PR DESCRIPTION
**Pull request by hughsie**
See https://gitlab.gnome.org/GNOME/json-glib/-/commit/7711cbc7f8d85d909bd4ccaa0c4c0f8d306f872f

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
I guess this is mostly a philosophical question if you want a deterministic fuzz run or fuzz essentially ToT for all the projects

**Comment by hughsie** [comment]
That's a good question. I'm erring on master for JSON-glib, glib and libxmlb as we know all upstream teams and I think it would be useful to know that something we depend on has regressed. On the logic, if fwupd is crashing in the field it's us who look like Muppets, even if it's some dep that's done something dumb.

**Comment by superm1** [comment]
> That's a good question. I'm erring on master for JSON-glib, glib and libxmlb as we know all upstream teams and I think it would be useful to know that something we depend on has regressed. On the logic, if fwupd is crashing in the field it's us who look like Muppets, even if it's some dep that's done something dumb.

I tend to agree - but the problem you run into though is what if a distro has an old snapshot with the crasher?  Like you still need a feedback loop to document somewhere that there was a vulnerability and people need to pick it up right?

**Comment by hughsie** [comment]
> what if a distro has an old snapshot

I don't think it's our job to ensure the distro(s) included  the fix. I guess a compromise would be to target the *branch* being shipped by something fairly aggressive, e.g. F33.

**Comment by hughsie** [comment]
I'll merge this; on the logic that there is no stable branch for json-glib-1-6 -- I'm happy to continue discussing the stable branch for glib tho, as I think that's the one that might bite us the hardest.

**Pull request merged**
