### PR TITLE
Allow plugins to opt-out of the child-device first depsolve

### PR DESCRIPTION
**Pull request by hughsie**
This fixes using the release priority for child-devices.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]

**Comment by hughsie** [comment]
Ya, but it doesn't seem to *work* yet :) I need to verify on actual hardware.

**Comment by hughsie** [comment]
@superm1 any idea why the coverage report would go down?

**Comment by hughsie** [comment]
> No; not sure

I'm wondering if it's the kind of issue that's just going to sort itself out, i.e. once we have the n+2 PR the problem goes away.

**Comment by superm1** [comment]
I just clicked through one and I notice `fu_test_plugin_verify` was missing here:
https://coveralls.io/jobs/135827704/source_files/20932168382#L164
but was present in original:
https://coveralls.io/builds/65558631/source?filename=plugins%2Ftest%2Ffu-test-plugin.c

**Comment by superm1** [comment]
I set the threshold for "failure" in decrease to 5% in coveralls.  Let's just keep an eye on it.

**Comment by hughsie** [comment]
@superm1 I think you might be on the money; it seems sometimes the test plugin doesn't get run in the gcov section; is that gated on !i386 or something? i.e. are we comparing i386 to x64 randomly?

**Pull request merged**
