### PR TITLE
Wip/hughsie/gi docgen fixes

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [X] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]
I just had a thought - I think it would be good if precommit could catch the two following things if possible:

New symbols in the libraries without documentation
Using "Since:" instead of "Since"

I know the former makes it not show up, and I think something committed yesterday had that.

**Comment by hughsie** [comment]
> Using "Since:" instead of "Since"

Wait, what's wrong with the former?

**Comment by superm1** [comment]
> > Using "Since:" instead of "Since"
> 
> Wait, what's wrong with the former?

gidocgen strips it.  I've noticed that if you include a line starting with `Since:` it's missing.

**Comment by hughsie** [comment]
> gidocgen strips it

Can you update your gi-docgen subproject and try again? I didn't see anything like that.

**Comment by superm1** [comment]
> > gidocgen strips it
> 
> Can you update your gi-docgen subproject and try again? I didn't see anything like that.

Apparently that wasn't the best idea.


```
[651/653] Generating doc-fwupd with a custom command
FAILED: docs/libfwupd
/home/supermario/src/fwupd/subprojects/gi-docgen/gi-docgen.py generate --quiet --add-include-path=/home/supermario/src/fwupd/build/docs/../libfwupd --config=docs/fwupd.toml --output-dir=docs/libfwupd --no-namespace-dir --content-dir=/home/supermario/src/fwupd/docs libfwupd/Fwupd-2.0.gir
Traceback (most recent call last):
  File "/home/supermario/src/fwupd/subprojects/gi-docgen/gidocgen/gidocmain.py", line 74, in run
    res = options.run_func(options)
  File "/home/supermario/src/fwupd/subprojects/gi-docgen/gidocgen/gdgenerate.py", line 2815, in run
    gen_reference(conf, options, parser.get_repository(), templates_dir, theme_conf, content_dir, output_dir)
  File "/home/supermario/src/fwupd/subprojects/gi-docgen/gidocgen/gdgenerate.py", line 2668, in gen_reference
    content_files = gen_content_files(config, theme_config, content_dir, ns_dir, jinja_env, namespace)
  File "/home/supermario/src/fwupd/subprojects/gi-docgen/gidocgen/gdgenerate.py", line 2327, in gen_content_files
    md = markdown.Markdown(extensions=utils.MD_EXTENSIONS, extension_configs=utils.MD_EXTENSIONS_CONF)
  File "/usr/lib/python3/dist-packages/markdown/core.py", line 99, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/usr/lib/python3/dist-packages/markdown/core.py", line 126, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/usr/lib/python3/dist-packages/markdown/core.py", line 160, in build_extension
    return ext(**configs)
  File "/usr/lib/python3/dist-packages/markdown/extensions/toc.py", line 311, in __init__
    super(TocExtension, self).__init__(**kwargs)
  File "/usr/lib/python3/dist-packages/markdown/extensions/__init__.py", line 42, in __init__
    self.setConfigs(kwargs)
  File "/usr/lib/python3/dist-packages/markdown/extensions/__init__.py", line 73, in setConfigs
    self.setConfig(key, value)
  File "/usr/lib/python3/dist-packages/markdown/extensions/__init__.py", line 61, in setConfig
    if isinstance(self.config[key][0], bool):
KeyError: 'permalink_class'
[652/653] Generating doc-fwupdplugin with a custom command
FAILED: docs/libfwupdplugin
/home/supermario/src/fwupd/subprojects/gi-docgen/gi-docgen.py generate --quiet --add-include-path=/home/supermario/src/fwupd/build/docs/../libfwupd --add-include-path=/home/supermario/src/fwupd/build/docs/../libfwupdplugin --config=docs/fwupdplugin.toml --output-dir=docs/libfwupdplugin --no-namespace-dir --content-dir=/home/supermario/src/fwupd/docs libfwupdplugin/FwupdPlugin-1.0.gir
Traceback (most recent call last):
  File "/home/supermario/src/fwupd/subprojects/gi-docgen/gidocgen/gidocmain.py", line 74, in run
    res = options.run_func(options)
  File "/home/supermario/src/fwupd/subprojects/gi-docgen/gidocgen/gdgenerate.py", line 2815, in run
    gen_reference(conf, options, parser.get_repository(), templates_dir, theme_conf, content_dir, output_dir)
  File "/home/supermario/src/fwupd/subprojects/gi-docgen/gidocgen/gdgenerate.py", line 2668, in gen_reference
    content_files = gen_content_files(config, theme_config, content_dir, ns_dir, jinja_env, namespace)
  File "/home/supermario/src/fwupd/subprojects/gi-docgen/gidocgen/gdgenerate.py", line 2327, in gen_content_files
    md = markdown.Markdown(extensions=utils.MD_EXTENSIONS, extension_configs=utils.MD_EXTENSIONS_CONF)
  File "/usr/lib/python3/dist-packages/markdown/core.py", line 99, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/usr/lib/python3/dist-packages/markdown/core.py", line 126, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/usr/lib/python3/dist-packages/markdown/core.py", line 160, in build_extension
    return ext(**configs)
  File "/usr/lib/python3/dist-packages/markdown/extensions/toc.py", line 311, in __init__
    super(TocExtension, self).__init__(**kwargs)
  File "/usr/lib/python3/dist-packages/markdown/extensions/__init__.py", line 42, in __init__
    self.setConfigs(kwargs)
  File "/usr/lib/python3/dist-packages/markdown/extensions/__init__.py", line 73, in setConfigs
    self.setConfig(key, value)
  File "/usr/lib/python3/dist-packages/markdown/extensions/__init__.py", line 61, in setConfig
    if isinstance(self.config[key][0], bool):
KeyError: 'permalink_class'
```

**Comment by superm1** [comment]
And with current version it seems that the `Since:`/`Since` thing is not a problem anymore for me either..

**Comment by hughsie** [comment]
> it seems that the Since:/Since thing is not a problem anymore for me either

Do you think we should standardize on the former or latter? Or it doesn't matter?

**Comment by superm1** [comment]
> > it seems that the Since:/Since thing is not a problem anymore for me either
> 
> Do you think we should standardize on the former or latter? Or it doesn't matter?

doesn't matter, as long as both work.

**Comment by hughsie** [comment]
> doesn't matter, as long as both work.

I wonder if both work for gtkdoc tho... /me tests.

**Comment by hughsie** [comment]
I don't think you can check for a python module version in meson yet: https://github.com/mesonbuild/meson/issues/3551

**Comment by superm1** [comment]
> I don't think you can check for a python module version in meson yet: https://github.com/mesonbuild/meson/issues/3551

Can we do our check that we used to use for building images? Run a python app that does it?

It were putting docs on by default, I think we need to make it relatively foolproof.

**Comment by hughsie** [comment]
> I'll look at this tomorrow.

Tomorrow came early.

**Review by superm1 — APPROVED** [review]

**Comment by superm1** [comment]
for the gidocgen stuff to me all that's missing to me now is a "top level" `index.html` to link out to the child ones for when this publishes to fwupd.github.io.

I just fixed up the CI job for it, so hopefully it should otherwise DTRT at next release.

**Comment by hughsie** [comment]
> a "top level" index.html to link out to the child ones

We almost want an introduction page, right?

> I just fixed up the CI job for it

I think we'll need to switch Ubuntu CI to using gi-docgen then... If the Ubuntu CI is the one uploading to fwupd.github.io? I'll admit I don't know why that magic bit happens.

**Comment by hughsie** [comment]
It needs to be copied from docs rather than build/docs, but something like this?

Screenshot 2021-06-11 at 10-00-18 fwupd

**Comment by superm1** [comment]
>It needs to be copied from docs rather than build/docs, but something like this?

Looks great!
Added a change to `docs/meson.build` to install it.

> I think we'll need to switch Ubuntu CI to using gi-docgen then... If the Ubuntu CI is the one uploading to fwupd.github.io? I'll admit I don't know why that magic bit happens.

Yeah Ubuntu CI makes docs and publishes them from Circle CI on tagged releases.  Just made some adjustments for it.

**Pull request merged**
