### PR TITLE
trivial: Add new convenience API to make plugins simpler

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
What do you think about including the word "from" in the new helper func names?

Ie `set_version_from_raw16`

**Comment by hughsie** [comment]
Maybe; what about counter-counter-proposal `fu_device_set_version_from_uint16`

**Comment by superm1** [comment]
> Maybe; what about counter-counter-proposal `fu_device_set_version_from_uint16`

Sure

**Comment by hughsie** [comment]
Updated^^

**Review by superm1 — APPROVED** [review]

**Pull request merged**
