### PR TITLE
trivial: add allow-stderr to ci autopkgtest

### PR DESCRIPTION
**Pull request by ycheng**
This commit + [87470ea](https://github.com/fwupd/fwupd/commit/87470ea3e010c58d927e0a57be7162c9fc740e73) fix https://github.com/fwupd/fwupd/issues/4299 per my test (against fwupd 1.7.5)

Type of pull request:

- [V] Code fix

### CODE REVIEW

**Comment by superm1** [comment]
Do to know what is actually emitted to stderr? I'm a bit surprised this is needed by default and would think it means a failure is hidden.

**Comment by ycheng** [comment]
Hi Mario, If you check https://ci.debian.net/data/autopkgtest/testing/amd64/f/fwupd/19232275/log.gz
Search for "test ci:  - - - - - - - - - - stderr - - - - - - - - - -" you will see lots of stderr output.

AFAIK, for autopkgtest, the default is: if the test job output anything to stderr, then the test failed.
So we need to add this, as --verbose is added to /usr/libexec/fwupd/fwupd in the test script.

Ref: https://github.com/fwupd/fwupd/blob/cda5879974d79e04bce3aa942636c0137c42b242/data/installed-tests/fwupdmgr-p2p.sh#L10

**Comment by superm1** [comment]
#4303 is merged, hopefully that fixes things.  Thanks a lot for the pointer about stderr!

**Comment by ycheng** [comment]
Hard to say if we should remove "--verbose". If a test fails, debugging is very struggling just like this time.
The test setup / env might not be trivial to everyone.

I think provide as log as much as possible shold be the right way to go.

IMO, maybe only 2>&1 only for the command with --verbose.

**Pull request closed without merging**
