### PR TITLE
optionrom: Set a read timeout when reading optionrom data

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/7964

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 i don't have any devices with optionrom on this machine, but I can certainly try a few machines with ROMs next week.

**Comment by superm1** [comment]
Well what do you know - I can reproduce the same issue as #7964.  With this branch, here's what I see.

```sh
22:30:20.527 FuMain               Called Verify('202d09740f7addab7b2ee4f2b0b62713c80c2754',)
22:30:32.223 FuStruct             FuStructUdevMonitorNetlinkHeader:
  header_size: 0x28
  properties_off: 0x28
  properties_len: 0x1b3
  filter_subsystem_hash: 0x79416616
  filter_devtype_hash: 0x1e54a61c
  filter_tag_bloom_hi: 0x8211a02
  filter_tag_bloom_lo: 0x9104000
22:30:32.223 FuEngine             udev changed card0
22:30:32.223 FuPlugin             udev_device_changed(linux_display)
22:30:32.223 FuStruct             FuStructUdevMonitorNetlinkHeader:
  header_size: 0x28
  properties_off: 0x28
  properties_len: 0x1b3
  filter_subsystem_hash: 0x79416616
  filter_devtype_hash: 0x1e54a61c
  filter_tag_bloom_hi: 0x8211a02
  filter_tag_bloom_lo: 0x9104000
22:30:32.223 FuEngine             udev changed card0
22:30:32.223 FuPlugin             udev_device_changed(linux_display)
22:30:32.223 FuClientList         client :1.3406 removed
22:30:32.223 FuMain               connected clients: 0
22:30:32.223 FuIdle               uninhibiting: timeout by connected-clients
```

```sh
(fwupd) ~/src/fwupd (hughsie/optionrom-with-timeout) [1]
❯ fwupdmgr verify 
WARNING: This package has not been validated, it may not work properly.
0.      Cancel
1.      202d09740f7addab7b2ee4f2b0b62713c80c2754 (AMD Radeon Pro WX 3200 Series)
2.      ce4c74a5188d5b9cdb1e72ed32dad2d313c1c999 (AQtion AQC107 NBase-T/IEEE 802.3an Ethernet Controller [Atlantic 10G])
3.      557960baa042cab815d0c30d318fa147f32cdd55 (System Firmware)
Choose device [0-3]: 1
failed to verify AMD Radeon Pro WX 3200 Series: failed to read firmware: timeout
```

I'd say we have a _real_ problem still with verify that it's not actually going out to the kernel to do stuff.

**Comment by superm1** [comment]
This is a 6.12-rc5 kernel with random assortment of patches (nothing that touches reading rom files though).

I don't know if this ever worked, but FWIW:
```
❯ fwupdmgr verify
WARNING: This package has not been validated, it may not work properly.
0.      Cancel
1.      202d09740f7addab7b2ee4f2b0b62713c80c2754 (AMD Radeon Pro WX 3200 Series)
2.      ce4c74a5188d5b9cdb1e72ed32dad2d313c1c999 (AQtion AQC107 NBase-T/IEEE 802.3an Ethernet Controller [Atlantic 10G])
3.      557960baa042cab815d0c30d318fa147f32cdd55 (System Firmware)
Choose device [0-3]: 2
failed to verify AQtion AQC107 NBase-T/IEEE 802.3an Ethernet Controller [Atlantic 10G]: failed to read firmware: failed to read 14: Input/output error
```

**Comment by hughsie** [comment]
I guess a timeout is better than a daemon hang :) Also good you can reproduce. Maybe also optionrom is now more trouble than it's worth? I do know some people that use it for verification, but I don't know if providing the feature is actually *useful* or meaningful security.

**Comment by superm1** [comment]
I think this regressed in https://github.com/fwupd/fwupd/commit/325d87ea749810c00660df58d40ecd7952b1c7cf.  That is it's trying to read `/dev/dri/card0` instead of `/sys/bus/pci/drivers/amdgpu/${BDF}/rom`

**Comment by superm1** [comment]
> I think this regressed in [325d87e](https://github.com/fwupd/fwupd/commit/325d87ea749810c00660df58d40ecd7952b1c7cf). That is it's trying to read `/dev/dri/card0` instead of `/sys/bus/pci/drivers/amdgpu/${BDF}/rom`

[Here's a fix](https://github.com/fwupd/fwupd/pull/8216)

**Comment by superm1** [comment]
(closing as this isn't needed now that it works properly)

**Pull request closed without merging**
