### PR TITLE
trivial: Fix build failure of missing fu-hash.h

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/3272

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by Asiderr — APPROVED** [review]
Fixes https://github.com/fwupd/fwupd/issues/3272

**Comment by dkwo** [comment]
If I try to build fwupd 1.6.3 on void linux (musl), I still get error
```
[1/468] Compiling C object plugins/tpm-eventlog/fwupdtpmevlog.p/fu-tpm-eventlog.c.o
FAILED: plugins/tpm-eventlog/fwupdtpmevlog.p/fu-tpm-eventlog.c.o
cc -Iplugins/tpm-eventlog/fwupdtpmevlog.p -Iplugins/tpm-eventlog -I../plugins/tpm-eventlog -I. -I.. -Ilibfwupd -I../libfwupd -Ilibfwupdplugin -I../libfwupdplug
in -I/usr/include/libxmlb-2 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gio-unix-2.0 -I/u
sr/include/gudev-1.0 -I/usr/include/json-glib-1.0 -I/usr/include/gusb-1 -I/usr/include/libusb-1.0 -I/usr/include/tss2 -fdiagnostics-color=always -DNDEBUG -D_FI
LE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c99 -Waggregate-return -Wunused -Warray-bounds -Wcast-align -Wclobbered -Wdeclaration-after-statement -Wdisc
arded-qualifiers -Wduplicated-branches -Wduplicated-cond -Wempty-body -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-signedness -Wignored-qualifiers
 -Wimplicit-function-declaration -Winit-self -Wlogical-op -Wmaybe-uninitialized -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmiss
ing-noreturn -Wmissing-parameter-type -Wmissing-prototypes -Wnested-externs -Wno-cast-function-type -Wno-address-of-packed-member -Wno-unknown-pragmas -Wno-mis
sing-field-initializers -Wno-strict-aliasing -Wno-suggest-attribute=format -Wno-unused-parameter -Wold-style-definition -Woverride-init -Wpointer-arith -Wredun
dant-decls -Wreturn-type -Wshadow -Wsign-compare -Wstrict-aliasing -Wstrict-prototypes -Wswitch-default -Wtype-limits -Wundef -Wuninitialized -Wunused-but-set-
variable -Wunused-variable -Wvla -Wwrite-strings -fstack-protector-strong -DFWUPD_COMPILATION -D_DEFAULT_SOURCE -DFWUPD_DISABLE_DEPRECATED -D_BSD_SOURCE -D__BS
D_VISIBLE -D_XOPEN_SOURCE=700 -D_GNU_SOURCE -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe -pthread -MD -MQ plugins/tpm-eventlog/fwupdtp
mevlog.p/fu-tpm-eventlog.c.o -MF plugins/tpm-eventlog/fwupdtpmevlog.p/fu-tpm-eventlog.c.o.d -o plugins/tpm-eventlog/fwupdtpmevlog.p/fu-tpm-eventlog.c.o -c ../p
lugins/tpm-eventlog/fu-tpm-eventlog.c
In file included from ../libfwupdplugin/fwupdplugin.h:33,
                 from ../plugins/tpm-eventlog/fu-tpm-eventlog.c:11:
../libfwupdplugin/fu-plugin-vfuncs.h:17:10: fatal error: fu-hash.h: No such file or directory
   17 | #include "fu-hash.h"
      |          ^~~~~~~~~~~
compilation terminated.
```
Do you know what is going wrong?

Thanks.

**Comment by superm1** [comment]
> If I try to build fwupd 1.6.3 on void linux (musl), I still get error
> 
> ```
> [1/468] Compiling C object plugins/tpm-eventlog/fwupdtpmevlog.p/fu-tpm-eventlog.c.o
> FAILED: plugins/tpm-eventlog/fwupdtpmevlog.p/fu-tpm-eventlog.c.o
> cc -Iplugins/tpm-eventlog/fwupdtpmevlog.p -Iplugins/tpm-eventlog -I../plugins/tpm-eventlog -I. -I.. -Ilibfwupd -I../libfwupd -Ilibfwupdplugin -I../libfwupdplug
> in -I/usr/include/libxmlb-2 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gio-unix-2.0 -I/u
> sr/include/gudev-1.0 -I/usr/include/json-glib-1.0 -I/usr/include/gusb-1 -I/usr/include/libusb-1.0 -I/usr/include/tss2 -fdiagnostics-color=always -DNDEBUG -D_FI
> LE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c99 -Waggregate-return -Wunused -Warray-bounds -Wcast-align -Wclobbered -Wdeclaration-after-statement -Wdisc
> arded-qualifiers -Wduplicated-branches -Wduplicated-cond -Wempty-body -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-signedness -Wignored-qualifiers
>  -Wimplicit-function-declaration -Winit-self -Wlogical-op -Wmaybe-uninitialized -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmiss
> ing-noreturn -Wmissing-parameter-type -Wmissing-prototypes -Wnested-externs -Wno-cast-function-type -Wno-address-of-packed-member -Wno-unknown-pragmas -Wno-mis
> sing-field-initializers -Wno-strict-aliasing -Wno-suggest-attribute=format -Wno-unused-parameter -Wold-style-definition -Woverride-init -Wpointer-arith -Wredun
> dant-decls -Wreturn-type -Wshadow -Wsign-compare -Wstrict-aliasing -Wstrict-prototypes -Wswitch-default -Wtype-limits -Wundef -Wuninitialized -Wunused-but-set-
> variable -Wunused-variable -Wvla -Wwrite-strings -fstack-protector-strong -DFWUPD_COMPILATION -D_DEFAULT_SOURCE -DFWUPD_DISABLE_DEPRECATED -D_BSD_SOURCE -D__BS
> D_VISIBLE -D_XOPEN_SOURCE=700 -D_GNU_SOURCE -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe -pthread -MD -MQ plugins/tpm-eventlog/fwupdtp
> mevlog.p/fu-tpm-eventlog.c.o -MF plugins/tpm-eventlog/fwupdtpmevlog.p/fu-tpm-eventlog.c.o.d -o plugins/tpm-eventlog/fwupdtpmevlog.p/fu-tpm-eventlog.c.o -c ../p
> lugins/tpm-eventlog/fu-tpm-eventlog.c
> In file included from ../libfwupdplugin/fwupdplugin.h:33,
>                  from ../plugins/tpm-eventlog/fu-tpm-eventlog.c:11:
> ../libfwupdplugin/fu-plugin-vfuncs.h:17:10: fatal error: fu-hash.h: No such file or directory
>    17 | #include "fu-hash.h"
>       |          ^~~~~~~~~~~
> compilation terminated.
> ```
> 
> Do you know what is going wrong?
> 
> Thanks.

can you open your own issue for this with a full copy of the build log?

**Comment by dkwo** [comment]
Done. #3657

**Pull request merged**
