### PR TITLE
Actually implement rescan in FuUdevDevice

### PR DESCRIPTION
**Pull request by hughsie**
This allows the plugin to force a reload of the device using a new GUdevDevice
object. This is required as the values are cached in the immutable object.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
there are plugins that use udev and implement rescan already so I think you need to check for subclassed no?

**Comment by superm1** [comment]
@ArchangeGabriel can you please check what's up with the TPM stuff 404'ing in CI?  Did a package or repo change?

**Comment by hughsie** [comment]
@superm1 in `thunderbolt/fu-thunderbolt-device.c` there is already logic to handle rescan, and I don't really want to touch it is it's working. The TBT rescan will "overwrite" the baseclass rescan -- which I think means we don't break anything. Synaptics MST is the same; we want to keep the existing logic.

**Comment by ArchangeGabriel** [comment]
> @ArchangeGabriel can you please check what's up with the TPM stuff 404'ing in CI? Did a package or repo change?

I don’t remember/see exactly at which step pacman cache gets updated in the CI, but this is a cache issue: pacman package list contains swtpm 0.5.1-1, but the mirror has been updated to 0.5.1-2 (released on 2020-12-02 04:41 UTC). It could be an unlucky timing issue: the package list was refreshed, and before it got to downloading the package that one has been replaced with a new version. Re-running should very likely fix.

**Comment by superm1** [comment]
> I don’t remember/see exactly at which step pacman cache gets updated in the CI, but this is a cache issue: pacman package list contains swtpm 0.5.1-1, but the mirror has been updated to 0.5.1-2 (released on 2020-12-02 04:41 UTC). It could be an unlucky timing issue: the package list was refreshed, and before it got to downloading the package that one has been replaced with a new version. Re-running should very likely fix.

Is the pacman cache built in the docker container or in the scripts that run in the arch script?  If it's in the container, I think we should add a step to the arch script to refresh at that time.  We split up the container generation to be nightly and automatic and then run the CI on demand for the job.  So we always have a good "baseline" even if distros break (famous last words I guess...)

**Comment by superm1** [comment]
I just re-ran it and it still fails.  I see it has `-S` in the call too.

**Comment by superm1** [comment]
> The TBT rescan will "overwrite" the baseclass rescan

Ah OK.  Fine in this case then.

**Review by superm1 — APPROVED** [review]

**Pull request merged**
