### PR TITLE
modem-manager: Fix one critical warning when updating

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by aleksander0m** [comment]
Not sure I get what the change is trying to fix? Why was the MMManager object added in `fu_mm_device_udev_new()` not good?

**Comment by aleksander0m** [comment]
I see, this is an attempt to fix https://github.com/fwupd/fwupd/discussions/4674#discussioncomment-2821300 right?
Couldn't it be that the `MMManager` pointer is actually a valid one, not NULL, and we're missing some ref somewhere? i.e. the warning happens because it was already disposed by the time we try to ref it again.

**Comment by aleksander0m** [comment]
Oh, I see the manager pointer may indeed be NULL, all the new "incorporate" logic is new to my eyes.
Why not just `self->manager = g_object_ref (donor->manager);` in `fu_mm_device_incorporate()`?

**Comment by hughsie** [comment]
> Why not just self->manager = g_object_ref (donor->manager); in fu_mm_device_incorporate()?

Ya, that's what I did first. g_set_object is slightly "safer" in that it will unref the destination if it's already somehow set, and also skip the operation if the source is the same as the destination.

**Comment by clobrano** [comment]
Just tested, it fix https://github.com/fwupd/fwupd/discussions/4674#discussioncomment-2820919 indeed :+1:

**Pull request merged**
