### PR TITLE
Add support for Qualcomm Series 5 Gen 1 and Gen 2 and Series 3 Gen 1 …

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
>Huh; again this is only caught in 1_9_X. Suspicious.

I've got a patch against master too -- but I'll also work out why the unused.py didn't detect it too.

**Comment by d4s** [comment]
@hughsie I did the test -- update works perfectly.
Strange, on original branch the device is properly detected as `QCC5171` (I did the check), but now on `main` and here I see 'Unknown device' instead,
```
├─Unknown Device:
│     Device ID:          0b3c94fad31628e8adddaad723b8b6b5e24a9665
│     Current version:    1.1.2
│     Vendor:             USB:0x0A12
│     GUID:               f3eb444d-46de-59da-97b1-7a281cb6a778 ← USB\VID_0A12&PID_4007
│     Device Flags:       • Updatable
│                         • Device stages updates
│                         • Device can recover flash failures
│                         • Device is usable for the duration of the update
│                         • Signed Payload
```

**Review by d4s — APPROVED** [review]

**Comment by hughsie** [comment]
> Strange, on original and main branches the device is properly detected as QCC5171

Can you compare main and this branch with `fwupdtool get-devices --plugins audio-s5gen2 -vv --no-timestamp` -- we might be missing a backport somewhere. Thanks!

**Comment by hughsie** [comment]
> device is properly detected as QCC5171

I'm now a bit confused on _how_ it works in `main` :)

**Comment by hughsie** [comment]
> I'm now a bit confused on how it works in main :)

I think I've worked it out with the emulation, we were missing c8a6d9d456bafed9eaca5e04705e0915e6dfc16b too. Can you retry please.

**Comment by d4s** [comment]
@hughsie brilliant! All works for now.

**Pull request merged**
