### PR TITLE
Wip/hughsie/firmware stream

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
> @superm1 also, FYI -- I think I'm going to branch 1_9_x just after the 1.9.10 tag (switching the Since tags to 1.10.0 or 1.10.1), and then work on the streaming work in main -- there are a lot of disruptive changes, and I've got a few more planned. I did my first zero-copy firmware update today -- 2GB of firmware payload with 7MB of RSS :)

2.0.0?

**Comment by hughsie** [comment]
> 2.0.0?

I think that implies ABI breaks -- I'm not really in the appetite for that yet.

**Comment by superm1** [comment]
Yeah just thinking big chance, fresh start to the year, clean up all the stuff in the deprecated list etc.

But can punt it further if you want.

**Comment by hughsie** [comment]
> fresh start to the year

Yup, I suppose. If I'm touching all the plugins maybe it's a good time. I'll branch.

**Pull request merged**
