### PR TITLE
fu-engine.c: do not inhibit on battery full but discharging

### PR DESCRIPTION
**Pull request by djcampello**
Change-Id: I45f71dbfc70a90aea2e33ec98fab1b247da3c714

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
> Strip out gerrit Change-IDs from commit message before upstream submission.

I don't have a strong feeling on this.  If it makes your backport / tagging process easier to get stuff you can leave them.  If you think they shouldn't be there, then perhaps we should have a pre-commit hook catch them in commit messages?

**Comment by hughsie** [comment]
I'm not sure I care, if it's helpful for you it's fine for me. I'm not sure about the logic tho; this feels like something that belongs in the powerd plugin, no?

**Comment by djcampello** [comment]
> > Strip out gerrit Change-IDs from commit message before upstream submission.
> 
> I don't have a strong feeling on this. If it makes your backport / tagging process easier to get stuff you can leave them. If you think they shouldn't be there, then perhaps we should have a pre-commit hook catch them in commit messages?

It makes life easier :)

> I'm not sure I care, if it's helpful for you it's fine for me. I'm not sure about the logic tho; this feels like something that belongs in the powerd plugin, no?

I think upower suffers of the same but I cannot confirm it. It seems that in some platforms when the battery is full, acpi? reports the state as discharging

**Comment by djcampello** [comment]
I need to think about this a bit more.... I will follow up here...

**Comment by djcampello** [comment]
If needed (we want to apply only to powerd) I can make the plugin set the battery state as FULL whenever it sees 100% battery regardless of the reported state. Let me know what you think

**Comment by hughsie** [comment]
> make the plugin set the battery state as FULL whenever it sees 100% battery

This does make me uncomfortable. If it's a hardware bug it should be worked around in the kernel, and if it's a powerd bug then it should be fixed in powerd -- otherwise everything that consumes that property will need to be fixed -- possibly in multiple projects. i.e. it seems like a workaround that needs to be pushed down.

**Comment by djcampello** [comment]
Agreed, closed this now and will look into a fix at a lower layer! Thanks for the review!

**Pull request closed without merging**
