### PR TITLE
Wip/hughsie/1 7 x backports

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 anything else you think we're missing?

**Comment by hughsie** [comment]
@superm1 I'm also a bit perplexed by the out-of-tree-link CI failure; any ideas?

**Comment by superm1** [comment]
> Run-time dependency fwupd found: YES1.8.3
> Run-time dependency fwupdplugin found: YES1.8.3

I think that's why it's failing.  It's trying to link with a 1.8.3 library.

**Comment by superm1** [comment]
> > Run-time dependency fwupd found: YES1.8.3
> > Run-time dependency fwupdplugin found: YES1.8.3
> 
> I think that's why it's failing. It's trying to link with a 1.8.3 library.

It seems to me when the just built package installs it happens to pull in the newer version from the arch repos.
>  fwupd-1.8.3-1-x86_64 downloading...

@ArchangeGabriel thoughts?

**Comment by superm1** [comment]
> @superm1 anything else you think we're missing?

anything for the ccgx docks so that they don't need 1.8.x to update?  That's all that comes to mind to me.

**Comment by ArchangeGabriel** [comment]
> > > Run-time dependency fwupd found: YES1.8.3
> > > Run-time dependency fwupdplugin found: YES1.8.3
> > 
> > 
> > I think that's why it's failing. It's trying to link with a 1.8.3 library.
> 
> It seems to me when the just built package installs it happens to pull in the newer version from the arch repos.
> 
> > fwupd-1.8.3-1-x86_64 downloading...
> 
> @ArchangeGabriel thoughts?

Yes, it happens when you run `pacman -Syu --noconfirm qt5-base` (https://github.com/fwupd/fwupd/blob/main/contrib/ci/arch.sh#L40). Given the time span between the first command and this last one, I’m not sure it’s relevant to be constantly upgrading the cache and the system. I initially added it to the first command to avoid caching issue w.r.t. to the database in the Docker image, but then this spread to other commands to. I’ll open two PR against 1_7_X and main to better fix this.

**Comment by superm1** [comment]
> > > > Run-time dependency fwupd found: YES1.8.3
> > > > Run-time dependency fwupdplugin found: YES1.8.3
> > > 
> > > 
> > > I think that's why it's failing. It's trying to link with a 1.8.3 library.
> > 
> > It seems to me when the just built package installs it happens to pull in the newer version from the arch repos.
> > 
> > > fwupd-1.8.3-1-x86_64 downloading...
> > 
> > @ArchangeGabriel thoughts?
> 
> Yes, it happens when you run `pacman -Syu --noconfirm qt5-base` (https://github.com/fwupd/fwupd/blob/main/contrib/ci/arch.sh#L40). Given the time span between the first command and this last one, I’m not sure it’s relevant to be constantly upgrading the cache and the system. I initially added it to the first command to avoid caching issue w.r.t. to the database in the Docker image, but then this spread to other commands too. I’ll open two PR against 1_7_X and main to better fix this.

Thanks so much!

**Pull request merged**
