### PR TITLE
Wip/hughsie/fu plugin add device gtype

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
For some reason the fuzzers were running wild for 5 hours eating through our minutes... I just stopped it.

**Comment by superm1** [comment]
@hughsie can you add https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes to the fuzzing job maybe?

**Review by superm1 — APPROVED** [review]

**Comment by hughsie** [comment]
@superm1 something like:

       fuzzing:
         runs-on: ubuntu-latest
    +    timeout-minutes: 10
         steps:

...right?

**Comment by superm1** [comment]
> @superm1 something like:
> 
> ```
>    fuzzing:
>      runs-on: ubuntu-latest
> +    timeout-minutes: 10
>      steps:
> ```
> 
> ...right?

yep something like that.

**Pull request merged**
