### PR TITLE
trivial: Fix fuzzers

### PR DESCRIPTION
**Pull request by superm1**
Hopefully this is the reason for the failure...
The variable seems to have changed from `fuzz-seconds` to `fuzz-time`

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Urgh, seriously? If so, bad form Google.

**Comment by superm1** [comment]
It's a guess - the documentation in https://google.github.io/oss-fuzz/getting-started/continuous-integration/ seems to make references to both...

**Comment by superm1** [comment]
Nope, seems it's still running past the 300 second timer still.

**Comment by jonathanmetzman** [comment]
CIFuzz maintainer here, sorry about this issue. I think I've located the problem and have a PR ready: https://github.com/google/oss-fuzz/pull/5651

**Pull request closed without merging**
