### PR TITLE
Wip/hughsie/412

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]

**Comment by AdamWill** [comment]
note the additional check here breaks KDE's "Discover" tool: https://bugzilla.redhat.com/show_bug.cgi?id=2173022 and https://bugs.kde.org/show_bug.cgi?id=466318 . Probably needs addressing in Discover, though, as the check does make sense.

**Comment by hughsie** [comment]
@AdamWill It wouldn't have worked before this PR either -- now the LVFS is filtering out insecure fwupd user agents less than 0.8 it would refuse to provide updates for `fwupd/(null)` which is what this PR fixes. It definitely needs fixing as you describe n discover, and TBH I completely forgot it was using libfwupd. tl;dr: call `fwupd_client_set_user_agent_for_package()` after connect has completed when we know the daemon version.

Both bugs are correct, well done for understanding the root cause.

**Comment by AdamWill** [comment]
Roger. Note the [API doc for connect](https://fwupd.github.io/libfwupd/method.Client.connect.html) says "Sets up the client ready for use. Most other methods call this for you, and do you only need to call this if you are just watching the client." Seems like that's not really correct, right? If I was writing an fwupd client from scratch based on the API docs, I probably wouldn't grok that I need to do `connect()` and `set_user_agent()` or `set_user_agent_for_package()` before anything will really work, which seems to be the case, right? Perhaps the API docs could use updating?

**Comment by hughsie** [comment]
So maybe it's best to just make it work both ways? i.e. *save* the package name and version and then only set the user_agent when the client has connected? That seems a whole less magic, and also means the sync-auto-connect stuff works easier.

**Comment by AdamWill** [comment]
anything you can do on the fwupd side to make life easier for clients sounds like a win to me!

**Pull request merged**
