### PR TITLE
Added completion script for fish shell

### PR DESCRIPTION
**Pull request by exploide**
Type of pull request:
- [ ] New plugin
- [ ] Code fix
- [X] Feature
- [ ] Documentation

I saw this repository already contains a completion script for bash. This PR adds a completion script for fish shell.

In case you don't like including it here, I could also submit it to the fish repository. However, it usually is preferred to ship completion scripts by upstream projects and bash is already included here.

What I have not done so far is adding the script to the spec file. It would belong into `/usr/share/fish/vendor_completions.d`.

### CODE REVIEW

**Comment by hughsie** [comment]
Doesn't it need installing somewhere?

**Comment by exploide** [comment]
> Doesn't it need installing somewhere?

Fish is autoloading functions and complete scripts depending on their name whenever they are located in one of the proper directories. For this that would be inside `/usr/share/fish/vendor_completions.d`. That could be done from within the spec file, at least for RPMs.

**Comment by hughsie** [comment]
I think it should be installed by meson.build too :)

**Comment by exploide** [comment]
Ok, that's possible.

If I should do that, can you give me a pointer? I have no experience with this build system.

**Comment by superm1** [comment]
Unlike bash-completion it appears you're not modifying the file at all with data from the installation variables.  So in that case you just need to install it to the proper directory.

1. Add your subdirectory to `data/meson.build`
2.  Some pointers in an example that installs a flat file into the filesystem are here:
https://github.com/fwupd/fwupd/blob/master/data/meson.build#L33
So make a `meson.build` in your subdirectory to do that.
3. Confirm it actually gets installed.
4. Add references to `contrib/fwupd.spec.in` and `contrib/debian/fwupd.install` as necessary to update deb/rpm packaging.

**Comment by exploide** [comment]
Ok, thank you! Since I need to do these changes and run a test build, I need to wait until I'm back home at the end of the week. No progress until then, hope that's fine.

**Comment by hughsie** [comment]
> No progress until then, hope that's fine

No problem at all, we appreciate the help!

**Comment by exploide** [comment]
Done!

It took me way too long to understand that I need to commit my changes in order to be recognized during the local test builds...

**Comment by hughsie** [comment]
Can you rebase against master and squash the commits together please. Then force push to update this PR then we're good to merge. Thanks!

**Comment by exploide** [comment]
Sure, done :)

**Pull request merged**
