### PR TITLE
Wip/hughsie/quirk typo

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]

**Comment by hughsie** [comment]
@superm1 one thing I wasn't sure about was if we should rename some of the quirks. eg. `FlashSize` -> `CcgxFlashSize` and `AvrChipId` -> `DfuAvrChipId`.

**Comment by superm1** [comment]
>@superm1 one thing I wasn't sure about was if we should rename some of the quirks. eg. FlashSize -> CcgxFlashSize and AvrChipId -> DfuAvrChipId.

no strong feeling either direction

**Comment by hughsie** [comment]
Okay, don't merge this just yet, I have a better idea still.

**Comment by hughsie** [comment]
Better idea in https://github.com/fwupd/fwupd/pull/2961

**Pull request closed without merging**
