### PR TITLE
Wip/hughsie/1 1 x sbat

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Lets see how much CI explodes. Needless to say, this is not what I wanted to do, but RHEL z-stream isn't going to allow a rebase.

**Comment by superm1** [comment]
I think you'll want to backport the CI changes from 1.2.x

**Review by martinezjavier — APPROVED** [review]
The backport looks good to me. Thanks for doing this.

**Comment by hughsie** [comment]
I'm really wondering if we want to do this upstream, it's a bag of hacks. I think maybe we just do this as a downstream patch for z-stream RHEL.

**Pull request closed without merging**
