### PR TITLE
Add an upgrade plugin for Goodix Touch Controller.

### PR DESCRIPTION
**Pull request by xulinkun**
Type of pull request:

- [x] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Hey @xulinkun -- there's still quite a bit wrong -- do you want me to push an origin branch with some of the fixups?

**Comment by xulinkun** [comment]
> Hey @xulinkun -- there's still quite a bit wrong -- do you want me to push an origin branch with some of the fixups?

Sorry, could you please point out mistakes?

**Comment by hughsie** [comment]
@xulinkun I've pushed a wip/hughsie/goodix-tp branch to origin with all the big changes. Using a derivable firmware and device baseclass means all the specifics get to go in the correct namespace without the horrible hw_ops thing that is just a workaround for not having a derivable baseclass. I've switched it to use plugin_class->backend_device_added so that the correct device superclass is created -- 100% untested, but other plugins do similar things.

Please can you have a look at the new branch and see if it makes sense to you; I'm happy to answer questions. There are a lot of FIXMEs so if you can fix up those and just push to the branch we can then squash them down when it's ready for review into a single commit. Don't worry about perfect commit messages, and please don't rebase or rewrite the branch.

**Comment by xulinkun** [comment]
> 

Thanks for your suggestion, I'll verify the code according to your branch.

**Comment by xulinkun** [comment]
Hi，@hughsie， I have a simple question.
```c
// FIXME this needs integrating with the usual FuDevice-> vfunc
#if 0
#include "fu-goodixtp-common.h"

static gboolean
read_pkg(FuDevice *device, guint32 addr, guint8 *buf, guint32 len, GError **error)
{
	guint8 HidBuf[PACKAGE_LEN] = {0};

	HidBuf[0] = REPORT_ID;
	HidBuf[1] = I2C_DIRECT_RW;
...........
```

How should I implement `FuDevice-> vfunc`, could you give me an example?

**Comment by hughsie** [comment]
> How should I implement FuDevice-> vfunc

Sure! What I meant by that was that it needs to use the FuDeviceClass helpers -- e.g.  `klass_device->write_firmware = fu_goodixtp_gtx8_device_write_firmware` is one that I stubbed out with `return TRUE; // FIXME` -- it's likely the old code in fu-goodixtp-hid-device can just be used -- and you don't need to use any indirection for gtx8.

**Comment by hughsie** [comment]
It's fine, don't worry. Just carry on and we can sort it out later.

**Comment by xulinkun** [comment]
I have modified code based on your branch, please review again.

**Comment by hughsie** [comment]
@xulinkun your branch seems a bit messed up; maybe due to the merge? I've grabbed your changes and pushed them to wip/hughsie/goodix-tp -- and added a whole lot more FIXMEs. Can you fix up those fixmes and push to *my* branch please, and then re-open a new pull request using my branch as a source. Thanks.

**Pull request closed without merging**
