### PR TITLE
trivial: Cache the DRM properties at ->probe()

### PR DESCRIPTION
**Pull request by hughsie**
Also, construct plausible GUIDs using the EDID if connected and enabled.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
Enabled changes when dpms is active. I suggest making guid whether enabled is set or not

**Comment by hughsie** [comment]
So just `if (priv->display_state == FU_DISPLAY_STATE_CONNECTED)`?

**Comment by superm1** [comment]
> So just `if (priv->display_state == FU_DISPLAY_STATE_CONNECTED)`?

Yeah. And enabled can still be saved for other decisions later potentially.

**Comment by hughsie** [comment]
Got it, fixed, and I've added an EDID fixup now we're using the EISA ID more prominently.

**Comment by superm1** [comment]
It's working now.  I don't see it show up in `get-devices`, but it's in `--verbose`.

```
Loading…                 [*************************              ]13:41:09.134 FuEngine             /sys/devices/pci0000:00/0000:00:08.1/0000:c2:00.0/drm/card1/card1-eDP-1 added FuDrmDevice:
  Name:                 B140QAN02.3
  Guid:                 3fd88d9e-d257-5366-af5d-b176d1b074f7 ← EDID\VEN_AUO&DEV_E68C ⚠
  Flags:                internal
  Guid[quirk]:          d07d4a5f-22c0-5c05-8739-e3377d6aabb1 ← DRM\TYPE_DRM_CONNECTOR
  PhysicalId:           card1-eDP-1
  BackendId:            /sys/devices/pci0000:00/0000:00:08.1/0000:c2:00.0/drm/card1/card1-eDP-1
  AcquiesceDelay:       2500
  PossiblePlugin:       linux_display
  Enabled:              true
  State:                connected
```

**Review by superm1 — APPROVED** [review]

**Comment by hughsie** [comment]
> I don't see it show up in get-devices

Right, it's got no "version" so it's not going to show up as a usual device.

**Pull request merged**
