### PR TITLE
also fix syntax for 20 other translation files

### PR DESCRIPTION
**Pull request by mendel5**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [x] Documentation

Related to https://github.com/fwupd/fwupd/pull/2257 .

This is the same type of syntax fix as in the pull request for the German translation file (see https://github.com/fwupd/fwupd/pull/2257 ). I have now used search and replace to fix this issue in all .po translation files.

### CODE REVIEW

**Comment by mendel5** [comment]
> The translation comment should automatically update.

Where do the updated translation comments come from?

**Comment by hughsie** [comment]
> Where do the updated translation comments come from?

`ninja fwupd-pot` regenerates the .pot file from the source files

**Comment by mendel5** [comment]
Do I understand it correctly that if this pull request was merged and you generated a new translation file, all the changes in this pull request would be overwritten?

Therefore changing `/* more than a minute */` to `/* more than a minute remaining */` will partially fix that?
https://github.com/fwupd/fwupd/blob/72f78dc060f82a537399ded5536cb6c0cd481cff/src/fu-progressbar.c#L142

Why does it say `TRANSLATORS:` in front of all other comments but not in front of the first comment?
https://github.com/fwupd/fwupd/blob/72f78dc060f82a537399ded5536cb6c0cd481cff/po/ca.po#L19

**Comment by hughsie** [comment]
> all the changes in this pull request would be overwritten

Correct. I've just synced transifex if you'd like to check.

**Comment by mendel5** [comment]
> I've just synced transifex if you'd like to check.

I would like to check it, but I don't know how... Can you tell me?

If you have synced transifex I would expect the files in https://github.com/fwupd/fwupd/tree/master/po to have changed recently due to the regeneration, but that does not seem to be the case. Why is that?

**Comment by hughsie** [comment]
> Can you tell me?

https://www.transifex.com/freedesktop/fwupd/dashboard/

> to have changed recently due to the regeneration

This is only done at release time to prevent git churn.

**Pull request closed without merging**
