### PR TITLE
Fix a CI failure for any distro using git >= 2.35.3

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
I saw you had this branch, which it seems like the right move to me if it fixes Fedora CI.

**Comment by hughsie** [comment]
> which it seems like the right move to me if it fixes Fedora CI

I think **if** is the key word there. I had high hopes; but I regen'd the containers with this change and Fedora (or any distro with the newest git) still fails. I still need to test just doing the v2 to v3 change, but gah.

**Comment by hughsie** [comment]
Also see this: https://github.com/actions/checkout/pull/770 -- it's all a bit of a mess.

**Comment by hughsie** [comment]
I think merging this is probably the correct thing to do, although I'm still not sure what the root issue is. I suspect meson is calling git and getting the permission error caused by the new git feature, and swallowing it, and returning as if there's no git tree there.

**Comment by hughsie** [comment]
@superm1 getting there! I'm now getting what I think is a false positive:

	In function ‘fu_dell_execute_simple_smi’,
	    inlined from ‘fu_dell_detect_dock’ at ../plugins/dell/fu-dell-smi.c:106:7:
	../plugins/dell/fu-dell-smi.c:84:13: error: ‘dell_simple_ci_smi’ reading 16 bytes from a region of size 4 [-Werror=stringop-overread]
	   84 |         if (dell_simple_ci_smi(class, select, obj->input, obj->output)) {
	      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	../plugins/dell/fu-dell-smi.c:84:13: note: referencing argument 3 of type ‘const u32[4]’
	../plugins/dell/fu-dell-smi.c:84:13: note: referencing argument 4 of type ‘u32[4]’
	In file included from ../plugins/dell/fu-dell-smi.h:12,
			 from ../plugins/dell/fu-dell-smi.c:9:
	/usr/include/smbios_c/smi.h: In function ‘fu_dell_detect_dock’:
	/usr/include/smbios_c/smi.h:40:26: note: in a call to function ‘dell_simple_ci_smi’
	   40 | LIBSMBIOS_C_DLL_SPEC int dell_simple_ci_smi(u16 smiClass, u16 select, const u32 args[4], u32 res[4]);
	      |                          ^~~~~~~~~~~~~~~~~~
	cc1: all warnings being treated as errors

Sanity check please?

**Comment by superm1** [comment]
> @superm1 getting there! I'm now getting what I think is a false positive:
> 
> ```
> In function ‘fu_dell_execute_simple_smi’,
>     inlined from ‘fu_dell_detect_dock’ at ../plugins/dell/fu-dell-smi.c:106:7:
> ../plugins/dell/fu-dell-smi.c:84:13: error: ‘dell_simple_ci_smi’ reading 16 bytes from a region of size 4 [-Werror=stringop-overread]
>    84 |         if (dell_simple_ci_smi(class, select, obj->input, obj->output)) {
>       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../plugins/dell/fu-dell-smi.c:84:13: note: referencing argument 3 of type ‘const u32[4]’
> ../plugins/dell/fu-dell-smi.c:84:13: note: referencing argument 4 of type ‘u32[4]’
> In file included from ../plugins/dell/fu-dell-smi.h:12,
> 		 from ../plugins/dell/fu-dell-smi.c:9:
> /usr/include/smbios_c/smi.h: In function ‘fu_dell_detect_dock’:
> /usr/include/smbios_c/smi.h:40:26: note: in a call to function ‘dell_simple_ci_smi’
>    40 | LIBSMBIOS_C_DLL_SPEC int dell_simple_ci_smi(u16 smiClass, u16 select, const u32 args[4], u32 res[4]);
>       |                          ^~~~~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors
> ```
> 
> Sanity check please?

Yeah looks false positive to me too. I wonder if you can cast an array to make it happier. But if not then a pragma to ignore makes sense to me

**Pull request merged**
