### PR TITLE
Only fail the kernel tainted HSI test for specific taint reasons

### PR DESCRIPTION
**Pull request by hughsie**
For example, working around a firmware bug in the kernel isn't really
what the HSI attribute was intended to measure.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
Which ones are you thinking of excluding explicitly? The argument for taint on staging drivers for example means they don't have the same rigor as other drivers.

**Comment by hughsie** [comment]
> Which ones are you thinking of excluding explicitly

I was thinking of excluding:

	KERNEL_TAINT_FLAG_KERNEL_OUT_OF_SPEC
	KERNEL_TAINT_FLAG_PROCESSOR_MCE
	KERNEL_TAINT_FLAG_BAD_PAGE
	KERNEL_TAINT_FLAG_REQUESTED_BY_USERSPACE
	KERNEL_TAINT_FLAG_KERNEL_DIED
	KERNEL_TAINT_FLAG_ACPI_OVERRIDDEN
	KERNEL_TAINT_FLAG_KERNEL_ISSUED_WARNING
	KERNEL_TAINT_FLAG_FIRMWARE_WORKAROUND_APPLIED
	KERNEL_TAINT_FLAG_SOFT_LOCKUP_OCCURRED
	KERNEL_TAINT_FLAG_KERNEL_LIVE_PATCHED
	KERNEL_TAINT_FLAG_STRUCT_RANDOMIZATION_PLUGIN
	KERNEL_TAINT_FLAG_IN_KERNEL_TEST

**Comment by superm1** [comment]
I guess I see the argument for those; but I think you should still not allow an acpi table to be overridden.  Allowing an ACPI table to be overridden is like having free reign of 32 bit register access to anything.

**Comment by hughsie** [comment]
> but I think you should still not allow an acpi table to be overridden

Ack, agreed. Modified.

**Review by superm1 — APPROVED** [review]

**Pull request merged**
