### PR TITLE
trivial: Convert update status in json state file to string

### PR DESCRIPTION
**Pull request by djcampello**
This makes for more clear debugging while looking at the json state file.

### CODE REVIEW

**Review by superm1 — APPROVED** [review]

**Comment by djcampello** [comment]
@shiyu-s this should help your debugging

**Comment by hughsie** [comment]
Not so fast: https://gitlab.com/fwupd/lvfs-website/-/blob/master/lvfs/reports/routes.py#L257 -- the LVFS requires an integer. We can workaround this on the LVFS and convert it if required, but I'd like to know if we can do better showing the user something else.

**Comment by superm1** [comment]
> Not so fast: https://gitlab.com/fwupd/lvfs-website/-/blob/master/lvfs/reports/routes.py#L257 -- the LVFS requires an integer. We can workaround this on the LVFS and convert it if required, but I'd like to know if we can do better showing the user something else.

Oh...  The other thing we can do is to update this in https://github.com/fwupd/fwupd/blob/master/src/fu-tool.c#L76 when it spits out the state file.

**Comment by hughsie** [comment]
> when it spits out the state file.

I'd much rather have a command that reads in the JSON dump and shows the user something with translations and that kind of thing, if we want the user to read the actual machine-parsed json file.

**Comment by djcampello** [comment]
> > when it spits out the state file.
> 
> I'd much rather have a command that reads in the JSON dump and shows the user something with translations and that kind of thing, if we want the user to read the actual machine-parsed json file.

I agree, I will drop this PR.

**Pull request closed without merging**
