### PR TITLE
trivial: allow manually running the container generation workflow

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by hughsie — APPROVED** [review]
THANK YOU!

**Comment by superm1** [comment]
> THANK YOU!

sure.  triggered the job, hopefully all is well now :)

**Comment by hughsie** [comment]
Hmm, the Fedora one is still failing; I can't reproduce it even when building the exact container locally. :(

**Comment by superm1** [comment]
Look like different behavior in fedora 36 to me:

```
Found ninja-1.10.2 at /usr/bin/ninja
+ ninja-build dist

[0/1] Creating source packages
Dist currently only works with Git or Mercurial repos
```

**Pull request merged**
