### PR TITLE
Build logind plugin for elogind-enabled systems

### PR DESCRIPTION
**Pull request by ixti**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 the Greetings CI target is doing something strange.

**Comment by superm1** [comment]
> @superm1 the Greetings CI target is doing something strange.

What happened?

**Comment by hughsie** [comment]
It failed; was that expected?

**Comment by superm1** [comment]
> It failed; was that expected?

Oh... It's this: https://github.com/actions/first-interaction/issues/10
There is a workaround posted there too to try.  We should try that and if it doesn't work abandon the greeting.

**Comment by superm1** [comment]
> > It failed; was that expected?
> 
> Oh... It's this: [actions/first-interaction#10](https://github.com/actions/first-interaction/issues/10) There is a workaround posted there too to try. We should try that and if it doesn't work abandon the greeting.

I applied it to main, we'll see if it helps.

**Pull request merged**
