### PR TITLE
Allow self tests to pass when run in LXC zones

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/4684

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@kloczek can you try this, and then sprinkle any additional `g_error_matches(error, G_IO_ERROR, G_IO_ERROR_CONNECTION_REFUSED)` where they are required please.

**Comment by kloczek** [comment]
One sec ..

**Comment by kloczek** [comment]
Tested 6aec72d5 and still test suite is failing
```console
+ cd fwupd-1.8.3
+ /usr/bin/meson test -C x86_64-redhat-linux-gnu --num-processes 48 --print-errorlogs
ninja: Entering directory `/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu'
ninja: no work to do.
 1/35 fwupd-exported-api                     OK               0.04s
 2/35 fwupdplugin-exported-api               OK               0.02s
 3/35 fwupd-context-test                     OK               0.07s
 4/35 fwupd-thread-test                      OK               0.09s
 5/35 fwupd-self-test                        FAIL             0.35s   killed by signal 6 SIGABRT
>>> G_TEST_BUILDDIR=/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd MALLOC_PERTURB_=61 G_TEST_SRCDIR=/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/libfwupd /home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stdout:
# random seed: R02S0237f0808145dcfdc4929872d07a0a6d
1..17
# Start of fwupd tests
ok 1 /fwupd/enums
ok 2 /fwupd/common{machine-hash}
ok 3 /fwupd/common{device-id}
ok 4 /fwupd/common{guid}
ok 5 /fwupd/release
ok 6 /fwupd/plugin
# Fwupd-DEBUG:   AppstreamId:          org.freedesktop.fwupd.request.remove-replug
#   RequestKind:          immediate
#   DeviceId:             950da62d4c753a26e64f7f7d687104ce38e32ca5
#   Created:              2022-08-22
#   UpdateMessage:        foo
#   UpdateImage:          bar
#
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): Fwupd-DEBUG: 15:25:45.607:   AppstreamId:          org.freedesktop.fwupd.request.remove-replug
  RequestKind:          immediate
  DeviceId:             950da62d4c753a26e64f7f7d687104ce38e32ca5
  Created:              2022-08-22
  UpdateMessage:        foo
  UpdateImage:          bar

ok 7 /fwupd/request

FwupdDevice:
  DeviceId:             USB:foo
  Name:                 ColorHug2
  Guid:                 18f514d2-c12e-581f-a696-cc6d6c271699 ← USB\VID_1234&PID_0001 ⚠
  Guid:                 2082b5e0-7a64-478a-b1b2-e3404fab6dad
  Guid:                 00000000-0000-0000-0000-000000000000
  Flags:                updatable|require-ac
  Checksum:             SHA1(beefdead)
  VendorId:             USB:0x1234
  VendorId:             PCI:0x5678
  Icon:                 input-gaming,input-mouse
  Created:              1970-01-01
  Modified:             1970-01-02

  [Release]
  AppstreamId:          org.dave.ColorHug.firmware
  Description:          <p>Hi there!</p>
  Version:              1.2.3
  Filename:             firmware.bin
  Checksum:             SHA1(deadbeef)
  Tags:                 vendor-2021q1
  Tags:                 vendor-2021q2
  Size:                 1.0 kB
  Uri:                  http://foo.com
  Uri:                  ftp://foo.com
  Flags:                trusted-payload
ok 8 /fwupd/device
ok 9 /fwupd/security-attr
ok 10 /fwupd/remote{download}
ok 11 /fwupd/remote{base-uri}
ok 12 /fwupd/remote{no-path}
ok 13 /fwupd/remote{local}
ok 14 /fwupd/remote{duplicate}
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): GLib-GIO-DEBUG: 15:25:45.613: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
# Fwupd-DEBUG: changing metadata URI from https://cdn.fwupd.org/downloads/firmware.xml.gz to https://cdn.fwupd.org/downloads/metadata.xml.gz
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): Fwupd-DEBUG: 15:25:45.614: changing metadata URI from https://cdn.fwupd.org/downloads/firmware.xml.gz to https://cdn.fwupd.org/downloads/metadata.xml.gz
ok 15 /fwupd/remote{auth}
# GLib-DEBUG: setenv()/putenv() are not thread-safe and should not be used after threads are created
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): GLib-DEBUG: 15:25:45.614: setenv()/putenv() are not thread-safe and should not be used after threads are created
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): GLib-GIO-DEBUG: 15:25:45.635: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.635: watch_fast: "/system/proxy/" (establishing: 0, active: 0)
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.635: watch_fast: "/system/proxy/http/" (establishing: 0, active: 0)
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.635: watch_fast: "/system/proxy/https/" (establishing: 0, active: 0)
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.635: watch_fast: "/system/proxy/ftp/" (establishing: 0, active: 0)
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.635: watch_fast: "/system/proxy/socks/" (establishing: 0, active: 0)
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.635: unwatch_fast: "/system/proxy/" (active: 0, establishing: 1)
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.635: unwatch_fast: "/system/proxy/http/" (active: 0, establishing: 1)
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.635: unwatch_fast: "/system/proxy/https/" (active: 0, establishing: 1)
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.635: unwatch_fast: "/system/proxy/ftp/" (active: 0, establishing: 1)
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.635: unwatch_fast: "/system/proxy/socks/" (active: 0, establishing: 1)
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.639: watch_established: "/system/proxy/" (establishing: 0)
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.640: watch_established: "/system/proxy/http/" (establishing: 0)
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.640: watch_established: "/system/proxy/https/" (establishing: 0)
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.640: watch_established: "/system/proxy/ftp/" (establishing: 0)
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): dconf-DEBUG: 15:25:45.640: watch_established: "/system/proxy/socks/" (establishing: 0)
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation libproxy (GLibproxyResolver) for ‘gio-proxy-resolver’
(/home/tkloczko/rpmbuild/BUILD/fwupd-1.8.3/x86_64-redhat-linux-gnu/libfwupd/fwupd-self-test:2490993): GLib-GIO-DEBUG: 15:25:45.644: _g_io_module_get_default: Found default implementation libproxy (GLibproxyResolver) for ‘gio-proxy-resolver’
Bail out! Fwupd:ERROR:../libfwupd/fwupd-self-test.c:1038:fwupd_client_remotes_func: assertion failed (error == NULL): GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: unit failed. (g-dbus-error-quark, 3)
stderr:
**
Fwupd:ERROR:../libfwupd/fwupd-self-test.c:1038:fwupd_client_remotes_func: assertion failed (error == NULL): GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: unit failed. (g-dbus-error-quark, 3)
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

 6/35 fwupdplugin-self-test                  OK               0.30s
 7/35 acpi-dmar-self-test                    OK               0.27s
 8/35 acpi-facp-self-test                    OK               0.27s
 9/35 acpi-ivrs-self-test                    OK               0.26s
10/35 acpi-phat-self-test                    OK               0.25s
11/35 ata-self-test                          OK               0.24s
12/35 bcm57xx-self-test                      OK               0.23s
13/35 ccgx-self-test                         OK               0.23s
14/35 dell-self-test                         OK               0.22s
15/35 fu-dfu-self-test                       OK               0.21s
16/35 elantp-self-test                       OK               0.20s
17/35 lenovo-thinklmi-self-test              OK               0.19s
18/35 linux-swap-self-test                   OK               0.18s
19/35 logitech-hidpp-self-test               OK               0.18s
20/35 mtd-self-test                          OK               0.17s
21/35 nitrokey-self-test                     OK               0.16s
22/35 nvme-self-test                         OK               0.15s
23/35 pxi-self-test                          OK               0.15s
24/35 redfish-self-test                      OK               0.14s
25/35 synaptics-mst-self-test                OK               0.13s
26/35 synaptics-prometheus-self-test         OK               0.12s
27/35 synaptics-rmi-self-test                OK               0.11s
28/35 tpm-self-test                          OK               0.09s
29/35 uefi-self-test                         OK               0.09s
30/35 uefi-dbx-self-test                     OK               0.08s
31/35 uf2-self-test                          OK               0.07s
32/35 vli-self-test                          OK               0.06s
33/35 wacom-usb-self-test                    OK               0.05s
34/35 thunderbolt-self-test                  OK               3.40s
35/35 fu-self-test                           OK               7.18s

Summary of Failures:

 5/35 fwupd-self-test                FAIL             0.35s   killed by signal 6 SIGABRT

Ok:                 34
Expected Fail:      0
Fail:               1
Unexpected Pass:    0
Skipped:            0
Timeout:            0
```

**Comment by kloczek** [comment]
Ha .. looks like in this case installed gvfs is mewssing with test suite 😞

**Pull request merged**
