### PR TITLE
Enable lzo compression for Snap packages

### LINKED ISSUE #4048: Enable Snap package lzo compression
**Is your feature request related to a problem? Please describe.**

Current snap cold start time is too long.

**Describe the solution you'd like**

Part of the issue is that by default Snap uses `xz` compression. There's a setting to enable much more faster `lzo` compression.

1. https://snapcraft.io/blog/snap-speed-improvements-with-new-compression-algorithm
2. https://snapcraft.io/blog/why-lzo-was-chosen-as-the-new-compression-method

Hoe to enable it: https://forum.snapcraft.io/t/how-to-switch-your-snap-to-use-lzo-compression/21714

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by the-spyke**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [x] Feature
- [ ] Documentation

Closes #4048

### CODE REVIEW

**Comment by superm1** [comment]
It seems we might need a newer version of the tools or something.

> Issues while validating snapcraft.yaml: Additional properties are not allowed ('compression' was unexpected)

**Comment by hughsie** [comment]
@the-spyke i see a failure in the CI with `Issues while validating snapcraft.yaml: Additional properties are not allowed ('compression' was unexpected)`?

**Comment by superm1** [comment]
Looking at the CI it was built using snapcraft: `2.43.1+18.04.1`.  That's the latest in Ubuntu 18.04.
Maybe need a newer version than that?

You can try:
```
diff --git a/.circleci/config.yml b/.circleci/config.yml
index 17b1a0f4..0113b96a 100644
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -58,7 +58,7 @@ jobs:

   build-snap:
     docker:
-      - image: ubuntu:18.04
+      - image: ubuntu:20.04
     steps:
       - run:
           name: "Update apt"
```

_Maybe_ that works.

**Comment by the-spyke** [comment]
@superm1 Yeah, if only Canonical made it easy to find the minimal required version. It should be >= 2.45.

**Comment by superm1** [comment]
Seems the universe isn't happy with that change :(

```
=> Installing the Snapcraft snap
==> Checking connectivity with the snap store
Configuring snapcraft
---------------------

Your system is unable to reach the snap store, please make sure you're
connected to the Internet and update any firewall or proxy settings as needed
so that you can reach the snap store.

You can manually check for connectivity by running "snap info snapcraft"

Aborting will cause the upgrade to fail and will require it to be re-attempted
once snapd is functional on the system.

Skipping will let the package upgrade continue but the Snapcraft commands will
not be functional until the Snapcraft snap is installed.

  1. Retry  2. Abort  3. Skip
Unable to reach the snap store
```

**Comment by superm1** [comment]
I think you're getting close - try to install `ca-certificates` for the latest error

**Comment by superm1** [comment]
> The linker version '2.27' used by the base 'core18' is incompatible with files in this snap:

That was from d5bcd19.  I think if you move up to core20 that would be fine too

**Comment by the-spyke** [comment]
@superm1 Updating base to `core20` is a whole another level :smile: Any ideas how to fix this?

```
Dependency fwupd-efi from subproject subprojects/fwupd-efi found: YES 1.1
Running command: /root/stage/bin/python3 po/test-deps
--- stdout ---
Error: missing dependency python gobject introspection (python3-gi)

--- stderr ---
Traceback (most recent call last):
  File "po/test-deps", line 17, in <module>
    gi.require_version("Pango", "1.0")
NameError: name 'gi' is not defined

../src/meson.build:435:6: ERROR: Problem encountered: Error: missing dependency python gobject introspection (python3-gi)
```

**Comment by hughsie** [comment]
This looks waaaaay more complicated than that blog post suggested. How much faster are we talking? e.g. 6000ms vs 60ms, or 40ms vs 60ms?

**Comment by superm1** [comment]
> This looks waaaaay more complicated than that blog post suggested. How much faster are we talking? e.g. 6000ms vs 60ms, or 40ms vs 60ms?

It's always *just one more thing* for it to work :)

**Comment by superm1** [comment]
> @superm1 Updating base to `core20` is a whole another level :smile: Any ideas how to fix this?
> 
> ```
> Dependency fwupd-efi from subproject subprojects/fwupd-efi found: YES 1.1
> Running command: /root/stage/bin/python3 po/test-deps
> --- stdout ---
> Error: missing dependency python gobject introspection (python3-gi)
> 
> --- stderr ---
> Traceback (most recent call last):
>   File "po/test-deps", line 17, in <module>
>     gi.require_version("Pango", "1.0")
> NameError: name 'gi' is not defined
> 
> ../src/meson.build:435:6: ERROR: Problem encountered: Error: missing dependency python gobject introspection (python3-gi)
> ```

It seems to me that python3 gobject introspection is not installed on the stage perhaps.

**Comment by the-spyke** [comment]
After a reboot my fwupdmgr start time returned from ~3s back to normal. I'm sorry for bothering you. I thought it was the same issue as with some other snaps where changing compression lowered start times by several seconds.

**Pull request closed without merging**
