### PR TITLE
Use flashrom and libjcat from arch archive

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
> Failed to create file “/root/.local/share/libjcat/pki/secret.key.IKBBK2”: Permission denied

Kinda weird.

**Comment by hughsie** [comment]
@superm1 obsolete now?

**Comment by superm1** [comment]
> @superm1 obsolete now?

No, I think we should be using them from that archive so we're testing "what people use" rather than the subproject if possible, once we update the PKGBUILD from arch again we should pick them up.

**Comment by hughsie** [comment]
I included this in the arch CI fix -- apologies I should have cherry-picked this really.

**Pull request closed without merging**
