### PR TITLE
thunderbolt: if doing disconnected update flow, lie about the version

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
I guess with the CI failure I'll need to plumb a little more in, but the other approach is that the daemon just automatically lies about the version when something goes into `needs-activation`.  Can tear out some code in other `dell-dock` plugins when this happens.

**Comment by hughsie** [comment]
I'm not convinced about faking the version. Can't we just skip the version checks if FWUPD_DEVICE_FLAG_NEEDS_ACTIVATION is set? I like the setting of the FuFirmware version tho, feel free to push that bit.

**Comment by superm1** [comment]
> Can't we just skip the version checks if `FWUPD_DEVICE_FLAG_NEEDS_ACTIVATION` is set?

You mean a client side fix?  We'll still have gnome-software and every other client offering firmware upgrades won't we?

**Comment by hughsie** [comment]
>  We'll still have gnome-software and every other client offering firmware upgrades won't we

Ohh, indeed. Can we take away `UPDATABLE` in that case?

**Comment by superm1** [comment]
> Ohh, indeed. Can we take away UPDATABLE in that case?

Like in the daemon if `FWUPD_DEVICE_FLAG_NEEDS_ACTIVATION` gets set we take away `FWUPD_DEVICE_FLAG_UPDATABLE` and then when activated we put it back?

**Comment by hughsie** [comment]
Yes, something like that. I think we want to take away FWUPD_DEVICE_FLAG_UPDATABLE, and add FWUPD_DEVICE_FLAG_UPDATABLE_HIDDEN when FWUPD_DEVICE_FLAG_NEEDS_ACTIVATION gets set. Maybe even in `fu_device_add_flag`....

**Review by hughsie — APPROVED** [review]

**Pull request merged**
