### PR TITLE
steelseries: adjust min size to 0x23000

### PR DESCRIPTION
**Pull request by superm1**
Link: https://github.com/fwupd/fwupd/issues/6689

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by gportay** [comment]
@superm1, if I remember well, there is firmware parsing. Does fwupd is able to parse it successfully? If so I guess it it the right fix.

**Comment by superm1** [comment]
I don't have the hardware, it was just going off the symptoms reported.  So hopefully you or @yukijoou can test it.

**Comment by gportay** [comment]
Unfortunately, I do not have hardware neither :(

**Comment by gportay** [comment]
@superm1 could you refresh my memory, how can I download the cabinet file? My LFVS account is disabled.

**Comment by superm1** [comment]
Go to https://fwupd.org/lvfs/devices/ and search for the device you want and when you find it there is a link to the public CAB.

**Comment by hughsie** [comment]
> My LFVS account is disabled.

Not anymore!

**Comment by gportay** [comment]
@hughsie Thanks ;)

**Pull request closed without merging**
