### PR TITLE
trivial: Make meson.build indentation consistent

### PR DESCRIPTION
**Pull request by gportay**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

The indentation used for the parameter is not consistent across the `meson.build` files; even in the same files. I picked the most commonly used (aka space, colon, space)  even though it is not the one I prefer.

I can change it if needed.

### CODE REVIEW

**Comment by superm1** [comment]
Thanks for taking a stab at improving this.  It's bugged me too, but we haven't had a nice reformatter for it, so stuff like this slips by all the time.

**Review by superm1 — DISMISSED** [review]
I don't have a strong opinion of which way is better for spacing, but I like the consistency, so the flip of a coin or whichever was more common sounds good to me.

**Comment by hughsie** [comment]
I believe meson upstream does `: ` i.e. no leading space.

**Review by hughsie — APPROVED** [review]

**Comment by gportay** [comment]
@hughsie what was wrong with the ci?

I have check, and nothing jumped to my eyes :/

However, I want to make a single small change, with the ternary operator, spacing before and after in the meson.build of the bash completion directory.

**Comment by hughsie** [comment]
@superm1 debian ideas please?

**Review by hughsie — APPROVED** [review]

**Pull request merged**
