### PR TITLE
Wip/hughsie/dfu

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@amfern can you test this branch please.

**Review by superm1 — APPROVED** [review]

**Comment by amfern** [comment]
Yes, it doesn't fail anymore but I still see assertion errors

```
decompressing:	0%
device-write:	0%
device-busy:	0%
device-erase:	0%
device-erase:	10%
device-write:	10%
device-write:	96%
unknown:	96%
device-verify:	96%
device-read:	96%

(dfu-tool:284352): FuProgress-CRITICAL **: 17:58:37.641: fu_progress_set_percentage_full: assertion 'progress_done <= progress_total' failed
unknown:	96%
unknown:	100%
device-busy:	100%
device-erase:	100%
device-write:	100%
unknown:	100%
device-verify:	100%
device-read:	100%

(dfu-tool:284352): FuProgress-CRITICAL **: 17:59:16.475: fu_progress_set_percentage_full: assertion 'progress_done <= progress_total' failed
unknown:	100%
device-busy:	100%
594320 bytes successfully downloaded to device
```

**Comment by hughsie** [comment]
@amfern can you grab a backtrace when `G_DEBUG=fatal-criticals` is set please.

**Comment by amfern** [comment]
Sure
```
G_DEBUG=fatal-criticals dfu-tool write -d 0483:df11 obj/fcos_v3.4.0-a1_HUNTER_V0_DIGITAL_KAKUTEF7.dfu
decompressing:	0%
device-write:	0%
device-busy:	0%
device-erase:	0%
device-erase:	10%
device-write:	10%
device-write:	96%
unknown:	96%
device-verify:	96%
device-read:	96%

(dfu-tool:292327): FuProgress-CRITICAL **: 18:18:19.969: fu_progress_set_percentage_full: assertion 'progress_done <= progress_total' failed
fish: Job 1, 'G_DEBUG=fatal-criticals dfu-too…' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by hughsie** [comment]
then do `t a a bt` at that gdb prompt please.

**Comment by hughsie** [comment]
ohh, you need `G_DEBUG=fatal-criticals gdb --args dfu-tool write...`

**Comment by amfern** [comment]
```
G_DEBUG=fatal-criticals gdb --args dfu-tool write -d 0483:df11 obj/fcos_v3.4.0-a1_HUNTER_V0_DIGITAL_KAKUTEF7.dfu
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from dfu-tool...
(gdb) run
Starting program: /usr/local/bin/dfu-tool write -d 0483:df11 obj/fcos_v3.4.0-a1_HUNTER_V0_DIGITAL_KAKUTEF7.dfu
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff623a640 (LWP 296948)]
[New Thread 0x7ffff5a39640 (LWP 296949)]
[New Thread 0x7ffff5165640 (LWP 296950)]
[New Thread 0x7ffff4964640 (LWP 296951)]
decompressing:	0%
device-write:	0%
device-busy:	0%
device-erase:	0%
device-erase:	10%
device-write:	10%
device-write:	96%
unknown:	96%
device-verify:	96%
device-read:	96%

(dfu-tool:296905): FuProgress-CRITICAL **: 18:35:30.967: fu_progress_set_percentage_full: assertion 'progress_done <= progress_total' failed

Thread 1 "dfu-tool" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff7b9f92b in g_logv () from /usr/lib/libglib-2.0.so.0
(gdb) t a a bt

Thread 5 (Thread 0x7ffff4964640 (LWP 296951) "GUsbEventThread"):
#0  0x00007ffff7912b2f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff74e413a in  () at /usr/lib/libusb-1.0.so.0
#2  0x00007ffff74e1a7e in  () at /usr/lib/libusb-1.0.so.0
#3  0x00007ffff74e2c98 in libusb_handle_events_timeout_completed () at /usr/lib/libusb-1.0.so.0
#4  0x00007ffff7b36c6f in  () at /usr/lib/libgusb.so.2
#5  0x00007ffff7bc5ce1 in  () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff7721259 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007ffff791d5e3 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7ffff5165640 (LWP 296950) "libusb_event"):
#0  0x00007ffff7912b2f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff74e9206 in  () at /usr/lib/libusb-1.0.so.0
#2  0x00007ffff7721259 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007ffff791d5e3 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7ffff5a39640 (LWP 296949) "gdbus"):
#0  0x00007ffff7912b2f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff7beb729 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7b96a63 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7dd6268 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff7bc5ce1 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff7721259 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff791d5e3 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7ffff623a640 (LWP 296948) "gmain"):
#0  0x00007ffff7912b2f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff7beb729 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7b94bc1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7b94c12 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff7bc5ce1 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff7721259 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff791d5e3 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff6564980 (LWP 296905) "dfu-tool"):
#0  0x00007ffff7b9f92b in g_logv () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff7b9fc00 in g_log () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7eea1eb in fu_progress_set_percentage_full (self=0x5555555ce400, progress_done=2048, progress_total=824) at ../libfwupdplugin/fu-progress.c:351
#3  0x000055555556798e in fu_dfu_target_stm_upload_element (target=0x555555624880, address=134217728, expected_size=824, maximum_size=824, progress=0x5555555ce400, error=0x7fffffffe438) at ../plugins/dfu/fu-dfu-target-stm.c:159
#4  0x00005555555661b5 in fu_dfu_target_upload_element (self=0x555555624880, address=134217728, expected_size=824, maximum_size=824, progress=0x5555555ce400, error=0x7fffffffe438) at ../plugins/dfu/fu-dfu-target.c:959
#5  0x0000555555566bce in fu_dfu_target_download_element (self=0x555555624880, chk=0x555555623680, progress=0x5555555ce380, flags=DFU_TARGET_TRANSFER_FLAG_VERIFY, error=0x7fffffffe438) at ../plugins/dfu/fu-dfu-target.c:1205
#6  0x0000555555566ff3 in fu_dfu_target_download (self=0x555555624880, image=0x55555563d2c0, progress=0x5555555ce380, flags=DFU_TARGET_TRANSFER_FLAG_VERIFY, error=0x7fffffffe438) at ../plugins/dfu/fu-dfu-target.c:1301
#7  0x0000555555562ee1 in fu_dfu_device_download (self=0x5555556302d0, firmware=0x5555555a32a0, progress=0x5555555c5700, flags=DFU_TARGET_TRANSFER_FLAG_VERIFY, error=0x7fffffffe438) at ../plugins/dfu/fu-dfu-device.c:1631
#8  0x000055555556329d in fu_dfu_device_write_firmware (device=0x5555556302d0, firmware=0x5555555a32a0, progress=0x5555555c5700, flags=FWUPD_INSTALL_FLAG_NONE, error=0x7fffffffe438) at ../plugins/dfu/fu-dfu-device.c:1747
#9  0x00007ffff7ecffe0 in fu_device_write_firmware (self=0x5555556302d0, fw=0x5555555b9000, progress=0x5555555c5700, flags=FWUPD_INSTALL_FLAG_NONE, error=0x7fffffffe438) at ../libfwupdplugin/fu-device.c:3565
--Type <RET> for more, q to quit, c to continue without paging--c
#10 0x000055555555e47b in fu_dfu_tool_write (self=0x55555559bbf0, values=0x7fffffffe698, error=0x7fffffffe438) at ../plugins/dfu/fu-dfu-tool.c:806
#11 0x000055555555c633 in fu_dfu_tool_run (self=0x55555559bbf0, command=0x7fffffffe9ca "write", values=0x7fffffffe698, error=0x7fffffffe438) at ../plugins/dfu/fu-dfu-tool.c:155
#12 0x000055555555ebad in main (argc=3, argv=0x7fffffffe688) at ../plugins/dfu/fu-dfu-tool.c:964
```

**Pull request merged**
