### PR TITLE
Wip/hughsie/fwupd device add string

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by hughsie** [comment]
For instance:

    $ sudo ./src/fwupdtool get-devices --verbose

...

    15:53:07:0853 FuMain                 Name:                 Unifying Receiver
      DeviceId:             d3fae86d95e5d56626129d00e332c4b8dac95442
      Guid:                 cc4cbfa9-bf9d-540b-b92b-172ce31013c1
      Guid:                 fcf55bf5-767b-51ce-9c17-f6f538c4ee9f <- HIDRAW\VEN_046D&DEV_C52B&REV_00
      Guid:                 279ed287-3607-549e-bacc-f873bb9838c4 <- HIDRAW\VEN_046D&DEV_C52B
      Summary:              A miniaturised USB wireless receiver
      Plugin:               logitech_hidpp
      Protocol:             com.logitech.unifying
      Flags:                updatable|supported|registered
      VendorId:             USB:0x046D
      Version:              RQR24.05_B0029
      VersionBootloader:    BOT03.01_B0008
      VersionFormat:        plain
      Icon:                 preferences-desktop-keyboard
      InstallDuration:      30
      Created:              2020-09-10
      FuLogitechHidPpRuntime:
        PhysicalId:         DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4.4/1-4.4.2/1-4.4.2.2/1-4.4.2.2:1.2
        SysfsPath:          /sys/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4.4/1-4.4.2/1-4.4.2.2/1-4.4.2.2:1.2/0003:046D:C52B.002B/hidraw/hidraw2
        SignedFirmware:     false

...

**Comment by superm1** [comment]
This feels like it's going to have the potential to leak private data.  I think it needs to be treated like how we do serial numbers where it's only added if an authenticated request.

**Comment by hughsie** [comment]
> This feels like it's going to have the potential to leak private data

Ahh, not really, but I understand the confusion. When you use fwupdtool you create FuDevices which subclass FwupdDevice, so you can print both the "public exported" data on the FwupdDevice and also the private, not-exported data on the FuDevice (like serial numbers). This always needs root.

When you use fwupdmgr all the device data goes over the bus, and the FwupdDevice data (and not the FuDevice data) gets converted to GVariants as required. When fwupdmgr gets the list of "devices" they're just FwupdDevice objects, *not* FuDevice objects so there's no vfunc set up and it's not possible to print the private data as it never went over the bus at all.

**Comment by superm1** [comment]
Ah thanks for explaining that..

**Comment by hughsie** [comment]
There's two things I'm not sure about

* Should `->add_string()` be `->to_string()` perhaps? It looks a bit odd in the exported header I'll admit.

* Do we want the `Name:                 ` change? I'm having second thoughts now.

**Comment by superm1** [comment]
> Should ->add_string() be ->to_string() perhaps? It looks a bit odd in the exported header I'll admit.

Yeah I think so

> Do we want the Name: change? I'm having second thoughts now.

I don't really like it.

> When you use fwupdmgr all the device data goes over the bus, and the FwupdDevice data (and not the FuDevice data) gets converted to GVariants as required. When fwupdmgr gets the list of "devices" they're just FwupdDevice objects, not FuDevice objects so there's no vfunc set up and it's not possible to print the private data as it never went over the bus at all.

Since this works how you explained it, I don't actually see a lot of value in the PR TBH.  It only really benefits fwupdtool, and you get the exact same output higher up in fwupdtool verbose output already.
On my system just using synaptics-rmi plugin I see the following from the get-devices section:
```
17:08:59:0865 FuMain                 Name:                 Touchpad
  DeviceId:             b26933c085b020ecf84c490812458523aee710ac
  Guid:                 f4384034-9243-5334-8075-a534be913e46 <- HIDRAW\VEN_06CB&DEV_76AF&REV_00
  Guid:                 424bd00e-9789-5cdf-a12a-3c81bc4676d6 <- HIDRAW\VEN_06CB&DEV_76AF
  Guid:                 140f4458-951b-5bb9-85e2-879bd5b02615 <- SYNAPTICS_RMI\TM3038-003
  Guid:                 b29d3c85-cd0e-503e-9c7e-f6731c1eaf2d <- SYNAPTICS_RMI\TM3038
  Plugin:               synaptics_rmi
  Protocol:             com.synaptics.rmi
  Flags:                internal|updatable|registered
  Vendor:               Synaptics
  VendorId:             HIDRAW:0x06CB
  Version:              1.5.2767034
  VersionBootloader:    54.0.0
  VersionFormat:        triplet
  Created:              2020-09-10
  FuSynapticsRmiDevice:
    PhysicalId:         HID_PHYS=i2c-CUST0001:00
    SysfsPath:          /sys/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-2/i2c-CUST0001:00/0018:06CB:76AF.0001/hidraw/hidraw0
    BlVer:              0x6
    BootloaderId:       56.36
    BlockSize:          0x10
    BlockCountFw:       0xe60
    BlockCountCfg:      0x40
    FlashConfigLength:  0x0
    PayloadLength:      0x0
    BuildID:            0x2a38ba
```

Scroll up 20 lines and I see this (IE the same information):
```
17:08:59:0852 FuMain               ADDED:
  Name:                 Touchpad
  DeviceId:             b26933c085b020ecf84c490812458523aee710ac
  Guid:                 f4384034-9243-5334-8075-a534be913e46 <- HIDRAW\VEN_06CB&DEV_76AF&REV_00
  Guid:                 424bd00e-9789-5cdf-a12a-3c81bc4676d6 <- HIDRAW\VEN_06CB&DEV_76AF
  Guid:                 140f4458-951b-5bb9-85e2-879bd5b02615 <- SYNAPTICS_RMI\TM3038-003
  Guid:                 b29d3c85-cd0e-503e-9c7e-f6731c1eaf2d <- SYNAPTICS_RMI\TM3038
  Plugin:               synaptics_rmi
  Protocol:             com.synaptics.rmi
  Flags:                internal|updatable|registered
  Vendor:               Synaptics
  VendorId:             HIDRAW:0x06CB
  Version:              1.5.2767034
  VersionBootloader:    54.0.0
  VersionFormat:        triplet
  Created:              2020-09-10
  FuSynapticsRmiDevice:
    PhysicalId:         HID_PHYS=i2c-CUST0001:00
    SysfsPath:          /sys/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-2/i2c-CUST0001:00/0018:06CB:76AF.0001/hidraw/hidraw0
    BlVer:              0x6
    BootloaderId:       56.36
    BlockSize:          0x10
    BlockCountFw:       0xe60
    BlockCountCfg:      0x40
    FlashConfigLength:  0x0
    PayloadLength:      0x0
    BuildID:            0x2a38ba
```

**Comment by hughsie** [comment]
> I don't actually see a lot of value in the PR TBH

Fair point, I appreciate your honesty :) What about if I dropped this PR and just exported the `Order` over D-Bus?

**Comment by superm1** [comment]
>Fair point, I appreciate your honesty :) What about if I dropped this PR and just exported the Order over D-Bus?

I'd actually ask if that matters too - can't you tell it from the topology?

**Comment by hughsie** [comment]
> can't you tell it from the topology

Yes, if you're printing without `--verbose` -- maybe that's indeed good enough.

**Pull request closed without merging**
