### PR TITLE
Add a D-Bus method that allows getting the device debug output

### PR DESCRIPTION
**Pull request by hughsie**
In some case this may be very verbose, and isn't really suitable to put as a D-Bus property stored in memory.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 a better name welcome than `debuglog`...

**Comment by superm1** [comment]
Does it really need to come over dbus?  It's debugging only, can't we KISS and put it in fwupdtool only?

**Comment by hughsie** [comment]
> can't we KISS and put it in fwupdtool only

Yes, that's completely valid. Will ponder. Did you have a better idea on the method name?

**Comment by superm1** [comment]
> > can't we KISS and put it in fwupdtool only
> 
> Yes, that's completely valid. Will ponder. Did you have a better idea on the method name?

Not really.

**Comment by hughsie** [comment]
> Will ponder

Maybe the real fix is to just dump the output into g_debug and read it back from `fwupdtool get-devices --plugins uefi_capsule -vv` -- it seems like anything like `get_debuglog` is really just returning stuff that we'd normally show in `-vv` and our difficulty in *naming* it is really because it's just console spam that's not useful to 99.999999% of people.

**Comment by superm1** [comment]
> > Will ponder
> 
> Maybe the real fix is to just dump the output into g_debug and read it back from `fwupdtool get-devices --plugins uefi_capsule -vv` -- it seems like anything like `get_debuglog` is really just returning stuff that we'd normally show in `-vv` and our difficulty in *naming* it is really because it's just console spam that's not useful to 99.999999% of people.

Sounds good to me.

**Comment by hughsie** [comment]
https://github.com/fwupd/fwupd/pull/6982

**Pull request closed without merging**
