### PR TITLE
Export the raw device version to the client --verbose output

### PR DESCRIPTION
**Pull request by hughsie**
It turns out this is really useful for debugging UEFI firmware updates which
typically use the 0x-prefixed version numbers without a version format.

### CODE REVIEW

**Comment by superm1** [comment]
To future proof this what do you think about making it guint64. Hard to predict what future devices version string comes from.

**Comment by hughsie** [comment]
> what do you think about making it guint64

I also pondered this. I didn't have any examples on where a version is represented as a uint64_t. "Enforcing" the uint32 type means we can always print the version with the right number of leading zeros without it looking uint64 crazy.

**Comment by superm1** [comment]
Isn't EFI ESRT version 64 bit?

**Comment by hughsie** [comment]
> Isn't EFI ESRT version 64 bit?

Nah, https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/esrt-table-definition says 4 bytes, so uint32

**Comment by superm1** [comment]
Huh, I guess I never looked closely enough. Okay then I guess this is fine.

**Pull request merged**
