### PR TITLE
trivial: Move the CI to Fedora 40

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
Can we move mingw too? Or still weird bugs?

**Comment by hughsie** [comment]
> Can we move mingw too

Ohh that's fedora:38! I'll give it a go tomorrow.

**Comment by superm1** [comment]
For this PR, trigger create containers manually using this branch and then rerun the job

**Comment by hughsie** [comment]
Seems to work fine.

**Pull request merged**
