### PR TITLE
Move binaries around to better adhere to FHS 3.0

### PR DESCRIPTION
**Pull request by superm1**
Include some updates from packaging in Debian, and then also shuffle some binaries that users can execute around to `usr/lib`.
See #1783 for more details.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

CC:
@bigon
@martinezjavier

### CODE REVIEW

**Comment by hughsie** [comment]
I'm still confused; what's the difference between libexec and libdir? Doing this kind of change breaks lots of documentation (e.g. VIA and Lenovo use fwupdtool for testing) and there needs to be a good reason for doing it.

**Comment by superm1** [comment]
> I'm still confused; what's the difference between libexec and libdir? Doing this kind of change breaks lots of documentation (e.g. VIA and Lenovo use fwupdtool for testing) and there needs to be a good reason for doing it.

If I understand it right; the difference is stuff in `libexecdir` is supposed to be seen as _internal_ to the application.  Binaries that a user or script shouldn't ever be executing.  Executable stuff in `libdir` being stuff that can execute.  That's my interpretation though; I could be completely off base here.  Others can speak up if so.

**Comment by superm1** [comment]
> Applications which use /usr/libexec in this way must not also use /usr/lib to store internal binaries, though they may use /usr/lib for the other purposes documented here.

Maybe this should actually be interpreted as stuff that you want internal either pick libexecdir or libdir, but not both.  Stuff that you want people running should be in usr/bin?

**Comment by hughsie** [comment]
I don't think I've seen a package that uses both.

**Comment by FFY00** [comment]
Yes, `lib*` holds architecture dependent binaries, `libexec` holds binaries that could be executed, `lib` holds binaries that shouldn't be executed (at least externally, think of it like a public API).

**Comment by superm1** [comment]
>Yes, lib* holds architecture dependent binaries, libexec holds binaries that could be executed, lib holds binaries that shouldn't be executed (at least externally, think of it like a public API).

So there are packages you know of using both?

> I don't think I've seen a package that uses both.

If we don't split along that libexec/libdir separation then maybe we should discuss which of those tools should actually leave libexecdir to go into usrbin (if any).  I think the most logical one is `fwupdtool` and `fwupdagent`.

**Comment by hughsie** [comment]
In which case fwupdtool should stay in libexec I guess.

**Comment by FFY00** [comment]
> So there are packages you know of using both?

In arch we set `libdir` and `libexecdir` both to `lib` so I am not sure about anything from the top of my mind, but I am pretty sure that git should use both, at least conceptually.

**Comment by FFY00** [comment]
That sounded weird -- I am not sure if it does, but I am pretty sure it should.

**Comment by superm1** [comment]
OK it's clear we don't have agreement here, so I am leaning on we should just leave it as is.  I'll tear out that last patch that moved stuff around and just merge the packaging changes that unify Debian and Ubuntu to using `libexecdir` in the first place .

**Comment by FFY00** [comment]
We can go back to the issue and discuss which components should be private and which should be public.

**Comment by bigon** [comment]
> > I'm still confused; what's the difference between libexec and libdir? Doing this kind of change breaks lots of documentation (e.g. VIA and Lenovo use fwupdtool for testing) and there needs to be a good reason for doing it.
> 
> If I understand it right; the difference is stuff in `libexecdir` is supposed to be seen as _internal_ to the application. Binaries that a user or script shouldn't ever be executing. Executable stuff in `libdir` being stuff that can execute. That's my interpretation though; I could be completely off base here. Others can speak up if so.

`bindir` is the one with "stuff that can execute", `libdir` is just only for libraries if `libexecdir`exists:

http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html:
>/usr/libexec includes internal binaries that are not intended to be executed directly by users or shell scripts. Applications may use a single subdirectory under /usr/libexec.
> Applications which use /usr/libexec in this way must not also use /usr/lib to store internal binaries, though they may use /usr/lib for the other purposes documented here.

**Comment by superm1** [comment]
> bindir is the one with "stuff that can execute", libdir is just only for libraries if libexecdirexists:

OK, so  since fwupd uses `libexecdir`, for stuff that we want _people_ executing, moving it to `bindir` is what makes sense.  Thanks for clarifying.  That's what the new PR does: https://github.com/fwupd/fwupd/pull/1788

**Pull request merged**
