### PR TITLE
Only show the CLI time remaining for predictable status phases

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/4540

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
Isn't the time to wait also predictable though? You know how long replug will take.

**Comment by hughsie** [comment]
> You know how long replug will take

We know the maximum time it will take, but it's typically a *lot* smaller. e.g. we allow 10 seconds for the OS to re-enumerate a USB device, but typically it's less than 500ms.

**Comment by superm1** [comment]
> > You know how long replug will take
> 
> We know the maximum time it will take, but it's typically a *lot* smaller. e.g. we allow 10 seconds for the OS to re-enumerate a USB device, but typically it's less than 500ms.

How about then "waiting for up to XX seconds for device to return"

**Comment by hughsie** [comment]
> How about then "waiting for up to XX seconds for device to return"

I'm not sure that's terribly useful for the end user. Maybe for the developer, e.g. in --verbose, but not in the main UI.

**Comment by superm1** [comment]
> > How about then "waiting for up to XX seconds for device to return"
> 
> I'm not sure that's terribly useful for the end user. Maybe for the developer, e.g. in --verbose, but not in the main UI.

okay

**Pull request merged**
