### PR TITLE
trivial: enable emulation-tag during Fedora testing

### PR DESCRIPTION
**Pull request by superm1**
I don't really expect this to work right now, but want to see if it stands out what's wrong.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
```
=================================================================
==134==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x7f254a5c0898 in realloc.part.0 (/lib64/libasan.so.8+0xf6898) (BuildId: a4ad7eb954b390cf00f07fa10952988a41d9fc7a)
    #1 0x7f2547c6292a in g_realloc (/lib64/libglib-2.0.so.0+0x6492a) (BuildId: 36b60dbd02e796145a982d0151ce37202ec05649)
    #2 0x7f2547c81a39 in g_string_expand (/lib64/libglib-2.0.so.0+0x83a39) (BuildId: 36b60dbd02e796145a982d0151ce37202ec05649)
    #3 0x7f2547c828f9 in g_string_insert_c (/lib64/libglib-2.0.so.0+0x848f9) (BuildId: 36b60dbd02e796145a982d0151ce37202ec05649)
    #4 0x7f254701395a in json_strescape (/lib64/libjson-glib-1.0.so.0+0xb95a) (BuildId: 37509c114447fa5502fa1529f9074f28dcacb81b)
    #5 0x7f254701afe6 in dump_node (/lib64/libjson-glib-1.0.so.0+0x12fe6) (BuildId: 37509c114447fa5502fa1529f9074f28dcacb81b)
    #6 0x7f254701a572 in dump_node (/lib64/libjson-glib-1.0.so.0+0x12572) (BuildId: 37509c114447fa5502fa1529f9074f28dcacb81b)
    #7 0x7f254701a8f9 in dump_node (/lib64/libjson-glib-1.0.so.0+0x128f9) (BuildId: 37509c114447fa5502fa1529f9074f28dcacb81b)
    #8 0x7f254701a4e2 in dump_node (/lib64/libjson-glib-1.0.so.0+0x124e2) (BuildId: 37509c114447fa5502fa1529f9074f28dcacb81b)
    #9 0x7f254701ab38 in dump_node (/lib64/libjson-glib-1.0.so.0+0x12b38) (BuildId: 37509c114447fa5502fa1529f9074f28dcacb81b)
    #10 0x7f254701b626 in json_generator_to_gstring (/lib64/libjson-glib-1.0.so.0+0x13626) (BuildId: 37509c114447fa5502fa1529f9074f28dcacb81b)
    #11 0x7f254701b6d6 in json_generator_to_data (/lib64/libjson-glib-1.0.so.0+0x136d6) (BuildId: 37509c114447fa5502fa1529f9074f28dcacb81b)
    #12 0x7f25496ec159 in fu_engine_backends_save_phase.isra.0 ../src/fu-engine.c:2830
    #13 0x7f2548ff9aa3 in fu_engine_add_device ../src/fu-engine.c:6362
    #14 0x7f2548ffacbd in fu_engine_plugin_device_added_cb ../src/fu-engine.c:5990
    #15 0x7f2547d5d649 in g_closure_invoke (/lib64/libgobject-2.0.so.0+0x11649) (BuildId: 327e1dbd4b402ab1171d32553c27b5a07e36af7d)
    #16 0x7f2547d8d5f2 in signal_emit_unlocked_R.isra.0 (/lib64/libgobject-2.0.so.0+0x415f2) (BuildId: 327e1dbd4b402ab1171d32553c27b5a07e36af7d)
    #17 0x7f2547d7e103 in signal_emit_valist_unlocked (/lib64/libgobject-2.0.so.0+0x32103) (BuildId: 327e1dbd4b402ab1171d32553c27b5a07e36af7d)
    #18 0x7f2547d7e360 in g_signal_emit_valist (/lib64/libgobject-2.0.so.0+0x32360) (BuildId: 327e1dbd4b402ab1171d32553c27b5a07e36af7d)
    #19 0x7f2547d7e422 in g_signal_emit (/lib64/libgobject-2.0.so.0+0x32422) (BuildId: 327e1dbd4b402ab1171d32553c27b5a07e36af7d)
    #20 0x7f25483a43df in fu_plugin_device_add (/usr/lib64/fwupd-2.0.2/libfwupdplugin.so+0x33a3df) (BuildId: 1501faf96e29bc9b73bca0a6cdbe4da61e9b04e3)
    #21 0x7f25495cd308 in fu_test_plugin_coldplug ../plugins/test/fu-test-plugin.c:52
    #22 0x7f25483ab14a in fu_plugin_runner_coldplug (/usr/lib64/fwupd-2.0.2/libfwupdplugin.so+0x34114a) (BuildId: 1501faf96e29bc9b73bca0a6cdbe4da61e9b04e3)
    #23 0x7f2548ff5226 in fu_engine_plugins_coldplug ../src/fu-engine.c:5928
    #24 0x7f2549011ccb in fu_engine_load (/usr/lib64/fwupd-2.0.2/libfwupdengine.so+0x25dccb) (BuildId: 62ff73566d12e7b1d8ea003a287e144210f8816b)
    #25 0x55c49ee75950 in fu_dbus_daemon_setup ../src/fu-dbus-daemon.c:2844
    #26 0x55c49ee47be7 in fu_daemon_setup ../src/fu-daemon.c:196
    #27 0x55c49ee41072 in main (/usr/libexec/fwupd/fwupd+0x13072) (BuildId: 19310472c1725776feb109bcc9f2088342005f9c)
    #28 0x7f25473c6087 in __libc_start_call_main (/lib64/libc.so.6+0x2a087) (BuildId: 77c77fee058b19c6f001cf2cb0371ce3b8341211)
    #29 0x7f25473c614a in __libc_start_main_alias_1 (/lib64/libc.so.6+0x2a14a) (BuildId: 77c77fee058b19c6f001cf2cb0371ce3b8341211)

SUMMARY: AddressSanitizer: 1024 byte(s) leaked in 1 allocation(s).
```

I'm not sure this is really `fu_engine_backends_save_phase`, it seems lower?

**Comment by hughsie** [comment]
> I'm not sure this is really fu_engine_backends_save_phase, it seems lower?

Ya, I can't see anything wrong with how we're using json_generator_to_data()... I wonder if it's anything to do with the data we're inserting as nodes. Will look now.

**Comment by hughsie** [comment]
Okay, I think this is a false positive; I don't possibly see how `g_realloc()` could leak -- it's a wrapper around `realloc()` -- that said it's detectable in valgrind **and** LeakSanitizer

**Comment by hughsie** [comment]
I see something odd. On it!

**Comment by superm1** [comment]
Well that's awesome thanks!

**Pull request merged**
