### PR TITLE
Wip/hughsie/s76 launch replug

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by ahoneybun** [comment]
I followed the steps on this page:

https://github.com/fwupd/fwupd/wiki/Compilation

But I'm running into this issue:

```shell
[aaronh@fedora fwupd]$ sudo systemctl status  dbus.service
● dbus-broker.service - D-Bus System Message Bus
     Loaded: loaded (/usr/lib/systemd/system/dbus-broker.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-11-24 21:13:29 EST; 14h ago
TriggeredBy: ● dbus.socket
       Docs: man:dbus-broker-launch(1)
    Process: 56984 ExecReload=/usr/bin/busctl call org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus ReloadConfig (code=exited, status=1/FAILURE)
   Main PID: 1493 (dbus-broker-lau)
      Tasks: 2 (limit: 18990)
     Memory: 7.3M
        CPU: 4.594s
     CGroup: /system.slice/dbus-broker.service
             ├─1493 /usr/bin/dbus-broker-launch --scope system --audit
             └─1521 dbus-broker --log 4 --controller 9 --machine-id ac57ce354b3843c2813ab45b6f815c1a --max-bytes 536870912 --max-fds 4096 --max-matches 131072 --audit

Nov 25 11:35:49 fedora systemd[1]: Reloading D-Bus System Message Bus...
Nov 25 11:35:49 fedora dbus-broker-launch[1493]: Access denied in /etc/dbus-1/system-local.conf +1: /etc/dbus-1/system-local.conf
Nov 25 11:35:49 fedora busctl[56923]: Call failed: Config invalid. Reload ignored.
Nov 25 11:35:49 fedora systemd[1]: dbus-broker.service: Control process exited, code=exited, status=1/FAILURE
Nov 25 11:35:49 fedora systemd[1]: Reload failed for D-Bus System Message Bus.
Nov 25 11:36:26 fedora systemd[1]: Reloading D-Bus System Message Bus...
Nov 25 11:36:26 fedora dbus-broker-launch[1493]: Access denied in /etc/dbus-1/system-local.conf +1: /etc/dbus-1/system-local.conf
Nov 25 11:36:26 fedora busctl[56984]: Call failed: Config invalid. Reload ignored.
Nov 25 11:36:26 fedora systemd[1]: dbus-broker.service: Control process exited, code=exited, status=1/FAILURE
Nov 25 11:36:26 fedora systemd[1]: Reload failed for D-Bus System Message Bus.
```

**Comment by hughsie** [comment]
If it helps, there are rpm packages for this branch here: https://people.freedesktop.org/~hughsient/fedora/32/x86_64/

**Comment by ahoneybun** [comment]
That helps a lot! So I have it installed since I grabbed all of the fwupd 1.7.3 packages there but I get this now:

```shell
[aaronh@fedora Downloads]$ fwupdmgr get-version
WARNING: This package has not been validated, it may not work properly.
Unsupported daemon version 1.7.3, client version is 1.7.2-20-g2b512160
```

**Comment by hughsie** [comment]
Ya, just use --force for now.

**Comment by ahoneybun** [comment]
That doesn't seem to work:

```shell
[aaronh@fedora Downloads]$ fwupdmgr get-version --force
WARNING: This package has not been validated, it may not work properly.
Command not found

Use fwupdmgr --help for help
```

**Comment by hughsie** [comment]
> Ya, just use --force for now.

e.g. `fwupdmgr update --force`

**Comment by ahoneybun** [comment]
Ah alright so we are getting closer! 

```shell
[aaronh@fedora Downloads]$ fwupdmgr update --force
WARNING: This package has not been validated, it may not work properly.
Devices with no available firmware updates: 
 • SDSSDA240G
 • SSD 970 EVO 500GB
 • System Firmware
 • UEFI dbx
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade Launch Configurable Keyboard (launch 1) from 0.7.103-4007-ga49720    ║
║ to 0.7.103-4011-g708ed5?                                                     ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ Add system76_ec command to disable input events. This mainly allows for the  ║
║ System76 production line to perform quality assurance tests faster than the  ║
║ previous method of setting and resetting the entire keymap.                  ║
║                                                                              ║
║ Launch Configurable Keyboard (launch 1) and all connected devices may not    ║
║ be usable while updating.                                                    ║
╚══════════════════════════════════════════════════════════════════════════════╝

Perform operation? [Y|n]: y
Downloading…             [***************************************]
Downloading…             [***************************************]
Downloading…             [***************************************]
Decompressing…           [***************************************]
Decompressing…           [***************************************]
Authenticating…          [***************************************]
Authenticating…          [***************************************]
Restarting device…       [***************************************]
Action Required: To ensure you have physical access, Launch Configurable Keyboard (launch 1) needs to be manually unlocked. Please press Fn+Esc to unlock and re-run the update.
Restarting device…       [***************************************]
Writing…                 [***************************************]
Waiting…                 [************************************** ]failed to get device before update reload: failed to wait for detach replug: device 29627b6877d3b89cccee135287435fde986fee98 did not come back
[aaronh@fedora Downloads]$ fwupdmgr get-devices --force
WARNING: This package has not been validated, it may not work properly.
Galago Pro
│
├─SDSSDA240G:
│     Device ID:          5dbeb140337f610d54913c0f43d15fdaa0eafb51
│     Summary:            ATA drive
│     Current version:    Z22000RL
│     Vendor:             SanDisk (ATA:0x15B7, OUI:001b44)
│     GUIDs:              434f4d0d-c71e-58f3-905a-80613815f10f
│                         09c5ce8a-75ab-5ae0-bc4c-4040a7da82fe
│                         f93a32a4-d5bc-566c-afd6-345dacb9b770
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─SSD 970 EVO 500GB:
│     Device ID:          e11623b2caa18fee292058a5c09ca4e6152f7ecf
│     Summary:            NVM Express solid state drive
│     Current version:    2B2QEXE7
│     Vendor:             Samsung (NVME:0x144D)
│     GUIDs:              0b4d773a-7ac3-58c1-a541-e22ef1cdfe02
│                         c9d531ea-ee7d-5562-8def-c64d0d144813
│                         6e54c992-d302-59ab-b454-2d26ddd63e6d
│                         47335265-a509-51f7-841e-1c94911af66b
│                         5fc1d3d7-f6cf-5f1c-ba7e-18a56f00f262
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
└─System Firmware:
  │   Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
  │   Summary:            UEFI ESRT device
  │   Current version:    2
  │   Minimum Version:    2
  │   Vendor:             System76 (DMI:American Megatrends Inc.)
  │   Update State:       Success
  │   GUIDs:              8a9ca8c8-8343-53d4-8418-7a2a0f34bfcb
  │                       230c8b18-8d9b-53ec-838b-6cfc0383493a
  │                       ee356cd2-d903-58aa-a40c-172d026c4b5a
  │   Device Flags:       • Internal device
  │                       • Updatable
  │                       • System requires external power source
  │                       • Needs a reboot after installation
  │                       • Device is usable for the duration of the update
  │ 
  └─UEFI dbx:
        Device ID:        362301da643102b9f38477387e2193e57abaa590
        Summary:          UEFI revocation database
        Current version:  77
        Minimum Version:  77
        Vendor:           UEFI:Linux Foundation
        Install Duration: 1 second
        GUIDs:            c6682ade-b5ec-57c4-b687-676351208742
                          f8ba2887-9411-5c36-9cee-88995bb39731
        Device Flags:     • Internal device
                          • Updatable
                          • Needs a reboot after installation
                          • Only version upgrades are allowed
      
________________________________________________

Devices that were not updated correctly:

 • Launch Configurable Keyboard (launch 1) (0.7.103-4007-ga49720 → 0.7.103-4011-g708ed5)
```

**Comment by ahoneybun** [comment]
So it did update the firmware once I both restarted `fwupd` and re-plug the Launch.

```shell
[aaronh@fedora Downloads]$ fwupdmgr update --force
WARNING: This package has not been validated, it may not work properly.
Devices with no available firmware updates: 
 • SDSSDA240G
 • SSD 970 EVO 500GB
 • System Firmware
 • UEFI dbx
Devices with the latest available firmware version:
 • Launch Configurable Keyboard (launch 1)
```

**Comment by hughsie** [comment]
@ahoneybun can you run this in one console tab: `sudo /usr/libexec/fwupd/fwupd --verbose &> log.txt` -- then do `fwupdmgr reinstall --force` in another tab -- and then upload the entire log.txt file to this bug please. I want to see why the daemon isn't detecting the runtime mode after the successful flash.

**Comment by ahoneybun** [comment]
This should be everything. 

[log.txt](https://github.com/fwupd/fwupd/files/7610747/log.txt)

**Comment by hughsie** [comment]
Super useful, thanks:

    21:40:37:0365 FuDeviceList         waiting 10000ms for ATm32U4DFU device removal
    21:40:37:0797 FuDevice             using 29627b6877d3b89cccee135287435fde986fee98 for usb:01:00:01:05
    21:40:38:0808 FuEngine             failed to add device usb:01:00:01:05: failed to execute version command: failed to read response: transfer timed out

It appears the launch doesn't accept the version command straight away after coming back from DFU mode. I've uploaded new rpms; can you install those and get the new log.txt please.

**Comment by ahoneybun** [comment]
Here you go! It looks like that worked much better!

[log.txt](https://github.com/fwupd/fwupd/files/7610804/log.txt)

**Comment by hughsie** [comment]
Looks good. Can you try a few more times and make sure it's reliable please. No need for logs this time.

**Comment by ahoneybun** [comment]
Reinstall only or should I try downgrading then updating again?

**Comment by hughsie** [comment]
Ideally, both please!

**Review by superm1 — APPROVED** [review]

**Comment by ahoneybun** [comment]
It looks like reinstalling, update from an older version and downgrading sometimes run into the same error but the next time they do work.

[update.txt](https://github.com/fwupd/fwupd/files/7610897/update.txt)
[downgrade.txt](https://github.com/fwupd/fwupd/files/7610898/downgrade.txt)
[reinstall-update.txt](https://github.com/fwupd/fwupd/files/7610899/reinstall-update.txt)

**Pull request merged**
