### PR TITLE
Wip/hughsie/dbx ignore

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
I would think for the purpose of VM testing of secure boot stuff you don't want dbx updates turned off by default

**Comment by hughsie** [comment]
> you don't want dbx updates turned off by default

You mean we should disable it when under emulation in all cases? Or we should instead nuke the extra entries and try to narrow it down to old "bios" versions with the new metadata and some extra time?

**Comment by superm1** [comment]
I mean we should leave it for emulation. So we can very easily validate dbx updates in an environment that can be controlled more easily.

**Comment by hughsie** [comment]
Okay, lets drop this one and have a rethink when we've got the data we need: https://github.com/fwupd/fwupd/pull/5224

**Pull request closed without merging**
