### PR TITLE
Lower libcurl requirement further still

### PR DESCRIPTION
**Pull request by hughsie**
This allows us to build on Ubuntu 16.04!

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
> This allows us to build on Ubuntu 16.04!

Ha, I would expect we're going to have a few other deps that don't work.... but it's in that direction.

**Review by superm1 — APPROVED** [review]

**Comment by hughsie** [comment]
> Ha, I would expect we're going to have a few other deps that don't work

I'm only compiling standalone fwupdtool enough for fuzzing, so maybe that's enough?

**Comment by superm1** [comment]
> I'm only compiling standalone fwupdtool enough for fuzzing, so maybe that's enough?

You had a new enough gnutls and meson to do that though?

**Comment by hughsie** [comment]
> You had a new enough gnutls 

I compiled jcat as a subproject with neither gpg nor pkcs7... :/ Not usable obviously, but good enough for a fuzzer....

> and meson to do that though?

`pip install meson` :/

**Pull request merged**
