### PR TITLE
Use systemd to create and manage more directories automatically

### PR DESCRIPTION
**Pull request by superm1**
This was the outcome of some debugging actions in why clearlinux fwupd wasn't working properly.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [x] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by AdamWill** [comment]
I don't think this works right at all. In Fedora it causes the same problem we [saw with iwd](https://bugzilla.redhat.com/show_bug.cgi?id=1749430) recently. If you refer to a non-existent directory in a service file like this, systemd will blow up with a slightly confusing error message. See also the discussion [here](https://bugzilla.redhat.com/show_bug.cgi?id=1743585#c13).

**Comment by AdamWill** [comment]
Crash observed in Fedora openQA testing after this change showed up:

    Oct 01 04:39:34 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com systemd[1991]: fwupd.service: Failed to set up mount namespacing: /run/systemd/unit-root/var/cache/fwupd: No such file or directory
    Oct 01 04:39:34 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com systemd[1991]: fwupd.service: Failed at step NAMESPACE spawning /usr/libexec/fwupd/fwupd: No such file or directory
    Oct 01 04:39:34 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com systemd[1]: fwupd.service: Main process exited, code=exited, status=226/NAMESPACE
    Oct 01 04:39:34 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com systemd[1]: fwupd.service: Failed with result 'exit-code'.

**Comment by AdamWill** [comment]
note, you won't see this on an existing system where `/var/cache/fwupd` was already created by an older fwupd, but if you do a fresh install and only ever install the new fwupd you should see it.

**Comment by superm1** [comment]
@AdamWill on my test system with master.

```
$ ls -alh /var/cache/
total 80K
drwxr-xr-x 16 root root 4.0K Oct  1 22:24 .
drwxr-xr-x 14 root root 4.0K Jul 12 02:42 ..
drwxr-xr-x  3 root root 4.0K Aug 13 12:03 apparmor
drwxr-xr-x  5 root root 4.0K Sep 30 11:44 app-info
drwxr-xr-x  3 root root 4.0K Sep 30 11:44 apt
drwxr-xr-x  2 root root 4.0K Jul 12 02:37 cracklib
drwxrwx---  3 root lp   4.0K Oct  1 22:23 cups
drwxr-xr-x  2 root root 4.0K Sep 29 14:33 debconf
drwxr-xr-x  2 root root 4.0K Jul 12 02:42 dictionaries-common
drwxr-xr-x  2 root root  20K Sep 26 07:03 fontconfig
drwxr-xr-x  2 root root 4.0K Jun 19 02:47 gdm
drwx------  2 root root 4.0K Sep 30 13:18 ldconfig
drwxr-xr-x 42 man  man  4.0K Sep 30 13:18 man
-rw-r--r--  1 root root    0 Oct  1 22:22 motd-news
drwxr-xr-x  3 root root 4.0K Jul 12 02:35 PackageKit
drwx------  4 root root 4.0K Sep 30 12:04 private
drwxr-xr-x  3 root root 4.0K Oct  1 22:23 snapd

$ sudo systemctl start fwupd
$ ls -alh /var/cache/
total 84K
drwxr-xr-x 17 root root 4.0K Oct  1 22:26 .
drwxr-xr-x 14 root root 4.0K Jul 12 02:42 ..
drwxr-xr-x  3 root root 4.0K Aug 13 12:03 apparmor
drwxr-xr-x  5 root root 4.0K Sep 30 11:44 app-info
drwxr-xr-x  3 root root 4.0K Sep 30 11:44 apt
drwxr-xr-x  2 root root 4.0K Jul 12 02:37 cracklib
drwxrwx---  3 root lp   4.0K Oct  1 22:23 cups
drwxr-xr-x  2 root root 4.0K Sep 29 14:33 debconf
drwxr-xr-x  2 root root 4.0K Jul 12 02:42 dictionaries-common
drwxr-xr-x  2 root root  20K Sep 26 07:03 fontconfig
drwxr-xr-x  2 root root 4.0K Oct  1 22:26 fwupd
drwxr-xr-x  2 root root 4.0K Jun 19 02:47 gdm
drwx------  2 root root 4.0K Sep 30 13:18 ldconfig
drwxr-xr-x 42 man  man  4.0K Sep 30 13:18 man
-rw-r--r--  1 root root    0 Oct  1 22:22 motd-news
drwxr-xr-x  3 root root 4.0K Jul 12 02:35 PackageKit
drwx------  4 root root 4.0K Sep 30 12:04 private
drwxr-xr-x  3 root root 4.0K Oct  1 22:23 snapd
```

I think this might be that 1.3.2 had an issue with the new fwupdmgr-refresh unit sharing the directory that just got reported.  See: https://github.com/fwupd/fwupd/pull/1420

**Comment by hughsie** [comment]
@AdamWill do you want me to build a F32 package with https://github.com/fwupd/fwupd/pull/1420/commits/e5669a7ddb0e6dcdcd4f80d9f354aa9307617846 included?

**Comment by superm1** [comment]
It is worth checking if /var/cache/fwupd is a symlink to private/fwupd. If it is, then we might need to do some cleanup in a preinst script.

**Comment by keszybz** [comment]
> I don't think this works right at all. In Fedora it causes the same problem we [saw with iwd](https://bugzilla.redhat.com/show_bug.cgi?id=1749430) 

Nope. ReadWritePaths= requires the directory to exist. But StateDirectory/CacheDirectory/ConfigurationDirectory do not have to exist, in fact systemd *expects* to manage them, similarly as is does PrivateTmp. That's why I recommended swithing to that in option 1. in https://bugzilla.redhat.com/show_bug.cgi?id=1743585#c13.

```
Failed to set up mount namespacing: /run/systemd/unit-root/var/cache/fwupd: No such file or directory
```
Could this be an selinux issue?

> It is worth checking if /var/cache/fwupd is a symlink to private/fwupd. If it is, then we might need to do some cleanup in a preinst script.

Systemd now supports automatic switching between DynamicUser=1 and DynamicUser=0, both ways. So if /var/cache/fwupd is a symlink to private/fwupd (the setup for DynamicUser=1), and the service is run with DynamicUser=0, the symlink will be removed and the directory renamed back to /var/cache/fwupd. If this does not work as expected, please open a bug against systemd. It should not be necessary to do this cleanup by hand (in F31+).

**Comment by superm1** [comment]
> Systemd now supports automatic switching between DynamicUser=1 and DynamicUser=0, both ways. So if /var/cache/fwupd is a symlink to private/fwupd (the setup for DynamicUser=1), and the service is run with DynamicUser=0, the symlink will be removed and the directory renamed back to /var/cache/fwupd. If this does not work as expected, please open a bug against systemd. It should not be necessary to do this cleanup by hand (in F31+).

If that part is working properly great, glad to hear.  The particular problem that we're seeing I think was two different units were both trying to use the same `CacheDirectory` but only one of them had `DynamicUser` set. So that's why we switched them to their own cache directories in that above fixup https://github.com/fwupd/fwupd/commit/e5669a7ddb0e6dcdcd4f80d9f354aa9307617846

**Comment by AdamWill** [comment]
Aha, thanks for the followups. I will do a scratch build with e5669a7 and see if it fixes things.

**Comment by AdamWill** [comment]
hum, no, I don't think that's it...

Oh, I've got it! It really is the `ReadWritePaths` thing...but this isn't the PR that broke it. I reproduced the bug manually, and there is no `/var/cache/fwupd` on the system, and `/usr/lib/systemd/system/fwupd.service` has this line:

    ReadWritePaths=/var/lib/fwupd /var/cache/fwupd /etc/fwupd /etc/fwupd/remotes.d -/boot/efi -/efi/

That's because of a fancypants Meson feature. In `meson.build`:

      dynamic_options = []
      if systemd.version().version_compare('>= 232')
        dynamic_options += 'ProtectControlGroups=yes'
        dynamic_options += 'ProtectKernelModules=yes'
      endif
      if systemd.version().version_compare('>= 231')
        dynamic_options += 'RestrictRealtime=yes'
    #    dynamic_options += 'MemoryDenyWriteExecute=yes'
        dynamic_options += ['ReadWritePaths=' + ' '.join(rw_directories)]
      else
        dynamic_options += ['ReadWriteDirectories=' + ' '.join(rw_directories)]
      endif
      con2.set('dynamic_options', '\n'.join(dynamic_options))

and in 1.2.11, which is the new version we actually sent out to F31, `rw_directories` is defined like this:

    rw_directories = []
      rw_directories += join_paths (localstatedir, 'lib', 'fwupd')
      rw_directories += join_paths (localstatedir, 'cache', 'fwupd')
      rw_directories += join_paths (sysconfdir, 'fwupd')
      rw_directories += join_paths (sysconfdir, 'fwupd', 'remotes.d')
      if get_option('plugin_uefi')
        rw_directories += ['-/boot/efi', '-/efi/EFI', '-/boot/EFI']
      endif

so we wind up with that `ReadWriteDirectories` line. The only thing included in it that doesn't exist on the fresh install is `/var/cache/fwupd`, and that was added to `rw_directories` in an *earlier* commit by @superm1 : https://github.com/fwupd/fwupd/commit/2bf3a372df6610d274155ae4085aa762e8a3107a

So I think the real story here is that this is broken in the `1_2_X` branch, which has that commit and not this one. It was probably broken on master branch between 00aabbf78bae4d3fec90a7364370650d04bd1bf4 and this PR, which likely *fixes* it on master branch.

**Comment by superm1** [comment]
Awesome detective work!  Sorry for the breakage on 1_2_X.  I tested 1_2_X with lots of the backports, but not specifically in the situation of missing `/var/cache/fwupd`.
So that probably means that we need to backport https://github.com/fwupd/fwupd/commit/277c196369f86f65f8831a049d01fab84cee4b1f to 1_2_X too.

Can you please confirm with a local build that if you backport that it sorts it out?

**Comment by AdamWill** [comment]
oh, I was just gonna have the package ship an empty `/var/cache/fwupd`, but I can test that instead.

**Comment by superm1** [comment]
and 00fdf83 I guess too.

**Comment by AdamWill** [comment]
I tried a scratch build with that patch but it doesn't appear to solve anything. `/var/cache/fwupd` doesn't appear, and the service still fails to start.

**Comment by AdamWill** [comment]
OK, with both of those commits backported it works...but on Fedora, only with `enforcing=0`, because with SELinux in enforcing mode it blocks the creation of the directory:

    type=AVC msg=audit(1570055823.561:216): avc:  denied  { create } for  pid=1942 comm="(fwupd)" name="fwupd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:var_t:s0 tclass=dir permissive=0

**Comment by hughsie** [comment]
@superm1 can you backport both commits to the stable branch please, and I'll do a tarball with that next week for Fedora. @AdamWill have you filed the SElinux bug yet, or do you want me to?

QA FTW btw, thanks.

**Comment by superm1** [comment]
> @superm1 can you backport both commits to the stable branch please, and I'll do a tarball with that next week for Fedora. @AdamWill have you filed the SElinux bug yet, or do you want me to?

OK done, backported.  Whoever files the SELinux bug post it here, I'm interested in following that rabbit hole.

> QA FTW btw, thanks.

:balloon: :tada:

**Comment by AdamWill** [comment]
@hughsie I filed https://bugzilla.redhat.com/show_bug.cgi?id=1757249 and asked for your opinion there on whether to do the backport+SELinux fix or just ship the directory in the package, so we can follow up there I guess.

**Comment by hughsie** [comment]
@AdamWill wrong bug ID?

**Comment by hughsie** [comment]
> so we can follow up there I guess.

I found the bug -- and to repeat here -- I think fixing selinux and creating in the %post is a good idea for the short term. @AdamWill can you commit your fix to fedora scm please and I'll do a new build for f31

**Comment by superm1** [comment]
What's the bug number? That one looks wrong

**Pull request merged**
