### PR TITLE
Drop @reboot/@resources/@swap system calls

### PR DESCRIPTION
**Pull request by RZR7332**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

This PR aims to drop the below system calls from fwupd:

- @reboot
- @resources
- @swap

The contents of each group of system calls will be detailed in the comments.

### CODE REVIEW

**Comment by RZR7332** [comment]
@reboot contains the following:

@reboot
    # Reboot and reboot preparation/kexec
    kexec_file_load
    kexec_load
    reboot

**Comment by RZR7332** [comment]
@resources contains the following:

@resources
    # Alter resource settings
    ioprio_set
    mbind
    migrate_pages
    move_pages
    nice
    sched_setaffinity
    sched_setattr
    sched_setparam
    sched_setscheduler
    set_mempolicy
    setpriority
    setrlimit

**Comment by RZR7332** [comment]
@swap contains the following:

@swap
    # Enable/disable swap devices
    swapoff
    swapon

**Review by hughsie — APPROVED** [review]
If CI works, LGTM, thanks.

**Pull request merged**
