### PR TITLE
Do not ask for device when using --json

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
I don't agree with this approach.  It means that you get different errors based on if it's launched by a script or by you in shell.

I think `as_json` should factor into the `is_interactive` check, and be a way that forces it not to be interactive anymore.

**Comment by hughsie** [comment]
> I don't agree with this approach. It means that you get different errors based on if it's launched by a script or by you in shell.

True, but this is for when the device is ambiguous. e.g. you typed `fwupdmgr update GUID` and you have two devices with the same GUID.

> I think as_json should factor into the is_interactive check, and be a way that forces it not to be interactive anymore.

I don't get it; how do we guess the device the script actually meant?

**Comment by superm1** [comment]
> True, but this is for when the device is ambiguous. e.g. you typed fwupdmgr update GUID and you have two devices with the same GUID.

Then you should be using the device ID instead.  A script running this in JSON mode can get the devices, figure out the information that indicates it's the right one and then call the command with the right one as an argument.

> I don't get it; how do we guess the device the script actually meant?

You don't.  In my mind it means that if you're operating in json mode you're not allowed to make guesses.
Think of it this way - let's say you're an organization and you run some script that is supposed to check for updates using `fwupdmgr --json` on bootup.  You don't want prompting of course.
Now lets say there is some problem and you want to debug it.  Then you run that same script interactively but things happen to work just fine because it's interactive and it guesses the first device.

You want deterministic behavior when it's in JSON mode.

**Comment by hughsie** [comment]
>  Then you run that same script interactively but things happen to work just fine because it's interactive and it guesses the first device

Ohh it's not doing that; it's returning with an error if we don't just have one matching device; as in return with failure if there is anything more than one "correct" answer.

**Comment by superm1** [comment]
Counter-proposal in #4328

**Comment by hughsie** [comment]
Closing in favour of https://github.com/fwupd/fwupd/pull/4328

**Pull request closed without merging**
