### PR TITLE
Show a link to discover more information about a specific plugin failure

### PR DESCRIPTION
**Pull request by hughsie**
Fixes bugs like https://github.com/fwupd/fwupd/issues/2531

### CODE REVIEW

**Comment by hughsie** [comment]
This shows:

    WARNING: UEFI ESP partition not detected or configured
      See https://github.com/fwupd/fwupd/wiki/PluginFlag:esp-not-found for more information.

**Comment by hughsie** [comment]
@superm1 can you help me flesh these out a bit? I'm not feeling very wordy today.

https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported
---

UEFI capsule updates not available or enabled

https://github.com/fwupd/fwupd/wiki/PluginFlag:unlock-required
---

Firmware updates disabled; run 'fwupdmgr unlock' to enable

https://github.com/fwupd/fwupd/wiki/PluginFlag:efivar-not-mounted
---

Required efivarfs filesystem was not found

https://github.com/fwupd/fwupd/wiki/PluginFlag:esp-not-found
---

UEFI ESP partition not detected or configured

https://github.com/fwupd/fwupd/wiki/PluginFlag:legacy-bios
---

Firmware can not be updated in legacy BIOS mode

https://github.com/fwupd/fwupd/wiki/PluginFlag:failed-open
---

Plugin dependencies missing

**Comment by hughsie** [comment]
>  I'm not feeling very wordy today.

In a flash of inspiration I wrote simple pages for all of them. Feel free to fix up any obscene violations of English grammar without asking :)

**Comment by superm1** [comment]
>In a flash of inspiration I wrote simple pages for all of them. Feel free to fix up any obscene violations of English grammar without asking :)

Well you beat me, I just added a few words to 2 of them about being able to compile without UEFI support as well.

**Pull request merged**
