### PR TITLE
Update rts54hub.quirk

### PR DESCRIPTION
**Pull request by AnyProblem**
add Vendor name

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [* ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@AnyProblem is this to replace `Good Way Technology Co., Ltd & GWC technology Inc.` with `Goodway`?

**Comment by AnyProblem** [comment]
Sorry I think show all vendor name 'Good Way Technology Co., Ltd & GWC technology Inc' is better.
this modification want to check why the Name tag show on Vendor line and not show on the first line when type get-devices also not show behind the GUID, 
So I add Vendor tag for odm to check

**Comment by hughsie** [comment]
@AnyProblem the `USB\VID_065F` should have made the `Good Way Technology Co., Ltd & GWC technology Inc` appear as the vendor automatically -- can you share the `-vv` output pls.

**Comment by AnyProblem** [comment]
@hughsie ,
I find not only [USB\VID_065F&PID_2260] has this problem, and [USB\VID_3749&PID_050B] [USB\VID_3749&PID_050D]
also has this showing info issue. can see the attachments
no_device_name
no_device_name_2
S__6144138
[2260_rts54hub_v_.txt](https://github.com/user-attachments/files/17093098/2260_rts54hub_v_.txt)
[2260_rts54hub_vv_.txt](https://github.com/user-attachments/files/17093099/2260_rts54hub_vv_.txt)

thank you

**Comment by hughsie** [comment]
@AnyProblem this is a problem with the USB device descriptor -- the vendor string is set as `USB-C Dual Display Dock` and **also** the name string is set as `USB-C Dual Display Dock` -- and fwupd tries to fix them up but fails. https://github.com/fwupd/fwupd/pull/7771 solves the unhelpful fwupd behaviour, but I think the root problem is that either the vendor string is wrong, or the USB string descriptor index is pointing to the wrong string.

**Comment by AnyProblem** [comment]
@hughsie ok I got it, 
I think can ignore this patch, I will ask the device engineer to review their report of USB device descriptor
thank you

**Pull request closed without merging**
