### PR TITLE
uefi-capsule: Include all the sections when using objcopy

### PR DESCRIPTION
**Pull request by hughsie**
Fixes the regression introduced in fde4b1676a2c64e70bebd88f7720307c62635654

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by martinezjavier — APPROVED** [review]
Looks good to me. Sorry for the regression...

**Comment by superm1** [comment]
@hughsie re-spin 1.5.x for this or put this as distro patches?  I guess i'll pull it back to 1.4.x and 1.3.x PR's when we merge.

**Comment by hughsie** [comment]
Yup, I'll do a 1.5.7 on Monday.

**Comment by FFY00** [comment]
I'll backport this to the arch package meanwhile.

**Pull request merged**
