### PR TITLE
dbxtool: List the checksums correctly for multiple EFI_SIGNATURE_LISTs

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/2319

### CODE REVIEW

**Comment by superm1** [comment]
It's really close to the regular dbxtool now, but there is an extra entry printed and it's not parsing identically.

```
$ diff -u fwupd.txt dbxtool.txt
--- fwupd.txt   2020-08-13 14:57:50.691035532 -0500
+++ dbxtool.txt 2020-08-13 14:57:22.299445231 -0500
@@ -1,4 +1,4 @@
-   1: {00000000-0000-0000-0000-000000000000} {x509_cert} f01614a7a81ba477f0746cf2de71b20dddec709e756c9ea57cb67f93f25ba9fd
+   1: {zero} {x509_cert} 3082066b30820453a003020102020a610c6a19000000000004300d06092a864886f70d01010b0500308188310b3009060355040613025553311330110603550408130a57617368696e67746f6e3110300e060355040713075265646d6f6e64311e301c060355040a13154d6963726f736f667420436f72706f726174696f6e31323030060355040313294d6963726f736f667420526f6f7420436572746966696361746520417574686f726974792032303130301e170d3130303730363230343032335a170d3235303730363230353032335a3079310b3009060355040613025553311330110603550408130a57617368696e67746f6e3110300e060355040713075265646d6f6e64311e301c060355040a13154d6963726f736f667420436f72706f726174696f6e312330210603550403131a4d6963726f736f66742057696e646f777320504341203230313030820122300d06092a864886f70d01010105000382010f003082010a0282010100c079bb3ab1f00f84b8ad642a751673d0bb07f63e0d9d14e4b19fc1c894b0387c1fd03355f5ba2366f52e284853c71683baf551ac7eace0267f0f74fc5995dcc9c6a2f752705a2c1d94ab19bfaf957daf66a16f9b626e6d4bbc2f356cdea46a635a5ffbf30d4d61cc0a7e31eb6c0ad04d970ffd7f3846e68ac77369765569964ce4d8f034ebbab11fce297ec44f9d1315ab131b725862566c8a81a36477984665299d8314a54c08a083d7231ff35fdf6f2ccfda16d80e720428d86b3ef813b17ca217794f7edc3ae49d70276bbfdbfc1ec707d8c0be0b931e28e0736dd254e9284cbf6b5d9fff5d331237952561346a42cb7c9d3abb8859e1a3426d3a505b48d10203010001a38201e3308201df301006092b06010401823715010403020100301d0603551d0e04160414d14fa98a0708cef4241898e500fff3d6791d37bc301906092b0601040182371402040c1e0a00530075006200430041300b0603551d0f040403020186300f0603551d130101ff040530030101ff301f0603551d23041830168014d5f656cb8fe8a25c6268d13d94905bd7ce9a18c430560603551d1f044f304d304ba049a0478645687474703a2f2f63726c2e6d6963726f736f66742e636f6d2f706b692f63726c2f70726f64756374732f4d6963526f6f4365724175745f323031302d30362d32332e63726c305a06082b06010505070101044e304c304a06082b06010505073002863e687474703a2f2f7777772e6d6963726f736f66742e636f6d2f706b692f63657274732f4d6963526f6f4365724175745f323031302d30362d32332e63727430819d0603551d2004819530819230818f06092b0601040182372e03308181303d06082b060105050702011631687474703a2f2f7777772e6d6963726f736f66742e636f6d2f504b492f646f63732f4350532f64656661756c742e68746d304006082b0601050507020230341e32201d004c006500670061006c005f0050006f006c006900630079005f00530074006100740065006d0065006e0074002e201d300d06092a864886f70d01010b050003820201002e41a686b5066ff08085fa3bca17e9c9fae439c29470c36494c3d856a6908efee49af46df56f8e538d5aa8f3aedb466cbe7f1d54561b3c1d71c45115547ebfeea5954233fd0d902424e3f9dc96cafcb8acbff4c23956b8bbed73b317dd7e8650238b5624cabba61d9a872f2785e7a1b60a9c0d1b8cf3006241ba48748782fd50c9f48729c303aa2bdf1a2979e812249a86edd02ed34081f5075f3306545d40b5f7b162fd4d48f76e4147521cbb1bc2573aa8995693d4c6de26a8607586bbec62a6f01d0445df3ea784d15b4423632536776fae5bdc22d514236a417fd042a6dbef257b04e3d296376206aff81b0f8eb3399abb89f53506e5a45bc38c9e375f53d1a337fda44fe81b0e6b76e4b88fb0c2eafd75f72c41b79ca3e11e05fe9792cb7f59036da84e8d4e8017d4d572f656e4489fa323ba06a0c08ed1884f9320f2705fd86b72a32049fc770c5dc5c7e1020f3842100edb02ae9a371d5080291ea4a7d9c69a2555fd40caad6410e831f91254791af20ed8d6ab1e33fe02e7266d61498ff125c28b7499dff9931a901ceedd94330e4250db7f50f89f6282eca682167c66bcec99b0c1585da8b09a611491d1992f49e43e8199d6e6efcae3fd3eeeec098603070d1b0d7cebf45ac995cf87120a5decc50292cd059972ca7df12a101838e431a328b4e64cc552a39c6ac77dc07109040d70de023f87ee56a1ecebb54c85
    2: {microsoft} {sha256} 80b4d96931bf0d02fd91a61e19d14f1da452e66db2408ca8604d411f92659f0a
    3: {microsoft} {sha256} f52f83a3fa9cfbd6920f722824dbe4034534d25b8507246b3b957dac6e1bce7a
    4: {microsoft} {sha256} c5d9d8a186e2c82d09afaa2a6f7f2e73870d3e64f72c4e08ef67796a840f0fbd
@@ -76,8 +76,8 @@
   76: {microsoft} {sha256} 939aeef4f5fa51e23340c3f2e49048ce8872526afdf752c3a7f3a3f2bc9f6049
   77: {microsoft} {sha256} 64575bd912789a2e14ad56f6341f52af6bf80cf94400785975e9f04e2d64d745
   78: {microsoft} {sha256} 45c7c8ae750acfbb48fc37527d6412dd644daed8913ccd8a24c94d856967df8e
-  79: {microsoft} {x509_cert} 90244cc221e00c1fe0a7b78b3ce945dd73bf1633019eb6c15fa5646f9c8d2e1e
-  80: {microsoft} {x509_cert} f156d24f5d4e775da0e6a9111f074cfce701939d688c64dba093f97753434f2c
+  79: {microsoft} {x509_cert} 3082042030820308a003020102020101300d06092a864886f70d01010b0500308184310b30090603550406130247423114301206035504080c0b49736c65206f66204d616e3110300e06035504070c07446f75676c617331173015060355040a0c0e43616e6f6e6963616c204c74642e3134303206035504030c2b43616e6f6e6963616c204c74642e204d617374657220436572746966696361746520417574686f72697479301e170d3132303431323131333930385a170d3432303431313131333930385a307f310b30090603550406130247423114301206035504080c0b49736c65206f66204d616e31173015060355040a0c0e43616e6f6e6963616c204c74642e31143012060355040b0c0b53656375726520426f6f74312b302906035504030c2243616e6f6e6963616c204c74642e2053656375726520426f6f74205369676e696e6730820122300d06092a864886f70d01010105000382010f003082010a0282010100c95f9b628f0bb06482acbec9e262e34bd29f1e8ad5611a2b5d38f4b7ceb99ab843b8439777ab4f7f0c70460bfc7f6dc66dea805e01d2b7661e87de0d6dd04197a8a5af0c634ff77cc252cca031a9bb895d991e466f5573b97669ecd7c1fc21d6c607e74fbd22dee4a85b2ddb95341997d6284b214ccabb1d79a6177f5af967e65c78453d106db017592611c557e37f4e82baf62c4ec8374dff85158447e0ed3b7c7fbcafe90105a70c6fc3e98da3cebea6e3cd3cb5582c9ec2031c60223739ff4102c129a46551ff3334aa4215f99578fc2df5da8a857c829dfb372c6ba5a8df7c550b802e3cb063e1cd384889e814060b82bcfdd407681b0f3ed915dd94111b0203010001a381a030819d300c0603551d130101ff04023000301f0603551d250418301606082b06010505070303060a2b0601040182370a0306302c06096086480186f842010d041f161d4f70656e53534c2047656e657261746564204365727469666963617465301d0603551d0e0416041461482aa2830d0ab2ad5af10b7250da9033ddcef0301f0603551d23041830168014ad91990bc22ab1f517048c23b6655a268e345a63300d06092a864886f70d01010b050003820101008f8aa1061f29b70a4ad5c5fd81ab25eac07de2fc6a96a0799367ee050e251225e45af6aa1af112f3058d875ef15a5ccb8d2373651d15b9de226bd64967c9a3c6d7624e5cb5f903834081dc879c3c3f1c0d519f94650a844867e4a2f8a64af0e7cdcdbd94e309d25d2d161b05150bcb44b43e614222c42a5c4ec51da3e2e052b2ebf48b2bdc38395dfb88a156655f2b4f26ff06781012eb8c5d32e3c645af259ba0ff8eef4709a3e98b37929269767e343b9205674eb025edbc5e5f8fb4d6ca40ffe4e231230c8525ae0c5501ece5475edf5bbc1433e3c6f518b6d9f7ddb3b4a131d35a5c5d7d3ebf0ae4e4e8b4597d3bb48ca31bb520a3b93e846f8c2100c339
+  80: {microsoft} {x509_cert} 308202fc308201e4a003020102020500a7468def300d06092a864886f70d01010b05003020311e301c0603550403131544656269616e2053656375726520426f6f74204341301e170d3136303831363138323235305a170d3236303831363138323235305a3024312230200603550403131944656269616e2053656375726520426f6f74205369676e657230820122300d06092a864886f70d01010105000382010f003082010a0282010100d3d183900fda65a22f075a6095ebf7c7867c2086da65a3a612eb5b3bcec8fb3fa1724b9edf50c50333a40c2b5fd641040db6cf9548ed8ab2add6e501374e60cdb24a3804b3448094af9f6e54dba81f3cb74b30de21816f09a366ba6a2b96d69a61770cd4ed3cd071bbad8cf0225c3e25cc6d222e619795af9b2e4d58b67e7802c30eb9fab25b27de7da2be0c14ac73ec97b0155eedede5a5753f78e071ce2fce83ed533130984ee6f901a28888a623087c0db7543a1695ed5e795e904efecdaade82fcf696714e4949b9d3e9b0ab7fd72a47b75330277cdc6698096fd17ef57f3d3ed4a26a8859022f2f3dc8c628de42fed9523d24c2fc409811f676bf8cbb650203010001a3393037301106096086480186f842010104040302041030150603551d25040e300c060a2b0601040182370a0301300b0603551d0f040403020780300d06092a864886f70d01010b05000382010100571ba4604c29e9f27d6b5c93dbcc6c9f183f69489a75de64f3834a09a92621eee9565de13ed975cbcc7fbf4de4e8893d7e11428740c3d5e07179dc006ce17162c798c2cb270b2f9fccecfa8bb2f30b9ef3f2c3c99fdb259390a4cdbb01e58ef4d755a8b4754131fd4e5d0318a0c2acc5de46e7dc1ccf12d59de8479d938c32cd44d574c7309a57a556d07ecf0511b4f4f329f9db9b53d2bd2fad6a75264564baba2896878eb7f07957fa7a0e3c4a3892bcf295f2e728d0f7d8981a5e399eb56580bdf3da123f507667299fd10b0a1e87975c72dbf301744add07ba76e96afcdd22db4602d7af0ac5ed15bc0f2ba9db8dbf7f6fada2b7c54d4a47b3c15690b617
   81: {microsoft} {sha256} 81d8fb4c9e2e7a8225656b4b8273b7cba4b03ef2e9eb20e0a0291624eca1ba86
   82: {microsoft} {sha256} b92af298dc08049b78c77492d6551b710cd72aada3d77be54609e43278ef6e4d
   83: {microsoft} {sha256} e19dae83c02e6f281358d4ebd11d7723b4f5ea0e357907d5443decc5f93c1e9d
```

**Comment by hughsie** [comment]
> -   1: {00000000-0000-0000-0000-000000000000} {x509_cert} f01614a7a81ba477f0746cf2de71b20dddec709e756c9ea57cb67f93f25ba9fd
+   1: {zero} {x509_cert} 3082066b30820453a003020102020a610c6a190000...

The `{zero}` thing I've got fixed in another pending branch, so ignore that. Displaying the checksums and not the entire certificate dump is deliberate. I'll add an `--export` action to match the `dbxtool` action in git master.

**Comment by superm1** [comment]
>The {zero} thing I've got fixed in another pending branch, so ignore that. Displaying the checksums and not the entire certificate dump is deliberate. I'll add an --export action to match the dbxtool action in git master.

Actually I was using `--list` for both of them.  It just seems like fwupd's might be parsing them in a different order

**Comment by hughsie** [comment]
>  It just seems like fwupd's might be parsing them in a different order

Eigh? I think it's just printing the SHA256 of the certificate rather than the rather useless raw bytes.

**Comment by superm1** [comment]
> Eigh? I think it's just printing the SHA256 of the certificate rather than the rather useless raw bytes.

You're right - i'm looking closer now.

**Pull request merged**
