### PR TITLE
amd-gpu: Allow emulating DRM_IOCTL_AMDGPU_INFO

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Note, this won't *work* to generate an emulation but I can work on the other bits on Monday.

**Comment by hughsie** [comment]
@superm1 i.e. can you check I've not broken physical hardware please.

**Comment by superm1** [comment]
> @superm1 i.e. can you check I've not broken physical hardware please.

yeah this still works on physical hardware.  I just checked on an APU (which can't flash) and it can enumerate fine.

**Comment by superm1** [comment]
Here's an emulation saved.
[setup.json](https://github.com/user-attachments/files/17530561/setup.json)

**Review by superm1 — APPROVED** [review]

**Pull request merged**
