### PR TITLE
Re-enable coverage data for Fedora

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
🤷

**Comment by superm1** [comment]
https://github.com/gcovr/gcovr/issues/736 ?

**Comment by hughsie** [comment]
I kinda think we should leave the Fedora build out of the coverage output; it's a bit weird to enable coverage for a *package build* -- and probably why we're hitting weird issues.

**Comment by superm1** [comment]
> I kinda think we should leave the Fedora build out of the coverage output; it's a bit weird to enable coverage for a _package build_ -- and probably why we're hitting weird issues.

There does seem to be some lower level bug going on.  But I'm fine to leave it out.

**Pull request closed without merging**
