### PR TITLE
Check the firmware requirements before adding SUPPORTED

### PR DESCRIPTION
**Pull request by hughsie**
100% untested

### CODE REVIEW

**Comment by superm1** [comment]
It does seem to work.  I only see `SUPPORTED` on one of my unifying dongles now:
```
(fwupdmgr:73236): FuMain-DEBUG: 15:55:08.697: Unifying Receiver
  DeviceId:             4e419dded9789c89c0050b3537950d03d13eb7a9
  Guid:                 9d131a0c-a606-580f-8eda-80587250b8d6
  Guid:                 fcf55bf5-767b-51ce-9c17-f6f538c4ee9f
  Guid:                 279ed287-3607-549e-bacc-f873bb9838c4
  Summary:              A miniaturised USB wireless receiver
  Plugin:               logitech_hidpp
  Protocol:             com.logitech.unifyingsigned
  Flags:                updatable|registered
  VendorId:             USB:0x046D
  Version:              RQR12.09_B0030
  VersionBootloader:    BOT01.04_B0016
  VersionFormat:        plain
  Icon:                 preferences-desktop-keyboard
  InstallDuration:      30
  Created:              2020-03-31

(fwupdmgr:73236): FuMain-DEBUG: 15:55:08.698: Unifying Receiver
  DeviceId:             8ad41d663d3f4ea61a81cbb32a54411a101eb850
  Guid:                 9d131a0c-a606-580f-8eda-80587250b8d6
  Guid:                 fcf55bf5-767b-51ce-9c17-f6f538c4ee9f
  Guid:                 279ed287-3607-549e-bacc-f873bb9838c4
  Summary:              A miniaturised USB wireless receiver
  Plugin:               logitech_hidpp
  Protocol:             com.logitech.unifying
  Flags:                updatable|supported|registered
  VendorId:             USB:0x046D
  Version:              RQR12.10_B0032
  VersionBootloader:    BOT01.02_B0014
  VersionFormat:        plain
  Icon:                 preferences-desktop-keyboard
  InstallDuration:      30
  Created:              2020-03-31
```

I can still try to reinstall though - so I think we need reinstall commands to look for and filter supported flag as well.
Notice it's missing:
```
$ fwupdmgr reinstall
Choose a device:
0.	Cancel
1.	8357922f7f208e1f3b7537141ce17db04bc219d9 (Thunderbolt controller in Dell dock)
2.	b5a854df85ab30fff48e4365ec7ad2249c90806e (Package level of Dell dock)
3.	0acceea54e71c4d8002593822afe0f4705616613 (RTS5413 in Dell dock)
4.	96969b82d977fdcbf607df084ef0dcf10119409b (RTS5487 in Dell dock)
5.	228ac6846b64d532dd1ea1b7e651e8f5f55fbc34 (VMM5331 in Dell dock)
6.	570867f4ddda9915445da59bd85cd0e0e507270e (WD19TB)
7.	b6c08fb9e5384d9d101853cc1ca20cf0ce2df2e2 (System Firmware)
8.	8ad41d663d3f4ea61a81cbb32a54411a101eb850 (Unifying Receiver)
```
Notice I can still try
```
# fwupdmgr reinstall 4e419dded9789c89c0050b3537950d03d13eb7a9
No releases found: Device Unifying Receiver doesn't support com.logitech.unifying
```

**Comment by superm1** [comment]
I think a second place that might need it is `fu_engine_is_device_supported`

**Comment by hughsie** [comment]
> I think a second place that might need it is fu_engine_is_device_supported

Good catch! We can combine both checks into one now too, making it all a bit simpler.

**Comment by superm1** [comment]
LGTM now, and confirmed it fixes the problem on my logitech dongle that was being marked supported when it shouldn't be.

**Pull request merged**
