### PR TITLE
trivial: fix win32 build

### PR DESCRIPTION
**Pull request by superm1**
Use the gusb that we build rather than the system one.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Looks good, but won't this break when the new libgusb appears in Fedora and the subproject no longer gets built?

**Comment by superm1** [comment]
> Looks good, but won't this break when the new libgusb appears in Fedora and the subproject no longer gets built?

Same problem as libxmlb I think..

**Comment by superm1** [comment]
> Looks good, but won't this break when the new libgusb appears in Fedora and the subproject no longer gets built?

Yeah I think that's true.  Can we maybe just force to always use subproject libgusb?

**Comment by hughsie** [comment]
> Same problem as libxmlb I think

Indeed. I'm not sure I want to be generating that file automatically but it might be safer.

**Comment by hughsie** [comment]
>  Can we maybe just force to always use subproject libgusb

ohh for win32, yes! that should work.

**Pull request merged**
