### PR TITLE
trivial: ci: install coverage

### PR DESCRIPTION
**Pull request by superm1**
hopefully fixes coveralls

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
Well so that's interesting - it fails on 0.6.9 too!  I wonder if this is a fwupd problem.

**Comment by hughsie** [comment]
@superm1 what does coverage.xml show? Is it an empty file or something weird perhaps?

**Comment by superm1** [comment]
> @superm1 what does coverage.xml show? Is it an empty file or something weird perhaps?

let's see, I just changed the job to save it to artifacts so we can tell.

**Comment by superm1** [comment]
It's empty!

**Comment by superm1** [comment]
My conclusion from that finding is something must have changed in the Debian container that broke coverage.  It just starts to show up today because containers regenerated about 16 hours ago.

**Comment by hughsie** [comment]
> something must have changed in the Debian container

Can we compare the .debs that were used in each?

**Comment by superm1** [comment]
But at least for the biggies.
* Same gcovr version 7.0-1
* Same GCC 13.2.0-23

**Comment by hughsie** [comment]
> It's a bit difficult to run diff on without some fancy pants filtering tools. You got any good ways?

I've got python! :) Easier files to diff attached -- but no smoking gun.

[old.txt](https://github.com/fwupd/fwupd/files/15175273/old.txt)
[new.txt](https://github.com/fwupd/fwupd/files/15175274/new.txt)

**Pull request closed without merging**
