### PR TITLE
Re-introduce GUID support to fwupdmgr and fwupdtool

### PR DESCRIPTION
**Pull request by hughsie**
This reverts commit dca4d6a5d69c46f7368b2f65b49b98d58f9217b8.

I've had two vendors ask me why the GUIDs have disappeared from the device.

### CODE REVIEW

**Comment by hughsie** [comment]
My logic here is that the GUID is the **thing** we refer to when writing metainfo files. Most users are not using the CLI and if you're poking around you probably need this kind of information. `--verbose` is just too hard to discover.

**Comment by FFY00** [comment]
Isn't running `--verbose` enough from them? Do they really need this information to be print by default?

**Comment by superm1** [comment]
> My logic here is that the GUID is the **thing** we refer to when writing metainfo files. Most users are not using the CLI and if you're poking around you probably need this kind of information. `--verbose` is just too hard to discover.

I'm of course saddened by reverting that commit, but I have to wonder if this is just a growing pain that needs some messaging / documentation about where to get the information?

Already you have to _know_ to call with sudo to figure out which `InstanceIDs` you care about that map to a GUID.

**Comment by hughsie** [comment]
> but I have to wonder if this is just a growing pain that needs some messaging / documentation about where to get the information

The problem was that both vendors had written documentation which specified how to get the GUID. I'm hesitant to break the existing behaviour, especially given how averse hardware vendors are to change.

**Comment by superm1** [comment]
> The problem was that both vendors had written documentation which specified how to get the GUID. I'm hesitant to break the existing behaviour, especially given how averse hardware vendors are to change.

Gotcha.  OK. :/

**Pull request merged**
