### PR TITLE
libfwupdplugin: fix fu_fmap_firmware_parse if running on a platform w…

### PR DESCRIPTION
**Pull request by superm1**
…ithout memmem

Should help fix cros_ec flashing on Windows

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
@bleungatchromium context is https://github.com/fwupd/fwupd/discussions/4082

**Comment by superm1** [comment]
the other alternative I come up with is a `#ifdef _WIN32` in `fu-tool.c` to set `FWUPD_INSTALL_FLAG_NO_SEARCH`

**Review by bleungatchromium — APPROVED** [review]
Thanks for this, Mario!

**Comment by superm1** [comment]
Hmm given there is still a failure [reported](https://github.com/fwupd/fwupd/files/7716890/log-20211215-1.txt) I don't think this is a proper solution.  The fmap offsets found are needed to figure out where to jump around.  So we really need an alternative to memmem to use.

**Comment by superm1** [comment]
Maybe use `strstr`?  It's semantically similar at least.

**Comment by hughsie** [comment]
Alternate proposal in https://github.com/fwupd/fwupd/pull/4087

**Pull request closed without merging**
