### PR TITLE
Thelio Io fixes

### PR DESCRIPTION
**Pull request by jackpot51**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

I will be collecting any fixes needed to flash Thelio Io here.

### CODE REVIEW

**Comment by hughsie** [comment]
For trivial stuff like this please feel free to push straight to my wip branch without asking (or do PRs if you're not sure). We can do a proper review when we're ready to merge to master. All stuff to master has to get approval from either me or Mario. Thanks!

**Comment by jackpot51** [comment]
That sounds good @hughsie

**Comment by superm1** [comment]
Just glancing at the branch, it would be good to mention in the readme what plugin picks up the device to actually do the flash when it's in bootloader mode.  It sounds like it might be DFU, but I wasn't sure since I saw some fastboot references in the code (but maybe that was just from the plugin this was forked from initially?)

**Comment by superm1** [comment]
Ah nevermind, I do see it mentioned already it's DFU mode now.

**Pull request merged**
