### PR TITLE
Wip/hughsie/fu usb device setup

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — DISMISSED** [review]
@CragW you should double check dell-dock with this change.

**Comment by hughsie** [comment]
Ahh, I broke dell dock as it failed the regex:

	klass_device->setup = fu_dell_dock_hid_get_hub_version;

Can I move `fu_dell_dock_hid_get_hub_version` into `fu-dell-dock-hid.c` and rename it `fu_dell_dock_hub_setup`?

**Comment by superm1** [comment]
> Ahh, I broke dell dock as it failed the regex:
> 
> ```
> klass_device->setup = fu_dell_dock_hid_get_hub_version;
> ```
> 
> Can I move `fu_dell_dock_hid_get_hub_version` into `fu-dell-dock-hid.c` and rename it `fu_dell_dock_hub_setup`?

Glad I mentioned it.  I don't think it should move out of `fu-dell-dock-hid.c`.  I think maybe add a new `fu_dell_dock_hub_setup` which calls the existing function.

**Comment by hughsie** [comment]
>  I think maybe add a new fu_dell_dock_hub_setup which calls the existing function.

Good idea. I did that, and also reviewed all the other USB/HID-using plugins.

**Pull request merged**
