### PR TITLE
Rename the audio-s5gen2 plugin to qc-s5gen2

### PR DESCRIPTION
**Pull request by hughsie**
Qualcomm can't possibly have a problem with the two letters of 'qc', and I'd argue even qualcomm-s5gen2 is 'fair use'.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]

**Comment by d4s** [comment]
I'm against of renaming -- atm we have the initial support of DevBoard only.
Vendor gives the name agreed with the legal department.
But I'm also do not like the current plugin name, to be honest.
What if we use `q-s5gen2` or even `qs5gen2` instead?

**Comment by hughsie** [comment]
> Vendor gave the name agreed with the legal department

I don't think even Qualcomm legal can say this isn't fair use.

> q-s5gen2

I don't understand why that is better than qc-s5gen2?

**Comment by d4s** [comment]
> > Vendor gave the name agreed with the legal department
> I don't think even Qualcomm legal can say this isn't fair use.
I'm not a lawer, I have no answer about that.

> > q-s5gen2
> I don't understand why that is better than qc-s5gen2?
no association with the Vendors' name at all, probably?

**Comment by hughsie** [comment]
> I'm not a lawer, I have no answer about that.

Would you be okay with qc-s5gen2 if i said _on my head be it_, i.e. I took responsibility?

**Comment by d4s** [comment]
> Would you be okay with qc-s5gen2 if i said _on my head be it_, i.e. I took responsibility?

I'm personally OK with any naming -- it's seen only by developers and QA.
And you are the Upstream ;)

**Comment by hughsie** [comment]
>  And you are the Upstream ;)

Ha! You can imagine a huge cloud opening up with the roar of "I HAVE THE POWER" but in reality I just write angry emails and click buttons. :)

**Pull request merged**
