### PR TITLE
genesys: If the transfer failed then do not retry the flash status

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by gportay** [comment]
I was not aware about that callback.

This trick is about dropping the retry traces "failed on try x of y"?

If so, this is very nice !

**Comment by hughsie** [comment]
> This trick is about dropping the retry traces "failed on try x of y"?

Yes and no. Genesys told us that we shouldn't be retrying the request if anything *other* than the register value is incorrect. e.g. a USB transfer failure should be fatal without retries. Not sure if it fixes the bug they saw tho.

**Comment by adamgene** [comment]
Hi all, the old issue was fixed by new hub FW. But for the new device, it has to support a new flash. Please add below into `cfi.quirk`. Very thanks.

[CFI\FLASHID_EF3011]
Name = W25X10CL
FirmwareSizeMax = 0x20000

**Comment by hughsie** [comment]
@adamgene I've added this in 0eee4d7faa0195b823865789e123851bbdab21a8 -- are there any other SPI chips you've used in other projects you'd like to add too?

**Comment by adamgene** [comment]
@hughsie Can you create a PR that I can commit these changes?

**Comment by hughsie** [comment]
@adamgene I've pushed directly to the main branch with that new W25X10CL CFI data, but if you have any more please push to a new wip/genesys/cfi or something -- you have commit ACLs.

**Pull request closed without merging**
