### PR TITLE
steelseries: Fix again the CounterpartGuid for the Aerox 3 Wireless Mouse

### PR DESCRIPTION
**Pull request by gportay**
Fixes https://github.com/fwupd/fwupd/issues/6689

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by gportay** [comment]
With this fix:

If the mouse is connected via the USB C->A cable:

```
(fwupd) gportay@archlinux ~/src/fwupd $ fwupdmgr install 4f3fac7c-981b-58cc-bb58-8a3b90f31c9c
[sudo] password for gportay: 
WARNING: This package has not been validated, it may not work properly.
Selected device: Aerox 3 Wireless Mouse
0.	Cancel
1.	1.11.4
2.	1.10.9
3.	1.9.4
Choose release [0-3]: 0
Request canceled
```

If the mouse is connected via the USB adapter:

```
(fwupd) gportay@archlinux ~/src/fwupd $ fwupdmgr install 291b0582-8d08-5714-88db-986911c744d9
WARNING: This package has not been validated, it may not work properly.
Selected device: Aerox 3 Wireless USB Receiver
0.	Cancel
1.	1.11.4
2.	1.4.2
3.	1.3.1
Choose release [0-3]: 0
Request canceled
```

**Comment by gportay** [comment]
And for the archeologists:

If the mouse is connected via the USB cable:

```
gportay@archlinux ~/src/fwupd $ fwupdmgr  --version
compile   com.hughsie.libxmlb           0.3.19
compile   org.freedesktop.Passim        0.1.7
compile   com.hughsie.libjcat           0.2.1
compile   org.freedesktop.fwupd         1.9.18
runtime   org.freedesktop.fwupd-efi     1.6
compile   org.freedesktop.gusb          0.4.8
runtime   com.hughsie.libxmlb           0.3.19
runtime   org.freedesktop.Passim        0.1.8
runtime   org.freedesktop.gusb          0.4.8
runtime   com.hughsie.libjcat           0.2.1
runtime   org.kernel                    6.8.7-arch1-2
runtime   org.freedesktop.fwupd         1.9.18

gportay@archlinux ~/src/fwupd $ fwupdmgr install 4f3fac7c-981b-58cc-bb58-8a3b90f31c9c
Selected device: Aerox 3 Wireless Mouse
0.	Cancel
1.	1.11.4
2.	1.11.4
3.	1.10.9
4.	1.9.4
5.	1.4.2
6.	1.3.1
Choose release [0-6]: 0
Request canceled
```

**Comment by d4s** [comment]
@gportay hm... I did a check locally:

1. with the directly connected mouse via USB C->USB A, with a `main` branch I have:
```
fwupdmgr install 4f3fac7c-981b-58cc-bb58-8a3b90f31c9c
Selected device: Aerox 3 Wireless Mouse
0.      Cancel
1.      1.11.4
2.      1.11.4
3.      1.10.9
4.      1.9.4
5.      1.4.2
6.      1.3.1
Choose release [0-6]: 0
Request canceled
```
2. for the connection via adapter, you choose to upgrade the adapter, not the mouse, so it looks valid according to [LVFS](https://fwupd.org/lvfs/devices/com.steelseries.Aerox-3-Wireless-USB-Receiver.firmware)

3. mouse upgrade via adapter indeed shows versions for the adapter:
```
fwupdmgr install 541b2713-d367-5240-a443-bed07f09ffbf
Selected device: Aerox 3 Wireless Mouse via USB Receiver
0.      Cancel
1.      1.11.4
2.      1.10.9
3.      1.9.4
Choose release [0-3]: 0
Request canceled
```

May I ask you to re-check please?

**Comment by d4s** [comment]
Hm... I've tried to cherry-pick the patch -- now I see that you mean. Now the F/W variants are correct in both cases and match to [LVFS](https://fwupd.org/lvfs/devices/com.steelseries.Aerox-3-Wireless-Mouse.firmware):
```
# ./fwupdmgr install 541b2713-d367-5240-a443-bed07f09ffbf
Selected device: Aerox 3 Wireless Mouse via USB Receiver
0.      Cancel
1.      1.11.4
2.      1.10.9
3.      1.9.4
Choose release [0-3]: 0
Request canceled

# fwupdmgr install 4f3fac7c-981b-58cc-bb58-8a3b90f31c9c
Selected device: Aerox 3 Wireless Mouse
0.      Cancel
1.      1.11.4
2.      1.10.9
3.      1.9.4
Choose release [0-3]: 0
Request canceled
```

Good catch! thank you!

**Review by d4s — APPROVED** [review]
Tested with the real device.

**Review by d4s — APPROVED** [review]

**Comment by gportay** [comment]
Hello @d4s, long time no see. Happy to see you around :)
 
> @gportay hm... I did a check locally:
> 
>     1. with the directly connected mouse via USB C->USB A, with a `main` branch I have:
> 
> 
> ```
> fwupdmgr install 4f3fac7c-981b-58cc-bb58-8a3b90f31c9c
> Selected device: Aerox 3 Wireless Mouse
> 0.      Cancel
> 1.      1.11.4
> 2.      1.11.4
> 3.      1.10.9
> 4.      1.9.4
> 5.      1.4.2
> 6.      1.3.1
> Choose release [0-6]: 0
> Request canceled
> ```

This is the main concern: `fwupd` must not propose the choice 1, 5 and 6 if the mouse is connected directly to the host via the USB cable. These firmware are for the adapter; and thus, not for the mouse.

This is the actual response (and what I have posted https://github.com/fwupd/fwupd/pull/7289#issuecomment-2129081033)

>     2. for the connection via adapter, you choose to upgrade the adapter, not the mouse, so it looks valid according to [LVFS](https://fwupd.org/lvfs/devices/com.steelseries.Aerox-3-Wireless-USB-Receiver.firmware)
> 
>     3. mouse upgrade via adapter indeed shows versions for the adapter:
> 
> 
> ```
> fwupdmgr install 541b2713-d367-5240-a443-bed07f09ffbf
> Selected device: Aerox 3 Wireless Mouse via USB Receiver
> 0.      Cancel
> 1.      1.11.4
> 2.      1.10.9
> 3.      1.9.4
> Choose release [0-3]: 0
> Request canceled
> ```
> 

Sure, those two points are for update through the dongle. So they do not concern the issue.

> May I ask you to re-check please?

**Review by hughsie — APPROVED** [review]
Well spotted!

**Pull request merged**
