### PR TITLE
Wip/hughsie/acquiesce composite

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]
The 2500 you came up with before; is it a fairly arbitrary guess?  I wonder if the same number should be used for all devices or if different types should have different numbers?

**Comment by hughsie** [comment]
> is it a fairly arbitrary guess

Yup. We could certainly have something like `fu_device_set_acquiesce_delay()` and quirk if you think that's useful. Better names welcome too.

**Comment by superm1** [comment]
> Yup. We could certainly have something like fu_device_set_acquiesce_delay() and quirk if you think that's useful. Better names welcome too.

Well just for future thought if this is too annoying/slow a value we find.  No rush on doing that now.

**Comment by hughsie** [comment]
We could also specify this in the config file if you think that's a good idea.

**Comment by superm1** [comment]
Config file /dropping the flag is a good idea.  Will make it easier to come up with the right values too.

**Comment by hughsie** [comment]
> Config file /dropping the flag is a good idea

Thinking about it a bit more, I think we **do** want per-device values; e.g. synaptics_mst wants a few seconds, scsi needs a new ms.

**Comment by hughsie** [comment]
Okay, reworked a bit ^^

**Review by superm1 — DISMISSED** [review]
That looks good, but I think that you should leave in the generated documentation that the default for USB and Udev devices is 2500.

**Comment by hughsie** [comment]
> that the default for USB and Udev devices is 2500

Ack, done. I also wondered about having a 50ms delay for *all* devices on the logic that it'll flush out any pending events and not actually make anything measurably slower.

**Comment by superm1** [comment]
> > that the default for USB and Udev devices is 2500
> 
> Ack, done. I also wondered about having a 50ms delay for *all* devices on the logic that it'll flush out any pending events and not actually make anything measurably slower.

Not a bad idea.

**Review by superm1 — DISMISSED** [review]

**Pull request merged**
