### PR TITLE
Hughsie/logi sight2

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@vcdmp I've not tested writing new firmware yet as I don't have firmware for the sight -- I have version 0.5.0 if that helps.

**Comment by vcdmp** [comment]
Indeed better design, let me test it out and report back. Since we do support Sight as stand alone device (e.g. not connected to RallyBar/RallyBarMini), we do need my original quirk file changes.

**Comment by hughsie** [comment]
Ahh, how do you connect the sight to the host pc without the rally bar?

**Comment by vcdmp** [comment]
> 

Sight is just another USB based camera device. So it can be used as stand alone device also. But most of the customer base uses Sight as a child device of RallyBar/RallyBarMini to get most out of Sight's features

**Comment by hughsie** [comment]
> So it can be used as stand alone device also

TIL! Agreed, it works here like that too. Patch updated.

**Comment by hughsie** [comment]
Lets merge this; it gets us closer and it was just bitrotting away.

**Pull request merged**
