### PR TITLE
trivial: Parse the CFU firwmare as surface verfmt

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]

**Comment by superm1** [comment]
When we have next ABI bump can we add to list to rename all these to something more descriptive rather than the first time they were used?

Ie VERSION_FORMAT_AA_BBCC_DD

**Comment by hughsie** [comment]
> When we have next ABI bump can we add to list to rename all these to something more descriptive

Yes, I think so too. Some are more tricky as they have bitshifts.

**Comment by hughsie** [comment]
I'm not against it -- I just struggled to some up with anything good last time. e.g. you'd need `FWUPD_VERSION_FORMAT_AAAPLUS11_BBBBB_CCCCCCCC_DDDDDDDDDDDDDDDD`

**Comment by superm1** [comment]
> I'm not against it -- I just struggled to some up with anything good last time. e.g. you'd need `FWUPD_VERSION_FORMAT_AAAPLUS11_BBBBB_CCCCCCCC_DDDDDDDDDDDDDDDD`

How about just for the easy ones then?

**Pull request merged**
