### PR TITLE
trivial: ci: arch: install gsettings-desktop-schemas

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 does it have to be in PKGBUILD too?

**Comment by superm1** [comment]
> @superm1 does it have to be in PKGBUILD too?

I don't think that's the issue; if you look at the log it's definitely getting installed now.

**Comment by hughsie** [comment]
So we merge and re-generate the container?

**Comment by superm1** [comment]
Yeah let's try that.

**Pull request merged**
