### PR TITLE
Only request the BOS descriptor when bcdUSB > 0x0200

### PR DESCRIPTION
**Pull request by hughsie**
See https://techcommunity.microsoft.com/t5/microsoft-usb-blog/usb-2-1-2-0-1-1-device-enumeration-changes-in-windows-8/ba-p/270775

Fixes https://github.com/fwupd/fwupd/issues/6871

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
Great!
Makes sense, but fixup the tests too.

**Comment by hughsie** [comment]
@Pinglinux does this break your new product? What does bcdUSB say for your new device please?

**Comment by Pinglinux** [comment]
I'll test it later today and get back to you. The bcdUSB is 0x0201 with size 2.

**Comment by hughsie** [comment]
> The bcdUSB is 0x0201

I think that's perfect then -- It shouldn't break anything.

**Pull request merged**
