### PR TITLE
vli: Ignore LIBUSB_ERROR_NO_DEVICE when rebooting VL103

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by memily — APPROVED** [review]
Tested: The error message is now "failed to wait for detach replug:device d787669ee4a103fe0b361fe31c10ea037c72f27c did not come back". 

I think fwupdtool does not know the PD is in ROM code mode because it grabs the correct Device ID in fu-device-list.c:316

Attached new log for reference, 
[vl103_fail_log.txt](https://github.com/user-attachments/files/17505566/vl103_fail_log.txt)

**Comment by hughsie** [comment]
> The error message is now "failed to wait for detach replug:device d787669ee4a103fe0b361fe31c10ea037c72f27c did not come back".

Okay, so that's better. Did you set up the `CounterpartGuid`? I forget how we did that now.

**Comment by memily** [comment]
> Okay, so that's better. Did you set up the `CounterpartGuid`? I forget how we did that now.

Yes, that made the error catching better! 

We're in the same boat paddling along next to you. I don't remember how fwupd does not show devices listed in `vli-noinst.quirk` with VID:2109, but will still see VID:2109 through lsusb. 

Adding `CounterpartGuid = USB\VID_2109&PID_0103` return the same error "failed to detach: failed to wait for detach replug: device d787669ee4a103fe0b361fe31c10ea037c72f27c did not come back". 
 
Attached for reference: [vl103_fail_log.txt](https://github.com/user-attachments/files/17515280/vl103_fail_log.txt)

**Comment by hughsie** [comment]
@memily I might have dropped the ball here -- you're still seeing the failure? Can you share what hardware this is? was USB\VID_2109&PID_0103 the runtime interface you were expecting? Do I have hardware here I can test this on locally?

**Comment by memily** [comment]
> @memily I might have dropped the ball here -- you're still seeing the failure? Can you share what hardware this is? was USB\VID_2109&PID_0103 the runtime interface you were expecting? Do I have hardware here I can test this on locally?


No worries, I have come down with a terrible cold these past two weeks, you are not the only one! 

Yes, we are still seeing the failure even after adding `CounterpartGuid = USB\VID_2109&PID_0103` to the vli-cablematters.quirk file. I wonder if this has to do with vli-noinst.quirk? 

Hardware: 
- Single PD, VL103
- YES, requires resetting device to ROM code mode to update 
- YES, requires power cycling after update to load new firmware

Firmware: USB\VID_2BD5&PID_5240 
Rom Code: USB\VID_2109&PID_0103

**Comment by hughsie** [comment]
> I wonder if this has to do with vli-noinst.quirk?

I think you might be right; we don't install the noinst one as it should be full of devboards that people are typically not going to see in the wild. I think we need to move out some of those devices out of noinst and into one of the other quirk files that *are* installed.

I see the following history for that file:

	commit 8141061a9afd47aa9eb08c922069b0a990f35c0d
	Author: memily <memily@users.noreply.github.com>
	Date:   Sat Mar 19 18:16:59 2022 +0800

	    vli: Move more devices out of the installed list
	    
	    These devices will probably never get updates from the LVFS.

	:100644 100644 fc93b2628 aa89eb6ae M    plugins/vli/vli-noinst.quirk

	commit de14bc6f0e0e2764949688fbac1d8ecbe455379f
	Author: Richard Hughes <richard@hughsie.com>
	Date:   Wed Mar 2 16:19:20 2022 +0000

	    vli: Do not probe devices with the firmware reference VID and PID
	    
	    But, leave the products with the VIA VID, but a non-default PID.
	    
	    Fixes https://github.com/fwupd/fwupd/issues/4352

**Comment by memily** [comment]
> I think you might be right; we don't install the noinst one as it should be full of devboards that people are typically not going to see in the wild. I think we need to move out some of those devices out of noinst and into one of the other quirk files that _are_ installed.

The dilemma is the VID/PIDs in noinst are necessary for devices that need to go into ROM code mode to update. Can you give me a refresher on how fwupd initializes devices with alternative VID/PID that users are not suppose to see?

Is it a variable pointed to by `FuDevicePrivate *priv` such as in line 5327, fu-device.c when `fu_device_attach_full` is called? Thanks!

**Comment by hughsie** [comment]
> Can you give me a refresher on how fwupd initializes devices with alternative VID/PID that users are not suppose to see

The way this works now for the case where a VID/PID changes is that you have quirk file like this:

    [USB/VID_RUNTIME&PID_RUNTIME]
    Plugin = vli
    GType = FuVliWhatever
    CounterpartGuid = USB/VID_BOOTLOADER&PID_BOOTLOADER

    [USB/VID_BOOTLOADER&PID_BOOTLOADER]
    Plugin = vli
    GType = FuVliWhateverCanBeDifferent

...so we do actually need the bootloader VID/PID in the normal quirks. noinst is supposed to be devboards rather than stuff that fwupd is going to see in the wild. Does that help?

**Pull request merged**
