### PR TITLE
Hughsie/ioctl emulate

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Ohh this needs a few extra things if we do https://github.com/fwupd/fwupd/pull/7975 -- I pondered quite hard a way to do the "parse into a structure" and "parse out of a structure" as part of a ->pre and ->post hook for the call to ioctl() and it got very messy very fast -- all the ioctls seem subtly different in tiny but important ways.

**Review by superm1 — APPROVED** [review]

**Comment by superm1** [comment]
> Ohh this needs a few extra things if we do #7975 -- I pondered quite hard a way to do the "parse into a structure" and "parse out of a structure" as part of a ->pre and ->post hook for the call to ioctl() and it got very messy very fast -- all the ioctls seem subtly different in tiny but important ways.

What if ioctl calls that use a different return buffer gave a hint to fwupd helper funcs where that buffer is and what it's size is?  Then the fwupd can just know to also grab that and "use" that when emulating.

**Comment by superm1** [comment]
> > Ohh this needs a few extra things if we do #7975 -- I pondered quite hard a way to do the "parse into a structure" and "parse out of a structure" as part of a ->pre and ->post hook for the call to ioctl() and it got very messy very fast -- all the ioctls seem subtly different in tiny but important ways.
> 
> What if ioctl calls that use a different return buffer gave a hint to fwupd helper funcs where that buffer is and what it's size is? Then the fwupd can just know to also grab that and "use" that when emulating.

Specifically something like this:

```
if (fu_device_has_flag(device, FWUPD_DEVICE_FLAG_EMULATION_TAG))
        fu_udev_device_set_ioctl_return(device, ADDRESS, OFFSET);
```

Then fwupd can know exactly what data to capture for the "return buffer", and when emulating can "replay" that data at the exact same offset.

**Comment by superm1** [comment]
> @superm1 how about something like this?
> 
> ```
> diff --git a/plugins/nvme/fu-nvme-device.c b/plugins/nvme/fu-nvme-device.c
> index 080034a79..283616b27 100644
> --- a/plugins/nvme/fu-nvme-device.c
> +++ b/plugins/nvme/fu-nvme-device.c
> +static gboolean
> +fu_nvme_device_ioctl_buffer_cb(FuIoctl *self,
> +			       gpointer wrapped,
> +			       guint8 *buf,
> +			       gsize bufsz,
> +			       GError **error)
> +{
> +	struct nvme_admin_cmd *cmd = (struct nvme_admin_cmd *)wrapped;
> +	memcpy(&cmd->addr, &buf, sizeof(gpointer)); /* nocheck:blocked */
> +	return TRUE;
> +}
> @@ -82,56 +142,23 @@ fu_nvme_device_submit_admin_passthru(FuNvmeDevice *self,
> 				     gsize bufsz,
> 				     GError **error)
>  {
> -	gint rc = 0;
> 	guint32 err;
> -	FuDeviceEvent *event = NULL;
> -	g_autofree gchar *event_id = NULL;
> -
> -	/* emulated */
> -	if (fu_device_has_flag(FU_DEVICE(self), FWUPD_DEVICE_FLAG_EMULATED) ||
> -	    fu_context_has_flag(fu_device_get_context(FU_DEVICE(self)),
> -				FU_CONTEXT_FLAG_SAVE_EVENTS)) {
> -		g_autofree gchar *buf_base64 = g_base64_encode(buf, bufsz);
> -		event_id = g_strdup_printf("NvmeIoctl:"
> -					   "Opcode=0x%02x,"
> -					   "Cdw10=0x%02x,"
> -					   "Cdw11=0x%02x,"
> -					   "Data=%s,"
> -					   "Length=0x%x",
> -					   cmd->opcode,
> -					   cmd->cdw10,
> -					   cmd->cdw11,
> -					   buf_base64,
> -					   (guint)bufsz);
> -	}
> -
> -	/* emulated */
> -	if (fu_device_has_flag(FU_DEVICE(self), FWUPD_DEVICE_FLAG_EMULATED)) {
> -		event = fu_device_load_event(FU_DEVICE(self), event_id, error);
> -		if (event == NULL)
> -			return FALSE;
> -		return fu_device_event_copy_data(event, "DataOut", buf, bufsz, NULL, error);
> -	}
> -
> -	/* save */
> -	if (fu_context_has_flag(fu_device_get_context(FU_DEVICE(self)),
> -				FU_CONTEXT_FLAG_SAVE_EVENTS)) {
> -		event = fu_device_save_event(FU_DEVICE(self), event_id);
> -		fu_device_event_set_data(event, "Data", buf, bufsz);
> -	}
> -
> -	/* submit admin command -- we can't use the emulation support in fu_udev_device_ioctl() as
> -	 * the buffer is specified indirectly using the cmd.addr field */
> -	if (buf != NULL)
> -		memcpy(&cmd->addr, &buf, sizeof(gpointer)); /* nocheck:blocked */
> -	if (!fu_udev_device_ioctl(FU_UDEV_DEVICE(self),
> -				  NVME_IOCTL_ADMIN_CMD,
> -				  (guint8 *)cmd,
> -				  sizeof(*cmd),
> -				  &rc,
> -				  FU_NVME_DEVICE_IOCTL_TIMEOUT,
> -				  FU_UDEV_DEVICE_IOCTL_FLAG_NONE,
> -				  error)) {
> +	gint rc = 0;
> +	g_autoptr(FuIoctl) ioctl = fu_udev_device_ioctl_new(FU_DEVICE_DEVICE(self), "NvmeIoctl");
> +
> +	fu_ioctl_add_key_u8(ioctl, "Opcode", cmd->opcode);
> +	fu_ioctl_add_key_u8(ioctl, "Cdw10", cmd->cdw10);
> +	fu_ioctl_add_key_u8(ioctl, "Cdw11", cmd->cdw11);
> +	fu_ioctl_add_buffer(ioctl, NULL, buf, bufsz, fu_nvme_device_ioctl_buffer_cb);
> +
> +	if (!fu_ioctl_execute(ioctl,
> +			      NVME_IOCTL_ADMIN_CMD,
> +			      cmd,
> +			      sizeof(*cmd),
> +			      &rc,
> +			      FU_NVME_DEVICE_IOCTL_TIMEOUT,
> +			      FU_UDEV_DEVICE_IOCTL_FLAG_NONE,
> +			      error)) {
> 		g_prefix_error(error, "failed to issue admin command 0x%02x: ", cmd->opcode);
> 		return FALSE;
> 	}
> @@ -144,9 +171,6 @@ fu_nvme_device_submit_admin_passthru(FuNvmeDevice *self,
> 	case NVME_SC_FW_NEEDS_CONV_RESET:
> 	case NVME_SC_FW_NEEDS_SUBSYS_RESET:
> 	case NVME_SC_FW_NEEDS_RESET:
> -		/* save response */
> -		if (event != NULL && buf != NULL)
> -			fu_device_event_set_data(event, "DataOut", buf, bufsz);
> 		return TRUE;
> 	default:
> 		break;
> ```

Love it.

**Comment by hughsie** [comment]
Alternate proposal in https://github.com/fwupd/fwupd/pull/7998

**Pull request closed without merging**
