### PR TITLE
cros-ec: Add progress completion when writing blocks

### PR DESCRIPTION
**Pull request by hughsie**
Also, simplify the helper that's passed to the retry function.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
This now has a progress bar that goes from 0..100 in nice linear steps.

**Comment by hughsie** [comment]
@bleungatchromium would it be okay to include public links to the Google Servo Micro Device Update v2.4.17 and v2.4.0 firmwares so I can also add a device test?

**Comment by bleungatchromium** [comment]
> @bleungatchromium would it be okay to include public links to the Google Servo Micro Device Update v2.4.17 and v2.4.0 firmwares so I can also add a device test?

Of course! Do you want me to flip those to public in LVFS by the way, or we can just link to them as is?

**Comment by hughsie** [comment]
Public would be best, but I don't know if your vendor group has the legal acl yet. I can just use the embargo ones if not.

**Review by superm1 — APPROVED** [review]

**Pull request merged**
