### PR TITLE
Fix the CI failures

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by hughsie — APPROVED** [review]

**Comment by superm1** [comment]
it seems the real problem is something with the repos, this bandaid doesn't seem to help. :/
But we also can't re-generate containers (they fail every night).

**Comment by hughsie** [comment]
Concur; `libsystemd-dev : Depends: libsystemd0 (= 249.11-0ubuntu3) but 249.11-0ubuntu3.1 is to be installed` is probably something that we can't fix, right? i.e. we just wait it out and click retry every day until it's fixed? :/

**Comment by superm1** [comment]
> Concur; `libsystemd-dev : Depends: libsystemd0 (= 249.11-0ubuntu3) but 249.11-0ubuntu3.1 is to be installed` is probably something that we can't fix, right? i.e. we just wait it out and click retry every day until it's fixed? :/

I don't see that on any of my other systems that take Ubuntu, I'm not sure why it's only happening on the CI ones.  I'm worried that CI needs a container regeneration, but containers don't want to publish for some reason still.

**Comment by hughsie** [comment]
They seem to be failing with:

    error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2454717565/Dockerfile: no such file or directory
Error: buildx failed with: error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2454717565/Dockerfile: no such file or directory

**Comment by hughsie** [comment]
I think we're hitting https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1979579 -- right?

**Comment by superm1** [comment]
Yeah. I've got a hunch it's caused by update phasing. I wonder if there's a way to turn it off.

**Comment by superm1** [comment]
@hughsie for now let's go back to using Ubuntu 20.04 for CI.  I made various cleanups to make those jobs work better, and also make `contrib/setup` more friendly for them.  We can try to go back to 22.04 by reverting [c44b9dc](https://github.com/fwupd/fwupd/pull/4763/commits/c44b9dcc056ddb389b043cb60b8c3994ef495040) sometime in the future whenever the mirror/phasing/whatever issue is sorted.

**Review by hughsie — APPROVED** [review]

**Pull request merged**
