### PR TITLE
WIP: fu-tool: Error if too many argument given

### PR DESCRIPTION
**Pull request by gportay**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

I found an something inconsistent between the help message and the number of argument; but I do not recall what... However, this is a draft and I will update the message latter.

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 I've got a neuron that's buzzing; wasn't there a reason we ignore the extra args?

**Comment by superm1** [comment]
> @superm1 I've got a neuron that's buzzing; wasn't there a reason we ignore the extra args?

Yes!  I think it's bash-completion breaks for autocompleting devices.

**Comment by gportay** [comment]
> Yes! I think it's bash-completion breaks for autocompleting devices.

What is wrong with bash autocompleting?

Does it make sense to fix the the argument parsing with a "too many argument given" error?

**Comment by superm1** [comment]
> > Yes! I think it's bash-completion breaks for autocompleting devices.
> 
> What is wrong with bash autocompleting?
> 
> Does it make sense to fix the the argument parsing with a "too many argument given" error?

Bash completion at parses get-devices output but you need to have device id and also a string describing it to know which one you are using.

We pass the combined string in for bash completion and the tools throw away the non GUID/device id output.

If you want to do this pull request, we need a better way to handle that.

**Comment by superm1** [comment]
> > We pass the combined string in for bash completion
> 
> Is there any env var we could use to know that we're being called from bash-completion and disable the (IMHO useful) checks here?

I would think we can add one

**Comment by superm1** [comment]
Mmm actually I don't know that will work. The problem isn't the bash completion - it's the use of the output for bash completion.

What about string detection from the name instead? Or instead putting everything in a quote so that it's "one" argument.

**Comment by hughsie** [comment]
> it's the use of the output for bash completion

Could we use the json output? I'm not sure I understand quite how cnf actually works....

**Comment by gportay** [comment]
It is in my TODO list, will do it after the new supported device.

**Pull request closed without merging**
