### PR TITLE
kinetic-dp: Make the matching GUID specific to the customer

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@FrancisLeeKinetic

**Comment by FrancisLeeKinetic** [comment]
Because the GUID has been updated, I have uploaded the firmware with the new GUID to LVFS.

**Comment by hughsie** [comment]
@FrancisLeeKinetic ahh yes, but doe the branch *work* for you? :)

**Comment by FrancisLeeKinetic** [comment]
Yes, it’s work.

**Pull request merged**
