### PR TITLE
Wip/hughsie/lenovo

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 I've merged this to avoid delaying the release. We can make it less broad when Lenovo tell us what's happened.

**Comment by superm1** [comment]
> @superm1 I've merged this to avoid delaying the release. We can make it less broad when Lenovo tell us what's happened.

How about making ux capsule opt in instead?

**Comment by hughsie** [comment]
> How about making ux capsule opt in instead?

I don't think any OEMs would actually opt-in and test.

**Comment by superm1** [comment]
> > How about making ux capsule opt in instead?
> 
> I don't think any OEMs would actually opt-in and test.

I seem to recall that you sent an inquiry out if anyone wants to use it and someone wanted to. If they really want to use it they can?

**Comment by hughsie** [comment]
> and someone wanted to

IIRC, that was Lenovo. :/

**Comment by superm1** [comment]
> > and someone wanted to
> 
> IIRC, that was Lenovo. :/

So all the more reason make it opt in for when they're ready! :)

**Pull request merged**
