### PR TITLE
Wip/hughsie/dos

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by chlee75 — COMMENTED** [review]
@hughsie 

Your change is good to me.

I think that it need to be validated on HP DMC dock before commit.
However I can't do it because I returned those docks to HP.
Have you ever validated it?
If not or can't, I can ask HP to validate it on real DMC dock.

And I will be out of duty on Dec 11, I will be back to work on Dec 14.

**Comment by hughsie** [comment]
@chlee -- I only have the Adicora one here -- I don't think that's DMC, right?

**Comment by chlee75** [comment]
@hughsie 
Adicora is DMC. You can validate your change on Adicora dock.

**Comment by hughsie** [comment]
> You can validate your change on Adicora dock

Thanks! Sure enough I ran the G5 device tests and these continued to pass. Thanks.

**Review by chlee75 — APPROVED** [review]
Code change is fine and you have already validated it.
Approve it.

**Review by superm1 — APPROVED** [review]

**Pull request merged**
