### PR TITLE
figure out what's going on with freebsd

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
@Asiderr, can you help?  I tried to look if the file got moved around, but I appear to be out of my depth and something that is outside of fwupd broke FreeBSD CI.

**Comment by Asiderr** [comment]
@superm1 Sure, I'll look into it by this Tuesday. I was AFK this weekend, so I need to catch up on my current work

**Comment by hughsie** [comment]
The FreeBSD CI isn't blocking, and we can disable it if required. It does seem fragile.

**Comment by hughsie** [comment]
I've disabled this for now, we can revert and fix when we know what the problem is.

**Pull request closed without merging**
