### PR TITLE
Add X-Dock and X-UsbDock update categories

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
Wait, what are we using for the other docks already supported?

**Comment by hughsie** [comment]
Either X-Device or X-Controller

**Comment by hughsie** [comment]
e.g. ` Lenovo ThinkPad Universal USB-C Dock Device Update` :/

**Comment by superm1** [comment]
That's too bad :/
I guess the new categories make sense but it would be nice to fix those up too.

**Comment by hughsie** [comment]
> but it would be nice to fix those up too.

Yes, I could do a LVFS fsck for sure. I have to be a little careful as some dock updates only target one part of it, and X-Device is probably fine for that. If it's "one component" for the dock _or composite_ then I think X-UsbDock makes sense.

**Pull request merged**
