### PR TITLE
synaptics-rmi: Ignore the ATTN reports from the hardware when reading DATA

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/1427

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 this fixes the problem for me completely, and also fixes an occasional failure to write I was experiencing. I've now done ~10 updates on my poor XPS13 in a row with zero failures -- all while dragging and clicking on the touchpad throughout.

**Comment by superm1** [comment]
Yes, helps for me on the touchpad in the XPS 7390 as well over 5 or 6 tries.

It's a little unfortunate that the touchpad is "frozen" while probing.  This is going to mean that when someone logs into their session as gnome-software-session starts up it will start fwupd and touchpad will be stuck for a short period of time.
I guess impossible to avoid unless a kernel driver read all the reports and relevant information at system bootup and exported as sysfs stuff.

**Comment by hughsie** [comment]
> Yes, helps for me on the touchpad in the XPS 7390 as well over 5 or 6 tries.

Good stuff, thanks for testing so quickly.

> It's a little unfortunate that the touchpad is "frozen" while probing. This is going to mean that when someone logs into their session as gnome-software-session starts up it will start fwupd and touchpad will be stuck for a short period of time.

How long does probing take for you?

> I guess impossible to avoid unless a kernel driver read all the reports and relevant information at system bootup and exported as sysfs stuff.

Ya, the kernel is lacking here. Maybe we can just make the ATTN duration as short as possible? I fear it's the PDT reading that takes most of the time.

**Comment by superm1** [comment]
> How long does probing take for you?

If i'm not touching the touchpad:
```
$ sudo time /usr/local/libexec/fwupd/fwupdtool get-devices --plugin-whitelist=synaptics_rmi --verbose

0.07user 0.02system 0:00.97elapsed 10%CPU (0avgtext+0avgdata 27068maxresident)k
0inputs+1576outputs (0major+3744minor)pagefaults 0swaps
```

If i'm touching it the whole time:
```
$ sudo time /usr/local/libexec/fwupd/fwupdtool get-devices --plugin-whitelist=synaptics_rmi --verbose

0.02user 0.02system 0:01.02elapsed 4%CPU (0avgtext+0avgdata 17432maxresident)k
0inputs+0outputs (0major+1051minor)pagefaults 0swaps
```

> Ya, the kernel is lacking here. Maybe we can just make the ATTN duration as short as possible? I fear it's the PDT reading that takes most of the time.

Like skip some pages that are information only?  Perhaps punt those to only read when the debug environment variable is set?

**Comment by hughsie** [comment]
1 second is a long time. I'll do some more detailed profiling and see what i can do.

**Comment by hughsie** [comment]
PROFILE: set RMA page: 0.8ms
PROFILE: scan PDT: 884.1ms
PROFILE: f01 basic query: 2.6ms
PROFILE: product id: 2.8ms
PROFILE: sendor id: 0.0ms
PROFILE: package ids: 2.6ms
PROFILE: ds4 query: 2.5ms
PROFILE: f01 query 43: 7.7ms
PROFILE: package-id: 2.5ms
PROFILE: build-id: 2.5ms
PROFILE: f34-ctrl: 2.6ms
PROFILE: bootloader id: 10.3ms
PROFILE: query is-BL: 2.5ms

**Comment by superm1** [comment]
I guess I'd say anything not strictly needed for the initial probe I'd ask if you can just read it when trying to write or validate an image. Anything not strictly needed at all only read in plugin verbose mode.

**Comment by hughsie** [comment]
I've got it down to 60ms total now. Still working on it.

**Comment by superm1** [comment]
Nice!

**Comment by hughsie** [comment]
https://github.com/fwupd/fwupd/pull/1431 should help here.

**Pull request merged**
