### PR TITLE
Wip/hughsie/yn

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@nullr0ute

**Comment by nullr0ute** [comment]
Did a scratch build to test. Overall looks good and works as expected:
```
Uploading firmware reports helps hardware vendors to quickly identify failing and successful updates on real devices.
Upload report now? (Requires internet connection) [Y|n]: m
Please enter either Y or N
y
```
Small nit is you may want to put a : at the end but works as expected.

**Comment by nullr0ute** [comment]
Also works with the follow up confirmation.

**Comment by hughsie** [comment]
> Small nit is you may want to put a : at the end

Good catch, fixed, thanks.

**Review by superm1 — APPROVED** [review]

**Pull request merged**
