### PR TITLE
trivial: Hard limit the fuzz duration to 10 minutes

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 I think the oss-fuzz service isn't respecting the fuzz-seconds any more for some reason. I guess this PR shows the `timeout-minutes: 10` is working...

**Comment by superm1** [comment]
Good.. In that case I wonder if we should just align it closer to what we want oss-fuzz timeout to be.

**Comment by hughsie** [comment]
The oss-fuzz timeout is 5 minutes, so I figured allowing 5 minutes **extra** for setup&teardown seemed plenty.

**Comment by superm1** [comment]
> The oss-fuzz timeout is 5 minutes, so I figured allowing 5 minutes **extra** for setup&teardown seemed plenty.

Hmm actually it looks like the building and teardown might take longer than I expected.
Looking at https://github.com/fwupd/fwupd/pull/3152/checks?check_run_id=2353819811
It was 7 minutes to get to the point everything was built, and then the fuzzer only ran for 3 minutes before timing out.

So maybe you want closer to 15 then.

**Review by superm1 — APPROVED** [review]

**Pull request merged**
