### PR TITLE
trivial: given https://github.com/fwupd/fwupd/issues/3652, it's seems…

### PR DESCRIPTION
**Pull request by ycheng**
trivial: put a condition on libjcat version to make the story complete.

### CODE REVIEW

**Review by superm1 — CHANGES_REQUESTED** [review]
We don't have a true runtime dependency on the newer version, it's just to avoid a particular bug.

I don't think this is a good idea to do in the runtime fields for packaging TBH.  It means that if you happen to have an older version you compile against you can't install the packages generated from that source package.

So if we're deciding to make this change in the upstream packaging the right solution here is that the **build** dependencies needs this change too.

**Comment by superm1** [comment]
BTW don't worry about the CI failure compiling against uefi capsule plugin - that isn't your fault.  https://github.com/fwupd/fwupd/pull/4184 is tracking the fix for it.

**Comment by superm1** [comment]
> We don't have a true runtime dependency on the newer version, it's just to avoid a particular bug.
> 
> I don't think this is a good idea to do in the runtime fields for packaging TBH. It means that if you happen to have an older version you compile against you can't install the packages generated from that source package.
> 
> So if we're deciding to make this change in the upstream packaging the right solution here is that the **build** dependencies needs this change too.

BTW `contrib/ci/dependencies.xml`.  Add blocks like this:

```
      <control>
        <version>(>= 0.1.4)</version>
      </control>
```

**Comment by hughsie** [comment]
> the build dependencies needs this change too

I'm not against this if all the CI targets have a new enough version. It sure makes the QA matrix smaller.

**Comment by superm1** [comment]
> > the build dependencies needs this change too
> 
> I'm not against this if all the CI targets have a new enough version. It sure makes the QA matrix smaller.

It looks like it won't happen until at least 5 days from now.

```
∙ ∙ Too young, only 2 of 7 days old
```

**Comment by ycheng** [comment]
IMHO, If we close the mentioned bug because we think libjcat has a bug, then we should just stop people from using it, or there will be an increase in the service loading.

It's not an API level runtime dependency, however, the bug in libjcat causes trouble, so we just recommend using a new version.

People can choose to ignore our recommendation, but they need to take their own risk.

**Comment by superm1** [comment]
I don't see a problem to make the packaging have this check but to bump the dependency we need CI to pass. So it needs a few days to promote new libjcat to debian testing from debian unstable so CI has it.

**Comment by ycheng** [comment]
btw, https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1943833/comments/17

**Comment by hughsie** [comment]
> btw, https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1943833/comments/17

I think you'll need to rebuild fwupd against that new libcat version if you want to see the fix.

**Comment by superm1** [comment]
The thing is they build against 0.1.3 which is what the macro  in fwupd checks.

Why would 0.1.4 building matter?

**Comment by hughsie** [comment]
> The thing is they build against 0.1.3 which is what the macro in fwupd checks

Ahh then I'm wrong, I though the LIBJCAT_CHECK_VERSION was 0.1.4.

**Comment by superm1** [comment]
Okay so we need to open back up that other issue then, there appears to likely still be a bug happening.

**Pull request closed without merging**
