### PR TITLE
Wip/hughsie/less generic

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]

**Comment by superm1** [comment]
I think this might have caused a regression.  I see this now.
```
no FuContext assigned for FuCpuDevice:
  Flags:                none
  AcquiesceDelay:       50
  HasSHSTK:             false
  HasIBT:               false
  HasTME:               false
  HasSMAP:              false

```

**Comment by superm1** [comment]
Oh; and we probably also want to hide `cpu` GUID too!

**Comment by hughsie** [comment]
> no FuContext assigned for FuCpuDevice:

I can't explain that one! Does reverting the patch remove the warning? If so, can you set critical warnings fatal and then get a backtrace please?

**Comment by hughsie** [comment]
Phew, thanks!

**Pull request merged**
