### PR TITLE
Wip/hughsie/fpc bootloader

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@jimzhang2 lets merge these few patches as it should make everything a little simpler to debug. They look okay to you?

**Comment by hughsie** [comment]
@jimzhang2 i'm also wordering if we can work around the broken firmware with a small delay, e.g.

	@@ -372,6 +372,7 @@ fu_fpc_device_detach(FuDevice *device, FuProgress *progress, GError **error)
		if (!fu_fpc_device_fw_cmd(self, FPC_CMD_BOOT0, NULL, 0, FALSE, error))
			return FALSE;
		fu_device_add_flag(device, FWUPD_DEVICE_FLAG_WAIT_FOR_REPLUG);
	+       fu_device_sleep(device, 100);
		return TRUE;
	 }

**Comment by jimzhang2** [comment]
> @jimzhang2 i'm also wordering if we can work around the broken firmware with a small delay, e.g.
> 
> ```
> @@ -372,6 +372,7 @@ fu_fpc_device_detach(FuDevice *device, FuProgress *progress, GError **error)
> 	if (!fu_fpc_device_fw_cmd(self, FPC_CMD_BOOT0, NULL, 0, FALSE, error))
> 		return FALSE;
> 	fu_device_add_flag(device, FWUPD_DEVICE_FLAG_WAIT_FOR_REPLUG);
> +       fu_device_sleep(device, 100);
> 	return TRUE;
>  }
> ```
> 
> i.e. that just blocks in the plugin for 100ms -- you could change the value to be much higher, and also experiment doing the same thing in `fu_fpc_device_attach()`

OK

**Comment by jimzhang2** [comment]
> @jimzhang2 i'm also wordering if we can work around the broken firmware with a small delay, e.g.
> 
> ```
> @@ -372,6 +372,7 @@ fu_fpc_device_detach(FuDevice *device, FuProgress *progress, GError **error)
> 	if (!fu_fpc_device_fw_cmd(self, FPC_CMD_BOOT0, NULL, 0, FALSE, error))
> 		return FALSE;
> 	fu_device_add_flag(device, FWUPD_DEVICE_FLAG_WAIT_FOR_REPLUG);
> +       fu_device_sleep(device, 100);
> 	return TRUE;
>  }
> ```
> 
> i.e. that just blocks in the plugin for 100ms -- you could change the value to be much higher, and also experiment doing the same thing in `fu_fpc_device_attach()`

This delay works fine. I will add it in the pull request. Thanks!

**Comment by hughsie** [comment]
@jimzhang2 i've added you as a contributor. If you accept that then you can push the additonal fix to my wip/hughsie/fpc-bootloader branch.

**Comment by jimzhang2** [comment]
> > @jimzhang2 i'm also wordering if we can work around the broken firmware with a small delay, e.g.
> > ```
> > @@ -372,6 +372,7 @@ fu_fpc_device_detach(FuDevice *device, FuProgress *progress, GError **error)
> > 	if (!fu_fpc_device_fw_cmd(self, FPC_CMD_BOOT0, NULL, 0, FALSE, error))
> > 		return FALSE;
> > 	fu_device_add_flag(device, FWUPD_DEVICE_FLAG_WAIT_FOR_REPLUG);
> > +       fu_device_sleep(device, 100);
> > 	return TRUE;
> >  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i.e. that just blocks in the plugin for 100ms -- you could change the value to be much higher, and also experiment doing the same thing in `fu_fpc_device_attach()`
>

**Comment by hughsie** [comment]
> There is still replug error.

Can you send me some hardware? Then I can help more easily.

**Comment by hughsie** [comment]
Lets merge this PR now as it makes it easier to debug -- even if the core issue remains.

**Comment by jimzhang2** [comment]
Hello~

Please send me the address.

Thanks!

**Comment by hughsie** [comment]
> Please send me the address.

Done by email -- thanks!

**Pull request merged**
