### PR TITLE
Only count the Microsoft hashes when getting the dbx version

### PR DESCRIPTION
**Pull request by hughsie**
HP include extra keys that means the version is higher than expected.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]
For environment variable enabled verbose mode, do you maybe want to emit the owners of skipped keys?

**Comment by hughsie** [comment]
> For environment variable enabled verbose mode

Just FWUPD_VERBOSE or something EFI specific?

**Comment by superm1** [comment]
> > For environment variable enabled verbose mode
> 
> Just FWUPD_VERBOSE or something EFI specific?

None of them seem to match this stuff, I think new variable.

**Comment by hughsie** [comment]
Something like that?? ^^

**Review by superm1 — APPROVED** [review]

**Pull request merged**
