### PR TITLE
Add support for '<name_variant_suffix>' to disambiguate some firmware

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by hughsie** [comment]
Right, all agreed. I've been back-and-forth with the maintainer of the AppStream specification about this, and this was the best name out of a bad bunch. I think it's the best we're going to get, and considering it's only going to be used for a handful of firmware files I think it's fine.

**Comment by superm1** [comment]
Why not just `name_variant`?

**Comment by hughsie** [comment]
> Why not just name_variant

As it's not clear what the front-end should do with it. From @ximion "I don't like name_variant because it really sounds like an alternative name"

**Comment by superm1** [comment]
How about `name_digressive`?  It then indicates what is a departure from the name.

**Comment by ximion** [comment]
@superm1 `name_variant` implies that this is a variant of the name, like an alternative, what this isn't about. `name_suffix` sounds like it's an unconditional suffix to the name. And `name_digressive` actually appears to be very confusing. I asked a Canadian and British speaker next to me just now, and nobody knew what this was supposed to mean (they guessed correctly, but it doesn't seem to be commonly used).
So, while the long `name_variant_suffix` is pretty ugly from a tag-name-beauty perspective, I really think that this is the most precise description of what this tag is actually supposed to be used for.

**Comment by superm1** [comment]
Yeah I agree it's not really a commonly used term.  OK one more shot: `name_aberrant`?  I really want to convey that it's just a slight modification to the name but not positional.

**Comment by ximion** [comment]
`aberrant` sounds like `erroneous`. If you don't want the positional information, `name_variant_term` would probably something that's okay too.
But conveying the position information is actually useful, I think. It might matter to the person writing the metadata where that term will actually appear.

**Comment by ximion** [comment]
`aberrant` sounds like `erroneous`. If you don't want the positional information, `name_variant_term` would probably be something that's okay too.
But conveying the position information is actually useful, I think. It might matter to the person writing the metadata where that term will actually appear.

**Comment by superm1** [comment]
> But conveying the position information is actually useful, I think. It might matter to the person writing the metadata where that term will actually appear.

Well I guess lets stick with suffix then and force it to be positional.  It will help force it's usage to stay positionally correct then.

**Comment by ximion** [comment]
@superm1 My thinking is that the variant text may be something like "for use in China". This makes sense if combined with a `<name/>` tag as "Flux Capacitor (for use in China)", but not if its prefixed or displayed as singular term somewhere.
Not sure if that's a common scenario, but I think it helps to know where this term goes. If you foresee any other uses of this tag for other scenarios, then it might be better to have a more generic name (I can't think of any though...).
One of my original suggestions was `variant_name`, that would have been more generic (and showed that it's the name of a variant).

**Comment by superm1** [comment]
Well there are obvious scenarios I know about right now:
* China specific firmware images (which is what's already mentioned)
* Different firmware for different CPU.

So for example you might have a "-U" and a "-H" CPU offered on the same SMBIOS product_name, but they have a different SMBIOS product_sku.  They would then most likely take a different system firwmare and have their own ESRT GUIDs.

They might both be called Latitude 7390, but this would disambiguate the differentiating factor about them.

So in that field if you filled it in with "-U CPU" and "-H CPU" as a suffixed you would see "Latitude 7390 -U CPU".  That isn't strictly accurate as it's system firmware that happens to be on the SKU that uses a "-U CPU".  If you just filled in "-U" then it's "Latitude 7390 -U".

So the meaning changes when you make an assumption on it being a suffix that the two words can actually be joined together and mean the right thing.  Whereas if it was just a variant description then you don't have an assumption they're put together in a particular order.

**Comment by hughsie** [comment]
With the current code, that would be rendered as `Latitude 7390 (-U)"

**Comment by superm1** [comment]
> With the current code, that would be rendered as `Latitude 7390 (-U)`

It looked to me that Variant would be it's own line in `fwupdmgr` output for `get-devices`

**Comment by hughsie** [comment]
Hmm, I guess you're right from a fwupd point of view, sorry. I meant more with the LVFS patch. If you think we should auto-suffix in fwupd too that would make sense I guess.

**Comment by superm1** [comment]
I think the fwupd approach of let the client decide whether to show it seems fine to me.

**Pull request merged**
