### PR TITLE
Use xz-compressed metadata to reduce bandwidth used by ~25%

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 if you want to test this you need to use qa.fwupd.org in the repo not cdn.fwupd.org as the server changes are not live yet

**Comment by superm1** [comment]
Can we have a fallback in case we 404?  That would let potentially old local LVFS instances work better too.

**Comment by hughsie** [comment]
>  That would let potentially old local LVFS instances work better too

I don't think we actually have any other instances; it's not something I want to encourage...

**Comment by superm1** [comment]
OK, LGTM then

**Review by superm1 — APPROVED** [review]

**Comment by gdamjan** [comment]
`lvfs-testing.conf` is in `install_data()` in meson.build, and needs to be in `configure()` to have the string replacement.

**Comment by hughsie** [comment]
https://github.com/fwupd/fwupd/pull/5253 -- will look at the lvfs-website bits now

**Comment by hughsie** [comment]
> pps. seems that url is invalid anyway:

Ohh it's a generated URL we get from the jcat file. With the fixed remote it all works.

**Pull request merged**
