### PR TITLE
Sort composite updates by the device order

### PR DESCRIPTION
**Pull request by hughsie**
I'm not sure we were sorting by release version, but it makes much more sense to sort by device order first.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by skomra** [comment]
[wacom_order_2.log](https://github.com/fwupd/fwupd/files/12480763/wacom_order_2.log)

For us, this solves the immediate issue of getting the parent to come first (it updates the main firmware first). However we don't get the second firmware (for me touch) updated because the device doesn't come back:

`
failed to wait for cleanup replug: device 3582e45d63cf1195f93ea1aa3ddb54a85ff37eac did not come back `

**Comment by hughsie** [comment]
@skomra it looks like the device didn't reboot/re-enumeate -- wasn't it supposed to?

**Comment by hughsie** [comment]
I've worked out why we were sorting by release order, and updated the code comment and commit message to match. I'll merge this, and we can work on the reboot bug as a new issue.

**Comment by skomra** [comment]
We are getting the same failure (as far as I can tell) on a production device. 

[output.txt](https://github.com/fwupd/fwupd/files/12527088/output.txt)

**Pull request merged**
