### PR TITLE
Add support for loongarch64

### PR DESCRIPTION
**Pull request by yetist**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [x] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by yetist** [comment]
My test results on [LoongArchLinux](https://loongarchlinux.org) are as follows:
```
Ok:                 30  
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
```

**Review by hughsie — APPROVED** [review]

**Review by superm1 — APPROVED** [review]
Does fwupd efi build successfully yet? There will probably be other places needed changes besides this.

**Comment by yetist** [comment]
I'll create another PR for fwupd-efi.

**Comment by yetist** [comment]
We already have the old version:
 https://loongarchlinux.org/package/?repo=extra&arch=loong64&name=fwupd-efi

**Pull request merged**
