### PR TITLE
Only suggest BIOS settings changes with --force

### PR DESCRIPTION
**Pull request by hughsie**
We're getting a bit of pushback with this feature, so lets test it for one more
release.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
Can you share more on the pushback?

**Comment by hughsie** [comment]
> Can you share more on the pushback?

Well my Twitter and https://www.phoronix.com/news/Ubuntu-No-GNOME-Device-Security -- although there seems to be genuine concerns with how well switching sleep to s2idle is going to work.

**Comment by superm1** [comment]
> > Can you share more on the pushback?
> 
> Well my Twitter and https://www.phoronix.com/news/Ubuntu-No-GNOME-Device-Security -- although there seems to be genuine concerns with how well switching sleep to s2idle is going to work.

Can we just not offer that one attribute for release perhaps until we dig in further to the specifics instead of all of them?

**Comment by hughsie** [comment]
> Can we just not offer that one attribute

Ya, that'd work too. Maybe we leave them all in and see how well this works. I'm open for advice.

**Comment by superm1** [comment]
Without some solid details of a system and kernel that breaks I expect it's a lot of "but I like s3 better ".

 Or " I don't care about the security implications of s3".

My preference is keep it all in and let's get the details out of the woodwork if there really is breakage from this.

The only AMD Lenovo systems that are going to offer this already only do s2idle...

**Comment by hughsie** [comment]
Sure, point taken, thanks.

**Pull request closed without merging**
