### PR TITLE
Wip/hughsie/ccgx attach

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by chlee75** [comment]
> static void
> fu_ccgx_hpi_device_setup_with_fw_mode (FuCcgxHpiDevice *self)
> {
> 	g_autofree gchar *name = NULL;
> 	name = g_strdup_printf ("USB-I2C Bridge (%s)",
> 				fu_ccgx_fw_mode_to_string (self->fw_mode));
> 	fu_device_set_name (FU_DEVICE (self), name);
> 	fu_device_set_logical_id (FU_DEVICE (self),
> 				  fu_ccgx_fw_mode_to_string (self->fw_mode));
> }

Why don't you about changing device name for user friendly such as below in case of ASYM FW.
 -  USB-I2C Bridge (FW1) -> USB-I2C Bridge (BACKUP FW),
-   USB-I2C Bridge (FW2) -> USB-I2C Bridge (PRIRMAY FW),

```
name = g_strdup_printf ("USB-I2C Bridge (%s)",fu_ccgx_fw_name_to_string (self->fw_mode));
fu_device_set_name (FU_DEVICE (self), name);
```
```
const gchar *
fu_ccgx_fw_name_to_string (FWMode fw_mode, FWImageType fw_imag_type)
{
	if (fw_imag_type == FW_IMAGE_TYPE_DUAL_ASYMMETRIC ) {
		if (fw_mode == FW_MODE_BOOT)
			return "BOOT FW";
		if (fw_mode == FW_MODE_FW1)
			return "BACKUP FW";
		if (fw_mode == FW_MODE_FW2)
			return "PRIMARY FW";
	} 

	if (fw_mode == FW_MODE_BOOT)
		return "BOOT";
	if (fw_mode == FW_MODE_FW1)
		return "FW1";
	if (fw_mode == FW_MODE_FW2)
		return "FW2";
	return NULL;
}

```

**Comment by chlee75** [comment]
This code needs two times fwupdmgr running to update FW1 and FW2 unlike PR#2001. Am I right?

**Comment by hughsie** [comment]
> This code needs two times fwupdmgr running to update FW1 and FW2 unlike PR#2001. Am I right?

Yup, I'm still working on that :)

**Comment by chlee75** [comment]
> Yup, I'm still working on that :)

I really appreciate it.

**Comment by hughsie** [comment]
> Why don't you think about changing device name as a user friendly such

Fixed, can you check the branch now please.

**Comment by chlee75** [comment]
> Fixed, can you check the branch now please.

I checked it. It works. Thanks a lot.

**Pull request merged**
