### PR TITLE
trivial: workaround for ERROR: Unknown variable "gcab"

### LINKED ISSUE #3270: Compiling with test support fails
data/tests/missing-hwid/meson.build:1:0: ERROR: Unknown variable "gcab".

Adding to data/tests/colorhug/meson.build the following (extracted from meson.build) resolves the issue:
gcab = find_program('gcab', required : get_option('tests'))

The Meson build system
Version: 0.55.3

Probably unrelated but also present in the logs (regardless of test feature):
WARNING: Project targeting '>=0.47.0' but tried to use feature introduced in '0.50.0': install arg in configure_file.

### PR DESCRIPTION
**Pull request by djcampello**
This change enables the use of tests in Chrome OS. Fixes #3270

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
I believe you it fixes the issue, but I don't quite understand _why_. Do you understand why that works?

**Comment by djcampello** [comment]
> I believe you it fixes the issue, but I don't quite understand _why_. Do you understand why that works?

No idea... it is pretty upsetting... That is why I tagged it as a "workaround"

**Comment by hughsie** [comment]
@djcampello on a hunch, can you try https://github.com/fwupd/fwupd/pull/3795 instead please?

**Comment by djcampello** [comment]
> @djcampello on a hunch, can you try #3795 instead please?

It still fails: `data/tests/colorhug/meson.build:1:0: ERROR: Unknown variable "gcabcmd".`

**Review by hughsie — APPROVED** [review]
Okay, lets merge this now, and I'll try to find out why it's haunted next week.

**Pull request merged**
