### PR TITLE
Do not use CoD even when advertized on non-aarch64 platforms

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/4823

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
I want to get confirmation from one OEM I've mailed a few hours ago before merging this; they are shipping test updates on the LVFS and I think that they *are* using CoD on x64

**Comment by superm1** [comment]
> I want to get confirmation from one OEM I've mailed a few hours ago before merging this; they are shipping test updates on the LVFS and I think that they _are_ using CoD on x64

If they are indeed; can you please also ask them to try to use the traditional method too to see if it still works?
Also - please find out who is the IBV.  If need be we could try to suss out IBVs for opt-in/opt-out, but hopefully we don't go that direction.

**Comment by hughsie** [comment]
> If they are indeed; can you please also ask them to try to use the traditional method too to see if it still works?

OEM has confirmed they actually don't *want* to use CoD.

**Comment by superm1** [comment]
> OEM has confirmed they actually don't want to use CoD.

Can you note here who the IBV is?  We should be aware of this for if/when we try to enable it again on x86.

**Comment by hughsie** [comment]
I'll ask.

**Pull request merged**
