### PR TITLE
trivial: Move the CI Win32 build to Fedora 40

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]

**Comment by superm1** [comment]
Hmm doesn't seem to work still.
image

**Comment by superm1** [comment]
It's improved, but still seeing some funny stuff.

```
PS C:\Program Files (x86)\fwupd\bin> .\fwupdtool.exe get-devices

((x86)\fwupd\bin\fwupdtool.exe:46880): FuDebug-WARNING **: 12:52:33.634: RegCreateKeyExA failed [187]
Loading…                 [ -                                     ]
Failed to load remotes: Failed to write file “C:\Users\mlimonci\fwupd\var\cache\fwupd\metainfo.xmlb”: ftruncate() failed: Permission denied
PS C:\Program Files (x86)\fwupd\bin> rm C:\Users\mlimonci\fwupd\var\cache\fwupd\metainfo.xmlb
PS C:\Program Files (x86)\fwupd\bin> .\fwupdtool.exe get-devices

((x86)\fwupd\bin\fwupdtool.exe:51472): FuDebug-WARNING **: 12:53:26.041: RegCreateKeyExA failed [187]
Loading…                 [*                                      ]17:53:26.156 FuContext            Failed to load quirks: Failed to write file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": ftruncate() failed: Permission denied
Loading…                 [*                                      ]17:53:26.179 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.210 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.240 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.265 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.288 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.313 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.331 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.357 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.378 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.404 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.425 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.443 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.467 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.488 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.505 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.523 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.545 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
17:53:26.564 FuQuirks             failed to build silo: Failed to open file "C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb": Permission denied
Loading…                 [**                                     ]
Failed to load AppStream data: cannot create metadata.xmlb: Failed to write file “C:\Users\mlimonci\fwupd\var\cache\fwupd\metadata.xmlb”: ftruncate() failed: Permission denied
PS C:\Program Files (x86)\fwupd\bin> rm C:\Users\mlimonci\fwupd\var\cache\fwupd\metainfo.xmlb
PS C:\Program Files (x86)\fwupd\bin> rm C:\Users\mlimonci\fwupd\var\cache\fwupd\quirks.xmlb
PS C:\Program Files (x86)\fwupd\bin> .\fwupdtool.exe get-devices

((x86)\fwupd\bin\fwupdtool.exe:55488): FuDebug-WARNING **: 12:53:46.234: RegCreateKeyExA failed [187]
Loading…                 [**                                     ]
Failed to load AppStream data: cannot create metadata.xmlb: Failed to write file “C:\Users\mlimonci\fwupd\var\cache\fwupd\metadata.xmlb”: ftruncate() failed: Permission denied
PS C:\Program Files (x86)\fwupd\bin> rm C:\Users\mlimonci\fwupd\var\cache\fwupd\metadata.xmlb
PS C:\Program Files (x86)\fwupd\bin> .\fwupdtool.exe get-devices
```

**Comment by hughsie** [comment]
I assume it's getting `EACCES` from `_chsize`  i.e. `if the specified file is read-only or the specified file is locked against access` -- I'm a complete newbie with windows debugging unfortunately. If you set the cachedir using an env variable (e.g. somewhere in `C:/temp...` do you get the same thing? I can debug a bit more tomorrow.

**Comment by hughsie** [comment]
I think it's this https://gitlab.gnome.org/GNOME/glib/-/issues/3340

**Comment by superm1** [comment]
Nice!

**Comment by hughsie** [comment]
I think the "fix" is https://github.com/hughsie/libxmlb/pull/177

**Comment by hughsie** [comment]
@superm1 seems to work here now, but in wine and proper Windows.

**Review by superm1 — APPROVED** [review]

**Pull request merged**
