### PR TITLE
Fix detection of 8Bitdo wireless usb adapter

### PR DESCRIPTION
**Pull request by javanthropus**
Limits copying the get version response payload to the size of the out buffer.
Devices that return a larger payload pack the necessary version information at the beginning of the payload.

Fixes: #1661

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
Can you please submit this first against master and then we can backport it to older branches?

**Comment by javanthropus** [comment]
I'll do that.  Should I close this PR and start a new one or edit this one in place?

**Comment by superm1** [comment]
I don't think it will let you change the target in a PR, you probably need to open a new one.  Also, make sure that on master you run `contrib/setup` before you commit, we've got some new stuff there that will require some pre-commit rules to pass and it will help test and format your code so it passes CI.

**Comment by javanthropus** [comment]
I'll cherry pick my change over to the master branch and open a new PR then.  Thanks!

**Pull request closed without merging**
