### PR TITLE
Restore check-unused.py in CI

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
@hughsie can you add your QC commits to this branch (unless you have another already)?

**Comment by hughsie** [comment]
Ohh good catch. https://github.com/fwupd/fwupd/pull/6972 is the other fixups.

**Comment by superm1** [comment]
Ok. I was expecting this branch to fail, but it's not so maybe the variable needs to be exported.

**Comment by superm1** [comment]
> Ok. I was expecting this branch to fail, but it's not so maybe the variable needs to be exported.

Yup that was it.  OK, so I've rebased on your branch.  It should pass now.

**Review by hughsie — APPROVED** [review]

**Pull request merged**
