### PR TITLE
Add support for synaptics prometheus 009a

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
@vhuag something I noticed is the existing quirk file has:
```
[USB\VID_06CB&PID_00A9]
```

Whereas this device that users are reporting is:
```
[USB\VID_06CB&PID_009A]
```

Those are too close to similar.  I need to see if this was just a typo initially.  Can you check if 00A9 is a real device and should be in the quirk file?

**Comment by superm1** [comment]
It seems this alone isn't enough to make the device work.

**Comment by vhuag** [comment]
hello
0x9a is an older sensor that can't be updated by the current plugin, and adding the quirk file isn't enough by the way.

**Comment by superm1** [comment]
> hello
> 0x9a is an older sensor that can't be updated by the current plugin, and adding the quirk file isn't enough by the way.

Thanks for confirming that.

**Pull request closed without merging**
