### PR TITLE
Add FuProgress to ->startup() and ->coldplug()

### PR DESCRIPTION
**Pull request by hughsie**
This allows us to profile the daemon startup so we can find any plugins
taking an inordinate amount of time to start.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
Shouldn't this be an ABI bump?

**Comment by hughsie** [comment]
> Shouldn't this be an ABI bump?

Ya, I just wanted your general approval of the concept before doing all that. With that patch and a little follow up one, I get an output of:

    ../src/fu-engine.c:6856:load-engine [548.71ms]:
        ../src/fu-engine.c:6228:load-plugins [30.91ms]:
            ../src/fu-engine.c:6209:load [30.82ms]:
                ../src/fu-engine.c:6182:/home/hughsie/.root/lib64/fwupd-plugins-6/libfu_plugin_tpm.so [1.57ms]:
                    ../src/fu-engine.c:6182:open [1.55ms]
                ../src/fu-engine.c:6182:/home/hughsie/.root/lib64/fwupd-plugins-6/libfu_plugin_modem_manager.so [3.85ms]:
                    ../src/fu-engine.c:6182:open [3.81ms]
                ../src/fu-engine.c:6182:/home/hughsie/.root/lib64/fwupd-plugins-6/libfu_plugin_flashrom.so [1.22ms]:
                    ../src/fu-engine.c:6182:open [1.18ms]
        ../src/fu-engine.c:6856:load-quirks [7.78ms]
        ../src/fu-engine.c:6856:load-hwinfo [3.94ms]
        ../src/fu-engine.c:6856:load-appstream [3.97ms]
        ../src/fu-engine.c:6856:backend-setup [4.60ms]
        ../src/fu-engine.c:6856:plugins-init [3.17ms]
        ../src/fu-engine.c:6856:hwid-quirks [3.61ms]
        ../src/fu-engine.c:5382:plugins-setup [8.36ms]:
            ../plugins/flashrom/fu-plugin-flashrom.c:277:flashrom [3.60ms]:
            ../src/fu-engine.c:5382:upower [1.16ms]
        ../src/fu-engine.c:5409:plugins-coldplug [104.74ms]:
            ../plugins/amt/fu-plugin-amt.c:437:amt [27.19ms]:
                ../plugins/amt/fu-plugin-amt.c:437:create-context [12.37ms]
                ../plugins/amt/fu-plugin-amt.c:437:get-version [8.49ms]
                ../plugins/amt/fu-plugin-amt.c:437:add-device [4.04ms]
            ../plugins/cpu/fu-plugin-cpu.c:26:cpu [5.85ms]:
            ../src/fu-engine.c:5409:superio [3.60ms]
            ../plugins/uefi-dbx/fu-plugin-uefi-dbx.c:27:uefi_dbx [7.82ms]:
                ../plugins/uefi-dbx/fu-plugin-uefi-dbx.c:27:probe [2.68ms]
            ../plugins/uefi-capsule/fu-plugin-uefi-capsule.c:820:uefi_capsule [58.19ms]:
                ../plugins/uefi-capsule/fu-plugin-uefi-capsule.c:820:find-esp [19.97ms]
                ../plugins/uefi-capsule/fu-plugin-uefi-capsule.c:820:check-bitlocker [8.31ms]
                ../plugins/uefi-capsule/fu-plugin-uefi-capsule.c:820:add-devices [27.85ms]
        ../src/fu-engine.c:6792:backend-coldplug [362.65ms]:
            ../src/fu-engine.c:6792:usb [188.84ms]
            ../src/fu-udev-backend.c:174:udev [173.75ms]:
                ../src/fu-udev-backend.c:142:pci [152.58ms]:
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:00.0 [5.02ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:02.0 [10.62ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:04.0 [4.99ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:08.0 [4.49ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:12.0 [4.95ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:14.0 [4.98ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:14.2 [4.51ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:14.3 [4.95ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:16.0 [5.07ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1b.0 [4.94ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1b.0/0000:02:00.0 [5.01ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0 [4.98ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0 [4.97ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0/0000:05:00.0 [5.01ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0/0000:05:00.0/0000:06:00.0 [5.00ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0/0000:05:01.0 [5.02ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0/0000:05:02.0 [5.00ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0/0000:05:02.0/0000:2c:00.0 [5.00ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0/0000:05:04.0 [4.99ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.7 [4.94ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.7/0000:54:00.0 [4.96ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1d.0 [4.96ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1d.0/0000:55:00.0 [4.94ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1f.0 [16.88ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1f.3 [4.98ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1f.4 [4.91ms]
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1f.5 [4.52ms]
                ../src/fu-udev-backend.c:142:i2c [1.40ms]:
                ../src/fu-udev-backend.c:142:block [2.34ms]:
                ../src/fu-udev-backend.c:142:thunderbolt [12.81ms]:
                    ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0/0000:05:00.0/0000:06:00.0/domain0/0-0 [12.53ms]
                ../src/fu-udev-backend.c:142:msr [1.47ms]:

...which is hugely useful.

**Comment by superm1** [comment]
> > Shouldn't this be an ABI bump?
> 
> Ya, I just wanted your general approval of the concept before doing all that. With that patch and a little follow up one, I get an output of:
> 
> ```
> ../src/fu-engine.c:6856:load-engine [548.71ms]:
>     ../src/fu-engine.c:6228:load-plugins [30.91ms]:
>         ../src/fu-engine.c:6209:load [30.82ms]:
>             ../src/fu-engine.c:6182:/home/hughsie/.root/lib64/fwupd-plugins-6/libfu_plugin_tpm.so [1.57ms]:
>                 ../src/fu-engine.c:6182:open [1.55ms]
>             ../src/fu-engine.c:6182:/home/hughsie/.root/lib64/fwupd-plugins-6/libfu_plugin_modem_manager.so [3.85ms]:
>                 ../src/fu-engine.c:6182:open [3.81ms]
>             ../src/fu-engine.c:6182:/home/hughsie/.root/lib64/fwupd-plugins-6/libfu_plugin_flashrom.so [1.22ms]:
>                 ../src/fu-engine.c:6182:open [1.18ms]
>     ../src/fu-engine.c:6856:load-quirks [7.78ms]
>     ../src/fu-engine.c:6856:load-hwinfo [3.94ms]
>     ../src/fu-engine.c:6856:load-appstream [3.97ms]
>     ../src/fu-engine.c:6856:backend-setup [4.60ms]
>     ../src/fu-engine.c:6856:plugins-init [3.17ms]
>     ../src/fu-engine.c:6856:hwid-quirks [3.61ms]
>     ../src/fu-engine.c:5382:plugins-setup [8.36ms]:
>         ../plugins/flashrom/fu-plugin-flashrom.c:277:flashrom [3.60ms]:
>         ../src/fu-engine.c:5382:upower [1.16ms]
>     ../src/fu-engine.c:5409:plugins-coldplug [104.74ms]:
>         ../plugins/amt/fu-plugin-amt.c:437:amt [27.19ms]:
>             ../plugins/amt/fu-plugin-amt.c:437:create-context [12.37ms]
>             ../plugins/amt/fu-plugin-amt.c:437:get-version [8.49ms]
>             ../plugins/amt/fu-plugin-amt.c:437:add-device [4.04ms]
>         ../plugins/cpu/fu-plugin-cpu.c:26:cpu [5.85ms]:
>         ../src/fu-engine.c:5409:superio [3.60ms]
>         ../plugins/uefi-dbx/fu-plugin-uefi-dbx.c:27:uefi_dbx [7.82ms]:
>             ../plugins/uefi-dbx/fu-plugin-uefi-dbx.c:27:probe [2.68ms]
>         ../plugins/uefi-capsule/fu-plugin-uefi-capsule.c:820:uefi_capsule [58.19ms]:
>             ../plugins/uefi-capsule/fu-plugin-uefi-capsule.c:820:find-esp [19.97ms]
>             ../plugins/uefi-capsule/fu-plugin-uefi-capsule.c:820:check-bitlocker [8.31ms]
>             ../plugins/uefi-capsule/fu-plugin-uefi-capsule.c:820:add-devices [27.85ms]
>     ../src/fu-engine.c:6792:backend-coldplug [362.65ms]:
>         ../src/fu-engine.c:6792:usb [188.84ms]
>         ../src/fu-udev-backend.c:174:udev [173.75ms]:
>             ../src/fu-udev-backend.c:142:pci [152.58ms]:
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:00.0 [5.02ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:02.0 [10.62ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:04.0 [4.99ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:08.0 [4.49ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:12.0 [4.95ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:14.0 [4.98ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:14.2 [4.51ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:14.3 [4.95ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:16.0 [5.07ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1b.0 [4.94ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1b.0/0000:02:00.0 [5.01ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0 [4.98ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0 [4.97ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0/0000:05:00.0 [5.01ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0/0000:05:00.0/0000:06:00.0 [5.00ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0/0000:05:01.0 [5.02ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0/0000:05:02.0 [5.00ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0/0000:05:02.0/0000:2c:00.0 [5.00ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0/0000:05:04.0 [4.99ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.7 [4.94ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.7/0000:54:00.0 [4.96ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1d.0 [4.96ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1d.0/0000:55:00.0 [4.94ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1f.0 [16.88ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1f.3 [4.98ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1f.4 [4.91ms]
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1f.5 [4.52ms]
>             ../src/fu-udev-backend.c:142:i2c [1.40ms]:
>             ../src/fu-udev-backend.c:142:block [2.34ms]:
>             ../src/fu-udev-backend.c:142:thunderbolt [12.81ms]:
>                 ../src/fu-udev-backend.c:142:/sys/devices/pci0000:00/0000:00:1c.0/0000:04:00.0/0000:05:00.0/0000:06:00.0/domain0/0-0 [12.53ms]
>             ../src/fu-udev-backend.c:142:msr [1.47ms]:
> ```
> 
> ...which is hugely useful.

Ah that's great indeed!  Yeah this approach makes sense to me.  While you're bumping ABI, don't forget to look for any opportunities to drop `_full` functions and the like too.

**Comment by hughsie** [comment]
>  While you're bumping ABI

Okay, rebased -- I'm tempted to remove the `_common_` name from a lot of functions, e.g. fu_common_vercmp_full -> fu_vercmp or fu_version_compare might be ben better.

**Comment by superm1** [comment]
> >  While you're bumping ABI
> 
> Okay, rebased -- I'm tempted to remove the `_common_` name from a lot of functions, e.g. fu_common_vercmp_full -> fu_vercmp or fu_version_compare might be ben better.

No complaints here on that

**Pull request merged**
