### PR TITLE
Wip/hughsie/update message

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by chlee75** [comment]
@hughsie 

I have tested with wip/hughsie/update_message and the result is same as before.
I attached cab file and fwupd log and screen shot.
Please check it.

[Lenovo-ifx-url-short-VIKING_DOCK-V0.0.4.1.zip](https://github.com/fwupd/fwupd/files/8338928/Lenovo-ifx-url-short-VIKING_DOCK-V0.0.4.1.zip)

1. gnome-software
  There are no update message and update image after firmware update.
[fwupd-updatemsg-gnome-software.log](https://github.com/fwupd/fwupd/files/8338908/fwupd-updatemsg-gnome-software.log)

2. gnome-firmware
   There is update message but update image is not shown after firmware update.
[fwupd-updatemsg-gnome-firmware.log](https://github.com/fwupd/fwupd/files/8338911/fwupd-updatemsg-gnome-firmware.log)

3. fwupdmgr
  There is update message but update image is not shown after firmware update.
   $fwupdmgr install Lenovo-ifx-url-short-VIKING_DOCK-V0.0.4.1.cab
   [fwupd-cli.log](https://github.com/fwupd/fwupd/files/8338912/fwupd-cli.log)
  
gnome-software-1

gnome-software-2

gnome-firmware-2

gnome-firmware-3

cli-update-message

**Comment by hughsie** [comment]
> gnome-software
> There are no update message and update image after firmware update.

Known needs a more in-depth fix.

> gnome-firmware
> There is update message but update image is not shown after firmware update.

Fixed in the wip/hughsie/gtk4 branch (with some test data!):

Screenshot from 2022-03-23 15-46-20

> fwupdmgr
> There is update message but update image is not shown after firmware update.
> $fwupdmgr install Lenovo-ifx-url-short-VIKING_DOCK-V0.0.4.1.cab

Right; there's no practicable way of showing the image on the console, so just the message is expected.

**Comment by chlee75** [comment]
> Known needs a more in-depth fix.

  OK. Let me know if you have any update. gnome-software is default package so it need to fix.

> Fixed in the wip/hughsie/gtk4 branch (with some test data!):

  I have tested wip/hughsie/gtk4 with Lenovo Viking Dock.
  Update Image is not displayed and gnome-firmware program exit with crash message. 
[gnome-firmware-crash.log](https://github.com/fwupd/fwupd/files/8339903/gnome-firmware-crash.log)
  
  Please check the log.

  Could you share cab file that you tested so that I compare it with my cab file?
  
  Do I need to add any flag to plugin for update message and imag?

**Comment by chlee75** [comment]
> Is that with wip/hughsie/gtk4 branch? If so, can you get a backtrace please?

I attached fwupd log and cab file and source code that I merge new ccgx to gtk4.
After I applied fu_device_inhibit () in case of update on disconnect. There is no gnome-firmware crash.
fu-ccgx-dmc-device.c 
`	if (manual_replug) {
		fu_device_add_flag(device, FWUPD_DEVICE_FLAG_NEEDS_ACTIVATION);
		fu_device_inhibit(device,
				  "update-pending",
				  "A pending update will be completed next time the device "
				  "is unplugged from your computer");
`
but update image is still no shown in gnome-firmware.
<client>update-action</client> also included in the cab file.
I applied same update message and update image url in the cab file that you shared.

[fwupd-gtk4.log](https://github.com/fwupd/fwupd/files/8346673/fwupd-gtk4.log)

[fwupd-wip-hughsie-gtk4-new-ccgx.zip](https://github.com/fwupd/fwupd/files/8346689/fwupd-wip-hughsie-gtk4-new-ccgx.zip)

[Lenovo-ifx-url-3-VIKING_DOCK-V0.0.4.1.cab.zip](https://github.com/fwupd/fwupd/files/8346695/Lenovo-ifx-url-3-VIKING_DOCK-V0.0.4.1.cab.zip)

gnome-firmware-decription

gnome-firmware-gtk4-new-ccgx

**Comment by hughsie** [comment]
Hey @chlee75 that's not the correct gnome-firmware. Do you want to try with the packages here? https://people.freedesktop.org/~hughsient/fedora/32/ -- they're for Fedora 36 so maybe a flatpak might be easier for you.

**Comment by chlee75** [comment]
@hughsie 

I remove some pictures and a cab file due to a Lenovo security reason.

> Hey @chlee75 that's not the correct gnome-firmware. Do you want to try with the packages here?

I will try it.

**Comment by chlee75** [comment]
@hughsie 

>>Hey @chlee75 that's not the correct gnome-firmware. Do you want to try with the packages here?
>I will try it.

I tried to install a new gnome-firmware from https://people.freedesktop.org/~hughsient/fedora/32/
But I get the error message below. Please check it.

[gnome-firmware-install-error.txt](https://github.com/fwupd/fwupd/files/8360606/gnome-firmware-install-error.txt)

**Pull request merged**
