### PR TITLE
logitech-bulkcontroller: Only move the progressbar forwards when writing

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by vcdmp** [comment]
Still seeing issues after applying this patch. FuProgress throws errors with both fu_progress_set_percentage_full() & fu_progress_set_percentage() APIs. Full log attached.
[console_output.txt](https://github.com/fwupd/fwupd/files/8875090/console_output.txt)

**Comment by hughsie** [comment]
@vcdmp can you build and install with the extra 3 commits on this branch please, and then also add "FWUPD_LOGITECH_BULKCONTROLLER_VERBOSE=1" before the fwupdtool line please. Then can I have the entire debug log again please. Thanks!

**Comment by vcdmp** [comment]
Thanks Richard. Here you go: 
[FuProgress_0610_10.txt](https://github.com/fwupd/fwupd/files/8880807/FuProgress_0610_10.txt)
.

**Comment by hughsie** [comment]
Ahh! You're using fwupdtool! That explains why I couldn't reproduce using the daemon. I know where the bug is (we're re-using the FuProgress in the wrong way in fu-tool.c) and I'll fix on Monday.

**Comment by vcdmp** [comment]
Thanks Richard for all your help. Have a nice weekend.

**Comment by hughsie** [comment]
@vcdmp try that?

**Comment by vcdmp** [comment]
No more errors.

**Review by vcdmp — APPROVED** [review]

**Pull request merged**
