### PR TITLE
Add a helper to get a GUsbDevice from a FuUdevDevice

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [x] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
100.0% untested.

**Review by superm1 — COMMENTED** [review]
I would think you want to return the FuUSBDevice associated not the FuUSBDevice, no?

**Comment by hughsie** [comment]
> I would think you want to return the FuUSBDevice associated not the GUSBDevice, no?

I think that would be misleading and possibly lead to trouble; what happens if we added that FuUsbDevice to the engine with a different context? The life-cycle stuff is all wrong.

**Comment by superm1** [comment]
I guess it depends on what you want to do with the helper :)

**Review by superm1 — COMMENTED** [review]
I'd still like to see how this is to be used.  Normally I don't think we really want to have plugins _directly_ interacting with gusb.

**Comment by hughsie** [comment]
Ack, agree. I don't want it to be a workaround for wait-for-replug for instance.

**Comment by hughsie** [comment]
In the example given by Logitech, I think it makes sense to add this.

**Comment by superm1** [comment]
But so what does the plugin do with this?

I am still not convinced we want to normalize plugins to directly interact with `GUsbDevice` instead of `FuUsbDevice`.
If the lifecycle is wrong, should the relationship be created by the engine between the two and put into metadata?  Parent/child or sibling or something?

**Comment by hughsie** [comment]
>  If the lifecycle is wrong

So my thinking here is that we should never add either the `GUdevDevice` from `fu_usb_device_find_udev_device()` or the `GUsbDevice` from `fu_udev_device_find_usb_device()` as a `FuDevice`-derived device. i.e. we'd have the FuUdevDevice as the lifecycled device and then we'd get the `GUsbDevice` **every single time** we needed to do any kind of bulk/control transfer and not store it in any kind of private state, i.e. it's only valid for the lifetime of the current function, not matching the lifecycle of the FuUdevDevice.

Would you be more comfortable if we enforced that you couldn't use a `fu_udev_device_find_usb_device` as the input to `fu_usb_device_new()`? Maybe we could check if the context is different, and do a critical warning or assert or something?

**Comment by hughsie** [comment]
> if we enforced that you couldn't use a fu_udev_device_find_usb_device as the input to fu_usb_device_new

I added that.

**Review by superm1 — APPROVED** [review]

**Pull request merged**
