### PR TITLE
Drop UEFI UX capsule support

### PR DESCRIPTION
**Pull request by superm1**
Potentially controversial, but I suppose with all the cleanups of dead and re-used code lately this is worth throwing on the chopping block to maybe take out too.

- [x] Code fix

### CODE REVIEW

**Comment by superm1** [comment]
And possibly close https://github.com/fwupd/fwupd/issues/844 too

**Comment by hughsie** [comment]
Are you sure no vendor uses it? Iirc, Intel were the ones complaining when it was broken...

**Comment by superm1** [comment]
I'm not 100% sure, I was only going off of what you were saying around it in the past with no one using it 😜 

Can you ask around on it?  It's a lot of code, it would be nice to not carry so much if it's really not needed.

**Comment by hughsie** [comment]
> Can you ask around on it?

Phoenix cared very much, but I don't know any OEM is actually using an updater that relies on it. I can ask on fwupd and lvfs-announce mailing lists if you think that's a good idea.

**Comment by hughsie** [comment]
> I can ask on fwupd and lvfs-announce mailing lists if you think that's a good idea

I did that. Lenovo are planning to use it from next year onwards. Sorry dude!

**Pull request closed without merging**
