### PR TITLE
ccgx: add Lenovo USB-C dock to the quirk file

### PR DESCRIPTION
**Pull request by chlee75**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [x] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by chlee75** [comment]
@hughsie 

Could you add a999153 (GitHub ID) who works for Wistron to this pull request?

**Comment by hughsie** [comment]
@chlee75 you you use an @ before the username then the user gets emailed about the change, e.g. @a999153 -- or do you want me to add @a999153 as a committer for this kind of data?

**Review by hughsie — APPROVED** [review]

**Comment by chlee75** [comment]
@hughsie 

I needed the review from Lenovo (mrhpearson) and Wistron (a999153) for this pull request even though my changes come from Lenovo.
Anyway, it has already merged with the main.
I will let Lenovo and Wistron know that this change has been merged.

Thanks.

**Comment by mrhpearson** [comment]
It all looks awesome - thanks @chlee75 !

**Comment by chlee75** [comment]
@mrhpearson 
I appreciate it.

**Comment by bdaase** [comment]
This got merged nearly 3 month ago but I still can't find the corresponding firmware on https://fwupd.org/lvfs/. Can we still expect the firmware to come available at some point?

**Comment by a999153** [comment]
@bdaase The firmware is already verified under embargo stage, currently OEM Linux team are under verifying.
It'll change to stable state after OEM team finished their verification.

**Pull request merged**
