### PR TITLE
Wip/hughsie/dell dock regression

### PR DESCRIPTION
**Pull request by hughsie**
Only lightly tested as I only have the DVT2.2 dock here.

### CODE REVIEW

**Comment by superm1** [comment]
> Only lightly tested as I only have the DVT2.2 dock here.

Is the plugin rejecting this board ID from further stuff and from flashing?  I forget if that hardware build was supposed to be blocked.

**Comment by hughsie** [comment]
https://fwupd.org/lvfs/firmware/3874 is still in embargo -- is that what you want me to try?

**Comment by superm1** [comment]
> https://fwupd.org/lvfs/firmware/3874 is still in embargo -- is that what you want me to try?

Yes

**Comment by hughsie** [comment]
Okay, that fails. Will need to do some more thinking here.

**Comment by superm1** [comment]
I haven't gotten to mine yet today to try this PR, logs from failure for insight?

**Comment by hughsie** [comment]
>  I forget if that hardware build was supposed to be blocked

FwupdError: Device Package level of Dell dock [b5a854df85ab30fff48e4365ec7ad2249c90806e] does not currently allow updates

But, I have another, simpler, idea.C=can I reference the firmware i embargo for the device-tests?

**Comment by hughsie** [comment]
Simpler idea here: https://github.com/fwupd/fwupd/pull/1979

**Comment by superm1** [comment]
> But, I have another, simpler, idea.C=can I reference the firmware i embargo for the device-tests?

Yeah, it's going to be stable eventually and if something newer makes it to stable adjusting device tests is a few line change.

**Comment by superm1** [comment]
> FwupdError: Device Package level of Dell dock [b5a854df85ab30fff48e4365ec7ad2249c90806e] does not currently allow updates

Hmm, that sounds like it might be that the board level is too old indeed.  Is this the board I sent you or was it an internal one?

**Comment by hughsie** [comment]
>  Is this the board I sent you or was it an internal one

This is the prototype DVT one. I'm still waiting for the "release" device from Karl.

**Comment by superm1** [comment]
Hmm, I just looked through my records, I sent a `DVT2.3-C2`.  Do you have that handy?  That's really close to production and should take all the production payloads.

**Comment by hughsie** [comment]
> I sent a DVT2.3-C2

I have that here.

**Comment by superm1** [comment]
Oh, you said DVT2.2 above

**Comment by hughsie** [comment]
> Oh, you said DVT2.2 above

Sorry, it says:

    Base: DVT2.2
    Module: DVT2.2

then there's a smaller label with:

    DP/N SLM-DVT2.3-C2 X02-03

Randomly I can install the updates now. Weird.

**Comment by superm1** [comment]
> Randomly I can install the updates now. Weird.

Remember it's got the delayed activation stuff.  If it's not been unplugged after an update you either need to manually call activate or unplug it.

**Pull request closed without merging**
