### PR TITLE
Use an external gcab binary when cross building

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/6325

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 this is two order of magnitude less work than duplicate defining all the deps `native: true` -- and I *think* is the pragmatic fix.

**Comment by superm1** [comment]
> @superm1 this is two order of magnitude less work than duplicate defining all the deps `native: true` -- and I _think_ is the pragmatic fix.

IDK, how much duplication are you talking?  The way it's done right now feels like weird tech debt to me that we're going to scratch our heads on 5 years from now.

**Comment by hughsie** [comment]
IIUC, that we need every dep used in libfwupdplugin also available is the cross-root (e.g. libxmlb, gio, jcat etc) as we do in the buildroot. The alternative is we use an emulator (e.g. wine is why the win32 build works). I'm not sure I care that much about crossroots, and maybe using the standalone package of libgcab is a pragmatic workaround.

**Comment by superm1** [comment]
> IIUC, that we need every dep used in libfwupdplugin also available is the cross-root (e.g. libxmlb, gio, jcat etc) as we do in the buildroot. The alternative is we use an emulator (e.g. wine is why the win32 build works). I'm not sure I care that much about crossroots, and maybe using the standalone package of libgcab is a pragmatic workaround.

How do all the other tests work right now?  Surely lots of other libfwupdplugin self tests also explode for the same dependency reason, **not just** `gcab`.  So if it really is limited to `gcab` seems like it should be a more narrow problem scope to solve than everything else.

There's always using `qemu` and `binfmt_misc` for cross roots with tests.

**Comment by hughsie** [comment]
> How do all the other tests work right now

Hmm. Good point.

**Comment by hughsie** [comment]
>>  How do all the other tests work right now
> Hmm. Good point.

I think the only answer for this is that they don't -- I guess for cross builds they're turned off with -Dtests=false -- I don't think they make sense for cross builds anyway -- it's not like you're running *on* the platform anyway.

I spent a bit of time making everything duplicate -- i.e. compiling twice -- once for native and once for target -- and I don't like it at all. I guess the other options we have are:

 * Re-re-implement gcab in python -- which I did a long long time ago for RHEL 6: https://python-cabarchive.readthedocs.io/en/latest/index.html
 * Stop generating the cab archives which we only seem to use for tests.... **hang on a minute**

If we're compiling with `-Dtests=false` we don't need the test inputs, and **we don't need the internal gcab**! PR updated!

**Review by superm1 — APPROVED** [review]

**Comment by ntsirakis** [comment]
> How do all the other tests work right now? Surely lots of other libfwupdplugin self tests also explode for the same dependency reason, **not just** `gcab`. So if it really is limited to `gcab` seems like it should be a more narrow problem scope to solve than everything else.

The other tests are working fine interestingly enough. My guess is that gcab being an internally-built tool causes some discrepancies in the way the test is run. In any case I've spoken to @hughsie about this, and we determined that this isn't on fwupd to fix. This is likely an internal tooling problem.

**Comment by rishabh-chromium** [comment]
Still running into this issue, probably need to force use gcab external when using meson cross-build

**Comment by hughsie** [comment]
In all honesty, I'm not sure why the self tests run and the gcab self-built binary doesn't. I assume the tests run on the host via an emulator but it's really not my area of expertise! I guess looking at the detailed build output might shed some clues.

**Comment by ntsirakis** [comment]
I believe this is on whatever is cross-compiling fwupd to orchestrate properly. IIRC the built gcab is looking in the build rootfs for libxmlb, and it should be looking in the host rootfs. It should just be a matter of adding extra linker flags to point it to the right sysroot.

That said, it’s possible that fwupd should utilize certain environment variables when building (rather than hardcoding, for example) to support this case.

We’ll see how Gentoo handles this when they uprev fwupd in their upstream layers. I’m curious to see if they open any PRs on the fwupd side.

**Pull request merged**
