### PR TITLE
Don't check the battery percentage if UPwer is unavailable

### PR DESCRIPTION
**Pull request by hughsie**
Based on a patch by Crag Wang <Crag.Wang@dell.com>, many thanks.

### CODE REVIEW

**Comment by hughsie** [comment]
@Crag.Wang does this work for you?

**Comment by superm1** [comment]
I think it's better to do this in startup and disable the plugin no?  Or are you concerned for race condition then?

**Comment by hughsie** [comment]
>  Or are you concerned for race condition

Well, less a race condition, more worried about the startup order. I guess that's less of an issue here as we're checking the upower state on firmware deployment. Maybe we check the name owner in startup, and if it's NULL we disable the plugin like you suggest?

**Comment by superm1** [comment]
> more worried about the startup order.

Like `fwupd` starts before `upowerd`?  And then `upowerd` doesn't have an owner yet?  This can be mitigated by making `fwupd.service` depend on `upower.service` I would think.

> Maybe we check the name owner in startup, and if it's NULL we disable the plugin like you suggest?

I think that makes more sense, yes.

**Comment by hughsie** [comment]
> This can be mitigated by making fwupd.service depend on upower.service I would think.

I don't think we need to worry about this, as `g_dbus_proxy_new_for_bus_sync()` will start upower for us if required as we're **not** using `G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START`

> I think that makes more sense, yes.

Okay, fixed up with that -- and it seems to work too.

**Comment by CragW** [comment]
It works. On Chrome the plugin is disabled as per the owner of UPower doesn't exist.

**Comment by superm1** [comment]
> It works. On Chrome the plugin is disabled as per the owner of UPower doesn't exist.

Great.  I also backported to 1_2_X since chromeos is still on 1.2.x AFAIK.

**Pull request merged**
