### PR TITLE
Wip/chlee75/ccgx newdock candidate

### PR DESCRIPTION
**Pull request by chlee75**
Just rename branch. It will be removed.

### CODE REVIEW

**Comment by chlee75** [comment]
I close this PR.

**Comment by chlee75** [comment]
This PR should be deleted.

**Comment by superm1** [comment]
> This PR should be deleted. 

I looked but don't see a delete button. @hughsie do you?

**Comment by chlee75** [comment]
@superm1 
The PR has been created by accident while I am trying to rename the branch to remove confidential data.

But I can't find a way to delete PR on the website.
As I know, users have to send the request form to GitHub to delete PRs. 
https://support.github.com/contact/private-information

Do you have any experience to delete PR?

**Comment by superm1** [comment]
I haven't ever done it, no.

**Pull request closed without merging**
