### PR TITLE
meson.build: update min meson version to 0.50.0.

### PR DESCRIPTION
**Pull request by ericonr**
The following feature is used:

 > * 0.50.0: {'install arg in configure_file'}

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
I think the warning can be ignored; unfortunately upping the meson buildrequires would break compiling on RHEL and Ubuntu LTS.

**Comment by ericonr** [comment]
Well, as long as it still works there :)

Would you prefer I leave this open as a reminder? Otherwise I can go ahead and close it.

**Comment by hughsie** [comment]
> Would you prefer I leave this open as a reminder

Ya, lets keep this open.

**Comment by ericonr** [comment]
do I have to do anything to avoid the bot closing it?

**Comment by superm1** [comment]
I sorta think we shouldn't bother keeping this open, it will be a few years until it's time to stop worrying about RHEL and current Ubuntu LTS versions.  Just re-visit it then.

**Comment by hughsie** [comment]
>  Just re-visit it then

Agree, we can reopen then.

**Pull request closed without merging**
