### PR TITLE
Remove redundant flag

### PR DESCRIPTION
**Pull request by sc12301230**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by sc12301230** [comment]
Remove redundant flag to let this PID device to enter right code condition.

**Comment by hughsie** [comment]
There seem to be conflicts -- can you rebase against main and squash the commits please.

**Comment by sc12301230** [comment]
Solved the conflicts.

**Review by hughsie — APPROVED** [review]

**Comment by hughsie** [comment]
Manually merged to main, thanks. Do you also want this cherry picked into the 1.9.x releases?

**Pull request closed without merging**
