### PR TITLE
Do not show an invalid warning when the vendor-id requirement failed

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Note: this won't fix the problem, but it will tell us which vendor-id is missing from the `dell` LVFS account...

**Comment by superm1** [comment]
> Note: this won't fix the problem, but it will tell us which vendor-id is missing from the dell LVFS account...

Actually seems to fix it...

1_2_X, 1.2.13, 1.2.14
```
$ git checkout 1_2_X
...
$ sudo ninja -C build install
...
$ fwupdmgr update
No upgrades for RTS5487 in Dell dock, current is 01.47: 01.47=same, 01.47=same, 01.47=same
No releases found for device: cannot handle firmware requirement 'vendor-id'
No releases found for device: cannot handle firmware requirement 'vendor-id'
No releases found for device: cannot handle firmware requirement 'vendor-id'
No upgrades for RTS5413 in Dell dock, current is 01.21: 01.21=same, 01.21=same, 01.21=same
No upgrades for XPS 13 7390 System Firmware, current is 0.1.7.0: 0.1.7.0=same, 0.1.6.0=older, 0.1.5.1=older, 0.1.4.0=older, 0.1.3.1=older
```

wip/hughsie/1_2_X-vendor-id
```
$ git checkout wip/hughsie/1_2_X-vendor-id
...
$ sudo ninja -C build install
...
$ fwupdmgr update
No upgrades for RTS5487 in Dell dock, current is 01.47: 01.47=same, 01.47=same, 01.47=same
No upgrades for WD19, current is 01.00.00.05: 01.00.00.05=same, 01.00.00.04=older, 01.00.00.00=older
No upgrades for Package level of Dell dock, current is 01.00.15.01: 01.00.15.01=same, 01.00.14.01=older, 01.00.04.01=older
No upgrades for VMM5331 in Dell dock, current is 05.04.06: 05.04.06=same, 05.04.03=older, 05.03.10=older
No upgrades for RTS5413 in Dell dock, current is 01.21: 01.21=same, 01.21=same, 01.21=same
No upgrades for XPS 13 7390 System Firmware, current is 0.1.7.0: 0.1.7.0=same, 0.1.6.0=older, 0.1.5.1=older, 0.1.4.0=older, 0.1.3.1=older
```

**Comment by hughsie** [comment]
> Actually seems to fix it...

Ah, actually you're probably right. You okay to push this one patch to Ubu or do you need a new tarball?

**Comment by superm1** [comment]
> Ah, actually you're probably right. You okay to push this one patch to Ubu or do you need a new tarball?

Did you see the mention on keybase using the wrong character (`.` vs `-`) about SBAT?  We might need to spin all them again..

**Comment by hughsie** [comment]
I did just now, thanks for ruining my Friday afternoon! :) I guess:

    -{0}-{1}
    +{0}.{1}

?

**Comment by superm1** [comment]
> I did just now, thanks for ruining my Friday afternoon! :) I guess:
> 
> ```
> -{0}-{1}
> +{0}.{1}
> ```
> 
> ?

think so, yeah.

**Pull request merged**
