### PR TITLE
Never write 'unknown' update state on success

### PR DESCRIPTION
**Pull request by hughsie**
This means we don't get asked to submit a report.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
This feels like the wrong solution. Why is the status ever unknown?

**Comment by hughsie** [comment]
I think it starts off in unknown, no?

**Comment by superm1** [comment]
But shouldn't it get updates elsewhere?

**Comment by superm1** [comment]
Let me elaborate.  `fu_engine_install_release` is only called from `fu_engine_install`, which calls that at the very end of the function _already_.

**Comment by hughsie** [comment]
>  So if you're calling it here, it should no longer be called there

Hmm. Indeed. Will ponder, thanks.

**Comment by hughsie** [comment]
Okay, I like this one much more ^^

**Review by superm1 — APPROVED** [review]

**Pull request merged**
