### PR TITLE
Fix FU_PLUGIN_RULE_BETTER_THAN to ignore lower priority devices

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 insane?

**Comment by superm1** [comment]
It makes sense to me. Can you also add it to the Amdgpu plugin? I'll see if if helps

**Comment by superm1** [comment]
Yeah it works

**Review by superm1 — DISMISSED** [review]

**Comment by hughsie** [comment]
@superm1 i tweaked the logic a bit, still working?

**Review by superm1 — APPROVED** [review]
Yeah still works

**Pull request merged**
