### PR TITLE
Quit the running fwupd instance when running fwupdtool

### PR DESCRIPTION
**Pull request by hughsie**
Also, this ensures we can't run more than one fwupdtool instance at a time.

Fixes https://github.com/fwupd/fwupd/issues/3019

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
It's not super awesome just having a "dead thread" to handle the DBus ownership but it seems to work...

**Review by superm1 — COMMENTED** [review]
Why not just a lockfile?

**Comment by hughsie** [comment]
> Why not just a lockfile

Because I want the first new `fwupdtool` instance to quit the _idle_ `fwupd` instance.

**Comment by superm1** [comment]
> > Why not just a lockfile
> 
> Because I want the first new `fwupdtool` instance to quit the _idle_ `fwupd` instance.

Don't we already do that? https://github.com/fwupd/fwupd/blob/master/src/fu-tool.c#L176

**Comment by hughsie** [comment]
> Don't we already do that? https://github.com/fwupd/fwupd/blob/master/src/fu-tool.c#L176

On one hand, I forgot all about that. On the other hand, what happens if we ask the systemd-controlled instance to manually stop during a firmware update? My gut says it probably does SIGQUIT and then after a few seconds does SIGKILL, and that's probably not what we want given a lot of the firmware updates take a lot longer than that. I guess my proposal would be to remove the calls to fu_systemd_unit_stop() and then let the daemon handle the replacement when it knows it's safe.

**Comment by superm1** [comment]
>My gut says it probably does SIGQUIT and then after a few seconds does SIGKILL, 

Actually this behavior is entirely controllable by `KillMode=` and `KillSignal=`. 

> and that's probably not what we want given a lot of the firmware updates take a lot longer than that. I guess my proposal would 
> be to remove the calls to fu_systemd_unit_stop() and then let the daemon handle the replacement when it knows it's safe.

Keep in mind someone launching `fwupdtool` as root while `fwupd.service` is running is a pretty advanced thing to do.  Don't want to over-engineer the solution.

The original report was two `fwupdtool` processes conflicting, which you might argue is better solved by it instead becoming two `fwupdgmr`  processes talking to one fwupd daemon process....

**Comment by hughsie** [comment]
> The original report was two fwupdtool processes conflicting

So maybe the fix here is to make fwupdtool claim the org.freedesktop.fwupd**tool** name -- which won't affect the fwupd process at all (other than the systemd service stopping) and would prevent the 2nd instance from running. I totally agree about using the daemon; it's almost like we designed something that provides this exact system-state-sharing functionality already...

**Comment by superm1** [comment]
Well back to my point about simple solution - if it's just two fwupdtool processes what's wrong with a simple lockfile? Or even exclusive access to the sqlite3 database. If you have exclusive access then the second process should fail immediately.

**Comment by hughsie** [comment]
> what's wrong with a simple lockfile

Isn't a lockfile far from simple when we're talking about making it work on win32 as well? Although, I guess the same point can be made about win32 where there's no DBus daemon.... If you have any pointers on how to implement a lockfile (ideally with GIO/Glib, rather than Unix primitives) I'm happy to give this a go.

**Comment by superm1** [comment]
Sqlite3 has this stuff natively:
https://sqlite.org/lockingv3.html

**Comment by hughsie** [comment]
I'm not totally convinced about using sqlite locking. What about https://github.com/fwupd/fwupd/pull/3147 ?

**Comment by superm1** [comment]
> I'm not totally convinced about using sqlite locking. What about #3147 ?

Seems fine to me.

**Pull request closed without merging**
