### PR TITLE
Superm1/1 9 x proposed

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Eigh? clang format doesn't like it.

**Comment by superm1** [comment]
> Eigh? clang format doesn't like it.

Something wonky is going on with clang-format-diff for me since upgrading this laptop to F40.  It's returning `1` when it it otherwise works.  I did this:
```
diff --git a/contrib/reformat-code.py b/contrib/reformat-code.py
index ad213c4fa..1c4597a7b 100755
--- a/contrib/reformat-code.py
+++ b/contrib/reformat-code.py
@@ -77,9 +77,9 @@ if __name__ == "__main__":
     if args.debug:
         print(cmd)
     ret = subprocess.run(cmd, input=ret.stdout, capture_output=True, text=True)
-    if ret.returncode:
-        print(f"Failed to run {cmd}\n{ret.stderr.strip()}")
-        sys.exit(1)
+#    if ret.returncode:
+#        print(f"Failed to run {cmd}\n{ret.stderr.strip()}")
+#        sys.exit(1)
     cmd = ["patch", "-p0"]
     if args.debug:
         print(cmd)
```

In order to get this updated.  Don't really understand why.  Any ideas?

**Comment by hughsie** [comment]
@superm1 doing `find . -name '*.c' -o -name '*.h' -o -name '*.proto' | xargs clang-format -i` seems to return 0 for success for me -- I'm also on F40 beta too (although, it does make changes to src..)

**Comment by hughsie** [comment]
fwiw, I'd be 100% with a project wide reformat -- there are a few places it's broken.

**Comment by superm1** [comment]
> fwiw, I'd be 100% with a project wide reformat -- there are a few places it's broken.

the problem with this is it makes backports a little less clean sometimes.

> @superm1 doing find . -name '*.c' -o -name '*.h' -o -name '*.proto' | xargs clang-format -i seems to return 0 for success for me -- I'm also on F40 beta too (although, it does make changes to src..)

Same for me - this returns 0, but it also doesn't reformat any of this specific code that's changed.  So I'm pretty baffled what's going on.

Can you try to fixup this PR while my machine is a mess with clang-format?

**Comment by hughsie** [comment]
The weird thing is that it's failing to run `patch` -- not clang-format.

**Comment by superm1** [comment]
> The weird thing is that it's failing to run `patch` -- not clang-format.

Do you mean within `clang-format-diff`?

```
$ ./contrib/reformat-code.py --debug origin/1_9_X
['git', 'describe', 'origin/1_9_X']
Reformatting code against origin/1_9_X
['git', 'diff', '-U0', 'origin/1_9_X']
['clang-format-diff', '-regex', '^.*\\.(c|h|proto)$', '-p1']
Failed to run ['clang-format-diff', '-regex', '^.*\\.(c|h|proto)$', '-p1']
```

**Comment by superm1** [comment]
```
(fwupd) $ git diff -U0 origin/1_9_X | clang-format-diff --verbose -regex "^.*\\.(c|h|proto)$" -p1
--- plugins/uefi-capsule/fu-uefi-cod-device.c	(before formatting)
+++ plugins/uefi-capsule/fu-uefi-cod-device.c	(after formatting)
@@ -258,7 +258,8 @@
 static void
 fu_uefi_cod_device_init(FuUefiCodDevice *self)
 {
-	fu_device_set_summary(FU_DEVICE(self), "UEFI System Resource Table device (Updated via caspule-on-disk)");
+	fu_device_set_summary(FU_DEVICE(self),
+			      "UEFI System Resource Table device (Updated via caspule-on-disk)");
 }
 
 static void
(fwupd) $ echo $?
1
```

**Review by hughsie — APPROVED** [review]

**Pull request merged**
