### PR TITLE
altos: Remove support for the ChaosKey

### PR DESCRIPTION
**Pull request by hughsie**
The hardware is discontinued, and no further update from 1.6.7 was ever supplied.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — CHANGES_REQUESTED** [review]
I think you need to change contrib/ci/dependencies.xml for this change too

**Comment by hughsie** [comment]
> I think you need to change contrib/ci/dependencies.xml

I did that, but then the ABI CI job failed. I think we can put it on the list to do after the 1.7.2 release.

**Comment by superm1** [comment]
> > I think you need to change contrib/ci/dependencies.xml
> 
> I did that, but then the ABI CI job failed. I think we can put it on the list to do after the 1.7.2 release.

Ah OK.  I guess as long as it's on the list and not totally forgotten about - maybe a comment in dependencies.xml to drop later?

**Comment by hughsie** [comment]
I've added it to my notes here. Thanks.

**Pull request merged**
