### PR TITLE
trivial: Ensure polkit is installed in Arch CI

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
I'd say disable it for now if it's just too splody and leave me a ticket to revive it when I get to it.

**Comment by superm1** [comment]
> I'd say disable it for now if it's just too splody and leave me a ticket to revive it when I get to it.

That being said; look closer as the errors in the CI logs. There's a lot of other messes showing.

**Comment by superm1** [comment]
Try starting polkit manually, maybe dbus activation is the reason for permission issue

**Comment by superm1** [comment]
Rather than last commit can we just manually start the daemon on each emulation test?

**Comment by hughsie** [comment]
> Rather than last commit can we just manually start the daemon on each emulation test?

I don't think so; it's done in the installed test itself. I guess the root issue is that dbus activation isn't working, although in CI I was surprised it worked in the first place.

**Comment by hughsie** [comment]
Lets merge and unblock CI; I've asked a few Arch people to work out what broke.

**Pull request merged**
