### PR TITLE
Hughsie/19x rustgen

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@CragW does this unblock you?

**Comment by CragW** [comment]
> @CragW does this unblock you?

Testing, I believe if rs changes back to 19x that will significantly reduce the backport effort.

BTW, is this an issue?
https://github.com/fwupd/fwupd/actions/runs/12008986324/job/33472758699?pr=8149#step:4:2016

```
libfwupdplugin/fu-efi-struct.h:98: Warning: FwupdPlugin: symbol='EfiFile': Unknown namespace for identifier 'EfiFile'
libfwupdplugin/fu-efi-struct.h:133: Warning: FwupdPlugin: symbol='EfiSection': Unknown namespace for identifier 'EfiSection'
libfwupdplugin/fu-efi-struct.h:154: Warning: FwupdPlugin: symbol='EfiSectionGuidDefined': Unknown namespace for identifier 'EfiSectionGuidDefined'
```

**Comment by hughsie** [comment]
Nah, it's only the fwupdplugin typelib generator. Ideally we could disable that as I'm not super keen on backporting all the .rs changes to each file...

**Comment by hughsie** [comment]
> I'm not super keen on backporting all the .rs changes to each file...

Narrator: _he did that_

**Review by superm1 — APPROVED** [review]

**Comment by superm1** [comment]
This looks to have broken 1.9.x fuzzing. Can you see if it's a missed fix to port?

**Comment by hughsie** [comment]
@superm1 the gnome servers seem to be down:

    fatal: unable to access 'https://gitlab.gnome.org/GNOME/json-glib.git/': The requested URL returned error: 503

**Pull request merged**
