### PR TITLE
trivial: ci: debian: Use helper script to install dependencies instead.

### PR DESCRIPTION
**Pull request by superm1**
Should fix building Debian stable containers
Fixes: #4901

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by Sean-StarLabs — COMMENTED** [review]
It works - but stops it creating deb files as it matches `if ! dpkg-checkbuilddeps; then`

Comment out the `exit 0` and you end up with:
```
+ . ./contrib/ci/get_test_firmware.sh
++ '[' true = true ']'
++ rm -rf fwupd-test-firmware
++ git clone https://github.com/fwupd/fwupd-test-firmware
Cloning into 'fwupd-test-firmware'...
remote: Enumerating objects: 242, done.
remote: Counting objects: 100% (140/140), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 242 (delta 28), reused 130 (delta 20), pack-reused 102
Receiving objects: 100% (242/242), 261.32 KiB | 1.62 MiB/s, done.
Resolving deltas: 100% (66/66), done.
++ cp fwupd-test-firmware/ci-tests/libfwupdplugin fwupd-test-firmware/ci-tests/plugins . -R
+ '[' -x /usr/lib/fwupd/fwupd ']'
+ EDITOR=/bin/true
+ dch --create --package fwupd -v 1.8.4 'CI Build'
+ debuild --no-lintian --preserve-envvar CI --preserve-envvar CC --preserve-envvar QUBES_OPTION
 dpkg-buildpackage -us -uc -ui
dpkg-buildpackage: info: source package fwupd
dpkg-buildpackage: info: source version 1.8.4
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by CI Builder <ci@travis-ci.org>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-source: info: using options from build/debian/source/options: --extend-diff-ignore=.vscode|venv|subprojects|build
dpkg-checkbuilddeps: error: Unmet build dependencies: gi-docgen libqrtr-glib-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
```

**Comment by superm1** [comment]
> It works - but stops it creating deb files as it matches `if ! dpkg-checkbuilddeps; then`
> 
> Comment out the `exit 0` and you end up with:
> ```
> + . ./contrib/ci/get_test_firmware.sh
> ++ '[' true = true ']'
> ++ rm -rf fwupd-test-firmware
> ++ git clone https://github.com/fwupd/fwupd-test-firmware
> Cloning into 'fwupd-test-firmware'...
> remote: Enumerating objects: 242, done.
> remote: Counting objects: 100% (140/140), done.
> remote: Compressing objects: 100% (73/73), done.
> remote: Total 242 (delta 28), reused 130 (delta 20), pack-reused 102
> Receiving objects: 100% (242/242), 261.32 KiB | 1.62 MiB/s, done.
> Resolving deltas: 100% (66/66), done.
> ++ cp fwupd-test-firmware/ci-tests/libfwupdplugin fwupd-test-firmware/ci-tests/plugins . -R
> + '[' -x /usr/lib/fwupd/fwupd ']'
> + EDITOR=/bin/true
> + dch --create --package fwupd -v 1.8.4 'CI Build'
> + debuild --no-lintian --preserve-envvar CI --preserve-envvar CC --preserve-envvar QUBES_OPTION
>  dpkg-buildpackage -us -uc -ui
> dpkg-buildpackage: info: source package fwupd
> dpkg-buildpackage: info: source version 1.8.4
> dpkg-buildpackage: info: source distribution UNRELEASED
> dpkg-buildpackage: info: source changed by CI Builder <ci@travis-ci.org>
>  dpkg-source --before-build .
> dpkg-buildpackage: info: host architecture amd64
> dpkg-source: info: using options from build/debian/source/options: --extend-diff-ignore=.vscode|venv|subprojects|build
> dpkg-checkbuilddeps: error: Unmet build dependencies: gi-docgen libqrtr-glib-dev
> dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
> dpkg-buildpackage: warning: (Use -d flag to override.)
> debuild: fatal error at line 1182:
> dpkg-buildpackage -us -uc -ui failed
> ```

Which I guess makes sense. The packaging isn't set up to go without those dependencies.

**Comment by Sean-StarLabs** [comment]
Indeed, but would it make sense to modify the `generate_debian.py` to remove "Package: fwupd-doc" based on docs being enabled?

**Comment by Sean-StarLabs** [comment]
That looks good to me, but unfortunately, `debian:stable` will fail due to only having meson 56.

It also causes an indefinite hang for `ubuntu:anything`:
```
Sending build context to Docker daemon  87.06MB
Step 1/9 : FROM ubuntu:rolling
 ---> df5de72bdb3b
Step 2/9 : ENV OS ubuntu-x86_64
 ---> Using cache
 ---> fa1dcf97883d
Step 3/9 : ENV CI_NETWORK true
 ---> Using cache
 ---> 3ad0e899bebc
Step 4/9 : ENV CC clang
 ---> Using cache
 ---> 6d600f238ee0
Step 5/9 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> bbe900f86142
Step 6/9 : RUN echo fubar > /etc/machine-id
 ---> Using cache
 ---> 7ad99d721733
Step 7/9 : RUN apt update -qq && apt install -yq --no-install-recommends python3-apt
 ---> Running in e0a5a14050f9

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

```

**Comment by superm1** [comment]
> That looks good to me, but unfortunately, `debian:stable` will fail due to only having meson 56.
> 
> It also causes an indefinite hang for `ubuntu:anything`:
> ```
> Sending build context to Docker daemon  87.06MB
> Step 1/9 : FROM ubuntu:rolling
>  ---> df5de72bdb3b
> Step 2/9 : ENV OS ubuntu-x86_64
>  ---> Using cache
>  ---> fa1dcf97883d
> Step 3/9 : ENV CI_NETWORK true
>  ---> Using cache
>  ---> 3ad0e899bebc
> Step 4/9 : ENV CC clang
>  ---> Using cache
>  ---> 6d600f238ee0
> Step 5/9 : ENV DEBIAN_FRONTEND noninteractive
>  ---> Using cache
>  ---> bbe900f86142
> Step 6/9 : RUN echo fubar > /etc/machine-id
>  ---> Using cache
>  ---> 7ad99d721733
> Step 7/9 : RUN apt update -qq && apt install -yq --no-install-recommends python3-apt
>  ---> Running in e0a5a14050f9
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> ```

I don't think we can do anything about debian stable with the meson version unless there is a backported repo with newer meson available.

I don't understand the Ubuntu failure. Can you try again, same results?

**Comment by superm1** [comment]
> > That looks good to me, but unfortunately, `debian:stable` will fail due to only having meson 56.
> > It also causes an indefinite hang for `ubuntu:anything`:
> > ```
> > Sending build context to Docker daemon  87.06MB
> > Step 1/9 : FROM ubuntu:rolling
> >  ---> df5de72bdb3b
> > Step 2/9 : ENV OS ubuntu-x86_64
> >  ---> Using cache
> >  ---> fa1dcf97883d
> > Step 3/9 : ENV CI_NETWORK true
> >  ---> Using cache
> >  ---> 3ad0e899bebc
> > Step 4/9 : ENV CC clang
> >  ---> Using cache
> >  ---> 6d600f238ee0
> > Step 5/9 : ENV DEBIAN_FRONTEND noninteractive
> >  ---> Using cache
> >  ---> bbe900f86142
> > Step 6/9 : RUN echo fubar > /etc/machine-id
> >  ---> Using cache
> >  ---> 7ad99d721733
> > Step 7/9 : RUN apt update -qq && apt install -yq --no-install-recommends python3-apt
> >  ---> Running in e0a5a14050f9
> > 
> > WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> > ```
> 
> I don't think we can do anything about debian stable with the meson version unless there is a backported repo with newer meson available.
> 
> I don't understand the Ubuntu failure. Can you try again, same results?

Also, Ubuntu built just fine for CI:
https://app.circleci.com/pipelines/github/fwupd/fwupd/10929/workflows/767207f8-7096-4a57-abdf-115e5b9c8da5/jobs/39255

**Comment by Sean-StarLabs** [comment]
For meson, pip3 or bullseye-backports would be options?

Will dig into Ubuntu, tried twice and purged docker images each time

**Comment by superm1** [comment]
> For meson, pip3 or bullseye-backports would be options?

Yeah, go ahead and add that to your debian:stable container and it should work.

> 
> Will dig into Ubuntu, tried twice and purged docker images each time

Maybe network access?  You can try to add more verbose information to the apt commands.

**Review by Sean-StarLabs — APPROVED** [review]

**Comment by Sean-StarLabs** [comment]
Poor download speed was the reason, I guess a mirror was down. All good now, will try to add meson for debian now!
Thanks :)

**Comment by Sean-StarLabs** [comment]
Almost there, but found one problem:
```
dh_install: warning: fwupd-doc missing files: usr/share/doc
dh_install: error: missing files, aborting
make[1]: *** [debian/rules:67: override_dh_install] Error 25
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:50: binary] Error 2
```

The only way I know to work around that is to remove `--fail-missing`, but it's a sledge hammer. Do you know any better ways?

**Comment by superm1** [comment]
> Almost there, but found one problem:
> ```
> dh_install: warning: fwupd-doc missing files: usr/share/doc
> dh_install: error: missing files, aborting
> make[1]: *** [debian/rules:67: override_dh_install] Error 25
> make[1]: Leaving directory '/<<PKGBUILDDIR>>'
> make: *** [debian/rules:50: binary] Error 2
> ```
> 
> The only way I know to work around that is to remove `--fail-missing`, but it's a sledge hammer. Do you know any better ways?

That shouldn't happen. Do you have a stale `contrib/debian/fwupd.docs` sitting around?

**Comment by Sean-StarLabs** [comment]
No, fresh clone, all containers deleted.
```
fwupd/build/debian$ grep -ri doc
rules:	#install docs (maybe)
rules:	[ -d debian/usr/share/doc ] || dh_install -pfwupd-doc usr/share/doc
control.in:Build-Depends-Indep: libglib2.0-doc <!nodoc>
control.in:Package: fwupd-doc
control.in:Section: doc
control.in:Description: Firmware update daemon documentation (HTML format)
control.in: This package provides development documentation for creating a package that
copyright:Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
copyright: SERVICES. DISTRIBUTION OF THIS DOCUMENT DOES NOT CREATE AN ATTORNEY-CLIENT
copyright: CREATIVE COMMONS MAKES NO WARRANTIES REGARDING THE USE OF THIS DOCUMENT OR THE
copyright: RESULTING FROM THE USE OF THIS DOCUMENT OR THE INFORMATION OR WORKS PROVIDED
copyright: surrendered, licensed or otherwise affected by this document.
copyright: to this document and has no duty or obligation with respect to this CC0 or use
copyright.in:Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
copyright.in: SERVICES. DISTRIBUTION OF THIS DOCUMENT DOES NOT CREATE AN ATTORNEY-CLIENT
copyright.in: CREATIVE COMMONS MAKES NO WARRANTIES REGARDING THE USE OF THIS DOCUMENT OR THE
copyright.in: RESULTING FROM THE USE OF THIS DOCUMENT OR THE INFORMATION OR WORKS PROVIDED
copyright.in: surrendered, licensed or otherwise affected by this document.
copyright.in: to this document and has no duty or obligation with respect to this CC0 or use
control:	libglib2.0-doc,
control:Build-Depends-Indep: libglib2.0-doc <!nodoc>
control:Package: fwupd-doc
control:Section: doc
control:Description: Firmware update daemon documentation (HTML format)
control: This package provides development documentation for creating a package that
```
```
fwupd/build/debian$ ls *
changelog         fwupd.maintscript               gir1.2-fwupd-2.0.install
clean             fwupd.pkla                      gir1.2-fwupdplugin-1.0.install
compat            fwupd.postinst                  libfwupd2.install
control           fwupd.postrm                    libfwupd-dev.install
control.in        fwupd.preinst                   libfwupdplugin7.install
control.qubes.in  fwupd-qubes-vm-whonix.install   libfwupdplugin-dev.install
copyright         fwupd-qubes-vm-whonix.postinst  not-installed
copyright.in      fwupd-qubes-vm-whonix.postrm    README.Debian
docs              fwupd-tests.install             README.source
files             fwupd-tests.postinst            rules
fwupd.dirs        fwupd-tests.postrm              watch
fwupd.install     gbp.conf

lintian:
fwupd  fwupd-tests

source:
format  lintian-overrides  options

tests:
ci  control  libfwupd-dev
```

**Pull request merged**
