### PR TITLE
corsair: remove support for some devices

### PR DESCRIPTION
**Pull request by dushko-devx**
Remove these mice from the plugin:
    * KATAR PRO WIRELESS
    * HARPOON RGB WIRELESS

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [x] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Ohh? How come? You don't need to remove the VID/PIDs even if you decide not to update firmware on the LVFS.

**Comment by dushko-devx** [comment]
Yes I know but I cannot change vendor's decision to do it like this

**Comment by dushko-devx** [comment]
It was vendor's decision to remove the unsupported devices from the plugin

**Comment by hughsie** [comment]
> It was vendor's decision to remove the unsupported devices from the plugin

**Review by hughsie — APPROVED** [review]
> It was vendor's decision to remove the unsupported devices from the plugin

It's 100% easier to add all the devices to the quirk files and then just upload the LVFS updates for the ones you want to update than to keep adding and removing things from the quirk file. That said, your plugin, your rules.

**Pull request merged**
