### PR TITLE
trivial: Add some more common Winbond SPI chips

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by adamgene — COMMENTED** [review]
There are many SPI flash of Winbond needs to do extra un-protection, and they may need to identify by specific `CfiDeviceCmdReadId`. Therefore, add them into quirk carefully. 

e.g. `W25X21CL`
image
image

**Comment by hughsie** [comment]
@adamgene really interesting, thanks! Do you happen to know which SPI chips support "Read Unique ID Number"?

**Comment by hughsie** [comment]
I'll merge this (as we only needed the size for the new hardware I'm trying to enable) and carry on investigations in the wip/hughsie/cfi-UniqueId branch. Thanks!

**Comment by adamgene** [comment]
All as I know, there are many manufacturers supporting below read ID command.

- **JEDEC ID (9Fh)**, must? but I found legacy flash does not support.
- **Read Manufacturer / Device ID (90h)**, most in recent year.
- **Release Power-down / Device ID (ABh)**, most in recent year.
- **Read Unique ID Number (4Bh)**, few  products, Winbond / GigaDevice.
- another rare command.

In our supporting flash list, we use 5 commands. 1D / 90 / 9F / 4B / AB.

--- 

I will keep trace `wip/hughsie/cfi-UniqueId`.

**Pull request merged**
