### PR TITLE
Wip/hughsie/esrt

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@SergiiDmytruk can you test ^^ on FreeBSD please? I can't get it to compile as there doesn't seem to be `efiboot` available.

**Comment by superm1** [comment]
Hmm, I guess the question I want to ask - do we really want plugins themselves to be introducing the concept of multiple backends?  It feels like it might be overloading the definition of backend.  Or should we keep that abstraction in libfwupdplugin directly.

**Review by SergiiDmytruk — DISMISSED** [review]

**Comment by SergiiDmytruk** [comment]
I've added a commit to fix FreeBSD. 3mdeb's fork of ports doesn't yet have [my changes](https://github.com/SergiiDmytruk/freebsd-ports/commits/fwupd) with `libefiboot` that can be linked to (mind that my fork lacks updates from 3mdeb's fork, maybe I should rebase).

**Comment by hughsie** [comment]
> I've added a commit to fix FreeBSD

Thanks, I've merged that into my commit.

>  3mdeb's fork of ports doesn't yet have my changes with libefiboot that can be linked to

I did wonder how much of libefiboot we actually use nowadays.

**Comment by hughsie** [comment]
> do we really want plugins themselves to be introducing the concept of multiple backends?

I also share that concern. I actually started with a FuUefiEsrt factory like @SergiiDmytruk suggested, but it was 70% the same code as FuBackend.

> Or should we keep that abstraction in libfwupdplugin directly.

So, that was my longer term plan. i.e. write the plugins to subclass FuBackend to build a device factory, and then if later we want to move the plugin coldplug into a more generic backend instantiated from the engine (to be used on multiple plugins) then the amount of changes should be minimal. i.e. we're converging to a more standard factory design longer term.

**Comment by superm1** [comment]
Yeah, I guess we don't realistically have a need for more plugins to access the ESRT.

OK fine by me.

**Pull request merged**
