### PR TITLE
Drop SuperIO plugin

### PR DESCRIPTION
**Pull request by superm1**
According to Sean the SuperIO plugin isn't in use anymore, and we don't want
to encourage anything that requires direct I/O access if we can avoid it.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [x] Feature
- [ ] Documentation

### CODE REVIEW

**Review by Sean-StarLabs — APPROVED** [review]
LGTM - assuming we were the only ones to use it...

**Comment by hughsie** [comment]
Can we get rid of fwupdoffline too perhaps?

**Comment by superm1** [comment]
> Can we get rid of fwupdoffline too perhaps?

I don't see why not.

**Comment by superm1** [comment]
@valentindavid the snap might be able to drop some caps with this change.

**Pull request merged**
