### PR TITLE
trivial: install the fwupdplugin-self-test to installed-tests

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Looks good, but coverage going down?

**Comment by superm1** [comment]
eh?
image

**Comment by hughsie** [comment]
Looking at https://coveralls.io/builds/65565789 -- fu-remote-list.c for example

**Comment by superm1** [comment]
> Looking at https://coveralls.io/builds/65565789 -- fu-remote-list.c for example

got it.  I wouldn't worry about it for now until we have explicit tests for more stuff.  Just looking for more low lying fruit right now.

**Pull request merged**
