### PR TITLE
Use a heuristic to detect internal DRM devices

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
I'd feel a lot better if it was explicitly enabled and connected with this heuristic

**Comment by superm1** [comment]
But it's still going to fall apart with say AIO devices that connect their panel with DP.

**Comment by hughsie** [comment]
> I'd feel a lot better if it was explicitly enabled and connected with this heuristic

IIRC, I've seen multiple eDPs in laptops -- i.e. one `connected` and one `disconnected`.

**Comment by hughsie** [comment]
> But it's still going to fall apart with say AIO devices that connect their panel with DP.

Right -- and we'd have to quirk those somehow -- but for the laptop that I'm trying to work around the eDP bit is set correctly.

**Review by superm1 — APPROVED** [review]

**Pull request merged**
