### PR TITLE
Fix reboot of logitech devices

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by FFY00** [comment]
I am not able to update nordic signed receivers, which appears to not have updates available. All other variants update fine, though I did not try without the patch.

```
$ sudo src/fwupdtool get-updates
22:00:44:0670 FuEngine             altos has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0670 FuEngine             amt has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0670 FuEngine             ata has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0671 FuEngine             colorhug has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0671 FuEngine             coreboot has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0671 FuEngine             csr has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0673 FuEngine             dell has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0673 FuEngine             dell_dock has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0673 FuEngine             dell_esrt has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0674 FuEngine             dfu has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0674 FuEngine             ebitdo has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0674 FuEngine             emmc has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0674 FuEngine             fastboot has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0675 FuEngine             jabra has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0675 FuEngine             logitech_hidpp has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0675 FuEngine             nitrokey has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0675 FuEngine             nvme has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0676 FuEngine             optionrom has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0676 FuEngine             redfish has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0676 FuEngine             rts54hid has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0676 FuEngine             rts54hub has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0677 FuEngine             solokey has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0677 FuEngine             steelseries has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0677 FuEngine             superio has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0677 FuEngine             synaptics_cxaudio has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0677 FuEngine             synaptics_mst has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0678 FuEngine             synaptics_prometheus has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0678 FuEngine             synaptics_rmi has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0678 FuEngine             thelio_io has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0678 FuEngine             thunderbolt has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0679 FuEngine             thunderbolt_power has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0679 FuEngine             tpm has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0680 FuEngine             tpm_eventlog has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0680 FuEngine             uefi has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0680 FuEngine             uefi_recovery has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0680 FuEngine             upower has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0681 FuEngine             vli_usbhub has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0681 FuEngine             wacom_raw has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
22:00:44:0681 FuEngine             wacom_usb has incorrect built version 8639e382d31cf2c046972eacada8c73c209315226059d2223e2bfc62e3e4e544
Loading…                 [-                                      ]22:00:44:0693 FuPluginUefi         /usr/libexec/fwupd/efi/fwupdx64.efi cannot be found
ERROR:esys:src/tss2-esys/esys_context.c:69:Esys_Initialize() Initialize default tcti. ErrorCode (0x000a000a)
22:00:44:0720 FuEngine             device 602b0a6cc821d155208724f0e22f8d111542b74c [GIGABYTE GP-GSTFS31240GNTD] does not define a vendor-id!
22:00:44:0724 FuEngine             device d88f7134f4194ea510702cc9d18bd0e14a4e77c0 [WDC WD10EZEX-00BN5A0] does not define a vendor-id!
22:00:44:0955 FuEngine             device 7f79a34e07df5677125dce5c4a147e2a7c2c45ef [Unifying Receiver] does define an update protocol
22:00:45:0165 FuEngine             device 7f79a34e07df5677125dce5c4a147e2a7c2c45ef [Unifying Receiver] does define an update protocol
Loading…                 [***************************************]
WARNING: This tool has loaded 3rd party code and is no longer supported by the upstream developers!
No upgrades for Unifying Receiver: No releases found: Bootloader is not compatible
```

**Comment by hughsie** [comment]
The first commit is a no-brainer "LGTM". I wonder if the 2nd commit is required -- async io is more fiddly than direct IO.

**Comment by superm1** [comment]
> The first commit is a no-brainer "LGTM". 

I'll cherry pick the first to master.

>I wonder if the 2nd commit is required -- async io is more fiddly than direct IO.

For the second commit: As I can tell the direct IO doesn't use the timeout at all, which was my suspicion to root cause of this issue in the first place.

**Comment by hughsie** [comment]
> As I can tell the direct IO doesn't use the timeout at all

Doh! Of course, gotcha.

**Comment by superm1** [comment]
> > As I can tell the direct IO doesn't use the timeout at all
> 
> Doh! Of course, gotcha.

However according to #1183 this isn't enough to fix it 😢

**Comment by hughsie** [comment]
@superm1 are these good to go now?

**Comment by superm1** [comment]
I never heard successful testing and I don't have this hardware myself to confirm it. I don't think we should merge it without proper testing.

**Comment by FFY00** [comment]
> I am not able to update nordic signed receivers, which appears to not have updates available. All other variants update fine, though I did not try without the patch.

**Comment by hughsie** [comment]
> All other variants update fine

Good enough for me, thanks.

**Pull request merged**
