### PR TITLE
Hughsie/fdt weirdness

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@sjg20 have you ever seen this before? The `size_dt_struct` is 4 bytes too small on one ChromeOS device we found.

**Comment by hughsie** [comment]
@sjg20 thanks -- can you sanity check my analysis please? I've attached the fdt image. [fdt.zip](https://github.com/user-attachments/files/17880357/fdt.zip)

**Comment by sjg20** [comment]
> @sjg20 thanks -- can you sanity check my analysis please? I've attached the fdt image. [fdt.zip](https://github.com/user-attachments/files/17880357/fdt.zip)

Hi, yes that file seems broken
off_dt_struct = 0x68
size_dt_struct = 22810
so it ends at 22878

But there is another cell at 22878 containing the END tag (9)

Also:
$ fdtgrep -a fdt.bin
Error at 'fdtgrep_find_regions': FDT_ERR_BADSTRUCTURE

It makes me wonder how it was created. Which device is this? it looks like mediatek,mt8188 but says it is unprovisioned.

I would expect the code that produced the FIT (which contains this FDT) to be here:

https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/master/eclass/cros-kernel2.eclass#2252

but that would suggest a bug in mkimage, which seems very strange.

**Comment by fei6409** [comment]
> It makes me wonder how it was created. Which device is this? it looks like mediatek,mt8188 but says it is unprovisioned.

This is a Lenovo Chromebook Duet 11, and the fdt was from a pre-MP device. I think that's why it says it's unprovisioned.

> I would expect the code that produced the FIT (which contains this FDT) to be here:
> 
> https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/master/eclass/cros-kernel2.eclass#2252

More precisely, s/master/main/ as the master branch is stalled: https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/main/eclass/cros-kernel.eclass#3043

But anyways, it still calls `mkimage` to produce the image, so that doesn't matter much I believe.

> but that would suggest a bug in mkimage, which seems very strange.

AFAICT it's not just an one-off. I can see the same problem on other MediaTek-based Chromebooks, and even on a Qualcomm one. The ending token (4-byte 0x9) always falls outside of the DT struct range.

**Comment by hughsie** [comment]
Okay, so the problem seems pretty widespread. I think we should probably just do a console warning in that case: https://github.com/fwupd/fwupd/pull/8163

**Comment by jwerner-chromium** [comment]
This is a bug in our bootloader, not in mkimage. We unpack and rebuild the FDT on boot to make it easier to manipulate, and it seems like we've always done it wrong. We can fix it going foward (https://review.coreboot.org/c/coreboot/+/85460), but existing Chromebooks will likely always have this issue unless it turns out to be a major problem, since bootloader updates are expensive for us.

**Comment by hughsie** [comment]
@jwerner-chromium I really appreciate you debugging this and pushing the proper fix upstream.

**Pull request closed without merging**
