### PR TITLE
Wip/hughsie/fmap harder

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]

**Comment by hughsie** [comment]
@bleungatchromium can you please test this with some real life fmap files please?

**Comment by bleungatchromium** [comment]
Will do. I'll sync to the latest and give this a try.

**Comment by bleungatchromium** [comment]
This worked fine for me for the 3 or 4 fmap firmware files I tried, fwiw. Thanks!

**Comment by hughsie** [comment]
@bleungatchromium in case you were wondering I've been fuzzing everything pretty hard. I've spent a bit of time working out how to integrate fwupd with oss-fuzz too; WIP.

**Comment by bleungatchromium** [comment]
Sounds good... might be a good idea to take the changes here and port them back to Google's flashmap implementation too...

**Pull request merged**
