### PR TITLE
Fix bash completion

### PR DESCRIPTION
**Pull request by superm1**
Thanks @exploide for the notification it was broken.  Resolve `get-devices` and `get-remotes` output to work properly.  Hopefully by slicing and dicing `fwupdagent` output the `get-devices` is less likely to break in the future.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Why do we get the extra arguments? Seems a bit of a hack...

**Comment by superm1** [comment]
> Why do we get the extra arguments? Seems a bit of a hack...

It's intentional - so you don't just get a list of `DeviceID`s and need to remember which one goes to which device.

Right now it's like this (paraphrased):
```
# fwupdgr install file.cab <tab>
432c5bc1-9a04-4cd8-aa20-d02f39410d4c { System Firmware }
5ebbaa00-2f49-4bf6-8dd9-66d1e753c314 { UEFI Device Firmware }
```

So if you don't print what they are, how will you know what to pick?

**Comment by hughsie** [comment]
So can we handle the '{' argument detection in the values[] parsing rather than in each cmd?

**Comment by superm1** [comment]
> So can we handle the '{' argument detection in the values[] parsing rather than in each cmd?

Sure, that should be fine.

**Comment by superm1** [comment]
> > So can we handle the '{' argument detection in the values[] parsing rather than in each cmd?
> 
> Sure, that should be fine.

Although it doesn't land in the same point in the array for both `install` and `activate` commands, so maybe not.

**Comment by hughsie** [comment]
Sure, but we could just set the first '{' to NULL, right?

**Comment by superm1** [comment]
> Sure, but we could just set the first '{' to NULL, right?

Ah yeah, good point. Thanks.

**Comment by exploide** [comment]
Are you sure that `command fwupdagent get-devices` will work out of the box? I get `bash: fwupdagent: command not found` because `fwupdagent` is in `/usr/libexec/fwupd/fwupdagent` which is not in `$PATH` by default.

**Comment by exploide** [comment]
To reply to your comment from #1830

> It's too bad jq isn't in most distros by default. I would say that is a better way to parse fwupdagent stuff so this doesn't break in future.

True. But I have seen other completion scripts using python for processing JSON. Checking first if `python` is available and then doing something like `/usr/libexec/fwupd/fwupdagent get-devices | python -S -c 'import json, sys; data = json.load(sys.stdin); print("\n".join(d["DeviceId"] for d in data["Devices"]))'`. The assumption here is that Python is available on most Linux installations.

But your approach might be robust enough and relying on a external program also has its downsides...

**Comment by superm1** [comment]
> Are you sure that `command fwupdagent get-devices` will work out of the box? I get `bash: fwupdagent: command not found` because `fwupdagent` is in `/usr/libexec/fwupd/fwupdagent` which is not in `$PATH` by default.

It changed in https://github.com/fwupd/fwupd/commit/bf6d4556877573641f63d1b957986d6927f045b5

> usr/libexec/fwupd/fwupdagent get-devices | python -S -c 'import json, sys; data = json.load(sys.stdin); print("\n".join(d["DeviceId"] for d in data["Devices"]))'

Lets see if my approach breaks anywhere.  If it does, something like what you proposed will work, but we need to print the `{ }` and `Name` attributes too.

**Comment by superm1** [comment]
> I fixed up a tiny leak, hope that's okay. If you squash them down (to 1 commit?) then LGTM, thanks.

Thanks!  I squashed it all to 1.

**Pull request merged**
