### PR TITLE
Hughsie/private flags

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by CragW** [comment]
If the display controller (screen) in idle state e.g.: within a remote session, a error message will be displayed.  Is it because the i2c device isn't ready to open?

```
13:46:16.600 FuEngine             failed to add device /sys/devices/pci0000:00/0000:00:02.0/drm/card1/card1-DP-2: failed to setup: invalid controller type: failed to read from port 0x0000: Remote I/O error
```

**Comment by hughsie** [comment]
> If the display controller (screen) in idle state e.g.: within a remote session, a error message will be displayed. Is it because the i2c device isn't ready to open?

I'd guess because the i2c device is powered down.

**Review by CragW — APPROVED** [review]

**Comment by superm1** [comment]
> > If the display controller (screen) in idle state e.g.: within a remote session, a error message will be displayed. Is it because the i2c device isn't ready to open?
> 
> I'd guess because the i2c device is powered down.

This brings up an interesting question I have.  What happens if the daemon starts while display is in idle?  Probe fails presumably, but is there an event that comes in later that it picks up and probe succeeds?

**Comment by superm1** [comment]
> I've never considered this (I've only ever TeamViewer'd into a remote system) -- I assume it's not handled well.

Yeah I think Crag will need to do some testing with this on the real hardware directly.  If it's not getting handled well it's worth checking what netlink events do come in that we can latch on.

**Pull request merged**
