### PR TITLE
trivial: debian: Don't use --parents when rmdir'ing /var/*/fwupdate

### PR DESCRIPTION
**Pull request by dannf**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [X ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
Can you please submit this to master too?

**Comment by dannf** [comment]
On Tue, Jan 21, 2020 at 2:51 PM Mario Limonciello
<notifications@github.com> wrote:
>
> Can you please submit this to master too?

hm.. I don't see the code I modified in master.

  -dann

**Comment by superm1** [comment]
https://github.com/fwupd/fwupd/blob/64d868a77bc98f1e801c93a07c05e84548fc8ce4/contrib/debian/fwupd.postinst#L32

**Comment by dannf** [comment]
> https://github.com/fwupd/fwupd/blob/64d868a77bc98f1e801c93a07c05e84548fc8ce4/contrib/debian/fwupd.postinst#L32

Well, yeah - now that I git pulled I see it :) Thanks @superm1 !

**Pull request merged**
