### PR TITLE
steelseries: Convert to rustgen

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@d4s i don't need detailed review (over 1000 lines!) but I need you to check it doesn't break any hardware please -- there are also a couple of FIXMEs of odd bits that I noticed.

**Comment by d4s** [comment]
> @d4s i don't need detailed review (over 1000 lines!) but I need you to check it doesn't break any hardware please -- there are also a couple of FIXMEs of odd bits that I noticed.

argh!
Sorry, I missed that PR somehow.
Will do the testing tomorrow with all supported HW, hopefully I have it on hands.

**Comment by hughsie** [comment]
@d4s did I break the world? :)

**Comment by d4s** [comment]
@hughsie sorry for a delay. Looks like partially broken.
- Arctis 5 Nova : ok, both dongle and device
- Aerox 3 Dongle: ok
- Aerox 3 Mouse (USB mode): ok
- Aerox 3 Wireless Mouse via USB Receiver -- incorrect erasing
- Stratus+ -- not detected
- Stratus Duo -- not detected
- Rival 3 were failed with segfault:
```
16:43:52.958 FuPluginSteelSeries  Request:
85 00 02 00 00 00 00 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
16:43:52.974 FuPluginSteelSeries  Request:
83 00 00 00 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
/home/lxdhome/d4s/work/fwupd/fwupd_steelseries_nova5/venv/bin/fwupd: строка 45: 965361 Ошибка сегментирования                   ${SUDO} ${ENV} ${DEBUG} ${EXE} "$@"
```

-----

Not related to the PR, but:
```
$ fwupdmgr update
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade Aerox 3 Wireless USB Receiver from 1.4.2 to 1.11.4?                  ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ This stable release fixes the following issue:                               ║
║                                                                              ║
║ • Fix issue with wireless connection dropping during use                     ║
║                                                                              ║
║ Aerox 3 Wireless USB Receiver and all connected devices may not be usable    ║
║ while updating.                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝
Perform operation? [Y|n]: 
Downloading…             [*********************************      ]
checksum invalid, expected 9881ab0f42c7dbb6b131149ec48b1a744836b003321be1840db7ba405ba2908b got 596d1032e7c916822ffae84a48d5f84d641808be761723536c0d82bb83ac077f
```

**Comment by hughsie** [comment]
Bleh. Can you attach a backtrace of the segfault please, and a fwupdtool get-updates -vv of the stratus please

**Comment by hughsie** [comment]
@d4s i've pushed two fixes for the two obvious crashers.

**Comment by hughsie** [comment]
@d4s hey, can you re-test this with all the steeelseries hardware you have please? I'd also love emulation data for as many of them as possible too -- e.g. https://github.com/fwupd/fwupd/blob/main/docs/device-emulation.md

**Comment by d4s** [comment]
@hughsie thanks for the ping.
Let me check why devices are not working as expected.

Tried to save but got emulation error, so not added emulation data:
```
Could not check for auth: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.fwupd.emulation-save is not registered
```

# Current status
<google-sheets-html-origin>
Device | Mode | Update | Version 
-- | -- | -- | -- 
Nova 5 Dongle | USB | Ok | [1.7.0](https://fwupd.org/downloads/26aa1d86f34f8e86bb15ba8f563c26b307323a769d3ec36085e5dda14fb56289-SteelSeries_Nova_5_Dongle_1.7.0.cab)
Nova 5 Headset | USB-C | Ok | [1.7.0](https://fwupd.org/downloads/6317a70eef744dabe4d70931962da42fd419bdebe5436dcf939a889782fe33e1-SteelSeries_Nova_5_Headset_1.7.0.cab)
Aerox 3 Mouse | USB-C | Ok | [1.11.4](https://fwupd.org/downloads/758d2461fadbfac3f953f74bf03bcba98a7353e0db5346157c39be079e40e5b4-aerox-3-wireless-mouse.cab)
Aerox 3 Mouse | via dongle | Ok | [1.11.4](https://fwupd.org/downloads/758d2461fadbfac3f953f74bf03bcba98a7353e0db5346157c39be079e40e5b4-aerox-3-wireless-mouse.cab)
Aerox 3 Mouse | BT | Not detected | [1.11.4](https://fwupd.org/downloads/758d2461fadbfac3f953f74bf03bcba98a7353e0db5346157c39be079e40e5b4-aerox-3-wireless-mouse.cab)
Aerox 3 Dongle | USB | Ok | [1.11.4](https://fwupd.org/downloads/9881ab0f42c7dbb6b131149ec48b1a744836b003321be1840db7ba405ba2908b-aerox-3-wireless-dongle.cab)
Rival 3 Wireless | via dongle | Segfault | [1.4](https://fwupd.org/downloads/77f9ba023f478a64e1c82012aa8e1030089586220845c808c640de87225b0e84-SteelSeries_Rival_3_Wireless_1.4.cab)
Stratus Duo Dongle | USB | Not detected | [1.75](https://fwupd.org/downloads/10521cfeed9086a597892469fbff79ab5d9b83d3b062f606a8ab6bf34664f6dd-steelseries-stratusduorx-1.75.cab)
Stratus Duo Gamepad | USB | Not detected | [1.75](https://fwupd.org/downloads/ecc54ffe68eebb0e5d77604683df698e7c15911421eee960d2876c175a2aa164-steelseries-stratusduo-1.75.cab)
Stratus+ Gamepad | USB-C | Not detected | [2.12](https://fwupd.org/downloads/e15807fe1878fe3f145eeabf1e175b7f02ad5a12e4ed7249ab03d4a5d7b6449d-steelseries-stratusplus-2.12.cab)

**Comment by superm1** [comment]
> Could not check for auth: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.fwupd.emulation-save is not registered

FWIW I've hit this too.  It's because we need to register the PK outside of the dev env.

Can you please try to copy `org.freedesktop.fwupd.policy` into the host filesystem in `/usr/share/polkit-1/actions/`?

We might need to do something like this in `contrib/setup` to make getting emulation data easier until distros have 2.x. in the rootfs.

**Comment by d4s** [comment]
> Can you please try to copy `org.freedesktop.fwupd.policy` into the host filesystem in `/usr/share/polkit-1/actions/`?

@superm1 that works, thank you! But oh!

**Comment by superm1** [comment]
> > Can you please try to copy `org.freedesktop.fwupd.policy` into the host filesystem in `/usr/share/polkit-1/actions/`?
> 
> @superm1 that works, thank you! But oh!

Great!  I've opened up https://github.com/fwupd/fwupd/pull/8028 to make it automagic next time.  If we end up having to change again I might instead to a checksum compare, but this should be good enough for now.

**Comment by d4s** [comment]
Fixed almost all devices, except the final stage for Aerox 3 in BT mode (see below).

Attaching the emulation data for all supported devices -- sorry, have access only to development variant of Nova headset to add to assets: 

[aerox-3-wireless-dongle_1.11.4_USB-C.emulation.zip](https://github.com/user-attachments/files/17625114/aerox-3-wireless-dongle_1.11.4_USB-C.emulation.zip)
[aerox-3-wireless-mouse_1.11.4_USB-C.emulation.zip](https://github.com/user-attachments/files/17625116/aerox-3-wireless-mouse_1.11.4_USB-C.emulation.zip)
[SteelSeries_Rival_3_Wireless_1.4.emulation.zip](https://github.com/user-attachments/files/17625122/SteelSeries_Rival_3_Wireless_1.4.emulation.zip)
[SteelSeries_Nova_5_Dongle_1.7.0.emulation.zip](https://github.com/user-attachments/files/17625118/SteelSeries_Nova_5_Dongle_1.7.0.emulation.zip)
[SteelSeries_Nova_5_Headset_1.7.0_USB-C.emulation.zip](https://github.com/user-attachments/files/17625119/SteelSeries_Nova_5_Headset_1.7.0_USB-C.emulation.zip)
[steelseries-stratusduo-1.75.emulation.zip](https://github.com/user-attachments/files/17625124/steelseries-stratusduo-1.75.emulation.zip)
[steelseries-stratusduorx-1.75.emulation.zip](https://github.com/user-attachments/files/17625126/steelseries-stratusduorx-1.75.emulation.zip)
[steelseries-stratusplus-2.12.emulation.zip](https://github.com/user-attachments/files/17625127/steelseries-stratusplus-2.12.emulation.zip)

-----

- Aerox 3 mouse via dongle -- emulation is not supported

-----

- Aerox 3 mouse in BT mode.

I fixed the device detection, but it is not properly updating in USB mode after the requesting user to attach via USB-C:

1. In CAB files at LVFS absent entry for `14b18a05-6162-58f6-bae4-a6ff3c8b66c1` (`HIDRAW\VEN_0111&DEV_183A`) -- hence user never got the notification if he is working in BT mode only.
2. After the request, attaching via USB-C and successful update and attach it is failing on reload:

```
Action Required: Aerox 3 Wireless Mouse via Bluetooth needs to be manually connected either via the USB cable, or via the 2.4G USB Wireless adapter to start the update. Please plug either the USB-C cable and put the switch button underneath to off, or the 2.4G USB Wireless adapter and put the switch button underneath to 2.4G.
....
failed to reload: failed to get device before update reload: device ID 4cfe6aadbfa9a73efece0e4c1f08d0fcd22dd20e was not found
```
The version updated to the target.

**Review by d4s — APPROVED** [review]
@hughsie at least everything works for now

**Comment by hughsie** [comment]
@d4s many many thanks for all that -- I'll rebase this branch and add the emulation data in the right place.

**Pull request merged**
