### PR TITLE
trivial: Fix the tests on s390x

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
Can I see the actual failure?

**Comment by hughsie** [comment]
Sure! https://koji.fedoraproject.org/koji/getfile?taskID=93975142&volume=DEFAULT&name=build.log&offset=-4000

**Comment by superm1** [comment]
Hmm, wouldn't it be better to expect that warning and run more of the test?

**Comment by hughsie** [comment]
> Hmm, wouldn't it be better to expect that warning and run more of the test?

I don't think it's going to work. I don't think we're going to find many s390x machines running on Synaptics MST-capable hardware...

**Comment by superm1** [comment]
> > Hmm, wouldn't it be better to expect that warning and run more of the test?
> 
> I don't think it's going to work. I don't think we're going to find many s390x machines running on Synaptics MST-capable hardware...

That's a good point.  Maybe we shouldn't be compiling the plugin even for that architecture then too..

**Comment by hughsie** [comment]
>  Maybe we shouldn't be compiling the plugin even for that architecture then too

I think the firmware parsing tests are maybe useful, but otherwise I don't mind.

**Comment by hughsie** [comment]
I'm not sure s390x even has working USB FWIW. Maybe it doesn't make sense at all.

**Comment by superm1** [comment]
> I'm not sure s390x even has working USB FWIW. Maybe it doesn't make sense at all.

oh you mean like axe fwupd for s390x all together?

**Comment by hughsie** [comment]
> oh you mean like axe fwupd for s390x all together?

Maybe; my worry is that it might get a bit political inside Red Hat. I'm erring on merging this, and testing the waters in Fedora.

**Comment by superm1** [comment]
> Maybe; my worry is that it might get a bit political inside Red Hat. I'm erring on merging this, and testing the waters in Fedora.

If you're gonna keep s390x I'd say axe this whole plugin, we can nickle and dime it away on breakages.

**Comment by hughsie** [comment]
Lets just use the DMI data we use in the libfwupdplugin self tests. Fixed!

**Review by superm1 — APPROVED** [review]

**Pull request merged**
