### PR TITLE
trivial: Add device-test for Steelseries Rival 3 Wireless

### PR DESCRIPTION
**Pull request by gportay**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [x] Feature
- [ ] Documentation

This adds a Json device-test for the Steelseries Rival 3 Wireless device.

### CODE REVIEW

**Comment by gportay** [comment]
@hughsie The cabinet files live in an embargo remote for now. Should I wait for them moved to stable?

**Review by hughsie — APPROVED** [review]

**Comment by gportay** [comment]
> That's fine, but can you give me the LVFS URL and I'll mark them as immutable so they don't get garbage collected when things get modified.

The URL are in the file already:

https://fwupd.org/downloads/fe3775d33b41898e69f06698ed03779a158d99b9716a9b1c0ee7e3051ab857c3-SteelSeries_Rival_3_Wireless_1.0.cab

and

https://fwupd.org/downloads/89791626948cb485e15d093ac47c7823d5ad6a7dcbe8b9917a3711f5c8694d52-SteelSeries_Rival_3_Wireless_0.20.cab

OOI, how is generated the "checksum" before the filename? why it changes?

**Comment by hughsie** [comment]
> how is generated the "checksum" before the filename? why it changes?

It's the SHA256 ish of the upload -- it makes the filename impossible to guess (e.g. if i wanted the hypothetical embargoed `SteelSeries_Rival_3_Wireless_2.0.cab`, and makes the CDN work much nicer as different file versions have different requests.

**Comment by hughsie** [comment]
I've marked both as immutable BTW.

**Pull request merged**
