### PR TITLE
bios: Only compile when UEFI is available

### PR DESCRIPTION
**Pull request by hughsie**
We're telling people on PPC64 to switch to UEFI mode...

### CODE REVIEW

**Comment by superm1** [comment]
Is it useful to still have the plugin but instead to use something like `HAVE_UEFI` to control whether or not `fu_plugin_bios_create_dummy` uses `NULL` for `reason` perhaps?

**Comment by hughsie** [comment]
> Is it useful to still have the plugin

What would it do? compiling with `-Dplugin_uefi` is basically saying "I don't have UEFI" and thus are unable to get updates using capsule for instance.

**Comment by superm1** [comment]
>What would it do? compiling with -Dplugin_uefi is basically saying "I don't have UEFI" and thus are unable to get updates using capsule for instance.

"Information only"
No different then the `tpm` or `cpu` plugin.  It just shows tpm version or cpu microcode version.

**Comment by hughsie** [comment]
> Information only

Ahh, in this case we don't even have FU_HWIDS_KEY_BIOS_VERSION as we only support SMBIOS rather than DT. I've asked the company driving this forward to provide the mapping between DT attributes and the HWID values we use.

Perhaps the right thing to do here is:

 * Set up the DT mapping for the HWIDs (which we might need in the future for other reasons)
 * Somehow conventionalize the `Firmware can not be updated in legacy BIOS mode, switch to UEFI mode` on being x64 and ix86 specific.

Note, it also doesn't make sense to talk about BIOS mode for ARM too, right?

**Comment by superm1** [comment]
Right

**Review by superm1 — APPROVED** [review]

**Pull request merged**
