### PR TITLE
Wip/hughsie/bios attr crash

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — APPROVED** [review]

**Comment by superm1** [comment]
BTW - can you add your system into the test cases with this empty attribute?

**Comment by superm1** [comment]
(Or just the bad attribute if that makes more sense)

**Comment by hughsie** [comment]
It was actually in ninja test, just with `-Db_sanitize=address,undefined` -- we should probably choose a CI target and do that there. Fedora perhaps?

**Comment by superm1** [comment]
Sure, sounds good.

**Comment by hughsie** [comment]
https://github.com/fwupd/fwupd/pull/4884

**Pull request merged**
