### PR TITLE
Fixups for pcap2emulation

### PR DESCRIPTION
**Pull request by superm1**
This get the Ally Windows dump into something that actually "loads" by fwupd.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
This is so much closer to working.

AFAICT At this point it looks like the remaining problem is that fwupd doesn't know what to do with giant buffers filled with garbage from Windows but the hardware doesn't really need.

This is with the converted emulation:
```
03:47:49.296 FuHidDevice          HID::SetReport [wValue=0x035a, wIndex=2]:5a d1 01 01 01 00 
03:47:49.296 FuEngine             failed to add device 1-3: failed to setup: failed to initialize device: failed to send packet: failed to SetReport: no event with ID ControlTransfer:Direction=0x01,RequestType=0x01,Recipient=0x01,Request=0x09,Value=0x035a,Idx=0x0002,Data=WtEBAQEA,Length=0x6
```

I'm not sure we can programmatically know what's junk and what's not, so manual fixups might be the only way.

**Comment by superm1** [comment]
Oh and here is that same control transfer converted from the script.  You can see the garbage in it.

```
        {
          "Id" : "ControlTransfer:Direction=0x01,RequestType=0x01,Recipient=0x01,Request=0x09,Value=0x035a,Idx=0x0002,Data=WtEBAQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==,Length=0x40",
          "Data" : "WtEBAQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
        },
```

**Comment by hughsie** [comment]
> I'm not sure we can programmatically know what's junk and what's not, so manual fixups might be the only way.

I think that's very true.

**Comment by superm1** [comment]
> > I'm not sure we can programmatically know what's junk and what's not, so manual fixups might be the only way.
> 
> I think that's very true.

OK, then in that case I think this PR is ready to go.

**Review by hughsie — APPROVED** [review]
I'm not qualified, but these look good to me -- thanks.

**Comment by superm1** [comment]
> I'm not qualified, but these look good to me -- thanks.

Thanks.  If there are any issues @fdanis-oss finds I'll follow up with them later.

**Pull request merged**
