### PR TITLE
Export the build timestamp from plugins

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
I'm not exactly convinced with the `build_timestamp` name. It's meant to be the "`date and time the firmware was built`" and seems to be hugely important to server vendors for some reason.

**Review by superm1 — COMMENTED** [review]
Everywhere it's `build_timestamp` I think it should explicitly be `fw_build_timestamp` to disambiguate manufacturing date and show that it's the firmware's build date

**Comment by hughsie** [comment]
> fw_build_timestamp

I'm not sure about that; we have `firmware` rather than `fw` everywhere in the API now. `firmware_build_timestamp` is kinda long. Some other ideas:

 * build_timestamp
 * build_version
 * build_created
 * version_timestamp
 * version_date
 * version_created
 * version_built
 * version_release
 * version_build
 * version_created

Other ideas certainly welcome.

**Comment by superm1** [comment]
> * version_created

That one is my favorite of those.  Or how about `firmware_build_date`

**Comment by hughsie** [comment]
> version_created

Actually, that's probably the most correct answer given we already have a `created` property on the release.

	/**
	 * fwupd_release_get_created:
	 * @self: a #FwupdRelease
	 *
	 * Gets when the update was created.
	 *
	 * Returns: UTC timestamp in UNIX format, or 0 if unset
	 *
	 * Since: 1.4.0
	 **/

**Comment by hughsie** [comment]
> given we already have a created property on the release

Actually that's not quite true; the created property seems to be the timestamp of the FuRelease creation, i.e. when the object was allocated. It might be confusing to have two integer properties with the same name and different semantics.

What about `version_date`? I think that's clearer.

**Comment by superm1** [comment]
I personally think it's worth biting the bullet and having a longer variable name than trying to understand what two somewhat related words mean

**Comment by hughsie** [comment]
> having a longer variable name

Fair point. The problem I have with `firmware_build_date` is that we don't have `firmware_version` or `firmware_serial` -- the fact that it's of the firmware is implicit. Maybe `version_build_date`, `version_build_timestamp` or `version_built_date` as a compromise?

**Comment by superm1** [comment]
Yup any of those last 3 sound good

**Pull request merged**
