### PR TITLE
Get the SMBIOS table on Windows

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/4253

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@nnecros2k7 can you try the .exe file generated by the `ci/circleci: build-windows` CI run please?

**Comment by necros2k7** [comment]
> @necros2k7 can you try the .exe file generated by the `ci/circleci: build-windows` CI run please?

what path exactly? 
here are no artifacts:
https://app.circleci.com/pipelines/github/fwupd/fwupd/8916/workflows/2234f06c-e06c-4812-a681-f15ec7cf4032/jobs/32645/artifacts

**Comment by hughsie** [comment]
@necros2k7 https://32645-31374735-gh.circle-artifacts.com/0/dist/setup/fwupd-1.7.5-setup-x86_64.exe

**Review by superm1 — DISMISSED** [review]
I think if the return codes less than zero means something they should be in the error message. Otherwise lgtm

**Comment by hughsie** [comment]
> they should be in the error message

Ahh yes, GetLastError() to the rescue. Fixed.

**Review by superm1 — APPROVED** [review]

**Comment by necros2k7** [comment]
> @necros2k7 https://32645-31374735-gh.circle-artifacts.com/0/dist/setup/fwupd-1.7.5-setup-x86_64.exe

thanx but how did you find it for future reference? it`s not obvious

**Comment by hughsie** [comment]
> but how did you find it for future reference

It doesn't show up in the artefacts section in the CI? e.g. https://app.circleci.com/pipelines/github/fwupd/fwupd/8919/workflows/c42fa5fc-34ed-4f59-949e-e578d8ef4534/jobs/32655/artifacts

**Comment by necros2k7** [comment]
Sorry I looked wrong direction - https://github.com/fwupd/fwupd/actions/workflows/main.yml

**Pull request merged**
