### PR TITLE
trivial: Explicitly look for `AMDGPU_INFO_VBIOS_INFO` to enable amd-gpu plugin

### PR DESCRIPTION
**Pull request by superm1**
Fixes: https://github.com/fwupd/fwupd/issues/6246

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
@sam412081go hopefully this fixes it for you since I CND.

**Comment by sam412081go** [comment]
@superm1 
I use your commit (7a6df5c230acbcd8a612c072fda9d9788678e65f).
still failing to compile.

My gio version is "2.68.1"
```
sdrf@OA-109048:~/fwupd_fw2_20231006/fwupd/build$ gio version
2.68.1
```

```
sdrf@OA-109048:~/fwupd_fw2_20231006/fwupd/build$ sudo ninja
[344/1118] Compiling C object plugins/amd-gpu/libfu_plugin_amd_gpu.a.p/fu-amd-gpu-device.c.o
FAILED: plugins/amd-gpu/libfu_plugin_amd_gpu.a.p/fu-amd-gpu-device.c.o 
ccache cc -Iplugins/amd-gpu/libfu_plugin_amd_gpu.a.p -Iplugins/amd-gpu -I../plugins/amd-gpu -I. -I.. -Ilibfwupd -I../libfwupd -Ilibfwupdplugin -I../libfwupdplugin -Isubprojects/libxmlb/src -I../subprojects/libxmlb/src -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/p11-kit-1 -I/usr/include/gudev-1.0 -I/usr/local/include/gusb-1 -I/usr/include/libusb-1.0 -I/usr/include/json-glib-1.0 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -Waggregate-return -Wunused -Warray-bounds -Wcast-align -Wclobbered -Wdeclaration-after-statement -Wdiscarded-qualifiers -Wduplicated-branches -Wduplicated-cond -Wempty-body -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-signedness -Wignored-qualifiers -Wimplicit-function-declaration -Wimplicit-int -Winit-self -Wint-conversion -Wlogical-op -Wmaybe-uninitialized -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-parameter-type -Wmissing-prototypes -Wnested-externs -Wno-cast-function-type -Wno-address-of-packed-member -Wno-unknown-pragmas -Wno-missing-field-initializers -Wno-strict-aliasing -Wno-suggest-attribute=format -Wno-unused-parameter -Wold-style-definition -Woverride-init -Wpointer-arith -Wredundant-decls -Wreturn-type -Wshadow -Wsign-compare -Wstrict-aliasing -Wstrict-prototypes -Wswitch-default -Wtype-limits -Wundef -Wuninitialized -Wunused-but-set-variable -Wunused-variable -Wvla -Wwrite-strings -fstack-protector-strong -DFWUPD_COMPILATION -D_DEFAULT_SOURCE -D_BSD_SOURCE -D__BSD_VISIBLE -D_XOPEN_SOURCE=700 -D_GNU_SOURCE -D_DARWIN_C_SOURCE=900000 -fPIC -pthread '-DG_LOG_DOMAIN="FuPluginAmdGpu"' -MD -MQ plugins/amd-gpu/libfu_plugin_amd_gpu.a.p/fu-amd-gpu-device.c.o -MF plugins/amd-gpu/libfu_plugin_amd_gpu.a.p/fu-amd-gpu-device.c.o.d -o plugins/amd-gpu/libfu_plugin_amd_gpu.a.p/fu-amd-gpu-device.c.o -c ../plugins/amd-gpu/fu-amd-gpu-device.c
../plugins/amd-gpu/fu-amd-gpu-device.c: In function ‘fu_amd_gpu_device_setup’:
../plugins/amd-gpu/fu-amd-gpu-device.c:111:31: error: storage size of ‘vbios_info’ isn’t known
  111 |  struct drm_amdgpu_info_vbios vbios_info;
      |                               ^~~~~~~~~~
../plugins/amd-gpu/fu-amd-gpu-device.c:115:28: error: invalid application of ‘sizeof’ to incomplete type ‘struct drm_amdgpu_info_vbios’
  115 |      .return_size = sizeof(struct drm_amdgpu_info_vbios),
      |                            ^~~~~~
../plugins/amd-gpu/fu-amd-gpu-device.c:116:25: error: ‘AMDGPU_INFO_VBIOS_INFO’ undeclared (first use in this function); did you mean ‘AMDGPU_INFO_VBIOS_IMAGE’?
  116 |      .vbios_info.type = AMDGPU_INFO_VBIOS_INFO,
      |                         ^~~~~~~~~~~~~~~~~~~~~~
      |                         AMDGPU_INFO_VBIOS_IMAGE
../plugins/amd-gpu/fu-amd-gpu-device.c:116:25: note: each undeclared identifier is reported only once for each function it appears in
../plugins/amd-gpu/fu-amd-gpu-device.c:111:31: warning: unused variable ‘vbios_info’ [-Wunused-variable]
  111 |  struct drm_amdgpu_info_vbios vbios_info;
      |                               ^~~~~~~~~~
[353/1118] Generating plugins/uefi-capsule/ux-capsule-tar with a custom command
ninja: build stopped: subcommand failed.

```

**Comment by superm1** [comment]
I'm not sure where you got stuck gio version in old Ubuntu.

Anyways issue I believe must be kernel header, what version of kernel do you have installed?

**Comment by superm1** [comment]
Ah I can reproduce if I downgrade linux-libc-dev in Ubuntu 22.04 to 5.4.0-164.181 match Ubuntu 20.04, I'll come up with a fix. 
 thanks!

**Review by hughsie — APPROVED** [review]

**Pull request merged**
