### PR TITLE
dfu: Add a quirk for Realtek camera hardware

### PR DESCRIPTION
**Pull request by hughsie**
100% untested until hardware arrives.

### CODE REVIEW

**Comment by superm1** [comment]
Not sure it's helpful - but at least with master if I run with `--plugin-whitelist=dfu` on a notebook that I know had a Realtek camera I can get this DFU device:

```
DfuDevice:
Integrated Webcam HD
  DeviceId:             51a5f0521bddd3e9d93388f831b2b5ffdf225d9a
  Guid:                 9a1becb6-4d9f-5855-99d0-145b1700da10 <- USB\VID_0BDA&PID_58FE&REV_9628
  Guid:                 d35eb209-22f9-59a5-a918-33d7307edab9 <- USB\VID_0BDA&PID_58FE
  Serial:                
  Plugin:               dfu
  Flags:                registered
  Vendor:               Integrated_Webcam_HD
  VendorId:             USB:0x0BDA
  Version:              96.28
  VersionFormat:        bcd
  Icon:                 drive-harddisk-usb
  Created:              2019-10-18
  PhysicalId:            usb:00:09
  State:                 appIDLE
  Status:                OK
  DoneUploadOrDownload:  false
  ClaimedInterface:      false
  Version:               0x110
  Force_version:         0x0
  RuntimePid:            0x58fe
  RuntimeVid:            0xbda
  RuntimeRelease:        0x9628
  TransferSize:          0x1000
  IfaceNumber:           0x4
  DnloadTimeout:         0x0
  TimeoutMs:             0x5dc
```

Doesn't show up without `plugin-whitelist=dfu` though.

**Comment by superm1** [comment]
And if I run detach on it, it pops out in `0bda:5800` which makes me wonder if you have a typo in your PR: `CounterpartGuid = USB\VID_0B0E&PID_5800`

**Comment by superm1** [comment]
Yep, detach doesn't work right now, fixing the typo and then applying that quirk from your branch I can go back and forth.

**Comment by hughsie** [comment]
> I notice that FWUPD_DEVICE_FLAG_UPDATABLE is not getting applied though on the regular device

I think that's intentional. I think other devices are only updatable when in bootloader mode.

**Comment by superm1** [comment]
>I think that's intentional. I think other devices are only updatable when in bootloader mode.

But so then you won't know some dfu devices are updatable and have update available unless you manually detach?

**Comment by hughsie** [comment]
It appears we only add the `UPDATABLE` flag when `priv->attributes & DFU_DEVICE_ATTRIBUTE_CAN_DOWNLOAD` -- I assume the DFU runtime doesn't advertise that?

**Comment by superm1** [comment]
Yeah that's what it seems to me.

**Comment by superm1** [comment]
Experimented some more to compare the devices created pre and post detach using fwupdtool.
Pre-detach the only flag it picks up is `registered`, and firmware version is set.  Runtime Release is set to 0x9628 and version gets set to 96.28.  Serial isn't visible in this state.

Once detached:
* Serial shows up
* It gets bootlaoder and updatable flags
* No version string
* No runtime release/runtimepid/runtimevid

**Comment by hughsie** [comment]
Realtek are sending me a range of their hardware to test this with, so I think I'll test with hardware and cab files before we merge this.

**Comment by superm1** [comment]
> Realtek are sending me a range of their hardware to test this with, so I think I'll test with hardware and cab files before we merge this.

Sounds good.  Could you also talk to them about the behavior I'm seeing while the HW is on the way?  With the way the runtime is showing up I don't see how a CAB can possibly work.  You can only detach manually from `fwupdtool` and then you don't get to copy attributes across the detach because the daemon doesn't know that happened.

**Comment by hughsie** [comment]
>  You can only detach manually from fwupdtool

I think logically `UPDATABLE` has to be set unconditionally in DFU runtime and DFU modes, right?

**Comment by superm1** [comment]
Yes and it's definitely not right now.

**Comment by hughsie** [comment]
> Yes and it's definitely not right now.

Does c119a21d2c8af1bf91e27ed29e5692adbded3a02 make sense to you?

**Comment by superm1** [comment]
Yes. But I think we should still detect the missing flag and issue a daemon warning to the logs for this situation perhaps.

**Pull request merged**
