### PR TITLE
Add support for the Belkin Thunderbolt 4 Core Hub dock

### PR DESCRIPTION
**Pull request by hughsie**
Fixes https://github.com/fwupd/fwupd/issues/5829

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by d4s** [comment]
@hughsie Arie (@alebrati) will be able to check the support tomorrow with the real device.

**Comment by hughsie** [comment]
@alebrati I guessed the CcgxDmcTriggerCode -- maybe try `0x2` too?

**Comment by d4s** [comment]
with the 0x01 the output is in attach:
[log2.txt](https://github.com/fwupd/fwupd/files/11721302/log2.txt)

**Comment by alebrati** [comment]
tried with 0x2.
attached full log (journalctl -u fwupd.service &>/tmp/full.log)
[
[full.log](https://github.com/fwupd/fwupd/files/11721866/full.log)
](url)

**Comment by hughsie** [comment]
@alebrati I'll merge this as it looks like it works well to enumerate -- but the update failure looks like because you're using the non-updateable `Devx` component firmware GUID _not_ the GUID of the `DmcDevice` -- can you try again with `d33143ec-1add-5df4-bfc1-bfeee3491762` in the metainfo please?

**Comment by alebrati** [comment]
Hi Richard,
I tried now with updated guid...not i get this failure:

root@yair-935QDB:/home/yair# fwupdtool install --allow-reinstall pd_dmc.cab
Loading…                 [*******************                    ]
WARNING: This package has not been validated, it may not work properly.
Waiting…                 [*********************************      ]

failed to get device before update reload: failed to wait for detach replug: device 42f81e42b1e21ceb211b345766cfd39439cb242f did not come back

**Comment by hughsie** [comment]
can you get me the `-v -v` version of that please -- and question -- does the USB device eventually re-enumerate after a few minutes or is it wait for you to take the cable out and re-insert it?

**Comment by alebrati** [comment]
yes its stay enumerated, no need to disconnect and reconnect.

thats my version. also be noted i use your branch, see below..

root@yair-935QDB:/home/yair# fwupdtool --version
Loading…                 [************************************** ]
WARNING: This package has not been validated, it may not work properly.
compile   org.freedesktop.fwupd         1.9.2
compile   com.hughsie.libxmlb           0.3.6
compile   com.hughsie.libjcat           0.1.9
runtime   org.freedesktop.fwupd-efi     1.9.2
compile   org.freedesktop.gusb          0.3.10
runtime   com.dell.libsmbios            2.4
runtime   org.freedesktop.gusb          0.3.10
runtime   org.kernel                    5.19.0-43-generic
runtime   org.freedesktop.fwupd         1.9.2

root@yair-935QDB:/home/yair/fwupd# git branch
* (HEAD detached at origin/wip/hughsie/belkin-usb4)
  main

**Comment by hughsie** [comment]
> yes its stay enumerated, no need to disconnect and reconnect.

if you disconnect and reconnect does it start the firmware update process and then a few minutes later re-enumerates?

**Comment by alebrati** [comment]
Hi Richard,
should we open a new issue for that ? as that one is closed https://github.com/fwupd/fwupd/issues/5829

**Comment by hughsie** [comment]
I've re-opened that one, thanks.

**Pull request merged**
