### PR TITLE
Backport the thunderbolt overhaul to 1.4.x

### PR DESCRIPTION
**Pull request by superm1**
The plugins should work the same now as 1.5.x does.  This will make enabling retimers and the authenticate on disconnect stuff more widely.

These should both be empty:
```
diff -u $master/plugins/thunderbolt $1_4_x/plugins/thunderbolt
diff -u $master/plugins/dell-dock $1_4_x/plugins/dell-dock
```

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [x] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Dropping the force power stuff does worry me slightly for the stable branch...

**Comment by superm1** [comment]
> Dropping the force power stuff does worry me slightly for the stable branch...

With how many reports there are of failures to come back on older designs, I was thinking it's probably the right thing to do..

**Comment by hughsie** [comment]
> many reports there are of failures to come back on older designs

Remind me, how does this new patch fix that problem? I thought it was a hardware issue...

**Comment by superm1** [comment]
It avoids the issue. 

The issue happens specifically because the device is force powered on. If you keep something connected instead over the update cycle you don't encounter it.

I do agree it's actually either a thunderbolt controller hardware issue or a thunderbolt controller firmware issue though.

**Comment by hughsie** [comment]
> If you keep something connected instead over the update cycle you don't encounter it

Right, I guess on one hand it's ceding defeat to the hardware, but on the other hand it's being pragmatic. I do think we should do this, but we should squash the commits down into something more manageable, and also merge the other PR into the same commit too. We probably ought to make the behaviour change explicit in the commit message too.

**Comment by superm1** [comment]
> > If you keep something connected instead over the update cycle you don't encounter it
> 
> Right, I guess on one hand it's ceding defeat to the hardware, but on the other hand it's being pragmatic. I do think we should do this, but we should squash the commits down into something more manageable, and also merge the other PR into the same commit too. We probably ought to make the behaviour change explicit in the commit message too.

Can you recommend what combination of commits you want squashed?  The other approach is the "merge commit"

**Comment by hughsie** [comment]
> Can you recommend what combination of commits you want squashed

Not easily, so maybe this is a bad idea.

**Pull request merged**
