### PR TITLE
modem-manager: Port to using fu_backend_create_device()

### PR DESCRIPTION
**Pull request by hughsie**
Drag the plugin into the 20th century by removing a lot of udev complexity that isn't needed and porting to fu_backend_create_device().

Note, I've probably broken mhi-pci-generic EDL firmware updates but someone with the hardware will need to add the code to change the mode to ->attach() rather than committing polling crimes in ->write_firmware().

Going forward I want the modem-manager plugin to work in the same way as the other plugins.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
nothing jumps out at me, but probably should pull in some of the people that worked on MM more closely

**Comment by aleksander0m** [comment]
I can review, but not sure I can actually properly test though, I would need to dig into the pile of hardware to find at least the first module I used to work on this plugin. How urgent is this review/test?

**Comment by hughsie** [comment]
> I would need to dig into the pile of hardware to find at least the first module I used to work on this plugin.

That's one of my problems -- I don't have any hardware with updates. I'm actually adding in the "emulate this device" functionality into fwupd this week, but without a device to "record" it's impossible to create.

> How urgent is this review/test?

Not urgent -- I think 2.0.0 is probably going to be followed quite quickly with 2.0.1, 2.0.2 etc as we discover all the other stuff we've broken with the API tidyups.

**Comment by superm1** [comment]
> That's one of my problems -- I don't have any hardware with updates. I'm actually adding in the "emulate this device" functionality into fwupd this week, but without a device to "record" it's impossible to create.

Could you "reinstall" a firwmare to demonstrate it works right?

**Comment by hughsie** [comment]
> Could you "reinstall" a firwmare to demonstrate it works right?

**Comment by hughsie** [comment]
The only device I have here is a preproduction Dell device on a PCIe devboard -- it won't accept any of the firmware payloads currently on the LVFS.

**Comment by hughsie** [comment]
@superm1 any reservations if I merge this so I can get the next "lets grop gudev" PR out? The next patch is the one that unlocks emulation.

**Comment by hughsie** [comment]
> just make sure it's on TODO somewhere

It's already on my {physical} whiteboard of shame.

**Comment by aleksander0m** [comment]
> The only device I have here is a preproduction Dell device on a PCIe devboard

Which one is it? I have a dw5821e, which is the one I originally used to write the MM plugin. I'm fine to give it away if it can be used for testing fwupd.

**Pull request merged**
