### PR TITLE
Remove SecurityReportURI from remote files

### PR DESCRIPTION
**Pull request by hughsie**
We can detect what kind of report is being sent server-side and make everything a lot simpler in fwupd.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
Can/should we update remotes on a system already to drop this field too?

**Comment by hughsie** [comment]
> should we update remotes on a system

**Comment by hughsie** [comment]
I don't think they're harmful, I'd vote for leaving them in case you use old and new fwupd versions with the same remotes configured.

**Comment by hughsie** [comment]
LVFS side here: https://gitlab.com/fwupd/lvfs-website/-/merge_requests/1437

**Pull request merged**
