### PR TITLE
dfu: Fix some unconverted FuProgress usage

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
@amfern could you try this please? If it works okay, you'll also get quite a few of these https://github.com/fwupd/fwupd/wiki/Daemon-Warning:-FuProgress-steps and I'd appreciate the verbose log if so.

**Comment by amfern** [comment]
This is the log I got.

```
dfu-tool write -d 0483:df11 obj/fcos_v3.4.0-a1_HUNTER_V0_DIGITAL_KAKUTEF7.dfu
decompressing:	0%
device-write:	0%
device-busy:	0%
device-erase:	0%
device-write:	0%
device-write:	10%
device-write:	96%
unknown:	96%
device-verify:	96%
device-busy:	96%
device-read:	96%

(dfu-tool:1824569): FuProgress-CRITICAL **: 12:54:35.607: fu_progress_set_percentage_full: assertion 'progress_done <= progress_total' failed

(dfu-tool:1824569): FuProgress-WARNING **: 12:54:35.607: child is at 2/3 step_max and parent done [../plugins/dfu/fu-dfu-target.c:1172]
2) ../plugins/dfu/fu-dfu-device.c:1598 (0/1)
1) ../plugins/dfu/fu-dfu-target.c:1172 (1/2)
0) ../plugins/dfu/fu-dfu-target-stm.c:101 (2/3)

unknown:	96%
unknown:	100%
device-busy:	100%
device-erase:	100%
device-write:	100%
unknown:	100%
device-verify:	100%
device-busy:	100%
device-read:	100%

(dfu-tool:1824569): FuProgress-CRITICAL **: 12:55:09.389: fu_progress_set_percentage_full: assertion 'progress_done <= progress_total' failed
verify failed: got 0x32, expected 0x36 @ 0x81be8
```

**Comment by amfern** [comment]
Is this the verbose log? Do i need to enable verbose log?

**Comment by hughsie** [comment]
@amfern and again please? just add `--verbose` to get the verbose log.

**Comment by amfern** [comment]
Uploaded the log to pastebin https://pastebin.com/RSDxX7KW

**Comment by hughsie** [comment]
@amfern you recompiled after the `f` commit?

**Comment by hughsie** [comment]
can you do the same thing with the latest branch please; fingers crossed

**Comment by amfern** [comment]
i will be afk for a while, will provide with new log abit later

**Comment by hughsie** [comment]
No panic at all, I can dig out my STM32 hardware I used for testing on Monday too.

**Comment by amfern** [comment]
dfu-tool write --verbose -d 0483:df11 obj/fcos_v3.4.0-a1_HUNTER_V0_DIGITAL_KAKUTEF7.dfu
[out.log](https://github.com/fwupd/fwupd/files/7532498/out.log)

dfu-tool write -d 0483:df11 obj/fcos_v3.4.0-a1_HUNTER_V0_DIGITAL_KAKUTEF7.dfu
```
decompressing:	0%
device-write:	0%
device-busy:	0%
device-erase:	0%
device-write:	0%
device-write:	10%
device-write:	96%
unknown:	96%
device-verify:	96%
device-busy:	96%
device-read:	96%

(dfu-tool:1899814): FuProgress-CRITICAL **: 19:58:38.370: fu_progress_set_percentage_full: assertion 'progress_done <= progress_total' failed
device-busy:	96%
device-busy:	99%
unknown:	99%
unknown:	100%
device-busy:	100%
device-erase:	100%
device-write:	100%
unknown:	100%
device-verify:	100%
device-busy:	100%
device-read:	100%

(dfu-tool:1899814): FuProgress-CRITICAL **: 19:59:12.110: fu_progress_set_percentage_full: assertion 'progress_done <= progress_total' failed
device-busy:	100%
unknown:	100%
verify failed: got 0x32, expected 0x36 @ 0x81be8
```

**Comment by hughsie** [comment]
@amfern and now?

**Comment by amfern** [comment]
it works now, but there is no more flash progress
```
dfu-tool write -d 0483:df11 obj/fcos_v3.4.0-a1_HUNTER_V0_DIGITAL_KAKUTEF7.dfu
decompressing:	0%
device-write:	0%
device-busy:	0%
device-erase:	0%
device-erase:	80%
device-write:	80%
device-write:	96%
unknown:	96%
device-verify:	96%
device-busy:	96%
device-busy:	97%
device-read:	97%
device-read:	99%
device-busy:	99%
unknown:	99%
unknown:	100%
device-busy:	100%
device-erase:	100%
device-write:	100%
unknown:	100%
device-verify:	100%
device-busy:	100%
device-read:	100%
device-busy:	100%
unknown:	100%
device-busy:	100%
601076 bytes successfully downloaded to device
```

**Comment by hughsie** [comment]
> but there is no more flash progress

You mean the progress bar thing?

**Comment by amfern** [comment]
Yes, this progress thing that was running when flashing, now it's just show 100% while it flashing

**Comment by hughsie** [comment]
Really, dfu-util is a compat binary that we're really trying to get people to move away from.

Does `sudo fwupdtool install-blob --plugins dfu obj/fcos_v3.4.0-a1_HUNTER_V0_DIGITAL_KAKUTEF7.dfu` work for you?

**Comment by amfern** [comment]
The command works, but the progress bar doesn't.

This is what I see on the start
```
Loading…                 [***************************************]
WARNING: This package has not been validated, it may not work properly.
Selected device: STM32 BOOTLOADER
Writing…                 [ -                                     ]
```
then nothing happens until the DFU is flashed and i see the progress like this
```
Loading…                 [***************************************]
WARNING: This package has not been validated, it may not work properly.
Selected device: STM32 BOOTLOADER
Waiting…                 [***********************************    ]
```

**Comment by hughsie** [comment]
> but the progress bar doesn't

How very strange. I see it fine on my stm32 sispeed test device here. Can you pastebin your `--verbose` log when using fwupdtool please?

**Comment by amfern** [comment]
Of course. Here is the log of 
`sudo fwupdtool --verbose install-blob --plugins dfu obj/fcos_v3.4.0-a1_HUNTER_V0_DIGITAL_KAKUTEF7.dfu`
[out.log](https://github.com/fwupd/fwupd/files/7534706/out.log)

**Comment by hughsie** [comment]
I only see one line :)

**Comment by amfern** [comment]
sorry, my bad :)
[out.log](https://github.com/fwupd/fwupd/files/7534711/out.log)

**Comment by hughsie** [comment]
@amfern and now? Thanks!

**Comment by amfern** [comment]
Its looks different but the progress doesn't move, here is a video of what i see https://www.youtube.com/watch?v=AY8if5XS4mo
```
sudo fwupdtool install-blob --plugins dfu --no-reboot-check obj/fcos_v3.4.0-a1_REMOTE_CONTROL_V2_XTEND_RC_REV01.dfu
Loading…                 [***************************************]
WARNING: This package has not been validated, it may not work properly.
Choose a device:
0.      Cancel
1.      a295c945bbd4533ec94a05f43d7c03c6cad26118 (Dell Universal Dock D6000)
2.      b0a78eb71f4eeea7df8fb114522556ba8ce22074 (STM32 BOOTLOADER)
2
Waiting…                 [***********************************    ]failed to get device before update reload: failed to wait for detach replug: device b0a78eb71f4eeea7df8fb114522556ba8ce22074 did not come back
```
[out.log](https://github.com/fwupd/fwupd/files/7539258/out.log)

**Comment by hughsie** [comment]
@amfern that is very odd indeed. Can you get the log again, but this time do: `sudo FWUPD_VERBOSE=1 fwupdtool install-blob --plugins dfu --no-reboot-check obj/fcos_v3.4.0-a1_REMOTE_CONTROL_V2_XTEND_RC_REV01.dfu` -- its going to be much more verbose :)

**Comment by amfern** [comment]
running without `--verbose` didn't give me much output, so this the command i ran
` sudo FWUPD_VERBOSE=1 fwupdtool  --verbose install-blob --plugins dfu --no-reboot-check obj/fcos_v3.4.0-a1_REMOTE_CONTROL_V2_XTEND_RC_REV01.dfu 2>&1 | tee out.log`

[out.log](https://github.com/fwupd/fwupd/files/7539396/out.log)

**Comment by hughsie** [comment]
@amfern 3326c6cd3939d1bbc4c0e5865554a45903d25338 should fix that critical warning and make the bar go from 50% to 100% correctly -- and dddcbfb237a8e28b7b4f1efd24c46098bdb6a602 should make it approximately linear.

**Comment by amfern** [comment]
dfu-tool works better but fwupdtool doesn't show any progress

```
dfu-tool write -d 0483:df11 obj/fcos_v3.4.0-a1_HUNTER_V0_DIGITAL_KAKUTEF7.dfu
decompressing:	0%
device-write:	0%
device-busy:	0%
device-erase:	0%

device-erase:	40%
device-write:	40%


device-write:	48%
unknown:	48%
device-verify:	48%
device-busy:	48%


device-read:	48%
device-read:	49%
device-busy:	49%
unknown:	49%
device-verify:	49%
device-verify:	50%
unknown:	50%
device-write:	50%
device-busy:	50%
device-erase:	50%
device-erase:	56%
device-erase:	63%
device-erase:	70%
device-erase:	76%
device-erase:	83%
device-erase:	90%
device-write:	90%
device-write:	91%
device-write:	92%
device-write:	93%
device-write:	94%
device-write:	95%
device-write:	96%
device-write:	97%
device-write:	98%
unknown:	98%
device-verify:	98%
device-busy:	98%
device-read:	98%
device-read:	99%
device-busy:	99%
unknown:	99%
device-verify:	99%
device-verify:	100%
unknown:	100%
device-busy:	100%
552108 bytes successfully downloaded to device
```

```
sudo fwupdtool install-blob --plugins dfu --no-reboot-check obj/fcos_v3.4.0-a1_REMOTE_CONTROL_V2_XTEND_RC_REV01.dfu 2>&1 | tee out.log
WARNING: This package has not been validated, it may not work properly.
Choose a device:
0.	Cancel
1.	a295c945bbd4533ec94a05f43d7c03c6cad26118 (Dell Universal Dock D6000)
2.	b0a78eb71f4eeea7df8fb114522556ba8ce22074 (STM32 BOOTLOADER)
2
failed to get device before update reload: failed to wait for detach replug: device b0a78eb71f4eeea7df8fb114522556ba8ce22074 did not come back
```

**Comment by hughsie** [comment]
Can you get the super-verbose output like last time pls. Also, what hardware you testing this on? It would be super to have something like that here for regression testing.

**Comment by amfern** [comment]
Yes, forgot to attach it. [out.log](https://github.com/fwupd/fwupd/files/7539889/out.log)

I am suing http://www.holybro.com/product/kakute-f7-aio-v1-5/

**Comment by hughsie** [comment]
> Yes, forgot to attach it. out.log

Hmm. I think `isatty(fileno(stdout))` is failing. Do you see the progressbar if you _don't_ use tee? I've also added a g_debug to include the percentage. Maybe that should really be a g_print(). I'll do that too as I think the \n kinda indicates our intention.

>I am using 

Something like this? https://www.ebay.co.uk/itm/124748888873?hash=item1d0b9cfb29:g:Dm4AAOSwLe5gs0vP

**Comment by amfern** [comment]
> Hmm. I think `isatty(fileno(stdout))` is failing. Do you see the progressbar if you _don't_ use tee? I've also added a g_debug to include the percentage. Maybe that should really be a g_print(). I'll do that too as I think the \n kinda indicates our intention.
yes, i do. i am seeing the progress bar, it moves a bit and doesn't reach the end.

```
Loading…                 [***************************************]
WARNING: This package has not been validated, it may not work properly.
Choose a device:
0.	Cancel
1.	a295c945bbd4533ec94a05f43d7c03c6cad26118 (Dell Universal Dock D6000)
2.	b0a78eb71f4eeea7df8fb114522556ba8ce22074 (STM32 BOOTLOADER)
2
Waiting…                 [***********************************    ]
```
https://youtu.be/dxvNyFARsjY

> Something like this? https://www.ebay.co.uk/itm/124748888873?hash=item1d0b9cfb29:g:Dm4AAOSwLe5gs0vP
yes, something like this. it's the same STM32F745

**Comment by hughsie** [comment]
>  yes, i do. i am seeing the progress bar, it moves a bit 

Okay, that's good enough for now, I've asked you for to many things already for one bug :)

> and doesn't reach the end.

That's expected; fwupd is waiting for the device to reappear with a DFU app interface (which your firmware doesn't seem to provide). You can prevent this from happening with the `Flags = will-disappear` in the quirk file for that VID/PID.

I'll have a look in my devboard box and see if I can find anything STM32FXXX -- if not I'll buy that little board and polish it up using that. Thanks again. @superm1 good for review now, thanks.

**Comment by amfern** [comment]
It's no problem at all, I appreciate your help and the effort you put into this project.
I set the `will-disappear` in `plugins/dfu/dfu.quirk` but i still see the error `failed to wait for detach replug`
```
# STM32F745 dfuse bootloader
[USB\VID_0483&PID_DF11]
Flags = absent-sector-size will-disappear
Plugin = dfu
DfuForceVersion = 011a
DfuForceTimeout = 5000
```

**Comment by hughsie** [comment]
Flags are separated by a comma, fingers crossed.

**Comment by amfern** [comment]
Comma separated also didn't work. I can open a separate issue for this. As it prevents me from switching away from dfu-tool
```
[USB\VID_0483&PID_DF11]
Flags = absent-sector-size, will-disappear
Plugin = dfu
DfuForceVersion = 011a
DfuForceTimeout = 5000
```
[out.log](https://github.com/fwupd/fwupd/files/7540780/out.log)

**Comment by hughsie** [comment]
> Flags = absent-sector-size, will-disappear

I don't know if it matters, but all the others have no space between the comma.

**Comment by amfern** [comment]
Removing the space between the commas like this `Flags = absent-sector-size,will-disappear` didn't remove the warning.
[out.log](https://github.com/fwupd/fwupd/files/7541908/out.log)

**Comment by hughsie** [comment]
Okay, lets merge this and continue tomorrow with the attach issue. Today I have a migraine... :(

**Comment by amfern** [comment]
Feel better, Thank you very much for your hard work :)

**Pull request closed without merging**
