### PR TITLE
trivial: Fix a recently added Bluez potential buffer-overread

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [X] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by d4s — DISMISSED** [review]
Good catch!
PS utf8 validation were unnecessary and preventing gathering info from the service.

**Comment by d4s** [comment]
> > PS utf8 validation were unnecessary and preventing gathering info from the service.
> 
> Ohh? Can you expand a bit.

it is failing complaining not utf8 string to any data in buffer, for instance:
```
10:32:52.215 FuBluezDevice        string: 1.0.0."(unreleased)"
10:32:52.215 FuBluezDevice        string in hex:  31 2e 30 2e 30 2e 22 28 75 6e 72 65 6c 65 61 73 65 64 29 22 00
```
here I've added trailing \0 just to be sure if that's not a case.

**Comment by d4s** [comment]
I've checked the source of g_utf_validation -- should pass indeed

**Comment by d4s** [comment]
argh! sure. buf->data

**Comment by d4s** [comment]
> argh! sure. buf->data

Definitely need to drink my coffee cup prior to removing anything :-/

**Review by d4s — APPROVED** [review]

**Comment by hughsie** [comment]
Good catch, thanks!

**Pull request merged**
