### PR TITLE
Wip/hughsie/md set version

### PR DESCRIPTION
**Pull request by hughsie**
Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
LGTM

**Comment by hughsie** [comment]
I've added all the device checksums to the existing firmware -- it'll need a fwupdmgr refresh before the version numbers will be correct on 1.9.1.

**Comment by superm1** [comment]
You mean 1.9.0 right?

**Comment by hughsie** [comment]
I think we've traditionally done .1 for the first release post branch.

**Pull request merged**
