### PR TITLE
trivial: ci: add a workaround for arch container generation issue

### PR DESCRIPTION
**Pull request by superm1**
This should be dropped at some point hopefully when the new
docker release has landed.
See: https://github.com/actions/virtual-environments/issues/2658
Fixes: #2894

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Review by hughsie — APPROVED** [review]
I bet that took some time, thanks. If CI's happy, so am I.

**Comment by superm1** [comment]
> If CI's happy, so am I.

Since containers generate on a cron job we won't know until after it's merged and ran later tonight.

**Review by FFY00 — APPROVED** [review]
LGTM :+1:

**Comment by superm1** [comment]
BTW - it looks like the workaround worked.
https://github.com/fwupd/fwupd/runs/1957440228?check_suite_focus=true

**Pull request merged**
