### PR TITLE
Switch the Ubuntu CI to Focal as Groovy is too broken...

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by superm1** [comment]
I'm surprised it's getting broken since there is the whole proposed promotion stuff (it should work like debian:testing in that regard).  But if it's breaking enough to warrant this PR LGTM.

**Comment by superm1** [comment]
Actually hold off a minute - is the breakage because of missing clang-6?  Maybe we should instead move to clang-9 which is in Groovy.

https://launchpad.net/ubuntu/+source/llvm-toolchain-9

**Comment by hughsie** [comment]
> is the breakage because of missing clang-

Yes, I think that's what I was seeing. Is there a "clang-latest" metapackage or something we could use instead?

**Comment by superm1** [comment]
Yeah.  `clang` and `clang-tools`.  I'll see if those work: https://github.com/fwupd/fwupd/pull/2307

**Pull request closed without merging**
