### PR TITLE
modem-manager: Assign the FuUsbDevice to the FuMmDevice

### PR DESCRIPTION
**Pull request by hughsie**
This allows protocol code like Sahara to use GUsb.

Type of pull request:

- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by ivanmikh** [comment]
> @ivanmikh this is how I think we should use GUsb for Sahara.

thanks, I will test it and add it to my pull request

**Comment by hughsie** [comment]
@ivanmikh -- did that help? Do you want me to merge this bit first?

**Comment by ivanmikh** [comment]
> @ivanmikh -- did that help? Do you want me to merge this bit first?

Yep, it works, thanks. I added this commit to my pull request, so we can probably close this one.

I ran into some issues after switching to the g_usb_device_bulk_transfer, I am still debugging it. I will update my pull request as soon as I resolve it.

**Comment by hughsie** [comment]
> so we can probably close this one

Mind if I merge this and then you rebase on top?

**Comment by ivanmikh** [comment]
> > so we can probably close this one
> 
> Mind if I merge this and then you rebase on top?

oh sure, i will rebase then

**Pull request merged**
