### PR TITLE
Enable building uefi-capsule plugin on FreeBSD 

### PR DESCRIPTION
**Pull request by SergiiDmytruk**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/fwupd/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

FreeBSD has Linux-like `<efivar-dp.h>` header, but it doesn't define type constants and it's not included implicitly by `<efivar.h>`.

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
I think would prefer to do ifdef here between Linux and freebsd to be more predicable in case anything changes in the future for the headers in either case and breaks one another.

Also can you add a CI target for bsd?

**Comment by SergiiDmytruk** [comment]
> I think would prefer to do ifdef here between Linux and freebsd to be more predicable in case anything changes in the future for the headers in either case and breaks one another.

Done in the latest commit.

> Also can you add a CI target for bsd?

There are quite [some changes](https://reviews.freebsd.org/D29332) needed for a successful build, but it is [possible](https://blog.3mdeb.com/2021/2021-03-15-fwupd-bsd-packages-and-ci/). It depends on whether you're OK with depending on those unmerged changes, which are even more WIP for dependencies of uefi-capsule.

**Comment by superm1** [comment]
> > I think would prefer to do ifdef here between Linux and freebsd to be more predicable in case anything changes in the future for the headers in either case and breaks one another.
> 
> Done in the latest commit.

Thanks

> 
> > Also can you add a CI target for bsd?
> 
> There are quite [some changes](https://reviews.freebsd.org/D29332) needed for a successful build, but it is [possible](https://blog.3mdeb.com/2021/2021-03-15-fwupd-bsd-packages-and-ci/). It depends on whether you're OK with depending on those unmerged changes, which are even more WIP for dependencies of uefi-capsule.

I just skimmed, but a majority of the focus seems to be on the fwupd daemon side of things. Is it pretty heavy on the EFI app too? If it's just depending on a master branch somewhere for CI purposes on bsd only thats different than random hacky patch. So I guess I mean it depends on what we're looking at :)

My main goal is that we have some way to tell that a change for BSD breaks Linux build or vice versa.

**Review by superm1 — APPROVED** [review]

**Comment by SergiiDmytruk** [comment]
I missed that someone is already adding CI in https://github.com/fwupd/fwupd/pull/3031 for the same ports fork, not sure what's the trouble with it.

> I just skimmed, but a majority of the focus seems to be on the fwupd daemon side of things. Is it pretty heavy on the EFI app too?

That PR hasn't yet been updated with the changes which make this plugin build (it just started to build successfully, hence the PRs here and to `fwupd-efi`).

**Comment by superm1** [comment]
Maybe for now, can you get the FreeBSD builds in fwupd-efi going?  That will be a good start to make sure the EFI application is building outside of linux.

**Pull request merged**
